### ISSUE TITLE
GITLAB: ERROR fatal: tag 'X.X.X' already exists

### ISSUE THREAD

**Issue by Gizmo2093** [release-it/release-it#1000]
HI, it's me again.
When i try use release-it in one branch i have this error.
My package.json:
"release-it": {
    "plugins": {
      "@release-it/conventional-changelog": {
        "infile": "CHANGELOG.md",
        "preset": {
          "name": "conventionalcommits",
          "types": [
            {
              "type": "feat",
              "section": "✨ Added"
            },
            {
              "type": "fix",
              "section": "🐛 Fixed"
            },
            {}
          ]
        }
      }
    },
    "npm": {
      "publish": false,
      "ignoreVersion": false
    },
    "git": {
      "commitMessage": "v${version}",
      "requireCleanWorkingDir": false,
      "requireUpstream": true
    },
    "github": {
      "release": false
    },
    "gitlab": {
      "release": false,
      "releaseName": "v${version}"
    },
    "hooks": {
      "before:init": "git fetch --prune --prune-tags origin"
    }
  }

**Comment by Gizmo2093** [comment]
gitlab-ci.yml   
before_script:
   - apk add --update git
   - git config --global user.name "$CI_PROJECT_NAMESPACE"
   - git config --global user.email "$GITLAB_USER_EMAIL"
   - git remote set-url origin 
 "https://$CI_PROJECT_NAMESPACE:$GITLAB_TOKEN@gitlab.ugsk.ru/$CI_PROJECT_NAMESPACE/${CI_PROJECT_NAME}.git"

   - it checkout -B ci_processing
   - npm i

script:
  - DEBUG=release-it:* npm run release -- patch --ci --verbose --no-git.push
   - git push --follow-tags origin ci_processing:${CI_COMMIT_REF_NAME} || true

what i do wrong?

I have example this code from: 
https://ruleoftech.com/2020/automate-versioning-and-changelog-with-release-it-on-gitlab-ci-cd

**Comment by Gizmo2093** [comment]
The problem was that the release-it was restarted with an empty tag, and after that there was already an error that the tag already exists. I found a workaround for GitLAB, I changed the git commit message and when I run it again, I don't trigger the release in the script for this trigger

**Comment by webpro** [comment]
Glad this is sorted
