### ISSUE TITLE
Real world monorepo example: turborepo + release-it.

### ISSUE THREAD

**Issue by b12k** [release-it/release-it#1005]
I recently wrote an article describing how to setup `turborepo` with `release-it` to utilize the power of caching to speed-up release process of semantically versioned monorepo packages.

I wonder what is a proper place in the docs/readme to mention it.

The article: https://medium.com/valtech-ch/monorepo-semantic-releases-db114811efa5
The demo repo: https://github.com/b12k/monorepo-semantic-releases

Thanx in advance!

**Comment by webpro** [comment]
Wow that's amazing, I really love to see all the awesome ways people are using release-it!

**Comment by webpro** [comment]
Added a new section for this very reason :)
