### ISSUE TITLE
gitlab: `CI_BUILD_REF_NAME` has been replaced with `CI_COMMIT_REF_NAME`

### ISSUE THREAD

**Issue by patshologram** [release-it/release-it#1006]
Hello

Based on https://github.com/release-it/release-it/blob/main/docs/ci.md#alpine the line
```
  - git checkout $CI_BUILD_REF_NAME
```

should be used. This worked fine till today where our CI broke, the error being `ERROR Must be on branch main`. Based on https://docs.gitlab.com/ee/ci/variables/predefined_variables.html the `CI_BUILD_REF_NAME` does not exists and `CI_COMMIT_REF_NAME` should be used. Changing the env variable worked for us.

**Comment by riverside-mrobinson** [comment]
Just ran into this same issue, came here to make the same ticket!

**Comment by mrobinson1022** [comment]
PR created, enjoy your holiday!

**Comment by webpro** [comment]
Thanks all!
