### ISSUE TITLE
Most recent tag is taken from only the current branch

### ISSUE THREAD

**Issue by imgrant** [release-it/release-it#1016]
To calculate the next version from git tags, release-it uses `git describe` to find the latest tag:
https://github.com/release-it/release-it/blob/14a73d977a30a817de5896a65f58a4069d8d7c88/lib/plugin/GitBase.js#L93-L101

The issue is that `git describe` can only find tags on the same branch, because it finds the most recent tag reachable from a commit (e.g. HEAD of the checked-out branch). This is not necessarily the same as the latest tag across all branches.

For example, consider a git flow approach where you want to tag builds from `main` as normal/full versions such as `v1.0.0`, but builds from `develop` with a suffix such as `-dev.X`:
1. `main` and `develop` are both at `v1.0.0`
2. Merging a feature branch to `develop` incrementing patch & modifier tags it as `v1.0.1-dev.0`
3. Merging `develop` to `main` incrementing patch tags it `v1.0.1`, which is great
4. Now you have `v1.0.1` pointing to `main` and `v1.0.1-dev.0` pointing to `develop`
5. Merging a new feature to `develop` you want it to be `v1.0.2-dev.0`, which is what incrementing from `v1.0.1` would give, but instead `git describe` finds `v1.0.1-dev.0` as the latest tag and so the increment results in `v1.0.1-dev.1`

Even though you are merging to `develop`, the real latest tag for the whole project is on `main`. What do you recommend here? `git tag --list` might be a solution, it will return all tags, but they would need sorting properly. Unsure if this would actually be undesirable, and some people *do* want the current latest tag from same branch only via `git describe` 🤔

**Comment by imgrant** [comment]
Fwiw, I ended up writing a local plugin to do this by implementing `getLatestVersion()` to override the internal `Git` functionality:

```node
'use strict';

import _ from 'lodash';
import { Plugin } from 'release-it';

const format = (template = '', context = {}, plugin = {}) => {
  try {
    return _.template(template)(context);
  } catch (error) {
    plugin.log.error(`Unable to render template with context:\n${template}\n${JSON.stringify(context)}`);
    plugin.log.error(error);
    throw error;
  }
};

class GitTagsFromAllBranches extends Plugin {
  async init() {
    const latestTagAllBranches = await this.getLatestTagNameAllBranches();
    const tagTemplate = this.options.tagName || ((latestTag || '').match(/^v/) ? 'v${version}' : '${version}');
    this.config.setContext({ latestTagAllBranches, tagTemplate });
  }

  getInitialOptions(options, pluginName) {
    return Object.assign({}, options[pluginName], {
      tagName:    options.git.tagName,
      tagMatch:   options.git.tagMatch,
    });
  }

  getLatestVersion() {
    const { tagTemplate, latestTagAllBranches } = this.config.getContext();
    const prefix = tagTemplate.replace(/\$\{version\}/, '');
    return latestTagAllBranches ? latestTagAllBranches.replace(prefix, '').replace(/^v/, '') : null;
  }

  getLatestTagNameAllBranches() {
    const { options } = this;
    const context = Object.assign({}, this.config.getContext(), { version: '*' });
    const match = format(this.options.tagMatch || this.options.tagName || '${version}', context, this);
    return this.exec(`git -c "versionsort.suffix=-" tag --list --sort=v:refname ${match} | tail -n 1`, { options }).then(
      stdout => stdout || null,
      () => null
    );
  }
}

export default GitTagsFromAllBranches;
```

However, if you still think this would be worth implementing as a configurable option as part of the internal `Git` or `GitBase`, I'd be happy to submit a PR.

**Comment by webpro** [comment]
Thanks @imgrant, I'm pretty sure there are more people interested in this option. I would be happy to review and merge it! I think the default should not change existing workflows, and the new option enables finding the latest tag from all branches.

Can't really think of a good name for the option though, something like `git.tagFindInAllBranches` or `git.tagsFromAllBranches` is not as obvious as it should be, I think.

**Comment by imgrant** [comment]
With hindsight, I think my situation can also be avoided/worked around by merging the `main` branch back into `develop` (i.e. as in 'proper' [git flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), versus [GitHub flow](https://docs.github.com/en/get-started/quickstart/github-flow), and is arguably the better way to do it. 🤔 

Nonetheless, PR #1020 implements a `git.` config parameter, as discussed.
