### ISSUE TITLE
Question: is possible to do git push before npm push?

### ISSUE THREAD

**Issue by multivoltage** [release-it/release-it#1022]
Hi.

I use relese-it both with github action and in my local.
Some times I have a problem with git push because of permission.
So my task is able to publish on npm but cannot push on git Then i need to push manually.

There is a method to change the task orders? I want for example git and then npm

**Comment by webpro** [comment]
Since `npm publish` is harder to undo than `git push` I've decided a long time ago to do that first. Unfortunately it's currently not possible to change the order.

**Comment by multivoltage** [comment]
ok thanks
