### ISSUE TITLE
Outdated dependency question

### ISSUE THREAD

**Issue by okonon** [release-it/release-it#1023]
Npm reporting following vulnerabilities. Is it possible to update vulnerable library dependency ?
Tahnks a lot 
Severity: critical
vm2 Sandbox Escape vulnerability - https://github.com/advisories/GHSA-cchq-frgv-rjh5
vm2 Sandbox Escape vulnerability - https://github.com/advisories/GHSA-g644-9gfx-q4q4

**Comment by guoxianzhe** [comment]
same problem

vm2 Sandbox Escape vulnerability - https://github.com/advisories/GHSA-cchq-frgv-rjh5
vm2 Sandbox Escape vulnerability - https://github.com/advisories/GHSA-g644-9gfx-q4q4

**Comment by ploh007** [comment]
Bump. Noticing this as well.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v16.1.1. See [Release 16.1.1](https://github.com/release-it/release-it/releases/tag/16.1.1) for release notes._
