### ISSUE TITLE
How to populate `gitlab.releaseNotes` with `conventional-changelog`?

### ISSUE THREAD

**Issue by chris-dura** [release-it/release-it#1025]
I've migrated to `release-it` as recommended by `standard-version`.

Currently, once I release, I'm manually creating a Release in GitLab and then copy+pasta the entries from `CHANGELOG.md` into the release notes.

I'm having a hard time finding examples, or figuring out, how I might get the from the `conventional-changelog` (or rather, the `@release-it/conventional-changelog`) to populate the release notes automatically?

I assume I need something like this in my `release-it.js`:

```js
module.exports = {
	 gitlab: {
	 	release: true,
	 	releaseName: "Release ${version}",
	 	releaseNotes(context) {
                  return "string that represents all the changes output to CHANGELOG.md";
                }
	 }
}
```

I just don't know how to get the string I need from CHANGELOG.md?

**Comment by webpro** [comment]
> I've migrated to `release-it` as recommended by `standard-version`.

Just out of curiosity, may I ask how/where this is recommended?
 
> Currently, once I release, I'm manually creating a Release in GitLab and then copy+pasta the entries from `CHANGELOG.md` into the release notes.
> 
> I'm having a hard time finding examples, or figuring out, how I might get the from the `conventional-changelog` (or rather, the `@release-it/conventional-changelog`) to populate the release notes automatically?
> 
> I assume I need something like this in my `release-it.js`:
> 
> ```js
> module.exports = {
> 	 gitlab: {
> 	 	release: true,
> 	 	releaseName: "Release ${version}",
> 	 	releaseNotes(context) {
>                   return "string that represents all the changes output to CHANGELOG.md";
>                 }
> 	 }
> }
> ```
> 
> I just don't know how to get the string I need from CHANGELOG.md?

Without the full picture, by this information I'm guessing the [@release-it/conventional-changelog plugin](https://github.com/release-it/conventional-changelog) is not installed/configured? In most scenarios you don't need to use `gitlab.releaseNotes` at all.

**Comment by chris-dura** [comment]
> Just out of curiosity, may I ask how/where this is recommended?

My mistake, `standard-version` recommended `release-please` -- which I found to be a little too opinionated, and I prefer a "manual via CLI" workflow, which I'm sure release-please supports... their docs just weren't geared towards it. And, I found `release-it` to be easier to get going.

> Without the full picture, by this information I'm guessing the [@release-it/conventional-changelog plugin](https://github.com/release-it/conventional-changelog) is not installed/configured? In most scenarios you don't need to use gitlab.releaseNotes at all.

... oops, I misread the docs, and didn't realize it gets populated by `git.changelog` automatically >_<

**Comment by michaelfaith** [comment]
> In most scenarios you don't need to use `gitlab.releaseNotes` at all.

@webpro  If we want the GitHub release page to be grouped in the same way that our changelog is, when using conventional-changelog, what's the best way to go about that?  It seems as though even if we're using the conventional-changelog plugin for generating the changelog entry on disk, the generated changelog for the GH release is just a list of all the commits ungrouped.  Am I missing something?

Example Changelog entry: https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/main/CHANGELOG.md#0211-2025-01-24
Corresponding GH Release: https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/releases/tag/v0.21.1

**Comment by chris-dura** [comment]
@michaelfaith -- Can you post your `release-it` config? I use `@release-it/conventional-changelog` and it is behaving as expected, but I use GitLab, not GitHub; however, I have no specific `gitlab.*` config in place.

**Comment by michaelfaith** [comment]
This what we have currently https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/main/.release-it.json

```json
{
	"git": {
		"commitMessage": "chore: release v${version}",
		"requireCommits": true
	},
	"github": {
		"autoGenerate": true,
		"release": true,
		"releaseName": "v${version}"
	},
	"npm": { "publishArgs": ["--access public", "--provenance"] },
	"plugins": {
		"@release-it/conventional-changelog": {
			"infile": "CHANGELOG.md",
			"preset": "angular",
			"types": [
				{ "section": "Features", "type": "feat" },
				{ "section": "Bug Fixes", "type": "fix" },
				{ "section": "Performance Improvements", "type": "perf" },
				{ "hidden": true, "type": "build" },
				{ "hidden": true, "type": "chore" },
				{ "hidden": true, "type": "ci" },
				{ "hidden": true, "type": "docs" },
				{ "hidden": true, "type": "refactor" },
				{ "hidden": true, "type": "style" },
				{ "hidden": true, "type": "test" }
			]
		}
	}
}
```

**Comment by chris-dura** [comment]
@michaelfaith -- looks like you might be experiencing a similar issue to this: https://github.com/release-it/conventional-changelog/issues/110

**Comment by michaelfaith** [comment]
Well, the CHANGELOG.md is generating correctly according to what's defined in the types: https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/main/CHANGELOG.md

It's that the GH Release page doesn't have the same groupings or hidden types: https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/releases  It just lists everything.  Since those are different parts of the config, I would expect that one doesn't affect the other, but I could be wrong.

**Comment by webpro** [comment]
`github.autoGenerate: true` tells GitHub to auto-generate the notes, my guess is that that overrides whatever's being sent with the body (as generated by conventional-changelog) by release-it.

**Comment by michaelfaith** [comment]
> `github.autoGenerate: true` tells GitHub to auto-generate the notes, my guess is that that overrides whatever's being sent with the body (as generated by conventional-changelog) by release-it.

This was it!  I created a dummy repo and ran through several different scenarios, and after removing `autoGenerate: true`, it used what was in the changelog generated from the conventional changelog plugin. Thanks for the recommendation @webpro!

https://github.com/michaelfaith/mf-cta-testing/releases (2.0.2 is the correct behavior after removing the prop; 2.0.1 was with autoGenerate enabled)

**Comment by JoshuaKGoldberg** [comment]
Aha! This is fantastic, thanks for the discussion!

The resolution of removing the one line is even better than I thought it would be. Not only is the issue fixed, but we have one less line of configuration. Incredible. 😄

**Comment by webpro** [comment]
Thanks everyone, added a note to the docs so others hopefully won't get confused.
