### ISSUE TITLE
Feature Request: Publish Command Should be delegated to the package manager cli.

### ISSUE THREAD

**Issue by louiss0** [release-it/release-it#1026]
## Movivation

I recently ran into an issue where a package that I installed was on npm depended on a package that said it needed the `"workspace:^"`
to install my packages. `pnpm publish` removes this word then assigns it the latest version of the package when publishing a package. 
That did not happen for the latest version of my package. I then figured out that release-it only uses the npm publish command to publish packages. 

It does not delegate the command to the package manager that you are using. 

## Further Context 

pnpm is a package manager that allows a package to be installed inside of another one as long as it's a part of a workspace.

It uses a syntax called the `"workspace:^"` to link two packages together. I was relying on this mechanic to publish my packages.
What `pnpm publish` does is remove the workspace value and replaces it with the latest version of the package in the workspace. 

**That did not happen when I was using release-it**  Instead the npm command was used

[pnpm workspaces docs](https://pnpm.io/workspaces)

## Request 

I think it's better for release-it to use the command of the package manager that the project is using rather than using npm to publish packages. Without this feature, I can't use the tool properly with pnpm. I would have to only use this tool to publish to Git Hub only but use pnpm to publish my dependencies.

**Comment by webpro** [comment]
Yes, agreed. There were unsuccessful attempts to support Yarn, Yarn Berry and pnpm in the past. Some relevant issues:

- https://github.com/release-it/release-it/issues/737
- https://github.com/release-it/release-it/issues/919
- https://github.com/release-it/release-it/issues/956

Personally I'm using npm in my own projects, but happy to consider pull requests that support pnpm.

**Comment by louiss0** [comment]
> Yes, agreed. There were unsuccessful attempts to support Yarn, Yarn Berry and pnpm in the past. Some relevant issues:
> 
> * [Support yarn berry #737](https://github.com/release-it/release-it/issues/737)
> * [Usage with Yarn #919](https://github.com/release-it/release-it/issues/919)
> * [Support Pnpm workspace #956](https://github.com/release-it/release-it/issues/956)
> 
> Personally I'm using npm in my own projects, but happy to consider pull requests that support pnpm.

I don't know how CLIs work under the hood. That kind of project is beyond my programming skill. I'd have to know how release-it uses npm then reverse engineer it so that it could look for the appropriate manager. There was a tool that was created that knows how to delegate commands it's called [ni](https://github.com/antfu/ni). Looking at that project may solve your problem. 

The way it works is that it detects the agent npm agent that you are using in your project.

**Comment by webpro** [comment]
We need more than what `ni` does (such as the equivalent of `npm version`, OTP handling, etc).

Not much to be done for me here not, so I'm closing this issue. As mentioned, anyone can feel free to open a pull request adding support for other package manager(s).

**Comment by webpro** [comment]
This might be interesting: https://github.com/hyoban/release-it-pnpm

**Comment by robinscholz** [comment]
```
hooks: {
    'after:bump': 'pnpm publish --no-git-checks',
  },
```

We are circumventing this by using a hook
