### ISSUE TITLE
`release-it` breaks due to use of `npm version` in a Yarn-based repo

### ISSUE THREAD

**Issue by markerikson** [release-it/release-it#1028]
Hi! Just mentioned this on Twitter and figured I'd follow up.

We use Yarn v3 in the various Redux repos like https://github.com/reduxjs/redux-toolkit and https://github.com/reduxjs/react-redux .

I began seeing issues in June of last year (and fortunately I wrote a lot of this down in a DM channel, so I'm copy-pasting from there). I tried to release an RTK build, but saw this error:

```
ERROR npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: eslint-config-react-app@7.0.1
npm ERR! Found: eslint@7.28.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.25.0" from the root project
npm ERR!   peer eslint@">=7.0.0" from eslint-config-prettier@8.3.0
npm ERR!   node_modules/eslint-config-prettier
npm ERR!     dev eslint-config-prettier@"^8.3.0" from the root project
npm ERR!     dev eslint-config-prettier@"^8.3.0" from @reduxjs/toolkit@1.8.3
npm ERR!     packages/toolkit
npm ERR!       @reduxjs/toolkit@1.8.3
npm ERR!       node_modules/@reduxjs/toolkit
npm ERR!         workspace packages\toolkit from the root project
npm ERR!         20 more (@graphql-codegen/typescript-rtk-query, ...)
npm ERR!   20 more (eslint-plugin-jest, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^8.0.0" from eslint-config-react-app@7.0.1
npm ERR! node_modules/eslint-config-react-app
npm ERR!   dev eslint-config-react-app@"^7.0.1" from the root project
npm ERR!   dev eslint-config-react-app@"^7.0.1" from @reduxjs/toolkit@1.8.3
```

After running `release-it -VV`, I saw that the offending command was:

```
npm version 1.8.3 --no-git-tag-version
```

which was being called here:

https://github.com/release-it/release-it/blob/2d13ba40342b218480b3220be9760d3ad5bbb134/lib/plugin/npm/npm.js#L79-L87

I investigated and concluded that `npm` was trying to actually _install_ everything in the repo as part of the `version` command, which is very wrong in this case because A) we don't use `npm` as our package manager, and B) it's just supposed to bump the `"version"` field.

This worked fine on my machine previously, so what had changed? I realized that I had recently upgraded my system's global NPM version from 8.4.0 to 8.12.0.

I dug further and found that NPM changed its behavior as of 8.6.0:

https://github.com/npm/cli/pull/4588

I don't have specific thoughts on a possible solution here. I _think_ there's a `yarn version` command. Can `release-it` maybe be configured to optionally use `yarn version` instead of `npm version` ?

**Comment by webpro** [comment]
This is basically handled in #942 (and, pfew... documented briefly also at https://github.com/release-it/release-it/blob/main/docs/npm.md#extra-arguments). You can do this (since [v15.5.0](https://github.com/release-it/release-it/releases/tag/15.5.0)):

```json
{
  "npm": {
    "versionArgs": ["--workspaces-update=false"]
  }
}
```

By the way, true support for other package managers would be great, but that'll take a lot more work than just swapping some strings (some attempts have been made, search for "pnpm" and "yarn").

**Comment by markerikson** [comment]
Ah, _wonderful_, thank you!
