### ISSUE TITLE
Github release seems not to work.

### ISSUE THREAD

**Issue by jogibear9988** [release-it/release-it#1029]
I select create github release,
I get no error, but no release is created.

<img width="848" alt="image" src="https://github.com/release-it/release-it/assets/364896/7a1896df-4dfc-4ae2-a2c0-d6b4caef53b9">

no release: https://github.com/node-projects/gauge.webcomponent/releases

**Comment by webpro** [comment]
This should be fixed by #1019 in [v16.1.5](https://github.com/release-it/release-it/releases/tag/16.1.5). Is it?

**Comment by jogibear9988** [comment]
works.

thx
