### ISSUE TITLE
Local plugin and parameters

### ISSUE THREAD

**Issue by LastDragon-ru** [release-it/release-it#1031]
I have a local plugin:

```js
import {Plugin} from 'release-it';

class Dump extends Plugin {
    getInitialOptions(options, pluginName) {
        return Object.assign({param: null}, options[pluginName]);
    }

    beforeRelease() {
        throw new Error(this.options.param);
    }
}

export default Dump;
```

It is added to config and it is work

```
plugins: {
    './.release-it/plugins/Dump.mjs':       {
        'param': 123
    },
},
```

But I cannot find a way to pass parameters to it :( When I try to pass `--plugins.<name>.param` it just fail with `Error: Cannot find module '<name>'`. I have tried `--plugins.dump.param=455`, `--plugins.Dump.param=455`, `--plugins../.release-it/plugins/Dump.mjs.param=455`, `--plugins./.release-it/plugins/Dump.mjs.param=455`, but nothing work. 

I'm doing something wrong or maybe it just not supported yet?

**Comment by webpro** [comment]
You can try quoting:

```
--'plugins./.release-it/plugins/Dump.mjs.param=455'
'--plugins./.release-it/plugins/Dump.mjs.param=455'
```

**Comment by khylias** [comment]
Which solution worked @LastDragon-ru ?

I've a similar case with local plugins but quotes annotations doesn't affect modules load.

***./release/.release-it.json***
```json
{
  "plugins": {
    "./release/calver-plugin.js": {
	    "format": "yyyy.0M.0D",
	    "increment": "calendar",
	    "rcIncrement": "calendar.rc",
	    "fallbackIncrement": "calendar",
	    "candidate": false
    },
    "@release-it/bumper": {
	    "in": ["package.json"],
	    "out": ["package.json"]
    },
    "./release/generate-changelog-plugin.js": {}
  }
}
```
***./package.json***
```json
"release-candidate": "release-it --ci --config ./release/.release-it.json --plugins./release/calver-plugin.js.candidate=true",
```

I can't find an effective annotation to configure my "candidate" argument. 
Best I can have is this message : `Error: Cannot find module '/release/calver-plugin'`

**Comment by LastDragon-ru** [comment]
> Which solution worked @LastDragon-ru ?

@khylias, to be honest, it working without plugin[.....](https://github.com/LastDragon-ru/lara-asp/blob/main/.release-it/config.js#L127-L133) 😅

**Comment by khylias** [comment]
Okay! Thx for answer @LastDragon-ru.

Any advice @webpro?

**Comment by webpro** [comment]
In the example `package.json`, the argument is not quoted

```shell
"release-candidate": "release-it '--plugins../release/calver-plugin.js.candidate'"
```

You'd need to fiddle a bit with the dots and the quotes to get it right. Here, dots are object key separators, but also path segments. Use `--debug` to see the results. I think providing the argument already means `true` (but probably any not-falsy value will do).

**Comment by khylias** [comment]
Yes, I didn't quote the command in the package.json but I was able to test with your first answer and nothing helped.

More precisely, I see in the debug that it's the .js extension that's causing the problem, precisely because the dot is a separator and a segment of the path.
The result is the same whether between quotes or not : 
```bash
$ release-it --debug --ci --config ./release/.release-it.json '--plugins./release/calver-plugin.js.candidate'
```
```json
plugins: {
    '/release/calver-plugin': { js: [Object] },
    './release/calver-plugin.js': {
      format: 'yyyy.0M.0D',
      increment: 'calendar',
      rcIncrement: 'calendar.rc',
      fallbackIncrement: 'calendar',
      candidate: false
    },
    '@release-it/bumper': { in: [Array], out: [Array] },
    './release/generate-changelog-plugin.js': {}
  },

```

Add more dot before extension will add more sub-object in configuration.

**Comment by webpro** [comment]
Maybe you can omit the `.js` extension? Or is it ESM and fails because of that?

Either way, it's something I might be able to handle/fix in release-it core.

**Comment by khylias** [comment]
No, unfortunately I can't. ESM does not allow you to import the module without the extension

**Comment by webpro** [comment]
Going to close this one. If there's any remaining issues left, your best bet is a PR we can discuss. But new issues are fine too.
