### ISSUE TITLE
Maintenance releases

### ISSUE THREAD

**Issue by tginiotis-at-work** [release-it/release-it#1032]
Is there any configuration strategy to support doing maintenance releases? 

**Example case:** Current release is 2.3.4, but a vulnerability pops up absolutely necessitating an update to an old release 1.5.2, i.e. doing a 1.5.2-1 or a 1.5.2.1 release.

**Comment by webpro** [comment]
Some ideas (without knowing anything about your workflow):

- Provide an explicit version. Instead of the bump. E.g. `release-it 1.5.2-1`
- Use `git.tagMatch` to get the latest version (https://github.com/release-it/release-it/blob/main/docs/git.md#tag-match)
- Use `git.tagExclude` to exclude version/ranges.
- Release from a branch (e.g the v1 branch or the v1 release branch)

**Comment by tginiotis-at-work** [comment]
Thanks for the quick response @webpro. As far as I looked into the code and the plugins' code - I couldn't figure out if it was possible to configure it how I would like to behave.

My workflow is to just run `release-it` in the `main` branch once code finally gets to it and it creates a tag depending on the last one via a recommended bump.

For maintenance releases I am thinking about making a `1.5.2.x` branch, where once `release-it` is run - it would force versions to do single increments to `x`, regardless if there are breaking changes or not. And once I am done with the maintenance release - I just merge the `1.5.2.x` to `main`, run `release-it` again and get a release as per the regular recommended bump.

Thinking about it, I could make CI logic to detect a "maintenace branch" named in the format of `EXISTINGVERSION.x` and then patch the `git.tagName` with the `EXISTINGVERSION.` prefix. Then just figure out some way to turn off semantic versioning and just do plain increments.

Not sure how would `tagMatch` or `tagExclude` help though. And right, writing logic to make the CI determine the version fully and then pass it to `release-it` is also an option.

Any thoughts on the patching `git.tagName` approach? Or whether it's possible to force release-it to do plain incremental versions?

**Comment by webpro** [comment]
> Not sure how would `tagMatch` or `tagExclude` help though. 

They can help when you don't branch out.

When you branch out from e.g. the 1.5.1 tag then release-it will find that as the latest branch? It does not `getLatestTagFromAllRefs` by default so this should work as wanted?

**Comment by tginiotis-at-work** [comment]
> When you branch out from e.g. the 1.5.1 tag then release-it will find that as the latest tag? 

That is correct.

>It does not `getLatestTagFromAllRefs` by default so this should work as wanted?

So release-it proposes the 1.5.2 tag, but that one already exists. And I am specifically targeting the 1.5.1 version with my maintenance release, so would like the version similar to 1.5.1-1 or 1.5.1.1. 

Currently release-it does not handle the case where the proposed tag already exists, right? Or am I missing something in this approach?

**Comment by webpro** [comment]
Maybe there's a misunderstanding in now semver works here.

After `1.5.1` you can bump to e.g. `1.5.2-0`. The `-0` suffix is a pre-release of `1.5.2`.

You can't go back from `1.5.1` to `1.5.1-0`.

Also see https://semver.org/ and/or https://github.com/npm/node-semver for more details.

**Comment by tginiotis-at-work** [comment]
Yes, I did misunderstand the pre-release notation, so versioning via a dash (e.g. `1.5.2-1`), would not work, since that indicates an earlier, not a later version.

I found the same discussion on the spec - https://github.com/semver/semver/issues/241, specifically [this comment ](https://github.com/semver/semver/issues/241#issuecomment-1458222309) with some suggestions.

So this means that what I am looking for is no longer strict semver according to the spec, because there is a need for another component besides MAJOR, MINOR, PATCH to be able to make a maintenance release for a specific PATCH version, i.e. an optional HOTFIX component would be useful, based off the current tag and some condition (conditions like proposed version already exists? Branch name is of the format EXISTINGVERSION.X?)

**Comment by webpro** [comment]
Do what you want, but release-it is based on semver and uses node-semver under the hood. You're on your own if you don't follow semver.

Fiddling in something between existing patch versions... oh well this is not the place to discuss those semantics :)

**Comment by webpro** [comment]
Obligatory warning for anyone ending up here in this thread: npm and tooling following semver may cause issues.

Glad you've seem to sort it out for you.
