### ISSUE TITLE
Npm publishing after github release breaks github actions

### ISSUE THREAD

**Issue by kaermorchen** [release-it/release-it#1034]
Hi. Thanks for this amazing tool.

I have small problem. This is a picture of my release steps.

![image](https://github.com/release-it/release-it/assets/11972062/6f90b721-ec13-4663-970c-0c6b0872c364)

`Publish to npm` after `Create a release on GitHub` but I have github action which started on `publishing` event and it needs fresh (v0.3.1 in this example). Npm isn't have v0.3.1 and the action breaks down.

Can we switch the order of the steps?

From this:
- Commit
- Tag
- Push
- Create a release on GitHub
- Publish to npm

To this:
- Commit
- Tag
- Push
- Publish to npm
- Create a release on GitHub

**Comment by webpro** [comment]
Not really. But since the `npm publish` is a command you can run from a hook, here's one idea:

```json
{
  "npm": {
    "publish": false
  },
  "hooks": {
    "before:github:release": "npm publish [...]"
  }
}
```

Not sure how this works when npm asks for OTP, though.

**Comment by ghiscoding** [comment]
For GitHub Actions requiring OTP input, I use this [wait-for-secrets](https://github.com/step-security/wait-for-secrets) Action, it provides a link that you can click and opens another tab with a form where you can enter your OTP and when provided the CI workflow continues

**Comment by webpro** [comment]
Thanks, @ghiscoding!

Closing this one.
