### ISSUE TITLE
Cannot find module for plugin when Node API run by action

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [release-it/release-it#1043]
I made a new GitHub Action, https://github.com/JoshuaKGoldberg/release-it-action, that runs `release-it`'s Node API. It's used in https://github.com/JoshuaKGoldberg/create-typescript-app/pull/927. But releases (when pnpm is the package manager) are failing with:

```plaintext
Error: Cannot find module 'file:///home/runner/work/create-typescript-app/create-typescript-app/node_modules/.pnpm/@release-it+conventional-changelog@7.0.1_release-it@16.1.5/node_modules/@release-it/conventional-changelog/index.js'
```

https://github.com/JoshuaKGoldberg/create-typescript-app/actions/runs/6378928430/job/17310427310

If I switch from `pnpm install` to `npm i`, the error remains with a simpler path:

```plaintext
Error: Cannot find module 'file:///home/runner/work/testing-branch-protections/testing-branch-protections/node_modules/@release-it/conventional-changelog/index.js'
```

https://github.com/JoshuaKGoldberg/testing-branch-protections/actions/runs/6379077592/job/17310847269

Note that `@release-it/conventional-changelog` is included as a dev dependency and the `.release-it.json` includes:

```json
{
	"plugins": {
		"@release-it/conventional-changelog": {
			"infile": "CHANGELOG.md",
			"preset": "angular"
		}
	}
}
```

Is there something funky about how release-it imports/requires plugins?

Apologies for such a weirdly specific issue but I'm not sure where to debug here 😅. 

Linked: https://github.com/JoshuaKGoldberg/release-it-action/issues/16

**Comment by webpro** [comment]
Very cool you are working on this!

For now I can see/suggest a few things:

- The plugin `load` function (you link to) isn't too fancy. Not very robust either, but can't remember hearing of issues here before. Should not end up in the second `catch` block so something odd is going on indeed. Maybe with `process.cwd()` being off inside `$`, maybe you can set it explicitly? No idea tbh.
- When running your action (stripped down from checks etc.) locally I can't repro the issue.
- Just slapped two `debug()` statements in a snapshot release dist-tagged `pl`, so you could try this:

```
pnpm install release-it@pl
```

..and something like this..

```
await $$`NODE_DEBUG=release-it:plugins release-it ...`  // OR
await $$`NODE_DEBUG=release-it:* release-it ...`
```

Or set the `NODE_DEBUG=release-it:*` somewhere else as environment variable. Hopefully that reveals something useful.

By the way, the `"preset": "angular"` config should become `"preset": { "name": "angular" }`

**Comment by JoshuaKGoldberg** [comment]
Thanks so much! I'm sad to say I just got it to work with [`execa`](https://github.com/sindresorhus/execa) (<code>await $\`npx -y release-it\`</code>), so I won't be debugging 😅.

**Comment by webpro** [comment]
Great! I'll keep the `debug()` in there anyway to close the other ticket as well :)
