### ISSUE TITLE
No error stack when plugin module cannot be found

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [release-it/release-it#1044]
Spinning off of #1043: if a plugin name cannot be resolved, the thrown error doesn't include an explanation of why or which paths were attempted. I think it might be useful to include that information. Do you think logging the caught errors in `lib/plugin/factory`'s `load` sounds reasonable?

https://github.com/release-it/release-it/blob/c1c0f99c70288882f0a30aee77f0a96605381967/lib/plugin/factory.js#L24

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v17.4.2. See [Release 17.4.2](https://github.com/release-it/release-it/releases/tag/17.4.2) for release notes._
