### ISSUE TITLE
Dockerise release-it for executing without node runtime

### ISSUE THREAD

**Issue by juancarlosjr97** [release-it/release-it#1045]
Hello,

I was wondering if you have considered Dockerise the project to run the release and publish a docker version of it that just executes and that is it.

If not, and the idea sounds good, I am happy to contribute and raise the first MRs with some thoughts around it.

**Comment by webpro** [comment]
I haven't considered that before, because I'm not a Docker expert. But I'm willing to include it, since it should be low maintenance (someone added a [Dockerfile in another project](https://github.com/webpro/reveal-md/blob/main/Dockerfile) which went well).

**Comment by juancarlosjr97** [comment]
Cool! I have an idea to manage additional dependencies besides the required one, and then we can go from there, I will try to get some time on it relatively soon :)

**Comment by juancarlosjr97** [comment]
I am putting my thoughts as I finally got some time to work on it.

* Dockerise works well
* The user can pass the list of additional dependencies
* The user can pass a list of additional commands to be executed


The problem... Git!

* Git configuration can be copied into the image from the host to avoid enforced configuration by the image, but those enforcing SSH then require SSH to be installed which is not a problem, but then additional configuration such as SSH keys and SSH-agent running passed to the image is required.

Still working out the git part, but the rest was quite straightforward.

**Comment by juancarlosjr97** [comment]
Hey @webpro I finished the dockerised version. Tested internally in my projects, I made some decisions for GPG, SSH and GIT. I tested into multiple conditions and more to come. :)

**Comment by webpro** [comment]
Very cool! Sorry I didn't respond before. Thanks a lot for the updates, here's looking forward to the final version :)

**Comment by juancarlosjr97** [comment]
All good! Fun weekend ahead for me :)

**Comment by juancarlosjr97** [comment]
So.. I finished https://github.com/juancarlosjr97/release-it-containerized. My main drive for this was for project that do not run with node and do not need to have any configuration around it, and I would dare to say that I have done it! All done thanks to the amazing work of release-it that inspired me :)

**Comment by webpro** [comment]
Guess we can close this one now, it's linked to from the docs here: https://github.com/release-it/release-it#containerized

Thanks for all the help and release-it-containerized!
