### ISSUE TITLE
Add New Plugins to README

### ISSUE THREAD

**Issue by JohnCampionJr** [release-it/release-it#1053]
Hi, I've built two plugins for Release It! that I was wondering if you would take a PR to add to the README.

https://github.com/jcamp-code/release-it-changelogen
Adds the growing-in-popularity [@unjs/changelogen](https://github.com/unjs/changelogen) functionality to Release It.

https://github.com/jcamp-code/release-it-dotnet
Add dotnet versioning and NuGet publishing

**Comment by webpro** [comment]
Sure! Happy to merge that.
