### ISSUE TITLE
Is there a way to get in output just the release-version without the dry-run strings ?

### ISSUE THREAD

**Issue by paolomainardi** [release-it/release-it#1056]
Hi and many thanks for this great project; I love it.

I am wondering if it is possible to have just the next-release version printed without having to do some bash gymnastic to remove the lines, just to be clear:

```shell
❯ release-it --no-git.requireCleanWorkingDir --dry-run --release-version
! git fetch --prune --prune-tags origin
$ git rev-parse --abbrev-ref HEAD
$ git config --get branch.feature/test-release-it.remote
$ git remote get-url origin
! git fetch
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git describe --tags --match=* --abbrev=0
$ git symbolic-ref HEAD
$ git for-each-ref --format="%(upstream:short)" refs/heads/feature/test-release-it
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git config --get branch.feature/test-release-it.remote  [cached]
$ git remote get-url origin  [cached]
! git fetch
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git describe --tags --match=* --abbrev=0  [cached]
$ npx auto-changelog --stdout --commit-limit false --unreleased --template https://raw.githubusercontent.com/release-it/release-it/main/templates/changelog-compact.hbs
0.7.16
```

**Comment by DiyanDev** [comment]
Hi, 
You can just remove --dry-run parameter, this should give you a clean output.
Also you can try running it as a npm script with --silent parameter.

**Comment by aecc** [comment]
@DiyanDev it seems like --release-version is broken since recently, that seems to be the reason for the feature request. I actually does the tagging even with the argument.

**Comment by paolomainardi** [comment]
Thanks, @aecc i guess the problem is that one, in fact the `--dry-run` confirms the git commands

**Comment by aecc** [comment]
Actually, it happens to me even without the --dry-run. Or maybe I don't understand how it would work.
`~$ git tag
1.0.0
1.0.0-35
1.0.0-39
1.0.1
1.0.2
1.0.3
1.1.0
1.1.0-0

~$ npx release-it --release-version 
1.1.1
~$ git tag
1.0.0
1.0.0-35
1.0.0-39
1.0.1
1.0.2
1.0.3
1.1.0
1.1.0-0
1.1.1-0`

I only rely on git tags. Version used: 16.1.5

**Comment by aecc** [comment]
it seems like the tag "1.1.1-0" is always wrongly created. Maybe this is a different issue and not related, but it seems like the --release-version is having side-effects, but the documentation says:
`Add the --release-version flag to print the next version without releasing anything.`

**Comment by aecc** [comment]
it seems like npx release-it --release-version actually fetches the tags from the origin, which was unexpected to me. You can ignore my comments.

**Comment by webpro** [comment]
- By default `package.json#version` is used: https://github.com/release-it/release-it#latest-version
- Using this with or without `--dry-run` should not make a difference (also it make no sense to add `--dry-run`).

```
$ cat package.json 
{
  "name": "release-it",
  "version": "16.2.1",
  ...
}
$ npx release-it --release-version
16.2.2
```

It should definitely not create a tag or touch anything.
