### ISSUE TITLE
Minor usability improvement: if prerelease, put next increment first

### ISSUE THREAD

**Issue by LeaVerou** [release-it/release-it#1061]
First, thank you for writing this awesome plugin! I was using my own Node script that I was copy-pasting from repo to repo, this is so much better!

I’m working on a prerelease version. If I run `npx release-it`, it asks me what the next version should be, and it (correctly) orders them with the most minor first. However, the one I most likely want is listed last:
<img width="252" alt="image" src="https://github.com/release-it/release-it/assets/175836/0b4b1492-611e-4f9b-af90-2b823e91f64d">

When the current version is a prerelease, the next version is far more likely to also be a prerelease, so this requires the user to hit the arrow key several times before selecting the right version. If it was listed first, it would only require a single keypress.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v17.0.0. See [Release 17.0.0](https://github.com/release-it/release-it/releases/tag/17.0.0) for release notes._

**Comment by webpro** [comment]
I _think_ I fixed it (just by looking at the logic)

**Comment by LeaVerou** [comment]
That was fast! Thank you!
