### ISSUE TITLE
Recommendations for version updates

### ISSUE THREAD

**Issue by 97vack** [release-it/release-it#1064]
I update the version and generate logs every time I commit. What I hope to do is trigger this release workflow only when the commit prefix is feature or fix, such as updating the version and generating logs. However, now when I submit a commit of type docs or style, this workflow will also be triggered. What should I do?

This is my release it

![image](https://github.com/release-it/release-it/assets/33567483/937bce69-c2ea-4378-86da-e95ade83ae9f)

**Comment by 97vack** [comment]
> I have patched release-it's code on my build environment to exclude commits with certain messages/prefixes with:
> 
> ```shell
> sed -i 's@git rev-list@git rev-list --grep="^PREFIX_I_DO_NOT_WANT" --invert-grep@g' /usr/local/lib/node_modules/release-it/lib/plugin/git/Git.js
> ```
> 
> Would be nice to have it as a configurable feature though.

Thank you for your feedback, but how should I use your plugin and the code above?

**Comment by tginiotis-at-work** [comment]
It is not a plugin, but a "dirty" hack. I wrote the `sed` command that patches the `Git.js` file. `^PREFIX_I_DO_NOT_WANT` is the regex that excludes messages that start with `PREFIX_I_DO_NOT_WANT`. You will have to figure out how to apply it to your case.

**Comment by 97vack** [comment]
> It is not a plugin, but a "dirty" hack. I wrote the `sed` command that patches the `Git.js` file. `^PREFIX_I_DO_NOT_WANT` is the regex that excludes messages that start with `PREFIX_I_DO_NOT_WANT`. You will have to figure out how to apply it to your case.

Thank you for your help. I think I understand what you mean. I'll give it a try.

**Comment by webpro** [comment]
Going to close this one. If there's any remaining issues left, your best bet is a PR we can discuss. But new issues are fine too. Although I think this issue should've been opened in the plugin repo.
