### ISSUE TITLE
`v.14.11.8` is not working with Bun `v1.0.11`

### ISSUE THREAD

**Issue by RSickenberg** [release-it/release-it#1065]
Greetings! 
When using Bun, there might be an issue but I might be wrong.

It's not a deal breaker for me since I can use node like everyone else for this.

Regards

<img width="1209" alt="image" src="https://github.com/release-it/release-it/assets/16922548/930ae8f0-0a1b-44e5-83b9-daffd82ace90">

**Comment by RSickenberg** [comment]
Sorry, it was a miss-configuration from my side. Disregard this, please.

**Comment by mrousavy** [comment]
Hey - are you using a monorepo? I can't seem to get release-it working with monorepos where a package has a `workspace:*` dependency...

```
ERROR npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:*
```
