### ISSUE TITLE
provide json schema of config file

### ISSUE THREAD

**Issue by hezhengxu2018** [release-it/release-it#1076]
like lerna, the json schema path has added to its config file after `lerna init`.
`"$schema": "node_modules/lerna/schemas/lerna-schema.json"`
provide the json schema would improve user experience，user can write config file without doc.

**Comment by ChromeGG** [comment]
Bump, also looking for this feature :)

**Comment by webpro** [comment]
That would be a nice feature indeed, if someone is willing to create and submit a JSON Schema file that would be great.

There's also ideas to add types in #1055.

**Comment by juancarlosjr97** [comment]
Cool idea! What is everyone's thought on having it centralized instead of part of the installation, the same as Renovate schema for example.

```json
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
```

**Comment by Sukaato** [comment]
I hope you're happy with these json schemas :)

**Comment by webpro** [comment]
This has also been added to create-release-it (https://github.com/release-it/create-release-it/blob/master/index.js#L40-L43) so it comes with `npm init release-it` by default.

**Comment by voxpelli** [comment]
I guess this can be closed as fixed then? :)

**Comment by webpro** [comment]
Yes, thanks again @Sukaato! Very appreciated.
