### ISSUE TITLE
Change Log Repeats

### ISSUE THREAD

**Issue by jscottSwift** [release-it/release-it#1077]
I'm new to semantic releases and trying to use release-it to auto-version and update change log.  The auto-versioning is working great, but I'm having an issue with the change log portion.

I'm using release-it in our GitLab CICD workflow.

Basic stripped-down example of the issue:
```
#v1.0.1
## New Features
* FeautureA

## Fixes
* BugFix1
* BugFix2

# v1.0.0
## New Features
* FeatureA

## Fixes
* BugFix1
```

Release v1.0.1 changes should only include BugFix2.

Do I have something configured wrong, is my workflow maybe not setup quite right as well?

Here is my config JSON
```
{
    "plugins": {
        "@release-it/bumper": {
            "in": "VERSION.txt",
            "out": "VERSION.txt"
        },
        "@release-it/conventional-changelog": {
            "infile": "CHANGELOG.md",
            "header": "# ChangeLog",
            "preset": {
                "name": "conventionalcommits"
            }
        }
    }
}
```

**Comment by webpro** [comment]
There's not much to infer from this information alone. Maybe a tag wasn't pushed?

You can use `-VV` and/or `--debug` to see better what's going on.

**Comment by fireflysemantics** [comment]
Hi - I have the same issue.  Did a detailed writeup here:

https://stackoverflow.com/questions/78196255/get-release-it-to-put-each-new-commit-under-the-corresponding-release-version-in

**Comment by webpro** [comment]
OK let's close this one indeed.
