### ISSUE TITLE
Bug - Issue with github comment on resolved items

### ISSUE THREAD

**Issue by juancarlosjr97** [release-it/release-it#1082]
v17.1.0 brings the functionality to add comments on PRs in CI environments.

However, it appears to be an issue with the feature as it now fails when trying to add a comment. See [here](https://github.com/juancarlosjr97/release-it-gh-comment/actions/runs/7951499800/job/21704994193).

The release does not fail as it happened before but execution fails.

**Comment by juancarlosjr97** [comment]
I have not had time to look into it, just noticed it one a release.

**Comment by juancarlosjr97** [comment]
The issue is...

```bash
file:///home/runner/work/release-it-pre-releases/release-it-pre-releases/node_modules/ora/index.js:385
		throw new TypeError('Parameter `action` must be a Function or a Promise');
		      ^

TypeError: Parameter `action` must be a Function or a Promise
```

From here https://github.com/sindresorhus/ora/blob/main/index.js#L384-L385

**Comment by webpro** [comment]
If it's an issue with Ora then there might be something off with `--ci` or `CI` env var not set? Otherwise you can try to set `github.comments.submit` to `false`.

Of course there can be a bug in release-it, too.

**Comment by juancarlosjr97** [comment]
The action is running `npx release-it --ci --git.tagExclude='*[-]*'`.

**Comment by juancarlosjr97** [comment]
Just in case, I tried updating the release configuration to github comments to false. See [here](https://github.com/juancarlosjr97/release-it-gh-comment/actions/runs/7951843312) and the [commit](https://github.com/juancarlosjr97/release-it-gh-comment/commit/10e44fc04eb944840dd3ced78b3b293973418c75)

**Comment by juancarlosjr97** [comment]
Well, it is correctly going to that scope as the `--ci` flag is set. Now, I am trying to understand why the `this.commentOnResolvedItems()` is identified as not a Promise.

**Comment by juancarlosjr97** [comment]
I got green pipeline across projects :)

Thank you!

**Comment by webpro** [comment]
Green is good! piew piew 🔫
