### ISSUE TITLE
[ERROR] GitLab CI error on NPM notice

### ISSUE THREAD

**Issue by ibnukipa** [release-it/release-it#1083]
I'm having an issue while running release-it in gitlab CI. I have configure based on the documentation but it's exciting the process with no clue, it just stop while running the NPM notice.

I have put the `-V` to verbose the logs but it still showing clueless information there.

<img width="904" alt="image" src="https://github.com/release-it/release-it/assets/12580174/47088c39-b4d7-42ee-8202-cb1b4d7d5c71">

<img width="904" alt="image" src="https://github.com/release-it/release-it/assets/12580174/c95e5183-00c4-4d73-9ae2-a02273e4ec79">

And it's not the timeout issue related as well
<img width="290" alt="image" src="https://github.com/release-it/release-it/assets/12580174/344a537b-a188-4706-8a57-84e6051003a9">

NB: I run it in my local with the same credentials and it's working.

**Comment by webpro** [comment]
Please use `--debug` as this contains a lot more details (see https://github.com/release-it/release-it?tab=readme-ov-file#troubleshooting--debugging)

**Comment by ibnukipa** [comment]
I found the issue, it was the gitlab credentials. It resolved! thanks
