### ISSUE TITLE
Error Invalid version

### ISSUE THREAD

**Issue by Visual-Dawg** [release-it/release-it#1088]
Hey, I am trying for some days now to set release-it up to publish to create a release and package when a new version with a release tag has been created.

I know this workflow is not optimal, but temporarily it seemed like the best option to get the CI going.

This is the command:
```bash
pnpm  release-it "1.0.1-next.46" --npm.skipChecks --VV  --npm.allowSameVersion --npm.ignoreVersion --npm.skipChecks=true  --gitlab.releaseName="@company/client@1.0.1-next.46" --no-increment --no-git  --gitlab.release --gitlab.releaseNotes='echo "Release version $CI_COMMIT_TAG."' --gitlab.assets="./output/*.tar.gz"
```

However, I get `ERROR Invalid Version: @company-name/client@1.0.1-next.46`

And it can be found here in the logs, but I am unsure where the error is coming from exactly.

```ini
RELEASE-IT:GITLAB 177: {
  url: 'https://gitlab.company.com/api/v4/projects/frontend/members/all/28',
  method: 'GET'
}
RELEASE-IT:GITLAB 177: {
  id: 28,
  username: 'project_6_bot_57fae3659ad5f53d9cd6d676fbcfc40c',
  name: 'release-ci',
  state: 'active',
  locked: false,
  avatar_url: '[https://secure.gravatar.com/avatar/a78464590787e1b3aedda79afa0b3dbaa5c3156d238f88fe6aa09094e410d64a?s=80&d=identicon'](https://secure.gravatar.com/avatar/a78464590787e1b3aedda79afa0b3dbaa5c3156d238f88fe6aa09094e410d64a?s=80&d=identicon%27),
  web_url: 'https://gitlab.company.com/project_6_bot_57fae3659ad5f53d9cd6d676fbcfc40c',
  access_level: 30,
  created_at: '2024-03-13T14:37:37.563Z',
  expires_at: '2025-03-13',
  membership_state: 'active'
}
RELEASE-IT:SHELL 177: {
  command: 'git log --pretty=format:"* %s (%h)" @company/client@1.0.1-next.46...HEAD',
  options: { write: false },
  code: 0,
  stdout: '',
  stderr: ''
}
ERROR Invalid Version: @company/client@1.0.1-next.46
Error: RELEASE-IT:CONFIG 177: { cosmiconfig: null }
RELEASE-IT:CONFIG 177: {
  system: { 'release-it': '17.0.3', node: 'v16.20.0', os: 'Linux 6.6' }
}
```

Where am I providing the invalid version?

**Comment by webpro** [comment]
The tag must be present on the remote in order to do create a release, but you're using `--no-git` (which also skips `git push`), so I guess that might be the culprit here.

**Comment by webpro** [comment]
The tag must be present on the origin (gitlab) to create a release there.

You could try something like this (not tested): `--no-git.comit --no-git.tag`

**Comment by webpro** [comment]
Don't forget to remove `--no-git` if you try my suggestion btw. You can see the resulting config in [debug mode](https://github.com/release-it/release-it?tab=readme-ov-file#troubleshooting--debugging)

**Comment by Visual-Dawg** [comment]
Thank you :) I already tried that, with the same result.
As the error said something about the version, I tried removing the version argument directly after `release-it`. 
It still wont create a release because of the error `You are not allowed to upload code`, even when I provide an elevated token.
It will create correctly versioned packages fine though.

```bash
NODE_DEBUG=release-it:*  pnpm  release-it  --npm.skipChecks --VV  --npm.allowSameVersion --npm.ignoreVersion --npm.skipChecks=true  --gitlab.releaseName="@company/client@1.0.1-next.57" --no-increment --no-git.commit  --gitlab.release --gitlab.releaseNotes='echo "Release version $CI_COMMIT_TAG."' --no-git.tag --gitlab.assets="./output/*.tar.gz"
```

I assume this has something do to with the `git clone master`. I will continue my research
And thank you again for being so responsive

**Comment by Visual-Dawg** [comment]
I solved it by using the [`Gitlab Release CLI`](https://docs.gitlab.com/ee/user/project/releases/release_cli.html) for the releases and `release-it` for the package.
It works, and I can still use `release-it` for the version bumping and tagging, which is nice
