### ISSUE TITLE
When publishing an npm package, when the publishPath option is set, isCollaborator should detect package.json under publishPath instead of the current directory.

### ISSUE THREAD

**Issue by Ru1ers** [release-it/release-it#1090]
When I execute publish npm in the root directory, he throws an exception

```
ERROR User xxxx is not a collaborator for release-it-test.
Documentation: https://git.io/release-it-npm
```
Apparently the error is telling me that I don't have publishing permissions for the project, which is no problem

But my project has a monorepo structure, and I cannot set the name in package.json in my root directory to the same name as the sub-package. This leads to the fact that what I release is a sub-project, and release-it detects the root directory.

![20240331142956](https://github.com/release-it/release-it/assets/32606572/82d765c6-b6db-4d2b-bc7f-c8b366c3be91)

```
  "npm": {
    "publishPath": "./src/test",
    "versionArgs": ["--allow-same-version"]
  },
```
This is the package.json of the subproject
![image](https://github.com/release-it/release-it/assets/32606572/8bb52177-d13e-4518-bcdd-db6a81a76927)

This is package.json in the root directory
![image](https://github.com/release-it/release-it/assets/32606572/52617e56-743d-4f32-afcb-998ce19d8823)

**Comment by webpro** [comment]
release-it uses npm under the hood, so you'd need to use that for auth/publish

**Comment by webpro** [comment]
Or try https://github.com/hyoban/release-it-pnpm
