### ISSUE TITLE
How can I change method of releasing (from "Release 0.0.1" to "v0.0.1") ?

### ISSUE THREAD

**Issue by vitalik203** [release-it/release-it#1092]

**Comment by webpro** [comment]
Guess you'd like to change the title of the GitHub Release? See here:

- https://github.com/release-it/release-it/blob/main/config/release-it.json#L40
- https://github.com/release-it/release-it/blob/main/docs/github-releases.md#release-name

In case you mean the commit message:

- https://github.com/release-it/release-it/blob/main/config/release-it.json#L13

**Comment by vitalik203** [comment]
> Guess you'd like to change the title of the GitHub Release? See here:
> 
> - https://github.com/release-it/release-it/blob/main/config/release-it.json#L40
> - https://github.com/release-it/release-it/blob/main/docs/github-releases.md#release-name
> 
> In case you mean the commit message:
> 
> - https://github.com/release-it/release-it/blob/main/config/release-it.json#L13

Thanks!

**Comment by vitalik203** [comment]
I tried to reconfigure, but it didn't help me. Probably, there are other methods, to do this ? Mayby in node_modules folder or others ?
