### ISSUE TITLE
How can I change parametrs from "Release 0.0.0" to "v0.0.0" after writing release-it, and publishing into repository ?

### ISSUE THREAD

**Issue by vitalik203** [release-it/release-it#1093]

**Comment by juancarlosjr97** [comment]
If I understood correctly, I think you are referring to `github.releaseName` or `gitlab.releaseName` and you can use `v${version}`

**Comment by vitalik203** [comment]
> If I understood correctly, I think you are referring to `github.releaseName` or `gitlab.releaseName` and you can use `v${version}`

Yep

**Comment by vitalik203** [comment]
> If I understood correctly, I think you are referring to `github.releaseName` or `gitlab.releaseName` and you can use `v${version}`

After pasting command release-it minor, after all agrees, I go to site, and then into field, where always release-it writes Release 0.0.0 for ex, but I need change to v0.0.0, without word "Release"

**Comment by webpro** [comment]
The docs I've linked to in #1092. What did yo try? What does [debug output](https://github.com/release-it/release-it?tab=readme-ov-file#troubleshooting--debugging) look like?

**Comment by vitalik203** [comment]
I`ve done this. Look at my project (https://github.com/vitalik203/Pig-game), and check, am I right.

**Comment by juancarlosjr97** [comment]
@vitalik203 update this https://github.com/vitalik203/Pig-game/blob/master/package.json#L20

to be like 

```
  "release-it": {
    "github": {
      "release": true,
      "releaseName": "${version}"
    }
  },
```

and try again :)

**Comment by vitalik203** [comment]
> @vitalik203 update this https://github.com/vitalik203/Pig-game/blob/master/package.json#L20 to be like 
> 
> ```
>   "release-it": {
>     "github": {
>       "release": true,
>       "releaseName": "${version}"
>     }
>   },
> ```
> 
> and try again :) 

Now, I helped me!
