### ISSUE TITLE
Return different message when requireCommitsFail is false

### ISSUE THREAD

**Issue by juancarlosjr97** [release-it/release-it#1095]
I have been thinking that when `git.requireCommitsFail` is set to `false` the message `ERROR There are no commits since the latest tag.` should not return `ERROR` but instead should return something else, like `INFO`.

It fails safe but still keeps the same message which I think is misleading in terms of logs.

Any thoughts?

**Comment by webpro** [comment]
I think you're right 💯

Feel free to open a PR for this :)
