### ISSUE TITLE
Commits to one dir generate release of another.

### ISSUE THREAD

**Issue by programad** [release-it/release-it#1096]
I am trying to achieve the following:

- Monorepo
  - packages/gen
  - packages/icons
  - packages/web

The icon package, only has an empty _package.json_ file.
When the **_package/gen_** runs, it generates all the contents of the **_packages/icons_** folder.
I want to publish ONLY the **_packages/icons_** release and npm package.

It works, but only if I commit something to the **_packages/icons_** folder.

I want to detect commits on **_package/gen_** in order to decide to generate a new release for **_packages/icons_**

Is that possible or I must commit something to **_packages/icons_** in order for this to work?

Thank you!

**Comment by webpro** [comment]
First of all, release-it doesn't have built-in support for monorepos. If you want to publish with separate versioning I'd suggest to run release-it from each package directly and start out from there.

There's quite a few things you could do using hooks, scripts and a fairly large set of built-in options.

If you have a configuration or setup you can share maybe I or others can look at it.

**Comment by webpro** [comment]
👍
