### ISSUE TITLE
Error 405 (Method Not Allowed) when creating Gitlab release (Gitlab self-hosted)

### ISSUE THREAD

**Issue by NielsCodes** [release-it/release-it#1102]
I have a new app with a new Gitlab repo and I would like to use release-it, but every time it tries to create a Gitlab release, I get the following error (in verbose mode):

```
? Create a release on GitLab (Release 0.1.0)? Yes
! gitlab releases#uploadAssets
! gitlab releases#createRelease "Release 0.1.0" (v0.1.0)
ERROR Response code 405 (Method Not Allowed)
 ELIFECYCLE  Command failed with exit code 1.
```

I have a Gitlab Personal Access Token that even has admin rights, which is configured as GITLAB_TOKEN in my .zshrc. I have also tried creating a new token with the API scope (like the docs say) in the new repo and using that instead, but the result is the same. 
I also have full permissions on the repository, so that can't be the cause of the issue either.

Here is my `.release-it.json`:

```json
{
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": "angular",
      "infile": "CHANGELOG.md"
    }
  },
  "npm": {
    "publish": false
  },
  "gitlab": {
    "release": true,
    "host": "https://gitlab.mycustomdomain.com/api/v4"
  },
  "git": {
    "commitMessage": "chore: release v${version}",
    "requireCleanWorkingDir": false,
    "tagName": "v${version}",
    "requireUpstream": false
  },
  "before:init": "git fetch --prune --prune-tags origin"
}
``` 
I have two other projects that also use release-it with the exact same config and those are working fine.
I cannot for the life of me seem to figure out what is different here.

I'm using version 17.2.0 of release-it and our Gitlab instance is on version v16.10.0-ee

Any help is much appreciated!

**Comment by webpro** [comment]
Maybe some misconfiguration in the local GitLab instance?

Try the `NODE_DEBUG` prefix and get more logging: https://github.com/release-it/release-it?tab=readme-ov-file#troubleshooting--debugging
