### ISSUE TITLE
Node 22 engine

### ISSUE THREAD

**Issue by Pelv** [release-it/release-it#1105]
Hi guys, any plan to update the engine on the package.json?

I've tried the node 22.1 version (with strict-engine false) and looks like it's working fine in my project.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v17.3.0. See [Release 17.3.0](https://github.com/release-it/release-it/releases/tag/17.3.0) for release notes._

**Comment by webpro** [comment]
Thanks @Pelv! Good point.

**Comment by Pelv** [comment]
@webpro thanks to you guys. I'm not good enough to really help you with the repo :( 
This issue was the only thing i could do.

**Comment by webpro** [comment]
All good! Raising issues is helpful too.
