### ISSUE TITLE
Working dir must be clear

### ISSUE THREAD

**Issue by MoinJulian** [release-it/release-it#1108]
When I run pnpm run release in my SvelteKit project I get this error:

```
(node:81341) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
ERROR Working dir must be clean.
Please stage and commit your changes.
Documentation: https://git.io/release-it-git
```

Can someone please help me?

**Comment by webpro** [comment]
```
ERROR Working dir must be clean.
Please stage and commit your changes.
```

By default, release-it is not going to release anything if you still have changes in your Git repository.

Also see https://github.com/release-it/release-it/blob/main/docs/git.md#clean-working-directory
