### ISSUE TITLE
`--npm.allowSameVersion` command arg does not work.

### ISSUE THREAD

**Issue by skycaptain** [release-it/release-it#1109]
It appears that setting `--npm.allowSameVersion` via command line arguments does not function as expected. Instead of translating to `true`, it is translated to an empty string, which does not yield the intended result. E.g. without  `--npm.allowSameVersion`, `npm.options` are:

```javascript
{
  allowSameVersion: false,
  ignoreVersion: false,
  otp: null,
  publish: false,
  publishArgs: [],
  publishPath: '.',
  skipChecks: false,
  tag: null,
  timeout: 10,
  versionArgs: [],
}
```

With `--npm.allowSameVersion` they are

```javascript
{
  allowSameVersion: '',
  ignoreVersion: false,
  otp: null,
  publish: false,
  publishArgs: [],
  publishPath: '.',
  skipChecks: false,
  tag: null,
  timeout: 10,
  versionArgs: [],
}
```

Thus calling `npm version` does not work as expected as `--allow-same-version` is not passed through:

```plain
...
$ npm version 0.1.0 --no-git-tag-version
npm
 verb cli /usr/local/bin/node /usr/local/bin/npm
npm info using npm@10.5.2
npm info using node@v20.13.1
npm info found workspace root at /builds/camerasystems/tfe/devops-labs/geneva/daggerverse-release-it 
npm verb title npm version 0.1.0
npm verb argv "version" "0.1.0" "--no-git-tag-version"
...
```

```shell
$ node --version
v20.13.1
$ release-it --version
v17.2.1
```

**Comment by webpro** [comment]
As a workaround you could set it as a boolean in `.release-it.json` until it's fixed.

**Comment by webpro** [comment]
You can also use something like `--npm.allowSameVersion=1` btw, value just needs to be true-ish
