### ISSUE TITLE
Gitlab: Create release without requiring git push

### ISSUE THREAD

**Issue by afrimberger** [release-it/release-it#1115]
**Current behavior**

Creating a Gitlab release without previous `git push` fails with `Response code 422 (Unprocessable Entity)` even though the Gitlab [releases API](https://docs.gitlab.com/ee/api/releases/#create-a-release) can create the corresponding tag automatically if it doesn't exist, yet (by passing `ref`).

**Motivation**

Using only the Gitlab API is much easier because you can just use the default token injected into the build job (`CI_JOB_TOKEN`). For using `git push` you need to create an Access Token what is cumbersome.

**Example configuration**

```json
{
  "git": {
    "push": false,
    "tag": false,
    "commit": false,
    "requireCleanWorkingDir": true
  },
  "gitlab": {
    "release": true,
    "tokenRef": "CI_JOB_TOKEN",
    "tokenHeader": "Job-Token"
  }
}
```

**What needs to be changed**

Just pass `branchName` in the field `ref` in the `createRelease()` method. Two lines in `GitLab.js` need to be adapted:

[Line 184](https://github.com/release-it/release-it/blob/3056a184265d60487ea570f85cfcd9835c6f8bb6/lib/plugin/gitlab/GitLab.js#L184):
```javascript
const { tagName, branchName } = this.config.getContext();
```

and [Line 200](https://github.com/release-it/release-it/blob/3056a184265d60487ea570f85cfcd9835c6f8bb6/lib/plugin/gitlab/GitLab.js#L200):
```javascript
const options = {
    json: {
        name,
        ref: branchName,  // pass branch name
        tag_name: tagName,
        description
    }
};
```

**Comment by webpro** [comment]
Thanks @afrimberger, feel free to open a pull request and I'm happy to look into it.

**Comment by fjakop** [comment]
We would appreciate this also very much, please merge this.

**Comment by webpro** [comment]
Can't merge, unfortunately the PR contains issues.

**Comment by robross0606** [comment]
> Can't merge, unfortunately the PR contains issues.

@webpro, what issues?

**Comment by webpro** [comment]
https://github.com/release-it/release-it/pull/1116#issuecomment-2182254217

Feel free to open a new PR though, seems like a fairly doable feat.

**Comment by robross0606** [comment]
You would think so, but the test feedback is almost non-existent.  What is failing?  The MR changes are so minimal, I can't fathom what's failing.

**Comment by webpro** [comment]
Probably has to do with the nock (API mocks) setup and the request no longer matching since something was added.

**Comment by robross0606** [comment]
I've never seen a test framework provide _less_ feedback.  🤣

**Comment by robross0606** [comment]
I checked out this project and cannot even get `npm ci` to work on Node 18.  There are conflicting peer dependencies:
```
C:\Code\public\release-it>npm ci             
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: eslint-plugin-import@2.29.1
npm error Found: eslint@9.3.0
npm error node_modules/eslint
npm error   dev eslint@"9.3.0" from the root project
npm error   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm error   node_modules/@eslint-community/eslint-utils
npm error     @eslint-community/eslint-utils@"^4.2.0" from eslint@9.3.0
npm error   4 more (eslint-config-prettier, eslint-plugin-ava, ...)
npm error
npm error Could not resolve dependency:
npm error peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8" from eslint-plugin-import@2.29.1
npm error node_modules/eslint-plugin-import
npm error   dev eslint-plugin-import@"2.29.1" from the root project
npm error
npm error Conflicting peer dependency: eslint@8.57.1
npm error node_modules/eslint
npm error   peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8" from eslint-plugin-import@2.29.1
npm error   node_modules/eslint-plugin-import
npm error     dev eslint-plugin-import@"2.29.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by robross0606** [comment]
> Probably has to do with the nock (API mocks) setup and the request no longer matching since something was added.

I have test fixes here for the nock interceptor problems. How shall I proceed? Should I fork from the current MR branch and submit a separate MR?

**Comment by webpro** [comment]
Closing this as #1161 is merged.

**Comment by webpro** [comment]
Big shoutout to @robross0606 for taking care of this! 🚀
