### ISSUE TITLE
FEATURE REQUEST: Command line options for answer cli prompts

### ISSUE THREAD

**Issue by fireflysemantics** [release-it/release-it#1118]
It would be nice to have command line options for answer the CLI prompts.

For example `--push` instead of saying `yes` to push.

SO Reference:
https://stackoverflow.com/questions/78634395/answer-release-it-command-line-prompts-with-options

**Comment by webpro** [comment]
- There's a `--ci` flag that skips all questions.
- There's also `--only-version` to skip all questions, except the one for the version.

See https://github.com/release-it/release-it?tab=readme-ov-file#interactive-vs-ci-mode

**Comment by fireflysemantics** [comment]
@webpro I was hoping for something like `--defaults --nopush --norelease`.  That way if we just want to create an `package.json` script that just generates the CHANGELOG we can do:

```
"changelog": "npx. release-it --defaults --nopush --norelease"
``` 

Thoughts?

**Comment by webpro** [comment]
If you want to disable specific plugins you can do this already. Basically any config option can be set from the CLI. Examples:

```
release-it --no-git.push
release-it --no-npm
```

See the docs for more details.

**Comment by fireflysemantics** [comment]
@webpro OK cool [I see it now!](https://github.com/release-it/release-it/blob/main/docs/configuration.md).  Sweet Thanks!!  I'll close.
