### ISSUE TITLE
Allow pre-releases to be numbered from 1 instead of 0

### ISSUE THREAD

**Issue by mgol** [release-it/release-it#1128]
In jQuery - which is in the process of switching to `release-it` - historically we've always numbered our pre-releases - alpha, beta or rc - starting with 1, not 0. It'd be great if this would be an option. That would also make it less confusing to say things like "this landed in the second beta".

With this option, I'd expect the following command:
```
release-it major --preRelease=beta
```
with the current latest release being `1.3.0` to generate the version `2.0.0-beta.1`.

**Comment by webpro** [comment]
> jQuery [...] release-it

Without getting sentimental, the other week I wrote https://www.webpro.nl/articles/privileged-but-not-a-clown and if you'd search for "jquery" and "release it" you'll understand why this is both a nice coincidence and a big honor :)

> historically we've always numbered our pre-releases - alpha, beta or rc - starting with 1, not 0. It'd be great if this would be an option. That would also make it less confusing to say things like "this landed in the second beta".

Must be my JavaScript mind, never crossed my mind. Makes sense. Luckily https://github.com/npm/node-semver has an option readily available for this.

**Comment by mgol** [comment]
Wow, that was really quick, thanks a lot! ❤️ The article was an interesting read as well. 🙂

**Comment by timmywil** [comment]
Thank you @webpro! I've incorporated this in the PR for jQuery. However, I wonder if this could also be an option that we could set in the release-it config file. I'm currently [always setting it in the npm script](https://github.com/jquery/jquery/blob/a33a431c70510b193b97c4d5f6507aa5951659ff/package.json#L62) to avoid any situation where one of us forgets to include it. Fortunately, it seems to be a noop for stable releases.

**Comment by webpro** [comment]
I think you can already just add the same `"preReleaseBase": "1"` to the config file :)

**Comment by timmywil** [comment]
Woops, thanks. You might want to add that to the config types.
