### ISSUE TITLE
Git Plugin PUSH Arguments ORDER needs to be flipped

### ISSUE THREAD

**Issue by jvenki** [release-it/release-it#1130]
First of all thanks for creating and maintaining this amazing library. Its super simple to configure and yet very powerful.

I am making use of Gitlab CI/CD pipeline to invoke this script. Gitlab always checks out a COMMIT and not the branch to avoid the issues of pipeline running for commits created later. This makes the git branch to be HEADLESS. Owing to the fact that the branch is HEADLESS, we face issues when "git symbolic-ref HEAD" is run. This is already reported in https://github.com/release-it/release-it/issues/834. Though https://github.com/release-it/release-it/issues/834#issuecomment-1736365271 talks about doing a git checkout, I think it defeats the purpose as the branch will now contain commits created after the pipeline was created and therefore I dont want it. 

I went through the code and found that "git symbolic-ref HEAD" is run only when hasUpstreamBranch method is called and the two places are 
https://github.com/release-it/release-it/blob/0ac44ba3292926b7d2f944c254e09b94c093ad8f/lib/plugin/git/Git.js#L46
https://github.com/release-it/release-it/blob/0ac44ba3292926b7d2f944c254e09b94c093ad8f/lib/plugin/git/Git.js#L143

I was able to find a way to avoid that by making the pushRepo to be a URL based thing and not just a name. 

I also configured pushArgs with a value so that when git push is called on a headless branch, it can push to the right origin's branch. Now the final config is something like this

```
export default {
    "git": {
        "requireCommits": true,
        "requireCleanWorkingDir": false,
        "commitMessage": "build(release): release v${version}",
        "tagName": "${npm.name}-${version}",
        "requireUpstream": false,
        "pushRepo": `https://gitlab-ci-token@gitlab.abc.com/my-repo.git`,
        "pushArgs": ["HEAD:master"]
    },
    "npm": {
        "publish": false
    },
    "gitlab": {
        "release": true
    },
    "plugins": {
        "@release-it/conventional-changelog": {
            "preset": {
                "name": "conventionalcommits"
            },
            "infile": "CHANGELOG.md"
        }
    }
} satisfies Config;
```

Now everything works fine and as per the best practices except for a small issue. The code in https://github.com/release-it/release-it/blob/0ac44ba3292926b7d2f944c254e09b94c093ad8f/lib/plugin/git/Git.js#L214 is doing 

`const push = await this.exec(['git', 'push', ...fixArgs(args), ...upstreamArgs]);`

Because of this, the final git command becomes

`git push HEAD:master https://gitlab-ci-token@gitlab.abc.com/my-repo.git`

This makes the command invalid as it should have been `git push https://gitlab-ci-token@gitlab.abc.com//my-repo.git HEAD:master`

I know the pushArgs is meant for flags and I believe the flags would continue even if they are added at the end. Therefore, would it be okay if the code is made

`const push = await this.exec(['git', 'push', ...upstreamArgs, ...fixArgs(args)]);`

Thanks for your time.

**Comment by jvenki** [comment]
I tried to use the hook to achieve it... but I had to make `git.push` to be false to avoid the issues of HEADLESS branch and because of which none of the commands like
1. git add
2. git commit
3. git tag

are executed. 

Since git.push is FALSE, I had to use the hook "before:release" and not "after:git:release. I have to add all the git commands into the hook which defeats the purpose of myself using this awesome library.

**Comment by webpro** [comment]
I'd be happy to accept a pull request! If you think swapping the arguments is good from a Git argument order perspective it'd be great fix to do.

**Comment by jvenki** [comment]
I found that the various git commands are still done inspite of git.push being FALSE. I just need to do the git push through the hook before:gitlab:release. With this I am currently able to get my requirements solved and dont want to touch your code  which is working for many people. 

Thanks for your prompt reply and for this library.
