### ISSUE TITLE
ERROR Timed out after 10000ms.

### ISSUE THREAD

**Issue by St-coder** [release-it/release-it#1135]
node版本是 20.9.0
release-it 版本是"version": "17.6.0",

package.json 部分内容
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "release": "release-it"
  },

过程：
执行npm run release
 报错 ERROR Timed out after 10000ms.
Documentation: https://git.io/release-it-npm

![image](https://github.com/user-attachments/assets/a65e8209-7d55-4bc9-aa79-885c09d769b3)

为了定位问题，做出的动作：
 代码基于上一个发布版本（在7月16号同样使用了release, ），重新拉分支，执行 npm run release ，还是报错。

**Comment by St-coder** [comment]
![image](https://github.com/user-attachments/assets/500b6703-75e9-433b-8dc7-9edb8022b66e)
调试了一波，发现是网络问题，这个  this.isAuthenticated() 函数执行时间 太长了，把超时时间改成100000 后，能够正常启动，望官方早点优化。

**Comment by webpro** [comment]
Try to set `npm.timeout` (https://github.com/release-it/release-it/blob/main/config/release-it.json#L36)
