### ISSUE TITLE
What does git.requiredBranch do?

### ISSUE THREAD

**Issue by axi92** [release-it/release-it#1138]
I am confused what git.requiredBranch does in the config.

The default config is `false` but the [docs](https://github.com/release-it/release-it/blob/main/docs/git.md#required-branch) example says its a string like `"main"`?
https://github.com/release-it/release-it/blob/1fcf79f1f8d832f345900f20b7830dc3db601f8e/config/release-it.json#L6

https://github.com/release-it/release-it/blob/1fcf79f1f8d832f345900f20b7830dc3db601f8e/schema/git.json#L16-L18
According to the schema its a boolean

**Comment by webpro** [comment]
Thanks for the report, just fixed the schema!

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v18.0.0-next.0. See [Release 18.0.0-next.0](https://github.com/release-it/release-it/releases/tag/18.0.0-next.0) for release notes._

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v17.7.0. See [Release 17.7.0](https://github.com/release-it/release-it/releases/tag/17.7.0) for release notes._
