### ISSUE TITLE
Unable to use release-it to release a prior version

### ISSUE THREAD

**Issue by angelAtSequent** [release-it/release-it#1142]
Hi team!

We are trying to modify our workflow to follow [release-flow](http://releaseflow.org/).
In this flow, you could have two branches:

- `release/2.3`
- `release/2.4`

to release the same feature on two different branches/releases. What i am struggling with is to use `release-it` in the case of releasing a feature in 2.4.1 and later propagate this to 2.3.1.

```shell
Run echo "Release Version (is prerelease: true): 2.3.0-alpha.9"
  echo "Release Version (is prerelease: true): 2.3.0-alpha.9"
  if [ "true" = "true" ]; then
    release-it --ci --increment=2.3.0-alpha.9 --preRelease
  else
    release-it --ci --increment=2.3.0-alpha.9 
  fi
  echo VERSION=$(git describe --tags --abbrev=0) | tee -a $GITHUB_ENV $GITHUB_OUTPUT
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***
Release Version (is prerelease: true): 2.3.0-alpha.9
🚀 Let's release step-release-flow-test (currently at 2.4.0-beta.0)
Changelog:
* RELEASE-FLOW: Adapt requireCommits on release-it (3a40d06)
No new version to release
🏁 Done (in 1s.)
```

Do you know if there is a configuration to avoid this check? (No new version to release)

**Comment by webpro** [comment]
Sorry, haven't been in this situation before myself and I don't see an option readily available.

From an implementation specific, sounds like you'd need `--no-increment` and `--increment=[previous-version]` at the same time 🤷‍♂️

Maybe try `--npm.ignoreVersion` so it ignores `package.json#version`?

**Comment by angelAtSequent** [comment]
it "works" while you dont mix tags from a release in another branch,

its key to only manage v2.4.x tags on the release/2.4 branch and v2.5.x tags on its release branch,

`git merge` branches must be avoid, use cherrypicking instead to propagate features between branches.

**Comment by webpro** [comment]
Also see docs around https://github.com/release-it/release-it/blob/main/docs/git.md#tag-match
