### ISSUE TITLE
usage of obsolete `is-ci` library

### ISSUE THREAD

**Issue by SuperITMan** [release-it/release-it#1145]
Hey everyone,

I remarked that the `is-ci` library has not been updated since 3 years and does not detect CI in the following environments:
- Earthly CI
- Prow CI
- Vela CI
- Agola CI
- Gitea Actions

See https://github.com/watson/ci-info/releases/tag/v4.0.0 for more details.

Since `is-ci` doesn't add any value to `ci-info` (on which it depends), I suggest to replace the library in order to get latest updates.

A PR will follow 😊 

Thanks for this great library!

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v17.7.0. See [Release 17.7.0](https://github.com/release-it/release-it/releases/tag/17.7.0) for release notes._
