### ISSUE TITLE
Migrate to generic package registry for Gitlab assets

### ISSUE THREAD

**Issue by jeffesquivels** [release-it/release-it#1154]
The API that is being currently used for uploading assets to a Gitlab release is meant for files that are going to be [used in a markdown context](https://docs.gitlab.com/ee/api/project_markdown_uploads.html#upload-a-file):

> Uploads a file to the specified project to be used in an issue or merge request description, or a comment. 

It would make sense to replace that with the generic package registry which seems to be more fitted for the purpose of [publishing release assets](https://docs.gitlab.com/ee/user/project/releases/release_fields.html#use-a-generic-package-for-attaching-binaries):

> You can use [generic packages](https://docs.gitlab.com/ee/user/packages/generic_packages/index.html) to store any artifacts from a release or tag pipeline, that can also be used for attaching binary files to an individual release entry.

**Comment by webpro** [comment]
Sounds reasonable! I wasn't aware of this yet, not using GitLab myself. Any chance you'd be up for a PR?

**Comment by jeffesquivels** [comment]
> Any chance you'd be up for a PR?

**Comment by mcharris** [comment]
Ran into this issue for a different reason but got a PR up for this
