### ISSUE TITLE
Add GitHub Discussion in a particular category after GitHub release

### ISSUE THREAD

**Issue by WasiqB** [release-it/release-it#1159]
I want to create GitHub discussion topic under `Announcement` category every time the GitHub release is created using Release-it, but it seems this feature is missing.

I was not able to find anything in the docs about this, nor I was able to find any issues related to this.

It would be great to have this feature in release-it.

**Comment by voxpelli** [comment]
Implementation wise this would probably amount to including `discussion_category_name` when calling the GitHub API: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release

Agree that this would be something nice to have :)
