### ISSUE TITLE
Failed to push some ref

### ISSUE THREAD

**Issue by chukwuemekainya** [release-it/release-it#1162]
I'm trying to run release-it in GitLab CI, I followed [the docs](https://github.com/release-it/release-it/blob/master/docs/gitlab-releases.md) but when I run it in GitLab CI, I get:

```
$ git push --follow-tags origin
Rolling back remote tag push 2.8.3
$ git push origin --delete 2.8.3
error: unable to delete '2.8.3': remote ref does not exist
```

The commit, tag operations seem to run smoothly, so, I don't think it's a token issue, what can I do about this?

**Comment by webpro** [comment]
First see https://github.com/release-it/release-it#troubleshooting--debugging

Perhaps try to run things locally as well.

**Comment by chukwuemekainya** [comment]
Dry run works perfectly both locally and on prod, but the real command fails locally and on prod.

I am running `release-it -VV`.

**Comment by webpro** [comment]
Dry run doesn't actually write or push anything. In debug mode you'll see more!

**Comment by chukwuemekainya** [comment]
This is as much details as I could get:

```
? Push? Yes
$ git symbolic-ref HEAD
refs/heads/release_it
$ git for-each-ref --format="%(upstream:short)" refs/heads/release_it

$ git rev-parse --abbrev-ref HEAD  [cached]
$ git push --follow-tags --set-upstream origin release_it
Rolling back remote tag push 2.8.3
$ git push origin --delete 2.8.3
error: unable to delete '2.8.3': remote ref does not exist
error: failed to push some refs to 'gitlab.com:path.git'
ERROR error: unable to delete '2.8.3': remote ref does not exist
error: failed to push some refs to 'gitlab.com:path.git'
```

FYI: `2.8.3` is the new version.

**Comment by webpro** [comment]
You could try something like this: https://github.com/release-it/release-it/blob/main/docs/ci.md#error-tag-already-exists

**Comment by chukwuemekainya** [comment]
No luck. 

Here is a sample of my `release-it.json` file:

```
{
    "git": {
        "commitMessage": "v${version}",
        "commit": true,
        "tag": true,
        "requireBranch": "release_it",
        "requireCommits": false,
        "requireCleanWorkingDir": false,
        "push": true,
        "pushArgs": ["--follow-tags"],
        "pushRepo": "origin",
        "requireUpstream": false
    },
    "gitlab": {
        "release": true,
        "draft": false,
        "releaseName": "v${version}"
    },
    "npm": {
        "publish": false,
        "ignoreVersion": false
    },
}
```

Also, the gitlab setup is an internally run one.

**Comment by webpro** [comment]
Sorry, there isn't much I can do from here. The tool mostly just executes the shell commands. My guess is that there's some issue as outlined in the CI docs I linked to. You can try to add `git fetch` or even `git pull` in an early hook.

**Comment by chukwuemekainya** [comment]
Okay, thank you very much. I will try the `fetch` or `pull` and revert.

**Comment by webpro** [comment]
Closing this. Also make sure to use the latest version as you might('ve) hit #1115.
