### ISSUE TITLE
GitLab release not created after update to v17.7.0

### ISSUE THREAD

**Issue by andboss** [release-it/release-it#1163]
After update to v17.7.0 (the only change in the workflow) release-it does not create a GitLab release anymore - the config is:

```json
{
  "hooks": {},
  "npm": {
    "publish": false
  },
  "git": {
    "tagName": "v${version}",
    "commitMessage": "ci(release): v${version}"
  },
  "gitlab": {
    "release": true,
    "releaseName": "v${version}",
    "tokenRef": "MAINTAINER_BOT_TOKEN"
  },
  "plugins": {
    "@release-it/bumper": {
      "in": {
        "file": "VERSION",
        "type": "text/plain"
      },
      "out": {
        "file": "VERSION",
        "type": "text/plain"
      }
    },
    "@release-it/conventional-changelog": {
      "preset": {
        "name": "conventionalcommits"
      },
      "infile": "CHANGELOG.md",
      "header": "# Changelog",
      "writerOpts": {
        "mainTemplate": "{{> header}}\n{{#if noteGroups}}\n{{#each noteGroups}}\n\n### ⚠ {{title}}\n\n{{#each notes}}\n* {{#if commit.scope}}**{{commit.scope}}:** {{/if}}{{text}}\n{{/each}}\n{{/each}}\n{{/if}}\n{{#each commitGroups}}\n\n{{#if title}}\n### {{title}}\n\n{{/if}}\n{{#each commits}}\n{{> commit root=@root}}\n{{/each}}\n{{/each}}"
      }
    }
  }
}
```

EDIT: adapted `preset` with `name`

Any hints how to analyze or workaround?

**Comment by webpro** [comment]
What are the errors? Try a [debug run](https://github.com/release-it/release-it?tab=readme-ov-file#troubleshooting--debugging) for more details.

Make sure to the latest version.

**Comment by andboss** [comment]
no errors shown, i will check with verbosity level...

**Comment by andboss** [comment]
`verbose: 2` in configuration file is not picking up / shows same result, no error with latest version:

```
🚀 Let's release use-release-it (1.5.5...1.5.6)
Changelog:
## [1.5.6](https://code.siemens.com/reusable-ci/include/use-release-it/compare/v1.5.5...v1.5.6) (2024-10-15)
Changeset:
 M CHANGELOG.md
 M VERSION
 M package.json
 M templates/version.gitlab-ci.yml
🔗 https://code.siemens.com/reusable-ci/include/use-release-it/-/releases
🏁 Done (in 6s.)
```

will try `-VV`...

**Comment by andboss** [comment]
now with `-VV` is does not show any error but there is no release:

```
$ release-it $RELIT_INCREMENT $RELIT_PRE_RELEASE $RELIT_FILTER_TAGS $RELIT_CONFIG $RELIT_GITLAB_TOKENREF $DRY_RUN $VERBOSE $RELIT_EXTRA_ARGS --ci
$ git diff --quiet HEAD
$ git rev-parse --abbrev-ref HEAD
release/1.5.6
$ git config --get branch.release/1.5.6.remote
origin
$ git remote get-url origin
[https://gitlab-ci:[MASKED]@code.siemens.com/reusable-ci/include/use-release-it.git](https://gitlab-ci:%5BMASKED%5D@code.siemens.com/reusable-ci/include/use-release-it.git)
$ git fetch
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git describe --tags --match=v* --abbrev=0
v1.5.5
$ git symbolic-ref HEAD
refs/heads/release/1.5.6
$ git for-each-ref --format="%(upstream:short)" refs/heads/release/1.5.6
origin/release/1.5.6
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git config --get branch.release/1.5.6.remote  [cached]
$ git remote get-url origin  [cached]
$ git fetch  [cached]
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git describe --tags --match=v* --abbrev=0  [cached]
🚀 Let's release use-release-it (1.5.5...1.5.6)
Changelog:
## [1.5.6](https://code.siemens.com/reusable-ci/include/use-release-it/compare/v1.5.5...v1.5.6) (2024-10-15)
### Bug Fixes
* use debug verbosity for release-it ([5d979f9](https://code.siemens.com/reusable-ci/include/use-release-it/commit/5d979f9aa9e633713bf1ce850b716ff1ee95ed25))
$ Writing version to VERSION
$ Writing version to templates/version.gitlab-ci.yml
$ npm version 1.5.6 --no-git-tag-version
v1.5.6
$ Writing changelog to CHANGELOG.md
$ git status --short --untracked-files=no
 M CHANGELOG.md
 M VERSION
 M package.json
 M templates/version.gitlab-ci.yml
Changeset:
 M CHANGELOG.md
 M VERSION
 M package.json
 M templates/version.gitlab-ci.yml
$ git add . --update
$ git commit --message ci(release): v1.5.6
[release/1.5.6 e261d35] ci(release): v1.5.6
 4 files changed, 9 insertions(+), 3 deletions(-)
$ git tag --annotate --message Release 1.5.6 v1.5.6
$ git symbolic-ref HEAD  [cached]
$ git for-each-ref --format="%(upstream:short)" refs/heads/release/1.5.6  [cached]
$ git push --follow-tags --push-option=merge_request.create --push-option=merge_request.label=🚀release --push-option=merge_request.target=main --push-option=merge_request.draft --push-option=merge_request.assign=andre.bossert --push-option=merge_request.label=🔎review
! gitlab releases#createRelease "v1.5.6" (v1.5.6)
gitlab releases#createRelease: done
🔗 https://code.siemens.com/reusable-ci/include/use-release-it/-/releases
🏁 Done (in 8s.)
```

**Comment by andboss** [comment]
using versions:

```json
"[@release-it/bumper](https://npmjs.com/package/@release-it/bumper)": "[6.0.1](https://npmjs.com/package/@release-it/bumper)",
    "[@release-it/conventional-changelog](https://npmjs.com/package/@release-it/conventional-changelog)": "[9.0.0](https://npmjs.com/package/@release-it/conventional-changelog)",
    "[release-it](https://npmjs.com/package/release-it)": "[17.9.0](https://npmjs.com/package/release-it)"
```

**Comment by andboss** [comment]
> At least this seems incorrect:
> 
> ```
> "preset": "conventionalcommits"
> ```
> 
> → https://github.com/release-it/conventional-changelog?tab=readme-ov-file#preset

It works as the right preset is selected (assume name is set), but thanks for the heads-up, i will adapt for consistency

**Comment by andboss** [comment]
Downgraded only release-it from ``17.9.0`` to ``17.6.0`` and GitLab release are published again! The `-VV` trace shows similar output.

![image](https://github.com/user-attachments/assets/8942a638-4a98-448b-b9ee-28119042c327)

IMHO: it's a bug in release-it `>17.6.0`

**Comment by webpro** [comment]
Did you try `"useIdsForUrls": true`: https://github.com/release-it/release-it/blob/main/docs/gitlab-releases.md#attach-binary-assets

This was just added in release 17.7.0

**Comment by andboss** [comment]
> Did you try `"useIdsForUrls": true`: https://github.com/release-it/release-it/blob/main/docs/gitlab-releases.md#attach-binary-assets
> 
> This was just added in release-it v17.7.0

No, you see the whole config above in the description.

Why should we use it?

Does the the new version expect it also without the usage of the "release artifacts" feature?

**Comment by webpro** [comment]
> Why should we use it?

As documented:

> Version 17.2 of Gitlab [started enforcing a new URL format](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/156939) for uploaded assets. If you are using this version (or later), you should set the useIdsForUrls flag to true:

**Comment by andboss** [comment]
> > Why should we use it?
> 
> As documented:
> 
> > Version 17.2 of Gitlab [started enforcing a new URL format](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/156939) for uploaded assets. If you are using this version (or later), you should set the useIdsForUrls flag to true:

Still don't get it:
- there is no configured assets upload
- this breaks valid configurations for release-it --> should be major bump then
- it works with previous release-it v17.6.0 and GitLab 17.4.2 do not see the reason that it should not wort with new version of release-it?

**Comment by webpro** [comment]
Not having your full context and I'm not working with GitLab myself. Just providing all the information I have.

**Comment by webpro** [comment]
Also see [release notes](https://github.com/release-it/release-it/releases) for potential changes that might've caused issues for you.

**Comment by andboss** [comment]
so may be related to https://github.com/release-it/release-it/pull/1153
@jeffesquivels would be great if you can comment on this, so i can check how to proceed...

**Comment by jeffesquivels** [comment]
> @jeffesquivels would be great if you can comment on this, so i can check how to proceed...

I took a look and found a bug on the migration from `got` and `node-fetch` to the native `fetch` API which could be the cause of the issue you're experiencing.

PR #1166 has a fix for this, can you please test it and let me know if it works for you?

**Comment by webpro** [comment]
Or try [17.10.0](https://github.com/release-it/release-it/releases/tag/17.10.0)

**Comment by andboss** [comment]
@jeffesquivels i've tested the version 17.10.0 and it works now, thank you 🥇

@webpro thank you for the quick comments and the release 👍
