### ISSUE TITLE
Improve error handling for Gitlab plugin

### ISSUE THREAD

**Issue by jeffesquivels** [release-it/release-it#1167]
Currently, [there is no check](https://github.com/release-it/release-it/blob/main/lib/plugin/gitlab/GitLab.js#L176-L187) to see if a request to Gitlab's API was successful, and if it wasn't there's also no indication to the user that something went wrong (it would actually seem to the user that the operation succeeded, which is very confusing).

I'll try to tackle this as soon as I have some free time, but I'm leaving it here in case someone else can implement it before that.

**Comment by webpro** [comment]
This is in [v17.10.0](https://github.com/release-it/release-it/releases/tag/17.10.0) (forgot to close through commit msg).
