### ISSUE TITLE
How to change the version number defined in another file？

### ISSUE THREAD

**Issue by nongyehong** [release-it/release-it#1171]
![QQ_1729740706845](https://github.com/user-attachments/assets/b73459be-1b6e-4b21-85ee-b4dc0432e8b7)

For example, my current project is built by tauri, and there are configuration files in tauri that need to configure the version number of the packaged application, how to use release-it to modify the version number defined in these files, I don't want to modify these files in advance before releasing the version

**Comment by 0xMurage** [comment]
1. Install the Bumper plugin https://github.com/release-it/bumper.
2.  Add the plugin to your [release-it configuration](https://github.com/release-it/release-it/blob/main/docs/configuration.md) :
```json
{
"plugins": {
  "@release-it/bumper": {
    "in": "tauri.conf.json",
    "out": "tauri.conf.json",
  }
},
.....
}
```

**Comment by nongyehong** [comment]
> 1. Install the Bumper plugin https://github.com/release-it/bumper.
> 2. Add the plugin to your [release-it configuration](https://github.com/release-it/release-it/blob/main/docs/configuration.md) :
> 
> ```json
> {
> "plugins": {
>   "@release-it/bumper": {
>     "in": "tauri.conf.json",
>     "out": "tauri.conf.json",
>   }
> },
> .....
> }
> ```

Thanks, I really need this
