### ISSUE TITLE
Skip Commit Prompt

### ISSUE THREAD

**Issue by caseywatts** [release-it/release-it#1174]
Hello!

Is there a way to skip the "commit?" prompt?

I tried to set the [git plugin](https://github.com/release-it/release-it/blob/main/docs/git.md) config option `{git: {commit: true}}`, but even with that set, I'm still being prompted each time.

Most other options I've managed to configure so they don't prompt me for my most-common happy-path releasing workflow, and this is the only one left I still get prompted for.

Thank you 🙏

**Comment by webpro** [comment]
Did you try `false`?

**Comment by caseywatts** [comment]
`false` skips the prompt but it also skips creating the commit, right?
I'm looking to skip the prompt but I DO want to create a commit.

I think the three settings for `commit` are:
`true` = always prompt
`false` = no prompt, always skip committing
[doesn't exist, the setting I'm looking for] = no prompt, always commit

I did find the `--ci` and `--only-version`! That helps me achieve what I wanted, so we can close this issue 👏

**Comment by webpro** [comment]
`commit: false` skips creating the commit, and thus the prompt, indeed.

Just wondering, how did you learn that you can skip prompts? Other than with the flags you've found. I think was possible only a very long time ago.

**Comment by caseywatts** [comment]
For the other items I wanted to skip the prompt for, I did NOT want to do the action, so false worked for those!

When I worked on the Heroku CLI some, we had of these, and our structure was: `["always", "never", "prompt"]` -- I was looking around for a similar pattern here.

**Comment by webpro** [comment]
Ah, gotcha! Thanks.
