### ISSUE TITLE
Feature request: Enable log of scripts .

### ISSUE THREAD

**Issue by distante** [release-it/release-it#454]
I have a couple of node scripts that I run along with the release-it `packaje.json` scripts (`beforeStart`, `afterBump`, etc) and I have notice that I the output (`console.log`s) coming from those scripts are never printed.

Is there a way to enable the logs of this scripts?  I have some logs that would be good if I can see the output.

**Comment by webpro** [comment]
You can add `--verbose`, although that will also give output of internal commands.

**Comment by distante** [comment]
Yes `--verbose` prints those but as you said then is hard to find it with all the internal commands.

BTW: I think you should put an extra white space after the emojis like 🚀 :
![image](https://user-images.githubusercontent.com/5490201/51633118-2f6d1200-1f51-11e9-92cc-54e5e686b9c8.png)

**Comment by webpro** [comment]
* It would be a nice feature: only verbose logs for user scripts. I'll keep it in mind.
* The space is there (https://github.com/webpro/release-it/blob/master/lib/tasks.js#L62), yet your terminal/font isn't rendering it nicely. Happy to learn how to deal with this, though.

**Comment by distante** [comment]
For info I am using git-bash inside vscode on windows. I Have seen this behavior on windows before. I just always add an extra space

**Comment by webpro** [comment]
This does not resolve the original issue, but I did make sure that `stdout` coming from scripts is now printed along with `stdout` for commands that fail (currently, only `stderr` is printed). For example, I noticed when `npm run lint`, which in turn runs eslint, logs issues, release-it didn't log the actual linting issues (only the `stderr` coming from `npm`).

Also, you can now provide an array for user scripts, example: https://github.com/release-it/release-it/blob/v11/.release-it.json

This is available from v11, you can try with `npm install release-it@alpha`.

I'm going to close this issue, as `--verbose` does the trick, even if it comes with release-it output.

**Comment by distante** [comment]
Hello!

Thanks for this, I will try it out when I have the time.

**Comment by webpro** [comment]
This has just been released in [v12.4.0](https://github.com/release-it/release-it/releases/tag/12.4.0).
