### ISSUE TITLE
I can not access the repo object for scripts

### ISSUE THREAD

**Issue by distante** [release-it/release-it#455]
I am using the exact example given in the [README#Scripts](https://www.npmjs.com/package/release-it#scripts)

`"afterRelease": "echo Successfully released ${name} v${version} to ${repo.repository}."`

But I am getting the error : 'ERROR repo is not defined' 

I tried looking into the [default configuration](https://github.com/webpro/release-it/blob/master/conf/release-it.json) like the README says but I did not found any info there.

My release-it config is:

```
"release-it": {
    "scripts": {
      "beforeStart": "node ./scripts/release_1_before-start.js",
      "afterBump": "node ./scripts/release_3_after-Bump.js ${version}",
      "afterRelease": "echo Successfully released ${name} v${version} to ${repo.repository}."
    },
    "git": {
      "commitMessage": "release: v${version}"
    },
    "github": {
      "release": true,
      "assets": [
        "dist-bundles/*.zip"
      ]
    }
  },
```

**Comment by webpro** [comment]
Thanks for the bug report, @distante. Must've been lost in the v10 refactoring.

**Comment by distante** [comment]
Thanks @webpro it works now!, just as interest. Is it possible to get the npm package URL as variable?

**Comment by webpro** [comment]
No (but it should be printed at the end of a run).

**Comment by distante** [comment]
Ah you were right. I am blind 🕶
