### ISSUE TITLE
Improve explanation in README on how to use auto-changelog as a companion

### ISSUE THREAD

**Issue by papb** [release-it/release-it#480]
Hello, I am testing out `release-it`, considering using it for one of my next projects. Seems promising so far, but I've encountered a weird behavior (at least to me) while following the steps suggested in the readme:

> Additionally, `scripts.beforeStage` will update the `CHANGELOG.md` with each release to get included with the release commit. Obviously this can be omitted if the project does not keep a `CHANGELOG.md` or similar.

What I find odd is: since the `CHANGELOG.md` is being updated *before* the version bump, `auto-changelog` won't know about the upcoming new version, and things will go under the `Unreleased` bullet. What should happen, IMO, is the changelog should reflect the new version at the same time the version is being released. If somehow I use another script hook (other than `beforeStage`) to do this, then the changelog will probably be correct but now it will only be generated after the release is done, effectively making the release itself "changelog-less".

I am honestly lost here, so I would be super happy with an explanation and I think README should be improved so that others don't become confused as I currently am.

On a side note, I think the script hooks deserve a better documentation. By their names, I would think that `afterBump` runs after the `package.json` version is bumped and committed, but all scripts until `beforeStage` run first and then `release-it` asks me if I want to commit.

**Comment by webpro** [comment]
* The `scripts.changelog` writes to `stdout` (not to a file) and is used to create a preview of the changelog (and can also be used as body for GitHub/GitLab releases).
* In the example, the actual update of `CHANGELOG.md` itself is done by `scripts.beforeStage`, which happens after the version bump.
* I can understand the issues re. the docs, perhaps it's a bit too concise. Is the "bump" confusion maybe coming from `npm version` which also does the commit by default?

**Comment by papb** [comment]
@webpro Thanks for the fast response! After experimenting more, I figured out a lot of it, and proposed a Pull Request with some changes (#482), let me know what you think.

Yes, I think part of the confusion came from `npm version`, exactly!
