### ISSUE TITLE
--verbose does not work

### ISSUE THREAD

**Issue by papb** [release-it/release-it#483]
Adding `--verbose` has no effect. Adding `"verbose": true` on `.release-it.json` also has no effect.

Using `--verbose=true` works, though. This is very strange.

**Comment by webpro** [comment]
This is a indeed bug, thanks for the report. Maybe you want to submit a PR? This project uses `yargs-parser` to parse the CLI input.

**Comment by papb** [comment]
@webpro You're welcome, thanks for the fast response (on all my issues! sorry for creating so many in such a short time!).

I don't have time to investigate this for now, unfortunately. And I don't see myself having the time soon either; sorry about that. Perhaps in a few months :) If you have a quick solution in mind, feel free to do it, of course.

**Comment by webpro** [comment]
Fixed in [v10.3.1](https://github.com/release-it/release-it/releases/tag/10.3.1)
