### ISSUE TITLE
[question] Is it possible to prevent manual `npm publish`?

### ISSUE THREAD

**Issue by papb** [release-it/release-it#484]
I really like release-it, now that I learned more how to use it. Is it possible to make a configuration such that manual `npm publish` is impossible? Only allowing publishing through `release-it`?

I know it's very unlikely, but I would hate to forget about release-it and end up running `npm publish` manually by accident.

**Comment by webpro** [comment]
Well, `release-it` can't prevent you from typing `npm publish`.

However, you could write a shell function or script `npm` that delegates everything to `npm` itself, except if the first argument is `publish`. Is this what you're after?

**Comment by papb** [comment]
@webpro That might work, although feels a bit hacky. Thanks for the suggestion. Another idea I had:

* Check in npm's `prepublishOnly` script if a certain file `.can-publish` exists, and fail otherwise
* Create the `.can-publish` file on `beforeStart` of `release-it` and delete it in `afterRelease`

This way a mistaken direct call to `npm publish` won't work. I think this is less hacky than your suggestion...

The purpose of this issue was to ask if a similar behavior already existed in `release-it`. I think this issue can be closed now, thanks for all the attention :grimacing:

**Comment by webpro** [comment]
I really don't see how that makes a *direct* call to `npm publish` fail (from the CLI, not from release-it).

**Comment by papb** [comment]
@webpro it fails because calling `npm publish` from anywhere runs the `prepublishOnly` script which will check if a `.can-publish` file exists, and since it doesn't, the direct call to `npm publish` won't work.

**Comment by jgentes** [comment]
fyi, we run a pre-push githook that runs release-it, thereby always ensuring a new release goes out with each push to github
