### ISSUE TITLE
Feature request: allow multiple npm tags (such as "beta" and "next")

### ISSUE THREAD

**Issue by papb** [release-it/release-it#485]
Using `release-it` to publish a version `1.0.0-beta.0`, I see it automatically published to `npm` using the `beta` tag, which is great. The published version can be installed with `npm install my-package-here@beta`. However, it would be nice if also by default the tag `next` was also applied, which would allow `npm install my-package-here@next` as well. I think `next` should be automatically applied for all kinds of pre-releases (`alpha`, `beta` and `rc`).

I don't know if the `npm publish` supports multiple `--tag` parameters, but even if it doesn't, this can be achieved with the command that I ended up using manually:

```
npm dist-tag add my-package-here@1.0.0-beta.0 next
```

Thanks for looking! Great library!

**Comment by papb** [comment]
For now, I've created a script to run on `afterRelease` to call the above command automatically for me when a prerelease is done - it is working perfectly. It would be cool if this was supported out of the box though.

**Comment by webpro** [comment]
Haven't heard of assigning multiple tags to a single version. I've never done this myself. I wonder if more people or projects do this?

Btw, you can do `release-it --preRelease=beta --npm.tag=next` to use a different tag (but this still applies a single tag).

**Comment by papb** [comment]
I haven't heard of that either... I don't know if others do this. It was just an idea I had, and it made sense to me. Alpha releases get the `alpha` tag, beta releases get the `beta` tag, and both get the `next` tag. Seems plausible to me. But if you think it's not worth a feature, I don't mind staying with my personalized solution of using the `afterRelease` hook, as mentioned above.

Therefore, you can close this issue if you want, or leave it open as a (low-priority) feature request :)

**Comment by webpro** [comment]
Closing this as I think it would be a very uncommon feature.

**Comment by jsamr** [comment]
Well I happen to have the same feature request; I'm using tags with different semantics, including the next / alpha / beta...
