### ISSUE TITLE
Feature request: Flag to make `npm ping` optional

### ISSUE THREAD

**Issue by benediktberger** [release-it/release-it#486]
Hi,

just started using `release-it` and works just great, but we have a problem with the `npm publish`. Because you do a `npm ping` to check if the repository is up, it fails on our side. We are using Sonatype Nexus as our Npm registry and they do not support the `npm ping` call. They have an issue for this problem since 2017, see https://issues.sonatype.org/browse/NEXUS-13434.

As a workaround, I disabled the automatic `npm publish` and call it manually on `afterBump` / `beforeStage`. That works for now, but feels a bit ugly. It would be great to be able to disable the `isRegistryUp()` call with an config option.

Best regards and keep up the great work,

Benedikt

**Comment by satya164** [comment]
We use release-it in visual studio team services and have the same issue. For now, I have used [patch-package](https://github.com/ds300/patch-package) to remove the check and everything works great.

```patch
diff --git a/node_modules/release-it/lib/tasks.js b/node_modules/release-it/lib/tasks.js
index b2cbd7b..99d82d4 100644
--- a/node_modules/release-it/lib/tasks.js
+++ b/node_modules/release-it/lib/tasks.js
@@ -39,7 +39,7 @@ const runTasks = async (opts, injected = {}) => {
     const npmClient = new npm(options.npm, { isPreRelease: options.preRelease, isDryRun }, { shell, log });
     const v = new Version({ preReleaseId: options.preReleaseId, log });
 
-    await Promise.all([gitClient.init(), ghClient.validate(), glClient.validate(), npmClient.validate()]);
+    await Promise.all([gitClient.init(), ghClient.validate(), glClient.validate()]);
 
     const run = shell.runTemplateCommand.bind(shell);
     const { latestTag, isRootDir, remoteUrl, repo } = gitClient;
```

**Comment by webpro** [comment]
I've just released [v10.4.0-0](https://github.com/release-it/release-it/releases/tag/10.4.0-0), could you please give it a try?

```
npm install release-it@next
```

**Comment by wmccracken** [comment]
> I've just released [v10.4.0-0](https://github.com/release-it/release-it/releases/tag/10.4.0-0), could you please give it a try?
> 
> ```
> npm install release-it@next
> ```

This fixes the issue with nexus for me.

**Comment by webpro** [comment]
@benediktberger Using v10.4.0? It now ignores 404s coming from `npm ping` and `npm whoami`. Can you run with `DEBUG=release-it:* release-it [...]` and see interesting output?

**Comment by webpro** [comment]
Thanks, looks like ping is not supported, but whoami is (although the `--registry` argument must be provided). I've just released [v10.4.1](https://github.com/release-it/release-it/releases/tag/10.4.1) that also ignores 400s, hope this helps!

**Comment by benediktberger** [comment]
@webpro Hell yeah, now it works like a charm :)

Still, I might have found another issue, should I post it as a new issue? I tried to do a pre-release where the npm publish fails:
```
$ npm run release
...

WARNING Ignoring unsupported `npm ping` command response.

🚀 Let's release MY-PROJ (currently at 0.2.0)

Changelog:
...

? Select increment (next version): prepatch (0.2.1-0)
✔ BEFORE-STAGE-TASK
Changeset:
M  CHANGELOG.md
M  package.json

? Commit (0.2.1-0)? Yes
? Tag (PREFIX_0.2.1-0)? Yes
? Push? No
? Publish MY-PROJ to npm? Yes
ERROR npm ERR! Tag name must not be a valid SemVer range: 0
```

Using a non-pre-release version works fine, as mentioned above.

**Comment by webpro** [comment]
@benediktberger Good to hear this issue is fixed. Please file a new issue.
