### ISSUE TITLE
Update @octokit/rest to avoid deprecation warning

### ISSUE THREAD

**Issue by ehmicky** [release-it/release-it#487]
The following is now sometimes printed:

```
[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
```

This is solved by [upgrading `@octokit/rest`](https://github.com/octokit/rest.js/releases/tag/v16.16.4) from `16.16.0` to `16.16.4`. There is a [PR](https://github.com/release-it/release-it/pull/475) but it's only for `16.16.3`, which won't solve this.

**Comment by webpro** [comment]
Thanks @ehmicky, dependencies are updated in [v10.3.0](https://github.com/release-it/release-it/releases/tag/10.3.0).
