### ISSUE TITLE
MINGW64 Arrow Keys Not Working

### ISSUE THREAD

**Issue by mikejr83** [release-it/release-it#491]
As the title says, I'm using "release-it" from within MINGW64, git-bash (in actuality I'm within ConEMU but I doubt that's the issue here).

When running `$(npm bin)/release-it --preRelease` I see the expected select the next version prompt where it asks to use the arrow keys to make a selection. I cannot use my arrow keys. 

I know this is something tied to MINGW as arrow navigation works in within the Windows command prompt. However, I've used other NodeJS CLI tools where it was not a problem. Yeoman is one of these where I haven't had a problem in the past (I haven't tested in the latest NodeJS LTS).

I was wondering if anyone knew if this was a known issue with NodeJS or if it lies with whatever package you're using for input (or if you've rolled your own).

**Comment by webpro** [comment]
In release-it, [Inquirer.js](https://github.com/SBoudrias/Inquirer.js) is used. Would be good to look into more light-weight options.

**Comment by webpro** [comment]
@mikejr83, I now see that yeoman also works with Inquirer. As I'm not eager to replace Inquirer while preparing for [the next major release](https://github.com/release-it/release-it/issues/501) I'm closing this issue for now.
