### ISSUE TITLE
warning: tag 'vX.X.X' is really 'X.X.X' here

### ISSUE THREAD

**Issue by broofa** [release-it/release-it#492]
'Not sure if this is an issue with this project, per se, but this problem broke the `release-it` command for me, with the cryptic error noted above.

I'm not sure what exactly the underlying problem was, but it appears to have been related to the tag definitions on the remote repo, where there were both lightweight and annotated tags defined for each tag name.  This caused the `git describe --tags --abbrev=0` step of `release-it` to fail with the error, "warning: tag 'vX.X.X' is really 'X.X.X' here".   There are a few more details on my SO answer, here: https://stackoverflow.com/a/55111016/109538

I'm not sure exactly what the problem was in my repo originally.  I ended up blowing away all my tags and recreating them, which seems to have fixed the problem though.  However, if there's a way to tweak the `git describe` command to account for this situation in a more graceful manner, that'd be nice.

**Comment by webpro** [comment]
Seems like this issue may occur after renaming a tag. Going to close this issue as I don't think release-it should do anything here. People can still find this when searching here. Thanks for the report @broofa, it may help someone in the future.
