### ISSUE TITLE
Don't bump version in package.json

### ISSUE THREAD

**Issue by franciscocpg** [release-it/release-it#493]
I don't want to bump the version in `package.json`.

The only workaround I see right now is to set a value in `pkgFiles` configuration with a file that does not exist. Eg:
```json
{
  "pkgFiles": ["none.json"]
}
```

Is there an option to not bump the version in `package.json`?

**Comment by franciscocpg** [comment]
This worked 
```json
{
  "pkgFiles": null
}
```

**Comment by danderson00** [comment]
If you're consuming `release-it` programmatically, it seems a way of achieving this is by executing the following:

```Javascript
require('release-it/lib/plugin/version/Version').isEnabled = () => false
```

This might be flaky if the `release-it` team decide to refactor the project structure.

**Comment by webpro** [comment]
That's pretty clever, @franciscocpg (although would not recommend indeed). Works only since yesterday's v11 release. What will happen is that the latest version will be taken from the latest Git tag, and the user is prompted for the next version.

Depends on what is needed. Based on release-it v11, if you don't want to bump `package.json` and also not publish to npm registry, then a `--no-npm` (or `npm: false`) will do the job.

**Comment by danderson00** [comment]
What a coincidence that I only just started looking at release-it today!

My use case is a simple CLI for running release-it on multiple packages in a directory (i.e. a yarn workspace), kind of like an alternative to lerna, but works with both mono and multi repos. 

The complexity here is updating local dependency versions in the relevant package.json files. I'm still learning more about release-it and nutting through the best approach, but the initial thoughts are to 
- handle bumping all the versions before running release-it, 
- disable release-it's versioning and then 
- pass the `git.requireCleanWorkingDir: false` option to release-it :worried:

Considering alternate approaches like calculating all the versions that will be bumped and using a plugin to update them. Probably not the ideal place for discussion, but any thoughts?

Call it `release-em` haha

**Comment by webpro** [comment]
Could you please copy-paste this into a new ticket? Happy to go into it! Thanks.
