### ISSUE TITLE
Tagging prereleases in npm with latest

### ISSUE THREAD

**Issue by marlass** [release-it/release-it#494]
For our projects we have unique flow where we are still version our packages with alpha tags, but we want to release them on npm under `latest` tag. Seems that this is not possible right now with config file and cli params.
I looked at the lib code and found this line: https://github.com/release-it/release-it/blob/d5b31a5fc8cbc273b89c4cb6de6fac99898ecd89/lib/npm.js#L83 which causes the problem.
Is it possible to change that behavior? If tag is explicity set by user in config or cli argument as `latest` it should be used instead of tag extracted from package version with semver.

**Comment by webpro** [comment]
So even when you're using `--npm.tag latest` it does not tag it with "latest" in npm?

**Comment by marlass** [comment]
Even if I added that argument to command it still tag the package with extracted tag from version.
This happens only with `latest` tag. Any other tag works correctly. In my understanding this happens because `DEFAULT_TAG` in your code equals to `latest`.

**Comment by webpro** [comment]
I have taken this into account during development of v11. You may want to give `release-it@alpha` a try which should handle this case correctly. Warning: v11 is still in early alpha stage.

**Comment by webpro** [comment]
Should be fixed in [v11.0.0](https://github.com/release-it/release-it/releases/tag/11.0.0).
