### ISSUE TITLE
Gitlab only exposed by http

### ISSUE THREAD

**Issue by jgarec** [release-it/release-it#497]
Hi

We are running gitlab under http, not https (sorry for that ...).
When i try to create integrate release-it with gitlab, it tries to access to https.

Considering that my remote url is http://foo.bar/my_org/my_project.git, this would work : 
```
this.origin = this.options.origin || `${this.repo.protocol}://${this.repo.host}`;
```

But this won't work if i use ssh:git@foo.bar:my_org/my_project.git.

× GitLab release
ERROR Unsupported protocol "ssh:"

How can we handle gitlab over http and git over ssh ?

**Comment by webpro** [comment]
Did you try to set `gitlab.origin` to e.g. `http://foo.bar`?

**Comment by jgarec** [comment]
Hi,

here is my config file : 
```
{
 "gitlab": {
    "release": true,
    "origin" : "http://foo.bar"
  }
}
```
Same result : 
× GitLab release
ERROR Unsupported protocol "ssh:"

**Comment by webpro** [comment]
Haha, glad you resolved it :)
