### ISSUE TITLE
Release-it does not expose ${version} variable

### ISSUE THREAD

**Issue by wheresvic** [release-it/release-it#498]
Node.js version: `10.15.2`
Release-it version: `10.4.0`

`.release-it.json`:

```
{
  "scripts": {
    "beforeStart": "echo ${version}",
    "beforeBump": null,
    "afterBump": null,
    "beforeStage": null,
    "changelog": "git log --pretty=format:\"* %s (%h)\" [REV_RANGE]",
    "afterRelease": null
  },
  "npm": {
    "publish": false
  }
}
```

throws an error

```
$ release-it --dry-run --no-git.requireCleanWorkingDir
$ git rev-parse --git-dir
$ git diff-index --quiet HEAD --
$ git config --get remote.origin.url
$ git symbolic-ref HEAD
$ git rev-parse --show-toplevel
$ git for-each-ref --format="%(upstream:short)" refs/heads/master
$ git fetch
$ git describe --tags --abbrev=0
ERROR version is not defined
```

**Comment by wheresvic** [comment]
Moreover if I do something like `env > env.out`, I don't see any variables coming from release-it :(

**Comment by webpro** [comment]
I agree it isn't documented very well, but for now you need to take "before start" quite literally and no interesting runtime information is available at that point. It should be available in the other hooks, though.

**Comment by wheresvic** [comment]
@webpro Thanks a lot for the quick response. 

You are right, it makes sense that the variables are there when you actually start releasing. I moved my scripts to the `beforeStage` hook and it works now :)
