### ISSUE TITLE
how to make release-it do nothing if there are no changes (commits) since the previous release 

### ISSUE THREAD

**Issue by lqueryvg** [release-it/release-it#500]
## Description
How can I make release-it do nothing if there are no changes (commits) since the previous release ?

## Related Issues
Similar to https://github.com/release-it/release-it/issues/330

## Use case
I want to use release-it in a CI/CD pipeline just before deploying to production.
However, in case of deployment errors I sometimes need to re-run the pipeline.
I don't want to create a new (and empty) release every time I re-run a deployment.

**Comment by webpro** [comment]
You could check the number of commits since the latest tag, eg:

```
git rev-list $(git describe --tags --abbrev=0)..HEAD --count
```

This could be used in `scripts.beforestart`:

```
"scripts": {
  "beforeStart": "if [ not release required? ]; then echo 'No changes.'; exit 1; fi"
}
```

**Comment by lqueryvg** [comment]
Hi @webpro, thanks for that.

I saw this on the other ticket, but I couldn't see how it would stop the execution; for some reason I assumed it would exit the script but release-it would continue.
But then I realised it's the exit status that stops the execution.

```
  "scripts": {
    "beforeStart": "if [ $(git rev-list $(git describe --tags --abbrev=0)..HEAD --count) == 0 ]; then echo 'No changes.'; exit 1; fi"
  }
```

The only downside is that it makes release-it fail.
The error therefore has to be caught and checked by my code (otherwise my pipeline will fail), and it still looks like an error occurred in the pipeline output.

It would be neater if there was a release-it option to say `no-empty-release` which does all the work and does not error in this situation.

Nevertheless, I've implemented your workaround and it'll be enough for me until something better comes along.

Thanks very much !

**Comment by webpro** [comment]
You could also do the check before running release-it.

I'll keep something like a `--git.no-empty-release` option in mind (and thus, this ticket open).

**Comment by martinrcfisher** [comment]
You could change the test to only run if the result is NOT 0....

**Comment by webpro** [comment]
This is now in [v12](https://github.com/release-it/release-it/releases/tag/12.0.0). It does exit with a non-zero code, though. I've documented things in https://github.com/release-it/release-it/blob/master/docs/prerequisites.md and https://github.com/release-it/release-it/blob/master/docs/recipes/require-commits.md.
