### ISSUE TITLE
Custom maxLines for changelog ? (feature request)

### ISSUE THREAD

**Issue by goldo** [release-it/release-it#503]
I'd like to know what has been merged before deciding which kind of release I make (patch/minor/major) but It often goes beyond the 10 max lines:

```
$ release-it --no-npm.publish

🚀 Let's release project (currently at 1.16.0)

Changelog:
* chore(deploy): fix deloy on preprod

[...]

* fix(theme): fix dropdown label colors
..and 16 more

? Select increment (next version): patch (1.16.1)
``` 

Here the `..and 16 more` is hiding these info.

I see this function can take a maxLines param, but I don't see it anywhere it can be modified:
https://github.com/release-it/release-it/blob/c96536596327682d2e09b5acfe8f966e77fc13f1/lib/util.js#L10

Would it be possible to get this info ?

**Comment by webpro** [comment]
Unfortunately, there's currently no way to configure this in release-it v10 (or below).

However, in v11 (currently in beta) I've removed this truncation altogether, so you may want to try it:

```
npm run release-it@beta
```

**Comment by goldo** [comment]
Thanks, I'll try it ! :D

**Comment by goldo** [comment]
@webpro I just tried it, but unfortunately, I got this message: 
```
Not authenticated with npm. Please npm login and try again
```
My monorepo is in `private: true`, and I also have `npm.publish: false` (It was working before v11)

**Comment by webpro** [comment]
Oops, one line was lost in translation in the v11 rewrite. Thanks for testing the beta!

Should now work in [11.0.0-beta.3](https://github.com/release-it/release-it/releases/tag/11.0.0-beta.3).

**Comment by goldo** [comment]
@webpro I tried the rc beta today and I got an empty changelog:
```
➜ yarn release
yarn run v1.13.0
$ release-it --no-npm.publish

🚀 Let's release my-project (currently at 1.18.0)


Empty changelog

? Select increment (next version): (Use arrow keys)
❯ patch (1.18.1)
  minor (1.19.0)
  major (2.0.0)
  prepatch (1.18.1-0)
  preminor (1.19.0-0)
  premajor (2.0.0-0)
  Other, please specify...
``` 

:(

**Comment by goldo** [comment]
my config:
```
  "git": {
    "changelog": "git log --merges --pretty=format:\"* %b (%h)\" [REV_RANGE]"
  },
```

**Comment by webpro** [comment]
Ah yes. Thanks for hitting a breaking change before the v11 release :-)

I'll make it backwards compatible, but the idea is to use it like this:

```
git log --merges --pretty=format:\"* %b (%h)\" ${latestTag}...HEAD
```

Does that help?

**Comment by goldo** [comment]
I'll try at the next release :P thx

**Comment by webpro** [comment]
It's in [v11.0.0-rc.1](https://github.com/release-it/release-it/releases/tag/11.0.0-rc.1). Just know that using `[REV_RANGE]` will be deprecated at some point.

**Comment by webpro** [comment]
[v11.0.0](https://github.com/release-it/release-it/releases/tag/11.0.0) is out so In'm closing this.

**Comment by goldo** [comment]
@webpro works like a charm btw, thx a lot !
