### ISSUE TITLE
release-it refuses to ignore `package.json` when not in root of repo

### ISSUE THREAD

**Issue by lqueryvg** [release-it/release-it#504]
Environment: release-it v10.4.0

I have a monorepo with multiple subdirs, each with their own `package.json`.
I want to ignore the version in `package.json` and manage only git tags and github releases. 
To keep npm happy, I've put a zero version in `package.json`
```
  "version": "0.0.0",
```

But, when I run `release-it`, it always uses the version in `package.json`.
So, when my latest tag is v0.0.1 it does this:
- finds '0.0.0' in `package.json`
- bumps it to '0.0.1'
- tries to create tag 'v0.0.1' and fails with "ERROR fatal: tag 'v0.0.1' already exists" 

I found this logic in `version.js`:

```
    if (use === USE_PKG_VERSION || !isRootDir) {
      if (isPkgValid) {
        return (this.details.latestVersion = pkgVersion);
      } else {
        this.log.warn(`The version in package.json (${pkgVersion}) is not a valid semver version.`);
      }
    }
```

With a debugger I can see that `use === USE_PKG_VERSION` is false, but `!isRootDir` is true, and so it returns the version from `package.json`, hence causing my problem.

I can see no way to override this behaviour.

WORKAROUND:
My only workaround is to set the version in `package.json` to something which npm is happy with, but `release-it` sees as invalid, eg. `0.0.0x`. This causes `release-it` to print a warning but continue and use the latest git tag version.

Details:

`.release-it.json`:

```
{
  "git": {
    "tagName": "v${version}",
    "requireCleanWorkingDir": false,
    "requireUpstream": false,
    "commit": false
  },
  "npm": {
    "publish": false
  },
  "github": {
    "release": true,
    "assets": null
  },
  "pkgFiles": null,
  "increment": "conventional:angular"
}
```

**Comment by webpro** [comment]
Yes, unfortunately that line has caused more people trouble. Usually it's OK to keep the `version` in `package.json` in sync with the Git tag, but apparently to some it's not.

If you want to ignore the `package.json` (and also not update it, nor publish to npm), you can try the beta of v11:

```
npm install release-it@beta
```

And use it with the `--no-npm` CLI argument, or `"npm": false` config option. 

Looking at your config, for v11 please note that:

* You can remove the `pkgFiles` option.
* The `conventional:angular` increment is no longer supported, and you should use a plugin for that. See #501 and/or https://github.com/release-it/release-it/tree/v11#conventional-changelog for more details.

**Comment by webpro** [comment]
I think the issue as described is resolved in v11 (by the `--no-npm` option), so I'm closing this issue. Feel free to discuss further if needed.

**Comment by jgentes** [comment]
Confirmed that `"npm": false` does the trick here :)
