### ISSUE TITLE
Tests depend on GITHUB_TOKEN

### ISSUE THREAD

**Issue by seanodell** [release-it/release-it#505]
Enjoying your project and wanted to help out!

A basic clone, install and test resulted in these kinds of errors:

```
  Rejected promise returned by test. Reason:

  Error (TokenError) {
    message: `Environment variable "GITHUB_TOKEN" is required for GitHub releases.␊
    Documentation: https://github.com/release-it/release-it#github-releases`,
  }
```

I haven't looked into what the tests do, but I am guessing they're a kind of integration test around preparing releases? I think the average cloner probably should see a 100% pass without having to set up GitHub tokens.

Not sure what your intention was, so take with a grain of salt. If you agree, I might try moving those tests somewhere else and send you a PR (unsure of my ability to make the right choice about where they should go).

Thanks for developing this project!

Cheers!

**Comment by seanodell** [comment]
I took a stab at fixing some tests. Let me know if there is anything I could do better for you on these.

* https://github.com/release-it/release-it/pull/506
* https://github.com/release-it/release-it/pull/507

**Comment by webpro** [comment]
Thanks a lot, @seanodell! Your help is much appreciated. Let's discuss in the other tickets you already linked to.
