### ISSUE TITLE
ERROR Could not create changelog (git log --pretty=format:"* %s (%h)" )

### ISSUE THREAD

**Issue by js2me** [release-it/release-it#509]
Hello, I'm using Travis CI for publish some packages and my job crashed with this message
![image](https://user-images.githubusercontent.com/16340911/56557448-b7d86e80-65a3-11e9-8903-c73e5ffa2596.png)
Travis CI job:
https://travis-ci.org/acacode/stonex/jobs/523324833
Release it config:
https://github.com/acacode/stonex/blob/feature/travis-ci-integration/.release-it.json

But if I try to manual use command `git log --pretty=format:"* %s (%h)"`
![image](https://user-images.githubusercontent.com/16340911/56557341-4ac4d900-65a3-11e9-878a-876a28e78f35.png)

I think that I do something wrong.
Because maybe I do some operation about git ?
But I do almost the same here: 
https://github.com/acacode/kinka/blob/master/.travis.yml and it works

Hope for your explanation.

**Comment by webpro** [comment]
The Travis log says there are no commits:

```
$ git status
On branch release

No commits yet
```

So the `git log` command returns nothing. Also:

```
$ release-it 0.0.4-alpha
🚀 Let's release stonex (currently at 0.0.4-alpha)
```

This means that the you're trying to release version `0.0.4-alpha` while the package is already at `0.0.4-alpha` (you probably want to bump it with a release).

**Comment by js2me** [comment]
@webpro yeah, my mistake, will try to fix it. Thank you!
About `0.0.4-alpha` . Currently package have `0.0.3-alpha` on npm and with that should be everything is ok.
