### ISSUE TITLE
Specific pkgFiles ignored when checking version

### ISSUE THREAD

**Issue by xakraz** [release-it/release-it#511]
## What you expected to see, and what happened instead.

When running `release-it`, it checks version against `packages.json` instead of `version.json` even if it is mentioned in the `.release-it.json` config file

## Your operating system and other environment information.

```
OS: Alpine Linux 3.8
Kernel: 5.0.9-arch1-1-ARCH 
```

```
release-it --version
v10.4.2
```
```
node --version
v11.6.0
```

## As much information as possible, such as the command and configuration used.

`version.json`
```
$ cat version.json
{
  "name": "my-project",
  "version": "1.2.0"
}
```

.release-it.json
```
{
  "preReleaseId": null,
  "pkgFiles": ["version.json"],
  "use": "git.tag",
  "scripts": {
    "beforeStart": null,
    "beforeBump": null,
    "beforeStage": null,
    "changelog": "git log --pretty=format:\"* %s (%h)\" [REV_RANGE]",
    "afterRelease": null
  },
  "git": {
    "requireCleanWorkingDir": true,
    "requireUpstream": true,
    "addUntrackedFiles": false,
    "commit": true,
    "commitMessage": "Release ${version}",
    "commitArgs": "",
    "tag": true,
    "tagName": "${version}",
    "tagAnnotation": "Release ${version}",
    "tagArgs": "",
    "push": true,
    "pushArgs": "",
    "pushRepo": "origin"
  },
  "npm": {
    "publish": false
  },
  "github": {
    "release": false,
    "releaseName": "Release ${version}",
    "releaseNotes": null,
    "preRelease": false,
    "draft": false,
    "tokenRef": "GITHUB_TOKEN",
    "assets": null,
    "host": null,
    "timeout": 0,
    "proxy": null
  }
}
```

## Interesting logs from a verbose and/or debug run.

CLI output

```
$ release-it minor --preRelease=rc --verbose 

$ git rev-parse --git-dir
.git

$ git symbolic-ref HEAD
refs/heads/feature/XXXX

$ git diff-index --quiet HEAD --

$ git config --get remote.origin.url
git@github.my.domain:leboncoin/data-streaming.git

$ git rev-parse --show-toplevel
/home/YYYY/workspace/data-streaming

$ git for-each-ref --format="%(upstream:short)" refs/heads/feature/XXXX
origin/feature/XXXX

$ git fetch

$ git describe --tags --abbrev=0

WARNING Latest Git tag (null) is not a valid semver version.
WARNING Could not find valid latest Git tag or version in package.json. Using "0.0.0" as latest version.

🚀 Let's release data-streaming (0.0.0...0.1.0-rc.0)

$ git log --pretty=format:"* %s (%h)"

...and 48 more

$ bump 0.1.0-rc.0
WARNING Could not bump version.json
$ git add version.json

$ git add . --update

$ git status --short --untracked-files=no
M  .release-it.json

Changeset:
M  .release-it.json

? Commit (Release 0.1.0-rc.0)? (Y/n) 
```

## All steps to reproduce the issue.

**Comment by webpro** [comment]
Yes, this is intended behavior, `pkgFiles` contains the files to bump, not to read from (e.g. to add `package-lock.json`). This project as it currently stands is meant for Git and/or npm projects, that's why it always reads from `package.json`.

However, with v11 this is no longer the case and you could write a simple plugin (3 lines of code) for what you need: https://github.com/release-it/release-it/blob/v11/docs/plugins/README.md#example

You can read that whole document and #501 if you're interested to learn more. You can already use v11 with e.g. `npm install release-it@beta`

**Comment by webpro** [comment]
Saw a need for this since release-it v11 (e.g. people wanting to update `bower.json` or `VERSION` etc). so now there is https://github.com/release-it/bumper :) Let me know if it works for you!
