### ISSUE TITLE
option for git push --tags (instead of --follow-tags)

### ISSUE THREAD

**Issue by lqueryvg** [release-it/release-it#514]
# Description

How can I make `release-it` push the new tag without pushing the branch ?
I.e. I want `git push --tags` behaviour, not `git push --follow-tags`.

# Use Case

I am automating `release-it` from a CI/CD pipeline (after a manual approval step to release to production). We are doing trunk-based development on master branch.
The problem is that if someone merges to master after the commit I am trying to release, `release-it` will fail on the git push because the tip of origin is newer (see below). I don't want to prevent all of my developers from merging to master, just because I chose to release from an earlier commit.
 
```
 * [new tag]         v0.0.1 -> v0.0.1
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:blahblah.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
```

**Comment by webpro** [comment]
Unfortunately, you can't, as release-it always does `git push --follow-tags`.

Would adding `--force` maybe help here? You can add extra arguments with the `git.pushArgs` option (e.g. `--git.pushArgs="--force"`).

**Comment by lqueryvg** [comment]
`--force` would overwrite someone else's work, so I don't want that.

I can see that `--follow-tags` is hard-coded and was introduced in https://github.com/release-it/release-it/commit/d690da6e77c36274aea5afe3028a4d4cad8458ae (release https://github.com/release-it/release-it/releases/tag/2.4.1).

https://github.com/release-it/release-it/blob/c31ed3c223909b0b87613fd4c7a08e677d2754cc/lib/git.js#L167

So, what I'm really asking for is an option to allows me to select the original behaviour.

Something like this:
```
  "git": {
    "followTags": false
  },
```

With this option it would run `git push --tags` instead of `git push --follow-tags`.
Since I'm the "special" case, the default would be `true`.

**Comment by webpro** [comment]
This has been released in [v12](https://github.com/release-it/release-it/releases/tag/12.0.0). It was a very simple change providing maximum flexibility, but unfortunately a breaking one for some (thus, a major bump).

Regarding your use case: you probably want `git.pushArgs: --tags`
