### ISSUE TITLE
Malformed config file doesn't show an error message

### ISSUE THREAD

**Issue by darekkay** [release-it/release-it#515]
Related to #307 

When the `release-it.json` file is malformed, `release-it (--verbose)` finishes without any output.

Example (the `,` breaks the JSON format):

```
{
  "git": {
    "tagName": "v${version}",
  }
}
```

- OS: Windows 10
- Bash: Tried both Windows CMD and Git Bash (MINGW)
- Node: 10.15.1
- release-it: 10.4.5

**Comment by webpro** [comment]
Thanks for the report, @darekkay. The fix is in [v11.0.1](https://github.com/release-it/release-it/releases/tag/11.0.1).
