### ISSUE TITLE
Using release-it on multiple packages

### ISSUE THREAD

**Issue by danderson00** [release-it/release-it#516]
Originally from #493 

My use case is a simple CLI for running release-it on multiple packages in a directory (i.e. a yarn workspace), kind of like an alternative to lerna, but works with both mono and multi repos.

The complexity here is updating local dependency versions in the relevant package.json files. I'm still learning more about release-it and nutting through the best approach, but the initial thoughts are to

- handle bumping all the versions before running release-it,
- disable release-it's versioning and then
- pass the `git.requireCleanWorkingDir: false` option to release-it 😟

Considering alternate approaches like calculating all the versions that will be bumped and using a plugin to update them. Any thoughts?

Call it `release-em` haha

**Comment by webpro** [comment]
Question upfront: how would the new version(s) need to be calculated? Using a system such as conventional changelog (e.g. Angular's)? Do all packages carry the same version?

**Comment by danderson00** [comment]
Just thinking through the same issue. Ideally, there would be a policy that would apply to the set of packages being released, like simply increment all versions (major / minor / patch), increment all versions in sync, possibly even just increment the versions of packages that have commits since the last release.

To paint a better picture, a (much simpler) folder structure that illustrates my requirements:
```
packages
- app
- library1.core
- library1.other
- library2
```
library1 and library2 are separate products but with dependencies between them. In my case, each package has its own repo, but it could apply to a monorepo as well. app has its own release process.

Back to the question - I'd like to create a simple set of shell scripts for common release tasks like release everything (just increment all versions) or release an individual product (increment everything in sync).

**Comment by danderson00** [comment]
It's worth noting that yarn workspaces have been working quite well so far for this scenario. I believe npm support for workspaces is on the way, too.

**Comment by webpro** [comment]
I just think that, apart from the versioning strategy, you could leave the bumping, commit/tag, and publishing to release-it if you want to, by enabling/disabling this on a per-package basis in your scripts. Examples including `--no-git`, `--no-git.tag`, `--no-npm`. And indeed a plugin to calculate the version if needed.

In any case, it would be great to put one or more recipes (could very well be shell scripts) in the docs to help more people out in similar situations.

**Comment by danderson00** [comment]
Definitely intend to leverage as much release-it functionality as possible. Looks to work sweetly, props!

Absolutely, I'm sure there are others in similar situations. Ideally, a really simple set of shell scripts around release-it should be all that is needed, but the versioning is a little complex. Package managers themselves would be the ideal place to provide this sort of support, all the code to do it is already there, and it looks like it's getting there. I know the folks at npm are pretty snowed under!

Going to investigate a plugin that requires a list of the other packages being released and updates the dependencies section of package.json accordingly. Tomorrow. Time for z's.

**Comment by danderson00** [comment]
I made a [thing](https://github.com/danderson00/release-em)...

A bit more work to do, and to actually test the damn thing with my projects, but it looks to work ok.

**Comment by danderson00** [comment]
Oh... It's not published yet... hehehe

**Comment by webpro** [comment]
How nice! I absolutely love the name! 😄
I'm going to give it a proper investigation very soon.

**Comment by danderson00** [comment]
**phew** I think I'm done for now. Haven't quite pulled the trigger on releasing packages in my project, but the dry run looks good. The validate option picks up silly mistakes like uncommitted changes nicely. I'll do a quick blog post on it at some point soon.

Many thanks for your help!

Now... To consume the fruits of my labor...

**Comment by webpro** [comment]
Thanks, @danderson00. Very cool to see something built on top of release-it! Receiving a lot of useful feedback from you and release-em.

Btw, maybe it's a good idea (if you haven't already) to have an example project that release-em is useful for. Also, a few monorepo users have opened issues with release-it before, so I do expect some interest in release-em.

**Comment by rwjblue** [comment]
FWIW, I created [release-it-yarn-workspaces](https://github.com/rwjblue/release-it-yarn-workspaces) to make releasing workspace packages really nice and easy. It takes a bit of a different route from `release-em` (it is a standard release-it plugin, vs wrapping release-it in a new bin).

Just commenting here in case folks find it useful, apologies for the noise.

**Comment by danderson00** [comment]
@rwjblue Awesome stuff. Time has been extremely limited lately and I haven't had any time to fix the issues with release-em. Definitely going to check this out, leveraging a workspace `package.json` sounds like a sound approach!

**Comment by mkay581** [comment]
Sounds great. Is there a npm version? That doesnt require yarn?

**Comment by webpro** [comment]
Don't have much time these days, but for now I've added the plugin to the main readme. And re-open this ticket for visibility. Thanks, @rwjblue!

**Comment by rwjblue** [comment]
> Sounds great. Is there a npm version? That doesnt require yarn?

@mkay581 - `npm` doesn't have support for "workspaces" built-in (e.g. you'd have to figure out how to `npm install` in all of your sub-packages on your own), but nothing about the `release-it-yarn-workspaces` _actually_ uses `yarn` (it still uses `npm` itself for publishing for example). If you check out the [configuration section of the README](https://github.com/rwjblue/release-it-yarn-workspaces#configuration), you can specify the location for your packages (via `release-it` config).

That does make me think that maybe I should rename the package (since "soon" `npm` will support workspaces too), 🤔...
