### ISSUE TITLE
Prevent release if unfetched upstream commits exist

### ISSUE THREAD

**Issue by danderson00** [release-it/release-it#520]
Me again. So I did a real run with release-em against my project, and it failed due to being unable to push the git commit - there just happened to be upstream commits that I hadn't fetched in one of the packages.

To illustrate why failure part of the way through a run might be painful, I have 9 packages in the workspace, 8 of which are libraries being published to npm. If you're releasing all 8 and it fails several packages in, you end up in this nasty state of some packages being published and dependencies updated, some not.

So... I did a bit of digging and it's possible to figure out if there are upstream commits by running `git remote update` followed by `git rev-list master..origin/master --count`.

Looking at the git plugin, it would be a piece of cake to implement, but testing is a little tricky. You'd have to create a new commit, push it, `reset HEAD~1 --hard`, run the test, then force push to remove the commit we just created. Not sure if you want this...

Anyway, I'll implement this in a simple plugin for now, but I'd be happy to put together the start of a PR if you think it would benefit the wider community. Let me know.

**Comment by danderson00** [comment]
You can see the plugin at https://github.com/danderson00/release-em/blob/master/src/CheckUpstreamPlugin.js.

**Comment by webpro** [comment]
Not behind a computer atm, but isn't a git fetch (which release-it already
does?) enough? Or a git pull if not.
-- 
Sent from Gmail Mobile

**Comment by danderson00** [comment]
Long story short - no. My release failed because of upstream commits. Not sure if it does a fetch, but definitely not a pull. I'd argue against doing a pull without user interaction - no guarantees there are no merge conflicts, tests have not been run, the code may not even compile after pulling!

I need to pick this up as part of a dry run, for the reasons described above. Pulling is a write operation, so it won't happen as part of a dry run anyway.

I dunno, the plugin works fine. Like I said, happy to prepare a PR, but not unless you're interested in the change.

**Comment by webpro** [comment]
Gotcha, totally agree about not pulling. I dug a bit into this, and I'd think we only need to handle the *current* branch. I.e. `git fetch` and then something like `git rev-list --count @{u}...HEAD` would be enough, right?

**Comment by danderson00** [comment]
Nice, that's much neater than what I had. Git does my head in! 

I thought `git remote show` might be faster than `git fetch` as it only gets the commit log instead of the actual commit data, but it also does it for all origins. Either way seems reasonable.

I didn't know about the `...` syntax! `git rev-list --count HEAD..@{u}` also works. Using three dots would also return local commits that haven't been pushed to the remote as well, but that's already detected by another step.

**Comment by danderson00** [comment]
Actually, other steps don't pick up where there are local commits not pushed to the remote, and using three dots picks this up. It's just not possible to figure out whether the local branch is ahead or behind the remote. There are other commands that show the same thing (`git status -sb` for example) but it requires parsing the output.

**Comment by webpro** [comment]
Thanks @danderson00, I'll dive into this and try a few things soon if I can find some time.
