### ISSUE TITLE
Problems with semVer and v12.0.1

### ISSUE THREAD

**Issue by arthureggert** [release-it/release-it#526]
Hello, I was using release-it v10.x.x, and everything was fine, the versions number were generated based on the semver system.
Today I migrated to version 12.0.1, and the increment version is always minor.
Debugging the code I notice that on the task.js line 46 the lib is calling: 
```javascript
let version = await reduceUntil(plugins, plugin => plugin.getIncrementedVersionSync({ latestVersion }));
```

But the only plugin that has this method is the Version the conventional-changelog only has the 
```javascript
getIncrementedVersion
```
I'm doing something wrong here? Or it is a problem?

**Comment by webpro** [comment]
Sounds like the `increment` is provided directly, as this is the only way for `getIncrementedVersionSync` to return something. Are you executing it like this:

```
release-it minor
```

**Comment by arthureggert** [comment]
I'm execution on the CI enviroment, and I'm calling via script as
```javascript
const releaseItConfig = require('../.release-it');
.....
releaseIt(releaseItConfig).then(output => console.log(chalk.green(output)));
```

Yeah, the increment is null, and in the previous versions i never needed to pass any 'param', the version was always generated by looking at the commits.

**Comment by webpro** [comment]
Indeed, on a CI environment the default value is `patch` and that conflicts with this new `getIncrementedVersionSync` method. Will look into this soon.

You might want to try `release-it foo` or some invalid value for `increment` for the time being.

**Comment by arthureggert** [comment]
I downgraded to v10.x.x for now.

**Comment by webpro** [comment]
You inspired me to add this feature which turns out to be pretty simple: disable core plugins. Things should work now in [v12.2.0](https://github.com/release-it/release-it/releases/tag/12.2.0) with [@release-it/conventional-changelog@1.0.2](https://github.com/release-it/conventional-changelog/releases/tag/1.0.2). Please let me know how it works for you. Thanks!

**Comment by LeBenLeBen** [comment]
@webpro I'm using those two versions and encoutering the same bug. Whatever I specify as version, it always do a minor bump.

* `npm run release -- 1.0.0`
* `npm run release -- patch`

Current version is 0.1.0 (sync between git tag, package.json and package-lock.json) and the proposed bump is 0.2.0.

Here’s my config:
```
{
  "scripts": {
    "afterRelease": "npm run deploy",
    "afterBump": "npm run build"
  },
  "npm": {
    "publish": true
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": "angular",
      "infile": "CHANGELOG.md"
    }
  }
}
```

**Comment by webpro** [comment]
@LeBenLeBen Sounds like intended behavior, when using the conventional changelog (plugin). The recommended bump is determined automatically (based on the "angular" commit conventions). Why would you want to override this?

**Comment by LeBenLeBen** [comment]
@webpro I just like to have control over the release. I use it mostly for internal projects and it happens developers aren't making 100% correct commit messages which results in a not-so-correct bump being done. I work hard on respecting semver 100% but sometimes you want an explicit version to be released.

**Comment by webpro** [comment]
In that case you can file an issue or open a PR with the plugin: https://github.com/release-it/conventional-changelog
