### ISSUE TITLE
release-it does not exit when complete

### ISSUE THREAD

**Issue by jhnlsn** [release-it/release-it#527]
I'm using the latest version from npm 12.2.0.

release-it config file:
```json
{
    "npm": {
        "publish": false
    },
    "github": {
        "release": false
    },
    "scripts": {
        "beforeStart": "echo 'test'",
        "afterRelease": "echo 'done release'"
    }
}
```

when running `release-it minor --ci`, the output makes it all the way to echo 'done release', however it just hangs there. I can see that the new version was pushed to github, but release-it doesn't exit when done.  Am I missing something?

**Comment by jhnlsn** [comment]
The issue is because you are tracking events to google analytics... For those of you who might run into this issue in the future when behind a proxy, use `--disable-metrics`

**Comment by webpro** [comment]
That looks fine; haven't heard of this issue before. Any chance you could give it a spin like this, and see where/why it gets stuck:

```
DEBUG=release-it:* release-it minor --ci
```

**Comment by webpro** [comment]
Ah yes, being behind a proxy could be an issue, but there's a `300ms` timeout (without retries) so that would be a bug. Anyway, glad you can move on :)
