### ISSUE TITLE
Provide hooks stdouts

### ISSUE THREAD

**Issue by pierreroth64** [release-it/release-it#531]
On the way of making `release-it` more open to customization (please refer to "lifecyle hooks" work in progress), it would be great if the output of executed hooks were available in the following ones.

Imagine the following:
1. the user gives such an arg `--hooks.after:git:release="./my-build-script.sh"`
2. `my-build-script.sh` stdout is:

```
artefact: my-build-binary-v1.2.3.tar.gz
docs: my-build-docs-v1.2.3.tar.gz
logs: my-build-logs-v1.2.3.tar.gz
```
3. having this **raw** output available in the following hook /step would help a lot. Could be used to push such an asset list to github release

The idea is to have a means to store hooks stdouts during the release-it flow and make them available. 
🤔 ...in that case, why not such a var: `'${after.git.release.stdout}'` ?

⚠️ Important note: No stdout parsing: this would be delegated to the user scripts.

**Comment by webpro** [comment]
This is exactly the kind of flexibility that [plugins](https://github.com/release-it/release-it/blob/master/docs/plugins/README.md) provide. Did you see this?

Btw, for this specific example: you can use e.g. `github.assets: ["my-build-binary-${latestTag}.tar.gz"]` or `["my-build-*.tar.gz"]`

**Comment by pierreroth64** [comment]
Ok, let's go for a plugin. I'm always thinking about devs that do not know `JS` and would use `release-it` like a simple CLI.

**Comment by webpro** [comment]
I don't think you can have that kind of simplicity *and* dynamics/flexibility at the same time. Maybe you have an example of something similar?

Happy to hear your feedback/findings with regards to plugins as well :)
