### ISSUE TITLE
Option to disable semver inc

### ISSUE THREAD

**Issue by muuvmuuv** [release-it/release-it#534]
In my case I increase my version manually because I'm creating release files which have the version in it. Would be great to disable this feature and just use the package.json version that is present.

**Comment by webpro** [comment]
One option would be to provide that same version directly to release-it, e.g. `release-it 1.2.3` - if it's already available? Then a bump does basically nothing.

Or exclude bumping package.json from the manual process.

Or make the "creating release files" part of the release-it process somehow.

**Comment by muuvmuuv** [comment]
@webpro this works for the CLI but how about using it programmatically?

**Comment by muuvmuuv** [comment]
Works with 

```js
const options = {
  increment: pkg.version,
```

but now I get this error:

```
$ npm version 1.10.0 --no-git-tag-version

WARNING Did not update version in package.json etc. (already at 1.10.0).
$ - Added vsix file
- Removed scripts and use [release-it](https://github.com/release-it/release-it)

ERROR /bin/sh: - : invalid option
Usage:  /bin/sh [GNU long option] [option] ...
        /bin/sh [GNU long option] [option] script-file ...
GNU long options:
```

Seems like a problem with my Changelog? It is in Markdown.

**Comment by muuvmuuv** [comment]
Ah okay, solved it. I haven't read the section where it says that changelog needs to be a shell command which prints to stdout. Fixed this.
