### ISSUE TITLE
hooks.before:release does not allow adding/staging new files

### ISSUE THREAD

**Issue by rwjblue** [release-it/release-it#536]
I've been using `hooks.before:release` (and `beforeStage` before `hooks`) in order to do things like update documentation, but I've noticed that the files updated/changed by a `hooks.before:release` are not added before the `git commit` for the release.

Am I doing something wrong here?

Examples:

* https://github.com/ember-codemods/ember-native-class-codemod/blob/4e74a913c36a519422e784f1e9fb3da7888e9b4e/package.json#L63-L78
* https://github.com/emberjs/ember-test-helpers/blob/4ca1ad848e8346865c14e0e498f8a35f7a6cbe48/package.json#L108-L123

**Comment by webpro** [comment]
The first thing that comes to mind is that the updated/changed files are not in version control. If that's the case they either need to be manually `git add`-ed, or use `git.addUntrackedFiles` (although this will add all untracked files).

**Comment by Marsup** [comment]
Hi, I see the same thing, the files are already tracked though.

**Comment by rwjblue** [comment]
Confirm, for me the files are definitely previously tracked.

**Comment by webpro** [comment]
Found the culprit. The plugins have the `beforeRelease` and `release` methods. The Git plugin does the staging in the `beforeRelease` phase, in order to show the changeset before showing the "Commit?" question.

This means the hook you need is `before:beforeRelease` (or `before:git:beforeRelease`, or alternatively `after:bump`) in order to make changes before files are staged by Git. Naming is hard 🤦‍♂️

If interested, here's the line: https://github.com/release-it/release-it/blob/b2223f1d0a182e8e9ffe0280a6e1d35a773b4d32/lib/plugin/git/Git.js#L43

**Comment by rwjblue** [comment]
I had assumed that `before:release` hooks specified would run *before* the plugin's `beforeRelease` method (since they _seem_ like synonyms), which would have supported the usage in question. Is that not correct, do the `before:release` hooks specified run _after_ plugin's `beforeRelease` methods are called?

**Comment by rwjblue** [comment]
Either way, I think we need to tweak the README (it currently states that you should migrate from `scripts.beforeStage` to `hooks.before:release` which isn't quite right).

**Comment by webpro** [comment]
> do the `before:release` hooks specified run after plugin's `beforeRelease` methods are called?

Yes. The lifecycle methods are (in order): `init`, `beforeBump`, `bump`, `beforeRelease`, `release` and `afterRelease`. Each of them has a `before:*` and `after:*` hook.

> Either way, I think we need to tweak the README (it currently states that you should migrate from `scripts.beforeStage` to `hooks.before:release` which isn't quite right).

Indeed! Apologies for the confusion.

**Comment by mkay581** [comment]
This helped me out quite a bit, thanks @rwjblue! I specifically was a little confused between `before:release` and `before:beforeRelease`, but I think I understand the difference now.

**Comment by webpro** [comment]
@mkay581 @rwjblue Please let me know whether the docs in its current state should be improved regarding this :) Updated yesterday: https://github.com/release-it/release-it#hooks
