### ISSUE TITLE
Missing --no-increment option

### ISSUE THREAD

**Issue by mooyoul** [release-it/release-it#537]
Hello. I'd like to use release-it for my npm publish workflow.

It looks like `--no-increment` option was added at release-it@6 (#195), but latest version of release-it does not support this.

It's especially useful for me because it enables below workflow:

- Trigger CI build job when master branch has updated
- If given version never published to npm, publish it. or skip publish step

It gives me two benefits:
- Prevent unnecessary releases (e.g. when updated lint configuration, updated README...)
- Prevent unexpected version bump (e.g. when there are some breaking changes, we need to increase major version) - by managing package version manually

Is there any workarounds to skip releasing?

**Comment by webpro** [comment]
You're right, @mooyoul. Somehow it got lost in, probably, the v11 refactoring.

I restored this and it will back in v12.3.1, but there's some annoying issue in Windows tests I should fix first.

**Comment by webpro** [comment]
Released in [v12.3.1](https://github.com/release-it/release-it/releases/tag/12.3.1)
