### ISSUE TITLE
[question] How to configure for a branch for pre-releases (@next)

### ISSUE THREAD

**Issue by pirix-gh** [release-it/release-it#538]
Hi,

I have a `next` branch and I would like **release-it** to release the pre-releases on it (but only when I am checked on that `next` branch). Would this be possible, or something similar?

**Comment by webpro** [comment]
Do you basically mean it should add `--preRelease=next` if on the `next` branch? There is no such feature in release-it that does this automatically.

Should not be too hard to implement this manually in some little shell script. One basic idea:

```
if [ `git rev-parse --abbrev-ref HEAD` == "next" ]; then release-it --preRelease=next; else release-it; fi;
```

**Comment by pirix-gh** [comment]
Thank you, and thanks for this amazing project
