### ISSUE TITLE
release-it/test/util is not exported anymore

### ISSUE THREAD

**Issue by jtassin** [release-it/release-it#539]
Hello,

thx for your nice lib.
I am writing a new plugin (for a JIRA/github integration) and I have a testing problem.

`release-it/test/util` since to be not exported anymore in the package `release-it`.

It was dropped in this commit : https://github.com/release-it/release-it/commit/d5f8790106a183d393f4e57285f74923bc41fa4d

**Comment by webpro** [comment]
Ah indeed. Should be fixed in [v12.3.4](https://github.com/release-it/release-it/releases/tag/12.3.4) - thanks for the report!

**Comment by Marsup** [comment]
@webpro It went away with 13 as well, was it intentional?

**Comment by webpro** [comment]
No @Marsup, thanks for reporting this. I've just released [v13.0.1](https://github.com/release-it/release-it/releases/tag/13.0.1) that restores this dir. Will look into about a better solution later.
