### ISSUE TITLE
Please update documentation and working examples

### ISSUE THREAD

**Issue by ansidev** [release-it/release-it#540]
Currently, I don't see descriptions for release-it options config.
And there are no working examples for GitHub and GitLab.
Please update them! Thanks!

**Comment by webpro** [comment]
What descriptions do you think are missing exactly?

To get started with GitHub Releases, see https://github.com/release-it/release-it/blob/master/docs/github-releases.md. What do you think is missing here? I don't think I can provide a real working example that works for everyone, as the `GITHUB_TOKEN` is a personal (secret) token.

**Comment by ansidev** [comment]
Currently, this is my problem with GitLab. I 've read your GitLab documentation and find nothing can solve the problem.

https://gitlab.com/ansidev/vue-bible-verse/-/jobs/258859361

**Comment by ansidev** [comment]
I mentioned 2 points:
- Documentation for release-it options: you just mention some options in the documentation, no documentation for them.
- Working examples: currently, the guideline for setup ci/cd is missing many things.

There are many CI/CD software, so I can have experience with this one but not that one.
For example, with GitLab you are missing:
- A sample `.gitlab-ci.yml`.
- How to add env var to GitLab project to make the CI/CD can run smoothly?
- How to get GITLAB_TOKEN, NPM_TOKEN?
You can provide the link to the official doc or just write your own steps.

In my opinion, good documentation will help developers to answer their question by theirself.

**Comment by webpro** [comment]
```
✖ Git push
ERROR remote: You are not allowed to upload code.
fatal: unable to access 'https://gitlab-ci-token:[MASKED]@gitlab.com/ansidev/vue-bible-verse.git/': The requested URL returned error: 403
```

This is an authorization issue with access to the (Gitlab) repo from the CI environment when trying to `git push` commits to your repo.

Please mind that this has nothing to do with [GitLab Releases](https://docs.gitlab.com/ee/user/project/releases/index.html).

**Comment by webpro** [comment]
> There are many CI/CD software, so I can have experience with this one but not that one.

It sounds like you do expect me to know all of them and document all possible scenarios. That is not realistic and not helpful. I wrote this page: https://github.com/release-it/release-it/blob/master/docs/ci.md, which says:

> the CI/CD environment should be authenticated with the original host

That's your responsibility (e.g. release-it basically only executes the `git push` command). There are a few examples, and I'm happy to add more documentation for e.g. the GitLab CI/CD environment. I rely on people like you to raise issues and provide information to improve the documentation for different environments :)

Thanks for opening this issue and your suggestions, I'm going to see what I can improve. However, please note that I don't have an actual GitLab CI/CD environment setup, so I can't really try and test things currently.

**Comment by webpro** [comment]
I have tried to make the relationship between Git and GitHub/GitLab releases more clear in the readme (918180d). Feel free to discuss further if you have any remarks or questions!
