### ISSUE TITLE
feature_request(package_managers): presets

### ISSUE THREAD

**Issue by Kristinita** [release-it/release-it#542]
### 1. Summary

It would be nice, if release-it will add/change release files for popular package managers as [**PyPI**](https://pypi.org/) or [**Package Control**](https://packagecontrol.io/).

### 2. Argumentation

For package release package developers not solely add changes to `CHANGELOG.md`, they add/update some other files. Currently, each developer need write own script. The script might look like [**this**](https://kristinita.netlify.com/it-articles/fastest-way-to-add-new-version-of-sublime-text-3-package#release-itjson):

```json
{
    "buildCommand": "changelog -f - -u https:\/\/${repo.host}\/${repo.repository} | tee messages\/${version}.txt | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md && sed -i '\/\\\"install\\\": \\\"messages\\\/install\\.txt\\\"\/i\\\"${version}\\\": \\\"messages\\\/${version}\\.txt\\\",' messages.json && js-beautify -r messages.json"
}

```

Each of many (for 8.4.2019 Package Control have [**4822 packages**](https://megalodon.jp/2019-0805-0006-05/https://packagecontrol.io:443/stats), PyPI — [**190569**](https://megalodon.jp/2019-0805-0007-28/https://pypi.org:443/)) developers must spend his time writing this script for standard releases.

It would be nice, if release process will be simpler. For example, that developers need to add solely 2 lines to `.release-it.yaml`:

```yaml
preset:
  $selected_preset$: true
```

release-it will add/change files in the same stage as [**change `CHANGELOG.md` or `history.md`**](https://github.com/release-it/release-it/blob/master/docs/changelog.md#changelog).

#### 3.1. PyPI

```yaml
preset:
  pypi: true
```

Run release-it → release-it make [**update**](https://kristinita.netlify.com/it-articles/how-to-publish-your-package-to-pypi-2018#Demonstration-1) version in `setup.cfg` or `setup.py` (see [**discussion**](https://github.com/pypa/packaging.python.org/issues/378) about formats in official PyPA issue tracker):

+ for `setup.cfg`:

    ```text
    version = ${version}
    ```

+ [**for `setup.py`**](https://github.com/pypa/sampleproject/blob/388156a01d3ca549b25fdfbf6108072790d30b0a/setup.py#L46):

    ```python
    version='${version}'
    ```

#### 3.2. Package Control

```yaml
preset:
  package_control_messages: true
```

release-it make [**these actions**](https://kristinita.netlify.com/it-articles/fastest-way-to-add-new-version-of-sublime-text-3-package#Demonstration):

1. Add line to `messages.json`:

    ```json
    "${version}": "messages/${version}.txt"
    ```

1. Add file `messages/${version}.txt` with content `${git.changelog}`.

See “[**Messaging**](https://packagecontrol.io/docs/messaging)” official documentation article for details.

#### 4.1. Developers have different custom configuration

It would be nice automatically add standard configuration. If developer want custom, he is not obliged add `preset:` to `.release-it.yaml`.

Thanks.

**Comment by webpro** [comment]
This is exactly what [plugins](https://github.com/release-it/release-it/blob/master/docs/plugins.md) are meant for. For instance, release-it internally uses the `git`, `github`, `gitlab`, and `npm` plugins.

I'm happy to help out with additional plugins for any language and/or package manager, etc.

**Comment by Kristinita** [comment]
Yes, this issue is still relevant.

Thanks.

**Comment by webpro** [comment]
Please implement plugins for this. Although I actually think by putting build and publish commands in hooks and using the bumper plugin people can accomplish a lot (without custom plugins).
