### ISSUE TITLE
ERROR 422 Unprocessable Entity (Validation Failed)

### ISSUE THREAD

**Issue by crimson-med** [release-it/release-it#544]
# Information

**release-it global version:**
```
12.3.5
```

**os**
```
MacOs Mojave
```

# The bug

**What I expect**
For the github release to be pushed

**What happened**
![image of error](https://i.imgur.com/YbyprKh.png)

**Configuration**

```json
{
  "git": {
    "tagName": "v${version}",
    "pushRepo": "https://github.com/xxxxx/xxxxx.git"
  },
  "github": {
    "release": true
  },
  "hooks": {
   "before:init": "echo please run: export GITHUB_TOKEN=\"xxxxx\"",
   "after:bump": "git push xxxxx master",
   "after:git:release": ["ssh -t ec2-user@xxxxx 'sudo ./pack.sh v${version}'","ssh -t ec2-user@xxxxx 'sudo ./unpack.sh v${version}'", "ssh -t ec2-user@xxxxx 'sudo ./unpack.sh v${version}'"],
   "after:release": "echo Successfully released ${name} v${version} to ${repo.repository}.\n"
 }
}
```
I have exported my token in the environment with:
```
export GITHUB_TOKEN="xxxxx"
```
I have just managed to do a patch to 0.0.5 and the github release was created with no problems.

GitHub releases work for Patch
GitHub releases don't work  for Minor

No idea for major

**Comment by webpro** [comment]
What I think might go wrong here: the Git tag must be present in the GitHub repo where the Release is created. But I see a `git.pushRepo` configured, so maybe the tag is pushed to a different remote than where the GitHub Release is tried to be created?

I also see the `git push xxxxx master` hook command, maybe adding the `----follow-tags` argument here solves the issue.

**Comment by crimson-med** [comment]
For our architecture I have in my git config two repos:
```
[remote "origin"]
	url = ssh://ec2-user@xxxxxx.xxxxxx.com/opt/git/xxxxxx.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[remote "redlan"]
	url = ssh://ec2-user@xxxxxx/opt/git/xxxxxx.git
	fetch = +refs/heads/*:refs/remotes/xxxxxx/*
```

So the idea is we have our dev server which is the `origin` then we have the `redlan` server which is the staging server with the client.

Then we want to publish the release just on the github.com

should I add in my git config the github.com as a pushurl? 

**However I do not see why this would be a difference between releasing a minor or a patch**

**Comment by webpro** [comment]
> should I add in my git config the github.com as a pushurl?

The Git tag must be there in the GitHub origin before creating the GitHub Release. So yes, this is a solution.

> However I do not see why this would be a difference between releasing a minor or a patch

I don't think this is related to the issue. Maybe the configuration was changed between those releases?

**Comment by crimson-med** [comment]
> > should I add in my git config the github.com as a pushurl?
> 
> The Git tag must be there in the GitHub origin before creating the GitHub Release. So yes, this is a solution.
> 
> > However I do not see why this would be a difference between releasing a minor or a patch
> 
> I don't think this is related to the issue. Maybe the configuration was changed between those releases?

The configuration didnt change I did the command: `release-it` and chose minor it crashed so I did the same command and chose patch and it worked.

**Comment by webpro** [comment]
> The configuration didnt change I did the command: release-it and chose minor it crashed so I did the same command and chose patch and it worked.

There's no logical difference between a patch and a minor bump in this context, in the end it's just a (semver-compliant) tag name. Maybe GitHub had a hiccup or caching issue when processing the tag.

> It says here there's an error on missing fields. https://developer.github.com/v3/#client-errors

It could also be an `invalid` or a `missing` tag. You can debug it using `DEBUG=release-it:* release-it [...]` and check the logs (including GitHub requests and responses).

**Comment by crimson-med** [comment]
After retrying a minor 0.1.0 which didn't work and a patch 0.0.6 which worked. 
I decided to uninstall release-it and reinstall it and this fixed the problem I was now able to push a Minor 0.1.0
