### ISSUE TITLE
Relative paths to dist/ folders above [Angular Library]

### ISSUE THREAD

**Issue by Disane87** [release-it/release-it#546]
Hey man,

I'm just developing a bunch of angular libs and I want to release them as I need. I just discovered, the released npm packages since the usage of this tools are all broken, because the sources are packaged and not the build and compiled sources.

My project structure:
![image](https://user-images.githubusercontent.com/956158/63084234-0a6ed980-bf4b-11e9-9842-736273f67f9a.png)

The libs are under `./projects/[lib name]` but the compiled are under `./dist/[lib name]`. I execute `release-it` from the source folder under `./projects`. In the config I have defined, that the assets should be fetches from `../../dist/[lib name]` but thats not working. Your script could not go up and fetch the sources. Any help here?

My config:
```
"release-it": {
    "git": {
      "tagName": "v${version}",
      "requireCleanWorkingDir": false,
      "addFiles": [
        "package.json",
        "CHANGELOG.md"
      ],
      "assets": [
        "dist/ngx-taskboard/*.zip"
      ],
      "changelog": "npm run changelog",
      "requireUpstream": true,
      "requireCommits": false,
      "addUntrackedFiles": false,
      "commit": true,
      "commitMessage": "Release ${version}",
      "commitArgs": "",
      "tag": true,
      "tagAnnotation": "${version}",
      "tagArgs": "",
      "push": true,
      "pushArgs": "--follow-tags",
      "pushRepo": "origin"
    },
    "github": {
      "release": true,
      "releaseNotes": "npm run changelog-stdout --silent",
      "assets": [
        "dist/ngx-taskboard/*.zip"
      ]
    },
    "hooks": {
      "before:init": [
        "npm run lint",
        "npm test"
      ],
      "after:bump": "npm run build && npm run changelog",
      "after:git:release": "echo After git push, before github release",
      "after:release": "echo Successfully released ${name} v${version} to ${repo.repository}."
    }
  },
```

**Comment by webpro** [comment]
The `git.assets` option is not known to release-it, it does nothing. Also, in general, you should not check such generated dist files into the Git repo.

If you want to publish the files from e.g. `dist/ngx-taskboard` (i.e. run `npm publish` as if you would be in that folder), you can set the `npm.publishPath` to `dist/ngx-taskboard`.

**Comment by Disane87** [comment]
I guess 

> If you want to publish the files from e.g. dist/ngx-taskboard (i.e. run npm publish as if you would be in that folder), you can set the npm.publishPath to dist/ngx-taskboard. Edit: or ../dist/ngx-taskboard depending from where you run release-it.

Was the missing hint. Will try that later!

**Comment by Disane87** [comment]
@webpro `npm.publishPath` was the hint! Thank you for the assistance! :)
