### ISSUE TITLE
Option to not modify package.json?

### ISSUE THREAD

**Issue by zanedev** [release-it/release-it#549]
Hi I only want to tag and release, no commit or push which is working well with the provided options but I don't want to rely on a version in or modify `package.json`.

I have release-it using the latest tag rather than a version in package.json but it adds the version to package.json after it runs so it leaves modified files when it's done.  Is there a way to have it not modify package.json if not using it or not commiting or pushing?

I've tried setting `npm: false` in my config below but that threw unexpected errors and killed the release.

I'm using release-it as a library and not through the command line, here is my current config:

```
release({
	'non-interactive': true, // ci mode
	verbose: true,
	increment: 'prerelease',
	preReleaseId: 'dev',
	// don't commit anything just create release, tag, and upload the files
	git: {
		commit: false,
	},
	github: {
		preRelease: 'dev',
		release: true,
		assets: ['dist/*.gz'],
	},
	npm: {
		publish: false,
	},
});
```

**Comment by webpro** [comment]
Can you please share logs/trace of the error(s) when using `npm: false`? This is supposed to work properly (e.g see [this test](https://github.com/release-it/release-it/blob/1d64aad4b2f0ad5216f0aaf55c1f1bcf434839b8/test/tasks.js#L83-L92)).

By the way, the `github.preRelease` is supposed to be a boolean (not `"dev"`, probably casted to `true`).
