### ISSUE TITLE
Is it possible to build and pack into another branch and tag that branch?

### ISSUE THREAD

**Issue by caasi** [release-it/release-it#550]
I usually work for companies without their own npm registry. So I have to source control output files.

I'm wondering if `release-it` can help me packing output files into another branch and tag that branch only?

**Comment by webpro** [comment]
It doesn't feature this out-of-the-box. You can release from non-master branch if you like. And/or use [hooks](https://github.com/release-it/release-it#hooks) to customize the process to your needs.

**Comment by caasi** [comment]
Thank you. I will take a look.
