### ISSUE TITLE
publish github release to a different repo

### ISSUE THREAD

**Issue by inlife** [release-it/release-it#556]
Hello,

Is there a way to keep all the actions related to creating git tags, and pushing bump commits happen in the local git repository, however, to push a new github release onto an external repo?

So let's say in case the general codebase is located in a private repository, you still could release freshly built binary files to an empty `releases` repository.

Cheers!

**Comment by webpro** [comment]
A GitHub release requires the tag to exist, so I think your workflow should first take this into account.
