### ISSUE TITLE
Please stop push all branches

### ISSUE THREAD

**Issue by LastDragon-ru** [release-it/release-it#559]
I have several clones (one for each major version) of app repo, I want to create a new release for one of the. In most cases, I miss pull/fetch/sync :( and the result is:
![phpstorm64_SMcX25Zhlc](https://user-images.githubusercontent.com/1329824/65680611-5e9bcc00-e068-11e9-8bc8-732f08a56402.png)

and I should remove tag, reset branch, and rerun release-it. This is very annoying :(

So, is there any reason why `release-it` trying to push all branches instead of the current branch?

**Comment by webpro** [comment]
The default for `git.pushArgs` is `--follow-tags`, but you can override this (e.g. `--tags`).

Also see:

* https://github.com/release-it/release-it/blob/master/docs/git.md#extra-arguments
* https://github.com/release-it/release-it/blob/c5634478a50faa4270d8703cd5ede93f9e5c0853/conf/release-it.json#L17

**Comment by LastDragon-ru** [comment]
@webpro, thank you. Unfortunately, I'm not sure that will be useful in my case, seems I need 

```
git push origin HEAD
```

but `pushArgs` cannot be used in this case, because args will be added before `origin` (upstream)

https://github.com/release-it/release-it/blob/c349342af809cb32db4ca572495cf682d4635af3/lib/plugin/git/Git.js#L154

**Comment by webpro** [comment]
I think you need to push the new tag, right? With `--tags`.

**Comment by LastDragon-ru** [comment]
Sure, so

```
git push --tags origin HEAD
```

**Comment by webpro** [comment]
For my understanding, what's the difference with `git push --tags origin`? What goes wrong for you?

**Comment by LastDragon-ru** [comment]
> `git push ... origin`

Push all branches (current behavior)

> `git push ...  origin HEAD`

Push the current branch only (desired behavior).

**Comment by webpro** [comment]
Maybe this workaround could do the job for you:

```
{
  "hooks": {
    "after:git:release": "git push origin HEAD"
  },
  "git": {
    "push": false
  }
}
```

**Comment by LastDragon-ru** [comment]
> Maybe this workaround could do the job for you:

Awesome 🎉 Thank you!

And the reason why I want this:
![image](https://user-images.githubusercontent.com/1329824/66398479-e087df80-e9ee-11e9-897b-34b780dd1b5a.png)

- `git push --follow-tags origin` - will fail ("Updates were rejected because the tip of your current branch is behind")
- `git push --follow-tags origin HEAD` - release created successfully

**Comment by webpro** [comment]
Great to hear it works for you! I'll add this to the docs soon. Maybe try to implement something so no workaround is needed. Closing this for now.

**Comment by tiagoboeing** [comment]
Any updates or workarounds about this?
