### ISSUE TITLE
feature request: release package to GitHub

### ISSUE THREAD

**Issue by brandonkal** [release-it/release-it#560]
The result of `npm pack` should be uploaded to GitHub by default when a GitHub release is made.

**Comment by webpro** [comment]
Why do you think this should be the default? I think there can be many files output by `npm pack` that should generally not be part of a GitHub release.

**Comment by brandonkal** [comment]
1. I am speaking specifically of JS projects that are also being published to a centralized package manager like npm.
2.  GitHub releases contain a zip of all source files. So `npm pack` will inherently contain less files.
3. One expects a release to be consumable in a project. This is the main point. Otherwise a GitHub release is just a fancy changelog entry.
4. Users would not need to rely on npm as the only source for said release.

**Comment by webpro** [comment]
Do you know about https://github.com/features/package-registry? Sounds like this is basically what you're after.
