### ISSUE TITLE
Bump package.json with npm disabled

### ISSUE THREAD

**Issue by lnmunhoz** [release-it/release-it#564]
I would like to use the bump package.json feature but don't publish to npm.

Currently if I set `npm: false` in my config, it will disable version bumping as well, which I think is not related.

Is there anyway to use only package bumping in a easy way without having to write a plugin?

By the way, great package!

**Comment by webpro** [comment]
Use ‘npm.publish: false’

**Comment by lnmunhoz** [comment]
That didn't worked 😅 

It still asks me to publish to npm.

- release-it version: 12.4.3.
- My config:
```
module.exports = {
  git: {
    commitMessage: 'chore(release): ${version}',
  },
  'npm.publish': false,
};

```

**Comment by webpro** [comment]
Oh sorry, I mean it should look like this:

```js
module.exports = {
  git: {
    commitMessage: 'chore(release): ${version}',
  },
  npm: {
    publish: false
  }
};
```

**Comment by lnmunhoz** [comment]
Works!

Thank you!

**Comment by webpro** [comment]
You're right, it was totally missing. Added in 19ab91c
