### ISSUE TITLE
[Help] Bump the version ignoring NPM and Git tag

### ISSUE THREAD

**Issue by vinyoliver** [release-it/release-it#565]
Hi,

I was wondering if is it possible to bump the version without have to look for Git tags or NPM. I just want to consider the version in my package.json locally;

Is it possible?

**Comment by webpro** [comment]
You can skip the Git tasks (please see docs), but npm is required to bump the version in package.json.

**Comment by vinyoliver** [comment]
Unfortunately, I couldn't figure out what I needed. I believe there's no way to achieve this (bump the version ignoring git tags and also ignoring npm publish).

I've managed to achieve what I need by bumping the version manually using: `npm --no-git-tag-version version patch`

Anyway, it's a great plugin! tks for the fast response.

**Comment by webpro** [comment]
For your use case I think you could use `--no-git` and `--no-npm.publish`.

But if you can do it using `npm` directly, then that would obviously more efficient.
