### ISSUE TITLE
File package.json does not exist

### ISSUE THREAD

**Issue by hernanmd** [release-it/release-it#566]
After reading the documentation, it is not clear for non-JavaScript projects (I want to release a bash based project) if I really need to create package.json to use auto-changelog. Example output:

> 
> $ release-it 0.4.5
> 
> 🚀 Let's release pi (0.4.4...0.4.5)
> 
> > 
> > Changelog:
> > _(Nothing yet)_
> > 
> > ⠙ npx auto-changelog -p
> > auto-changelog: Generating changelog…
> > ✖ npx auto-changelog -p

This is my .release-it.json
```

{
    "git": {
        "commitMessage": "Release v${version}",
        "tagAnnotation": "Release v${version}",
        "requireCleanWorkingDir": false,
        "changelog": "npx auto-changelog --stdout --commit-limit false -u --template ./.changelog.hbs" x       
    },
    "github": {
        "release": true,
        "releaseName": "v${version}",
        "tokenRef": "GITHUB_TOKEN"
    },
    "npm": {
        "publish": false
      },
    "hooks": {
        "after:bump": "npx auto-changelog -p"
      },
    "plugins": {
        "@release-it/conventional-changelog": {
          "preset": "cli",
          "infile": "CHANGELOG.md"
        }
    }
  }
```
  
Should I create a minimal package.json anyway?

Update 1: I created the initial CHANGELOG.md using auto-changelog and re-ran release-it:

```
 release-it 0.4.5
ERROR Cannot find module '@release-it/conventional-changelog'
Require stack:
- /Users/testuser/git_projects/pi/noop.js
```

Is there any additional setting for disabling npm plugin? I thought the following would be just enough:

```
    "npm": {
        "publish": false
      }
```

**Comment by webpro** [comment]
A few things here:

* Looks like `auto-changelog` (3rd-party) requires a `package.json` (release-it does not require it). To use it locally, it makes sense to install it with `npm` (and this requires a `package.json`).
* If you want to use `@release-it/conventional-changelog`, it should be installed. For this it's good to install it locally to the project, which also requires a `package.json`.
* I think you should use either `auto-changelog` or `@release-it/conventional-changelog`. Or none, to go without a `package.json`, and the GitHub release notes will consist of the output of `git log [..]` (the `git.changelog` command).
* To disable the `npm` plugin entirely, you can use `"npm": false`. The `npm` plugin is also disabled if there is no `package.json`.
