### ISSUE TITLE
Pre-release auto version increment

### ISSUE THREAD

**Issue by zanedev** [release-it/release-it#567]
We're skipping npm publish and I'm not using package.json for versions so it was incrementing the version from the tags no problem like `Release 1.0.17-dev.37` to `Release 1.0.17-dev.38` and when I changed the `preReleaseId` to something different like `prod` the releases became `Release 1.0.17-prod.0` which is good but now if I change it back to do a `dev` prerelease after the `prod` release it's resuming from the last version `prod` was on like `Release 1.0.17-dev.1` etc but that tag already exists because I've been doing dev releases all along.

Is there a way to have `release-it` automatically figure out and resume where the latest `preReleaseId` left off?  Thanks

**Comment by webpro** [comment]
Unfortunately not... I guess one thing you can do is to explicitly pass the next version once (e.g. `Release 1.0.17-dev.39` as per your example) and take it from there.
