### ISSUE TITLE
Prevent versioning directory in asset (.tar.gz,.zip)

### ISSUE THREAD

**Issue by hernanmd** [release-it/release-it#569]
I want to release my asset file in such way to be decompressed/untarred in a **generic** sub-directory instead of a versioned sub-directory:

my_app/

instead of

my_app-0.0.1/
my_app-0.0.2/
...

Is this possible with the current release-it?

**Comment by webpro** [comment]
If I understand correctly, you are doing GitHub releases, and you want to customize the name of the downloaded assets, right?

The default assets that GitHub always creates (e.g. https://github.com/release-it/release-it/archive/12.4.3.zip) are downloaded by the browser as e.g. "release-it-12.4.3.zip", which is by default extracted to a folder with the same name (without the ".zip") extension). All of this is outside the control of release-it.

You can extract a file such as "release-it-12.4.3.zip" to any directory you want, but you'd need to customize the command for this.

You could add an additional asset to the GitHub release with the specific name you want, but that would be unnecessarily redundant in my book.

**Comment by hernanmd** [comment]
Yes exactly, I try to go from a downloaded mypkg-1.2.3.tar.gz to mypkg/ but as I imagined this is a GitHub issue. I will check how other bash projects install mypkg in the same $HOME user path across subsequent versions.

Thank you Lars!
