### ISSUE TITLE
Flow like in ship.js

### ISSUE THREAD

**Issue by jeetiss** [release-it/release-it#575]
Hello 
release-it is so nice, but guys from algolia make ship-js with better release flow.

Main question is can I make similar flow with release-it?

flow:
```
1 step: release-it creates PR with auto changelog and bumped version
2 step: I fix some messages and merge PR
3 step: release-it creates github release and publish to npm
```

**Comment by webpro** [comment]
Creating a PR and then do things manually is not really the philosophy of release-it.

However, for the draft GitHub release you can use `github.draft`, and you have essentially the same.

In theory you could use hooks (to create branch, PR), and things like `github.draft` and `npm.publish: false` for the first run. Then, do manual things. And in the second run of release-it, use a fixed version and `git.commit: false` etc. etc. Let me know if you try this route and whether I can help you out with this.
