### ISSUE TITLE
release-it doesn't appear to work when trying to run in CI with github actions

### ISSUE THREAD

**Issue by jamesla** [release-it/release-it#578]
My config works fine however when I run in a CI environment (github actions) using npm run release -- minor --ci I get the following error.

```
ERROR Unable to fetch from https://github.com/jamesla/test-pkg
fatal: could not read Username for 'https://github.com': No such device or address
```

I am not sure why it is trying to fetch. I even configured commit to false but it still seems to want to try and fetch (it shouldn't need to fetch anything - it already has the repo). 

my config is as follows:
```
"release-it": {
    "github": {
      "release": true
    },
    "git": {
      "requireUpstream": false,
      "requireCleanWorkingDir": false,
      "commit": false
    }
  }
```

Why am I getting this error and how do I prevent it?

**Comment by webpro** [comment]
It always does a `git fetch` to make sure the latest commits/tags are in. And if it can't fetch, chances are it will not be able to push either.

Please also see #554.

**Comment by jamesla** [comment]
Ok thanks @webpro I've had a read through that other issue but I'm still super confused.

I've ensured an SSH key is installed on my CI server and have verified it's working with ssh -v git@github.com which comes back saying it recognises me.

I added a pushConfig that uses ssh and my package.json looks like the following:

```
"release-it": {
    "github": {
      "release": true
    },
    "git": {
      "requireUpstream": false,
      "requireCleanWorkingDir": false,
      "pushRepo": "git@github.com/jamesla/test-pkg.git"
    }
  }
```

And still getting this error:
```
ERROR Unable to fetch from git@github.com/jamesla/test-pkg.git
13
fatal: could not read Username for 'https://github.com': No such device or address
```

Why does it keep trying to use https rather than git protocol to fetch?

**Comment by jamesla** [comment]
ok so got a bit further by setting
```
git config --global --add url."git@github.com:".insteadOf "https://github.com/"
```

However when it tries to perform the commit
```
ERROR error: The destination you provided is not a full refname (i.e.,
starting with "refs/"). We tried to guess what you meant by:

- Looking for a ref that matches 'HEAD' on the remote side.
- Checking if the <src> being pushed ('HEAD')
  is a ref in "refs/{heads,tags}/". If so we add a corresponding
  refs/{heads,tags}/ prefix on the remote side.

Neither worked, so we gave up. You must fully qualify the ref.
hint: The <src> part of the refspec is a commit object.
hint: Did you mean to create a new branch by pushing to
hint: 'HEAD:refs/heads/HEAD'?
error: failed to push some refs to 'git@github.com:weprospect/ui-framework'
```

What is this talking about?

**Comment by jamesla** [comment]
ok it turns out to be something wierd with the github checkout action

can fix it by using the version 2 beta

```
- uses: actions/checkout@v2-beta
```

**Comment by webpro** [comment]
OK. By the way, `pushRepo` is only used by release-it when doing `git push`.
