### ISSUE TITLE
Trying to work out a sensible release flow that works with release-it?

### ISSUE THREAD

**Issue by jamesla** [release-it/release-it#579]
I have hooked release-it up to my release pipeline and I am trying to work out a workflow that works with CI and keep the package.json file up to date with the github release.

1. If I run the release on merge to master then it will obviously end up in an infinite loop where it makes a deploy then updates the package.json file and then deploy that and then increment the package.json file etc etc.

2. If I don't push the update back then my package.json becomes out of date.

3. I thought about using github tags however I would have to keep the package.json file version number up to date which is what I'm trying to avoid.

What is a sensible automated CI driven release pattern are other people using with release-it in order to automatically build packages and at the same time keep the package.json and github releases all in sync? 

What has worked for others?

**Comment by webpro** [comment]
> If I run the release on merge to master then it will obviously end up in an infinite loop

If the release is only triggered when merging to master, there should be no infinite loop, right?

If any commit to master triggers a release, you could add `[ci-skip]` or similar for your specific CI environment to the `git.commitMessage` option.

**Comment by jamesla** [comment]
ci-skip tag worked thanks
