### ISSUE TITLE
Where to create the GITHUB_TOKEN environment variable?

### ISSUE THREAD

**Issue by elvticc** [release-it/release-it#581]
"Make sure the token is available as an environment variable" on [Node.js](https://dev.to/numtostr/environment-variables-in-node-js-the-right-way-15ad) or the [OS](https://apple.stackexchange.com/questions/356441/how-to-add-permanent-environment-variable-in-zsh) ? 🤔

Thanks for your help.

**Comment by webpro** [comment]
From the OS, then release-it will pick it up when it runs (from e.g. `process.env.GITHUB_TOKEN`).

Personally, I like to permanently add it to something like a `.bash_profile` so it's always available when I open a terminal.

**Comment by elvticc** [comment]
Thanks a lot. Have a nice day.
