### ISSUE TITLE
Enforce releases only on master/specific branches?

### ISSUE THREAD

**Issue by franzese** [release-it/release-it#584]
I've been reading the docs, my apologies if I've missed this but is there a way to configure the use of `release-it` to only work on a specific branch, such as master, or set of branches? 

Thanks

**Comment by franzese** [comment]
Solved this by using this simple [shell script I wrote](https://gist.github.com/franzese/eef732ebf9fdd68ceec91c644e00122a) and using this configuration 
`"hooks": { "before:init": "./bin/is-on-master.sh" }`

**Comment by ystarlongzi** [comment]
@walokra Can this feature be integrated into the tool? Like [np](https://github.com/sindresorhus/np#usage)

**Comment by webpro** [comment]
It's indeed a good feature to have built-in. I'll re-open this to keep it on the radar!

**Comment by webpro** [comment]
I've added this in [v12.6.0](https://github.com/release-it/release-it/releases/tag/12.6.0).

Also see https://github.com/release-it/release-it/blob/master/docs/prerequisites.md#required-branch
