### ISSUE TITLE
Unable to render template with context: ${latestVersion} or ${latestTag}

### ISSUE THREAD

**Issue by franzese** [release-it/release-it#585]
I'm trying to basically copy this repo's GitHub release notes configurations from [the docs](https://github.com/release-it/release-it/blob/master/docs/github-releases.md) but having a couple issues recreating it successfully 

1. ~~Cannot find the script `generate-release-notes.sh` as I had expected to find it somewhere in the project, "no worries" I thought because there is a simpler one-liner in the default git `changelog` config I can use`"git log --pretty=format:\"* %s (%h)\" ${latestTag}...HEAD"`  which leads me to...~~
2. The `${latestTag}` and `${latestVersion}` both throw errors when referenced in the `github` config. It is late but am not sure what I am missing here so some help would be greatly on either of these fronts.

**Comment by franzese** [comment]
I didn't find `generate-release-notes.sh` but [I wrote one myself!](https://gist.github.com/franzese/6254548f234cd2b76d5af7433fc813e4)

**Comment by webpro** [comment]
There's indeed no such shell script in this repo, it was meant as a "placeholder" and you picked it up by writing one custom script yourself. Great!

I'll keep this ticket open and investigate the other issue you mention shortly.

**Comment by webpro** [comment]
The following variables are available in `github.releaseName`:

```
${version}
${latestVersion}
${github.latestTagName}
${github.tagName}
```
