### ISSUE TITLE
Wrong incrementation on prepatch

### ISSUE THREAD

**Issue by Sharcoux** [release-it/release-it#588]
Maybe I'm misunderstanding how prepatch is supposed to work, but I was at 0.10.4, I then did a prepatch and went to 0.10.5-0. I want to release the next prepatch this is considered to be 0.10.6-0. Shouldn't it be 0.10.5-1?

Thanks for your very helpful package!

**Comment by webpro** [comment]
- A prepatch when on 0.10.5 results in 0.10.6-0.
- When on 0.10.5-0 there was also a higher version 0.10.5, so the prepatch after this became 0.10.6-0.

**Comment by Sharcoux** [comment]
My bad. I was on 0.10.4. I messed up in my question.

**Comment by webpro** [comment]
> After 0.10.5-0 should be 0.10.5-1, no?

Yes. What command(s) did you use? I guess a `release-it prepatch` and/or the `--preRelease` argument?

**Comment by Sharcoux** [comment]
I was using the prompt that let you choose between patch, minor, major, prepatch, preRelease, and other.
I will try on a new version to see if it happens again.

**Comment by Sharcoux** [comment]
Ok, I'm with v 12.4.3.

**Comment by webpro** [comment]
I'm going to close this issue for now. Feel free to re-open when you encounter any issues. By the way, release-it uses the [semver](https://www.npmjs.com/package/semver) package.

**Comment by Sharcoux** [comment]
I can confirm the bug. I was on 11.0,
prepatch -> 11.0.1-0,
next prepatch is 11.0.2-0

v12.4.3

**Comment by Sharcoux** [comment]
@webpro I cannot re-open. I don't have enough privilege...

**Comment by webpro** [comment]
I can indeed reproduce this using the version selector in interactive mode.

I always use `release --preRelease` for continuation pre-releases.

But I'll leave this open as this is definitely a bug I'll fix soon.

**Comment by webpro** [comment]
Should be fixed in [v12.5.0](https://github.com/release-it/release-it/releases/tag/12.5.0)
