### ISSUE TITLE
"Dirty" release page

### ISSUE THREAD

**Issue by reintroducing** [release-it/release-it#590]
OK, this one is indeed an issue (unlike my last bug report) that I can't seem to wrap my head around. My changelog gets generated correctly but my releases page is a bit messy and I can't figure out why.

CHANGELOG
<img width="708" alt="Screenshot 2020-01-20 15 32 01" src="https://user-images.githubusercontent.com/259901/72761697-0b5f0380-3b9a-11ea-877e-9c2d760c881c.png">

RELEASES PAGE
<img width="1006" alt="Screenshot 2020-01-20 15 32 35" src="https://user-images.githubusercontent.com/259901/72761720-1b76e300-3b9a-11ea-9284-66b5a79ce73d.png">

and releases further down the page...
<img width="960" alt="Screenshot 2020-01-20 15 33 08" src="https://user-images.githubusercontent.com/259901/72761742-2e89b300-3b9a-11ea-95e4-573da6c97bfc.png">

As you can see, not only are the commits in 4.0.4 (from the changelog) not listed under the 4.0.4 release but the prior releases are being listed under there as well.

My config:
```js
module.exports = {
    hooks: {
        'after:bump': 'npx auto-changelog -p',
        'after:release':
            'echo Successfully released ${name} v${version} to ${repo.repository}.',
    },
    git: {
        changelog:
            'npx auto-changelog --stdout --commit-limit false --template ./ci-cd/changelog.hbs',
        commitMessage: 'release: Generated v${version}',
    },
    github: {
        release: true,
    },
    npm: {
        publish: false,
    },
};
```

What am I doing wrong? I appreciate any help offered.

**Comment by webpro** [comment]
What I can see at a glance, is that the `git.changelog` command misses the `-u` argument for `auto-changelog`.
