### ISSUE TITLE
Google Analytics Ping

### ISSUE THREAD

**Issue by felixdorn** [release-it/release-it#591]
Hello,

Could be possible to have a global config to disable Google Analytics in every command ? Instead of adding `--disable-metrics`

I do not want to send anything to Google even if this is about how i use your tool .

cf [lib/metrics.js](/blob/master/lib/metrics.js)
Related #385

**Comment by webpro** [comment]
Try this in your config (`.release-it.json`):

```
{
  "disableMetrics": false
}
```
