### ISSUE TITLE
Dont Works yarn test

### ISSUE THREAD

**Issue by JotaP13** [release-it/release-it#593]
Hi, when i do release and in before:init option do the "yarn test" terminal becomes freeze and dont do the next steps.

My yarn version is 1.21.1
I do test with jest 24.9.0
The proyect is in Vue 2.6
My system is Windows 10

Thanks fo all.

**Comment by webpro** [comment]
Sounds like a duplicate of #574. Please check my latest comment and see if that works for you. Thanks!
