### ISSUE TITLE
Trigger release-it before merge

### ISSUE THREAD

**Issue by benpetsch** [release-it/release-it#595]
How to trigger release-it before before merging to the master branch?

How do you handle major / minor release in that case?

Can you provide a small example or am I missing something?

**Comment by webpro** [comment]
Not sure what your question is.

You can run release-it from any branch. This is unrelated from the type of bump (major/minor).

If you can tell/show me more about your use case, I'm happy to help out.

**Comment by benpetsch** [comment]
I'm struggling with two questions

1. How to trigger release-it automatically on merge to master branch?

2. How to read major / minor / patch bump from commit messages?

**Comment by webpro** [comment]
1. I think you'll need to configure/script your CI environment for this. (Or perhaps use a Git merge hook for a local environment to automate this.)
2. For one idea, please see [conventional changelog](https://github.com/release-it/release-it/blob/master/docs/changelog.md#conventional-changelog).
