### ISSUE TITLE
can i use release-it to publish only the dist folder?

### ISSUE THREAD

**Issue by talwaserman** [release-it/release-it#596]
This is more of a question...
Can i use release-it to publish only the dist folder and not all the files and folders in the root?

thanks

**Comment by webpro** [comment]
If you mean `npm publish`, then this is done using the `npm. publishPath` option.

https://github.com/release-it/release-it/blob/master/conf/release-it.json#L22

**Comment by katp1998** [comment]
I tried adding the dist folder into the `publishPath` but then release-it identifies dist as the npm package name and tries to publish the package to dist. is there a specific way that we can refer to only the content in dist folder and publish the content in the dist folder to npm?
