### ISSUE TITLE
TypeScript ?

### ISSUE THREAD

**Issue by joris-** [release-it/release-it#598]
👋  Hi ! 

What about use TypeScript or add type defs ? 
It could be a good thing for creating Plugins for example.

**Comment by webpro** [comment]
Yes, especially for the Plugin stuff that would be great. Any chance you could start this thing? What would be the best way to add typings to this project?

**Comment by joris-** [comment]
Yes, I've start to working on a type defs file.

We can add typings by 3 ways : 
- Re-write project in TS
- Add types to https://github.com/DefinitelyTyped/DefinitelyTyped
- Or add types to this project (<= I choose this)

**Comment by webpro** [comment]
I don't have much experience with TS other than writing TS from scratch (or join existing TS codebase). I don't really like the idea of rewriting the whole project now, so let's go for it. Thanks! We can always add these to DefinitelyTyped later, I guess.

**Comment by joris-** [comment]
So I've spend times to get type defs but I'm not satisfied. Maybe someone will get a better result.
