### ISSUE TITLE
Verify as collaborator with GitLab on init doesn't work for inherited members of a project

### ISSUE THREAD

**Issue by walokra** [release-it/release-it#602]
Seems that the changes introduced in [Authenticate and verify as collaborator with GitLab on init](https://github.com/release-it/release-it/commit/923a56cb55625874f854555022038776e023f0fa ) doesn't return collaborators correctly if project members are defined in group level and are inherited members to the project.

The check is made to project members (GET /projects/:id/members) endpoint which doesn't return all members. The endpoint should be "GET /projects/:id/members/all" which returns all members of a project including inherited members. Or use "GET /projects/:id/members/all/:user_id" directly.

After we updated from 12.4.3 to >=12.5.0 the release-it gives the "is not a collaborator for" error when we run it on GitLab CI pipeline. Our users are defined as group owners and inherited to the project.

**Comment by webpro** [comment]
Thanks, @walokra and @ benediktberger!

Could you please try `release-it@12.6.2-next.0` and verify it works for inherited members as well?

**Comment by benediktberger** [comment]
Ah sorry, didn‘t see this issue although I browsed the issue overview 🤦‍♂

**Comment by webpro** [comment]
Actually I was really happy to see a PR for this, thanks for that, Benedikt. But while I was looking at the options I found an alternative which should be faster. Does it work for you now when you `npm install release-it@next`?
