### ISSUE TITLE
 Creating integrated release with auto-changelog and pre-commit

### ISSUE THREAD

**Issue by leandromoreirati** [release-it/release-it#604]
Hello,
I am trying to use the integrated auto-changelog release-it and running pre-commit checks.

The configuration I made in ~ / .release-it.json is very simple it will generate the CHANGELOG file before configuring the release, until this point everything works perfectly

{
  "src": {
    "tagName": "v $ {version}"
  },
  "github": {
    "release": true
  },
  "hooks": {
    "before: release": "npx auto-changelog --commit-limit false https://raw.githubusercontent.com/release-it/release-it/master/conf
/keepachangelog.hbs "
  },
  "git": {
    "requireCleanWorkingDir": false,
    "changelog": "npx auto-changelog --stdout --commit-limit false --unreleased --template https://raw.githubusercontent.com/relea
se-it / release-it / master / conf / changelog-compact.hbs "
  }
}

The problem is when generating the release, it is giving error in the pre-commit, but I can't identify where the problem is.

root @ docker: ~ / tf-modules / bucket # release-it

🚀 Let's release tf-module-bucket (currently at 0.0.0)

Changelog:
- Configuration of the Amazon S3 module. [`7418b32`] (https://github.com/leandromoreirati/tf-module-bucket/commit/7418b325bed11592475a8432df33c297902c1129)
- Configuration of the Amazon S3 notification module. [`c1e56cf`] (https://github.com/leandromoreirati/tf-module-bucket/commit/c1e56cf9737cfa088bfef413a4f2e2a8d366e7d9)
- First commit [`731a35f`] (https://github.com/leandromoreirati/tf-module-bucket/commit/731a35f5ce402d11e093464f127c7c5fb2b80652)
- Project changelog configuration. [`b2790df`] (https://github.com/leandromoreirati/tf-module-bucket/commit/b2790df8c8fd4febf7c4187b238662ddfad2d161)

? Select increment (next version): major (1.0.0)

Empty changeset

✔ npx auto-changelog --commit-limit false https://raw.githubusercontent.com/release-it/release-it/master/conf/keepachangelog.hbs
? Commit (Release 1.0.0)? Yes

On branch master
Your branch is ahead of 'origin / master' by 3 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
ERROR Error: Terraform fmt ........................................ (no files to check ) Skipped
Terraform docs ....................................... (no files to check) Skipped
Check for merge conflicts ............................ (no files to check) Skipped

When I disable pre-commit and run the release, it works normally.

My doubt, is it possible to create the release using the pre-commit?

Another doubt, is there a possibility that it will auto-changelog and commit the changelog file automatically when generating the release?

**Comment by leandromoreirati** [comment]
I did a new test running the relsease-it with debug enabled, if I disable pre-commit this error does not occur.

? Commit (Release 1.0.0)? Yes
Terraform fmt........................................(no files to check)Skipped
Terraform docs.......................................(no files to check)Skipped
Check for merge conflicts............................(no files to check)Skipped
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
  **release-it:shell {
  release-it:shell   command: "git commit --message='Release 1.0.0' ",
  release-it:shell   options: {},
  release-it:shell   code: 1,
  release-it:shell   stdout: 'On branch master\n' +
  release-it:shell     "Your branch is ahead of 'origin/master' by 2 commits.\n" +
  release-it:shell     '  (use "git push" to publish your local commits)\n' +
  release-it:shell     'nothing to commit, working tree clean',
  release-it:shell   stderr: 'Terraform fmt........................................(no files to check)Skipped\n' +
  release-it:shell     'Terraform docs.......................................(no files to check)Skipped\n' +
  release-it:shell     'Check for merge conflicts............................(no files to check)Skipped\n'
  release-it:shell } +17s**

On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
  release-it:git Error: Terraform fmt........................................(no files to check)Skipped
  release-it:git Terraform docs.......................................(no files to check)Skipped
  release-it:git Check for merge conflicts............................(no files to check)Skipped
  release-it:git
  release-it:git     at cb (/usr/lib/node_modules/release-it/lib/shell.js:49:18)
  release-it:git     at /usr/lib/node_modules/release-it/node_modules/shelljs/src/exec.js:127:9
  release-it:git     at ChildProcess.exithandler (child_process.js:302:5)
  release-it:git     at ChildProcess.emit (events.js:223:5)
  release-it:git     at maybeClose (internal/child_process.js:1021:16)
  release-it:git     at Socket.<anonymous> (internal/child_process.js:430:11)
  release-it:git     at Socket.emit (events.js:223:5)
  release-it:git     at Pipe.<anonymous> (net.js:664:12) +0ms
  release-it:metrics {
  release-it:metrics   url: 'http://www.google-analytics.com/collect',
  release-it:metrics   statusCode: 200,
  release-it:metrics   statusMessage: 'OK',
  release-it:metrics   body: 'GIF89a\u0001\u0000\u0001\u0000��\u0000���\u0000\u0000\u0000,\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0002\u0002D\u0001\u0000;',
  release-it:metrics   request: {
  release-it:metrics     gotOptions: {
  release-it:metrics       path: '/collect',
  release-it:metrics       protocol: 'http:',
  release-it:metrics       slashes: true,
  release-it:metrics       auth: null,
  release-it:metrics       host: 'www.google-analytics.com',
  release-it:metrics       port: null,
  release-it:metrics       hostname: 'www.google-analytics.com',
  release-it:metrics       hash: null,
  release-it:metrics       search: null,
  release-it:metrics       query: null,
  release-it:metrics       pathname: '/collect',
  release-it:metrics       href: 'http://www.google-analytics.com/collect',
  release-it:metrics       retry: [Object],
  release-it:metrics       headers: [Object],
  release-it:metrics       hooks: [Object],
  release-it:metrics       decompress: true,
  release-it:metrics       throwHttpErrors: true,
  release-it:metrics       followRedirect: true,
  release-it:metrics       stream: false,
  release-it:metrics       form: true,
  release-it:metrics       json: false,
  release-it:metrics       cache: false,
  release-it:metrics       useElectronNet: false,
  release-it:metrics       retries: 0,
  release-it:metrics       body: 't=exception&exd=Error%3A+Error%3A+Terraform+fmt........................................%28no+files+to+check%29Skipped',
  release-it:metrics       gotTimeout: [Object],
  release-it:metrics       method: 'POST'
  release-it:metrics     }
  release-it:metrics   }
  release-it:metrics } +29s
ERROR Error: Terraform fmt........................................(no files to check)Skipped
Terraform docs.......................................(no files to check)Skipped
Check for merge conflicts............................(no files to check)Skipped

**Comment by webpro** [comment]
> My doubt, is it possible to create the release using the pre-commit?

The pre-commit hook raises an error (a non-zero exit code), so the release-it process stops.

So either you need to make sure the hook does not raise an error, or you could disable the hook by adding this to your release-it config:

```json
{
  "git": {
    "commitArgs": "--no-verify"
  }
}
```

> Another doubt, is there a possibility that it will auto-changelog and commit the changelog file automatically when generating the release?

Yes, with `git.requireCleanWorkingDir: false` it will also commit the updated changelog file (if it's already under version control).

**Comment by leandromoreirati** [comment]
@webpro, it worked thank you very much!

According to your guidance `"commitArgs": "--no-verify"` and I managed to execute the release-ti perfectly, thank you very much!

If you can give me one more help, I set up a `hooks` so that the changelog file is generated, I know that it is a third-party application, but I tried everything so that the changelog is generated automatically but it doesn’t work, in that first moment to creating a changelog based on this model, but as I evolve, I will create my own template.

   `"hooks": {
     "before: release": "npx auto-changelog --commit-limit false https://raw.githubusercontent.com/release-it/release-it/master/conf
/keepachangelog.hbs "
   },`

If I execute the command `npx auto-changelog --commit-limit false https://raw.githubusercontent.com/release-it/release-it/master/conf/keepachangelog.hbs` it manually generates the changelog, which doesn’t occur during the release generation.

I am grateful if you can give me any tips.

**Comment by webpro** [comment]
Looks like the `"before: release"` hook contains a space that should not be there.

(Perhaps good for release-it to raise an error when an unknown hook is used, noted.)

**Comment by leandromoreirati** [comment]
Thank you very much for your attention and especially for sharing this fantastic project with the community.
Thanks!
