### ISSUE TITLE
Problems to integrate with auto-changelog

### ISSUE THREAD

**Issue by leandromoreirati** [release-it/release-it#605]
Hello!
I performed the interplay of the release-it with the auto-change log so that it can generate the changelogs of my projects.

When starting the repository I create an empty CHANGELOG.md file and commit / push it.

But when generating the release, I can't get him to generate the file with the changes and include it in the release, I end up having to do the commit / push separately from the changelog file.

 know that auto-changelog is a plugind and third parties, but if someone has a similar scenario and can help I am grateful, because for me it is clear that the problem is `configuration`, and something that I am not able to do and not with the `release-it`.

Follows the configuration of the release I am using.
```
{
  "hooks": {
    "after:release": "npx auto-changelog --commit-limit false https://raw.githubusercontent.com/release-it/release-it/master/conf/
keepachangelog.hbs"
  },
  "git": {
    "requireCleanWorkingDir": false,
    "changelog": "npx auto-changelog --stdout --commit-limit false --unreleased --template https://raw.githubusercontent.com/relea
se-it/release-it/master/conf/changelog-compact.hbs",
    "commitArgs": "--no-verify"
  },
  "src": {
    "tagName": "v${version}"
  },
  "github": {
    "release": true
  }
}
```

Thanks!

**Comment by webpro** [comment]
You are using the `after:release` hook, which is executed after the `release` part of the Git plugin, which includes the commit and push of the changes.

You can use `after:bump` for this, also see https://github.com/release-it/release-it/blob/master/docs/changelog.md#auto-changelog

**Comment by leandromoreirati** [comment]
Dear @webpro thank you for your time and attention, thanks to your tip I managed to find the errors that were in the configuration:

1) Incorrect hook configuration replaces:
```
"after: release": "npx auto-changelog --commit-limit false https://raw.githubusercontent.com/release-it/release-it/master/conf/keepachangelog.hbs"
```
Per:
```
"after: bump": "npx auto-changelog -p /my_user_home/package.json"
```
And he started to generate the file and commit it, which led me to the second error:

2) Wrong understanding on my part because of the settings, because in the initial understanding I had, when I use (`.release-it.json`) I would not need to use the `package.json` configuration file, when creating the `package.json` file the problem has been fully resolved.

One last doubt, using the package.json file, I have to manually insert the Release version, is there any way to automate this process, I tried instead of the version to insert the variable version ("version": "$ {version}",) but it did not work.

Thanks!

**Comment by leandromoreirati** [comment]
@webpro thank you very much for your attention, I managed to solve the problem, removing the version information from the package.json and passing it in the npx command, as below, this way when generating the release the version is sent to the auto-changelog automatically

Thank you for your attention and fix the inconvenience.
```
  "hooks": {
     "after:bump": "npx auto-changelog -v ${version} -p /my_home_directory/package.json"
  },
```
