### ISSUE TITLE
pathspec '4.0.0-rc.6'' did not match any file(s) known to git

### ISSUE THREAD

**Issue by zpr1g** [release-it/release-it#606]
```bash
// ...

? Commit (Release 4.0.0-rc.6)? Yes
ERROR Error: error: pathspec '4.0.0-rc.6'' did not match any file(s) known to git

// ...
```

What happened?

**Comment by webpro** [comment]
I should ask you :) What happened before you started the release-it process? What was the state of the repo? Is this happening in a CI environment?

I think the repo is in a "detached head" state.

**Comment by zpr1g** [comment]
1. Not at all, just `release-it`
2. I tried delete and clone my repo, the same problem.
3. Not CI environment, it's in my local machine, windows 10.

It's ok before some time, but now it's not work in my different repos.

**Comment by webpro** [comment]
With this information there's not much I can do. Please read https://github.com/release-it/release-it/blob/master/CONTRIBUTING.md#-file-a-bug and try to help me help you.

**Comment by zpr1g** [comment]
Emmm... It works in WSL environment. I still can not remember what special I have done before it not work in Windows 10.

Maybe I should migrate all my projects to WSL, interesting 😂

**Comment by coderhaotf** [comment]
I run into the same problem 。。。
`
 // release-it version: 12.6.2
// system enviroment:  win10;  version: 18362.778
// node:  v12.14.1
// git version 2.19.1.windows.1
`

**Comment by coderhaotf** [comment]
I run into the same problem 。。。this is my enviroment:
`release-it version: 12.6.2 `
` system enviroment: win10;` 
`version: 18362.778 ;`
`node: v12.14.1 ;`
`git version 2.19.1.windows.1`
@webpro
