### ISSUE TITLE
`prepublishOnly` script not work?

### ISSUE THREAD

**Issue by zpr1g** [release-it/release-it#607]
```
"prepublishOnly": "npm run lint && npm run build",
```

I have migrated my project to WSL, but the `prepublishOnly` script is not work like Windows 10 before publish.

**Comment by webpro** [comment]
`prepublishOnly` is a feature of npm. When release-it does `npm publish`, this script in your `package.json` should also run.

Please, again, see https://github.com/release-it/release-it/issues/606#issuecomment-590974397

**Comment by zpr1g** [comment]
I got it. `npm` is outdated version, `3.*`, in WSL. It works after I updated `node` to `10.*` with `npm@6.*`.

I'm sorry for my carelessness.
