### ISSUE TITLE
Cannot update project to v2.2.1

### ISSUE THREAD

**Issue by LeddaZ** [release-it/release-it#611]
I have a node.js Telegram bot currently on version 2.2.0, when I try to update it to 2.2.1 this is what happens:
`error: pathspec '2.2.1'' did not match any file(s) known to git`
Is there a fix?

**Comment by webpro** [comment]
- What OS are you using?
- Do you know what version of release-it you used when you did a successful release?
- What version of release-it did you use now?

**Comment by LeddaZ** [comment]
I'm on Windows 10 x64, when I did the last succesful release I was on 12.4, now I'm on 12.6.2

**Comment by BrkDalkiran** [comment]
Yes, i checked it. It's working on 12.4, but didn't work 12.6.2. I have same problem.

**Comment by webpro** [comment]
OK, pretty sure this change/bug was introduced in v12.5.0. It fixed some quoting issues, but apparently breaks things on Windows. You could downgrade to v12.4.3 for now.

There will be different implementation for this in v13 (which will fix this issue), for which I'll soon release a pre-release.

To be sure: you aren't using a custom `git.commitMessage`?

**Comment by LeddaZ** [comment]
No, I have the default one

**Comment by webpro** [comment]
Please try `release-it@13.0.0-beta.0` and let me know how this works for you (note that there are some [breaking changes](https://github.com/release-it/release-it/blob/v13/CHANGELOG.md#v13)).

**Comment by webpro** [comment]
Thanks to @PhilippeRoy there is also a fix in v12 ([12.6.3](https://github.com/release-it/release-it/releases/tag/12.6.3)), so I'm closing this issue.
