### ISSUE TITLE
shell-quote causes error on windows

### ISSUE THREAD

**Issue by PhilippeRoy** [release-it/release-it#612]
shell-quote will use single quotes for commit messages i.e.

`$ git commit --message='0.0.1-beta.0'`

That will not work on windows.

It should be forces to double quotes as the following will work:

`$ git commit --message="0.0.1-beta.0"`

**Comment by PhilippeRoy** [comment]
Similar issue here - https://github.com/streamich/git-cz/issues/21

There solution was to use `any-shell-escape` - https://www.npmjs.com/package/any-shell-escape

**Comment by webpro** [comment]
It's essentially a duplicate with #611. Please use `release-it@beta` (v13). Thanks a lot for your suggestion, I will try that to fix v12.

**Comment by PhilippeRoy** [comment]
Okay thanks, i'll use v13 in the meantime. Let me know if want me to submit a PR with a fix.

**Comment by webpro** [comment]
A PR would be much appreciated! As I don't have a Windows machine myself.

**Comment by PhilippeRoy** [comment]
NP. In v13 you removed the following (see below), was that to get around the current issue or you no longer need that code?

```javascript
    template = template.startsWith('git log')
      ? template.replace('[REV_RANGE]', '${latestTag}...HEAD')
      : template.replace(/%s/g, '${version}');
```

**Comment by webpro** [comment]
It's removed as it was supporting old syntaxes for template replacements. It has nothing to do with the issue at hand :)

**Comment by PhilippeRoy** [comment]
Okay I've made a PR - https://github.com/release-it/release-it/pull/613. This resolves the single quote double quote issue in the commit messages.

There is one test that will still fail when running on windows (test: 'should commit and tag with quoted characters'). The reason is windows doesn't support multi-line commits the same as UNIX. 

The following will work on UNIX systems:
 ` tagAnnotation: 'Release ${version}\n\n${changelog}'`
but will fail on windows.

The line breaks (\n) and `EOL` in the test work on UNIX but not Windows.

If I come up with a solution I'll submit another PR. But hopefully that gives some clarification on the other issue now.

**Comment by webpro** [comment]
Awesome! Maybe we can either remove newlines, or make a note and simply skip that test on Windows.

(Currently, the tests fail on Travis CI in Windows anyway, so don't worry about that - mostly because there is a problem with `git clone` + `git-upload-pack`).
