### ISSUE TITLE
Error when generating release with changelog

### ISSUE THREAD

**Issue by leandromoreirati** [release-it/release-it#616]
Hello!
I am running the release integrated with auto-changelog and it is returning the following error:

`$ npx auto-changelog --stdout --commit-limit false -u --template https://raw.githubusercontent.com/release-it/release-it/master/conf/changelog-compact.hbs
404: Not Found`

I went to check the address of the template and it does not exist, did the address change, or is this integration being discontinued?

**Comment by webpro** [comment]
This file has been moved from the `conf` directory to `templates`. I tried to made a symlink to keep it backwards compatible, but obviously this didn't work. Apologies for the inconvenience!

**Comment by webpro** [comment]
I did just put some proper symlinks in place, though.
