### ISSUE TITLE
Access NPM package commands from within `hooks` / `git.changelog` / etc?

### ISSUE THREAD

**Issue by rwjblue** [release-it/release-it#622]
I'd like to allow folks to use installed packages from `after:bump`/`git.changelog`/etc, but it seems that `this.exec` does not resolve commands provided by installed packages.

I'm thinking of something like :

```json
{
  "release-it": {
    "hooks": {
      "after:bump": "some-installed-package-cli --awesome-flag-here"
    },
    "git": {
      "changelog": "other-package-here"
    }
  }
}
```

Has this previously been considered? Is this something that you think would make sense?

**Comment by rchl** [comment]
I think you should be able to do `npx some-installed-package-cli`

**Comment by rwjblue** [comment]
Ya, that would work but (at least as far as I understand it) it would always download the package and run its command. In the cases above, my project already has the specified dependencies installed and the command (when invoked) should run that specific version (vs latest).

**Comment by webpro** [comment]
The main reason release-it doesn't automatically make a hook with just `eslint` work, is that `npm` and `npx` are specific to Node modules and this has its own path/module resolution machinery. Yet release-it is a generic release tool, not tied to e.g. Node modules.

Also, this is exactly where `npx` is designed for:

> By default, `npx` will check whether `<command>` exists in `$PATH`, or in the local project binaries, and execute that. If `<command>` is not found, it will be installed prior to execution.

An alternative is to use e.g. `"npm run lint"` where `lint` is a script defined in package.json:

```
{
  "hooks": {
    "before:init": "npm run lint"
  }
}
```

In `package.json`:

```
{
  "scripts": {
    "lint": "eslint src",
    "release": "release-it"
  }
}
```

Now you can be sure `eslint` from the package dependencies (not the global one) will be used.

**Comment by rwjblue** [comment]
> If <command> is not found, it will be installed prior to execution.

Sure, but in this case, I don't want latest `eslint` which is what `npx` would do (and all libraries don't know to properly defer to the local installation when present).

Also, FWIW, if the project is using `yarn` you can do:

```js
{
  "hooks": {
    "before:init": "yarn some-installed-package-cli --awesome-flag-here"
  }
}
```

This works because `yarn foo` will attempt to execute the local command for `foo` if present (and not overridden by a `package.json` `scripts` entry).

**Comment by webpro** [comment]
Thanks! Didn't know about that `yarn` feature.

**Comment by rwjblue** [comment]
> The main reason release-it doesn't automatically make a hook with just eslint work, is that npm and npx are specific to Node modules and this has its own path/module resolution machinery.

Makes sense!

> Yet release-it is a generic release tool, not tied to e.g. Node modules.

True, but it definitely has built in affordances to make using it with `npm` very convenient (just like it does with `git` for example).

**Comment by webpro** [comment]
In any case, for convenience, there needs to be _something_ to tell release-it it's e.g. a Node.js CLI module (that lives in `node_modules/.bin`). This works out-of-the-box with `npm script` or `npx` (or `yarn`). Not sure whether it's worth the hassle when existing solutions work fine.

**Comment by rwjblue** [comment]
Seems good, thanks for chatting through it with me. 😸
