### ISSUE TITLE
How can I create a github release from an existing tag? 

### ISSUE THREAD

**Issue by amir20** [release-it/release-it#624]
Hello,

I am currently working on a project that is a little a different. I am creating multi-arch Docker images which can take up to 20 minutes to build. My current solution is using Github Actions. In GH, I have a workflow that gets triggered on tag creations. I use Actions to push docker images to docker hub. It takes a long time so that's why I setup a workflow. 

This whole process is kicked off with a tag creation. Currently, I call `release-it` locally where the tag is created with a "Github release" and pushed. Once the action is triggered, it will build the docker image and pushed to hub. 

The problem is when something breaks with the docker image. The Github release has already been created but the docker image doesn't exist. Instead, what I need is to create the tag, push the docker image, _only if successful_ create the Github release. 

I can update the action to only call `release-it` if docker push has been successful. However, I am not sure how to create a github release with an existing tag? Is that even possible?

**Comment by amir20** [comment]
I am also OK with doing `release-it` similar to #529 but then I am not sure how to trigger the build.

**Comment by webpro** [comment]
> The problem is when something breaks with the docker image. The Github release has already been created but the docker image doesn't exist. Instead, what I need is to create the tag, push the docker image, only if successful create the Github release.

One approach is to use hooks (as taken from #529), e.g.:

```
{
  "hooks": {
    "after:git:tag": "# build/push the docker image OR",
    "before:github:release": "# build/push the docker image"
  }
}
```

If any command fails with a non-zero exit code, release-it stops the process.

> I can update the action to only call `release-it` if docker push has been successful. However, I am not sure how to create a github release with an existing tag? Is that even possible?

You can use `--no-git` (or `"git": false`) to not perform any Git tasks, and use just the GitHub Release tasks (they're separate plugins).

**Comment by amir20** [comment]
Thanks @webpro. Some follow up questions: 

My goal is to use Github Actions to automate this whole thing. If I were to use the hooks to trigger a build, then what would be a good way to trigger the release. Right now it's based off a tag, but if `release-it` is to create the tag then how have others used the `--ci` option. 

I don't think my original question was answered. If I were to use `--no-git`, is it it possible to create a release based on existing tags. So for example, something like `release-it --from-tag=1.2.1 --to-tag=1.2.2`. Otherwise, I believe the existing behavior creates a release with no changelog. 

Thanks! Hope you are safe out there.

**Comment by amir20** [comment]
Just to be clear, these are the steps I have in mind: 

1. Locally create a tag and push
2. GH Actions picks up the tag, creates a docker image and pushes
3. Only if that has succeeded, a release page is created.

**Comment by webpro** [comment]
> if `release-it` is to create the tag then how have others used the `--ci` option.

Not sure I understand. The `--ci` option is mostly used in CI environments like Travis, Circle, etc. or to simply trust it to do its thing without questions when running from your own machine. GitHub Actions is a recent addition to this, and it might be a little "intertwined" in a scenario like yours. It's interesting of course to see if/how they can cooperate better.

> I believe the existing behavior creates a release with no changelog.

You're right, I'm sorry. The mechanism to determine the from/to tags and the corresponding changelog is missing. It's a good feature to have, it's on my radar now.

**Comment by amir20** [comment]
Hello, @webpro. 

I was trying to understand what is the use case for `--ci`? Most CI environments kickoff a release based on a tag or branch. But since `release-it` creates the tag then I wonder if there was a different use case. I am assuming `--ci` is automating the release cycle based on some trigger. I am wondering what that trigger can be besides a tag. 

Perhaps, a smarter feature would be to create a release based on previous releases and not tags. So when doing `--no-git` then `release-it` is smart enough to query GH for the most recent release and diff against that to create the changelog. That would probably be the most common use. Something like `git log tag@(recent-gh-release)...HEAD`

Hope this time I made more sense.

**Comment by webpro** [comment]
> I am wondering what that trigger can be besides a tag.

Initially, release-it was made to ease the process of doing a release _for humans_ by showing a changelog since the latest tag, to _help determine the next tag_. Then e.g. update package.json, commit, tag, and push it. This has evolved into automating more and more parts of this process, such as creating a release on GitHub (or GitLab, or... you name it).

The use case for `--ci` is to let release-it go ahead in a non-interactive shell, and skip asking for confirmation. In a CI environment, it automatically activates this non-interactive mode.

> Something like `git log tag@(recent-gh-release)...HEAD`

It's a bit of a work-around, but this might be temporary solution:

```json
{
  "git": false,
  "github": {
    "release": true,
    "releaseNotes": "git log --pretty=format:\"* %s (%h)\" $(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))...HEAD~1"
  }
}
```

It will give "Empty changelog" initially (since the Git plugin is deactivated), but the "Release notes:" for the release should be correct. If you want the initial changelog as well, this works, too:

```json
{
  "git": {
    "changelog": "git log --pretty=format:\"* %s (%h)\" $(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))...HEAD~1",
    "commit": false,
    "tag": false,
    "push": false
  },
  "github": {
    "release": true
  }
}
```

For the release notes, the GitHub plugin uses the result of `git.changelog` by default, but this can be overridden with `github.releaseNotes`.

Note that this uses `HEAD~1` to leave out the latest commit (often a separate commit is used for the bumped version and/or updated changelog). Omit the `~1` to include the commit for the latest tag.

**Comment by amir20** [comment]
That's a little different for my use case. One might have multiple tags, but not releases in GH. For example, I may have tag v1, v2 and v3 in git. But only have released v1 and v3 because v2 failed. IMO, `release-it` should query GH and diff against the latest release. 

I think you missed my question about `--ci`. In typical CI env, something usually triggers a build. This may be a git commit, a user action or some cron job. In most places I have worked, master always builds latest. There can be a production branch as well. For independent libraries,  I usually let my CI build releases based on tags. You can see Travis' [documentation](https://docs.travis-ci.com/user/deployment/releases/) for examples.  Based on that, I don't think `--ci` makes sense as tag has already been created. There should be an option for `--ci` to release artifacts, create release page and documentation without mutating git.  
 
When I have time, I think I'll create some JS script that fetches latest release, diffs and output a template based on `git diff`.  I'll try to share that or create a PR. 

I appreciate your responsiveness.  Feel free to close this bug. :)

**Comment by webpro** [comment]
It's totally fine if you think `--ci` doesn't make sense as it works currently, I was only explaining to you what this flag does in release-it. It used to be `--non-interactive`, maybe that also helps in understanding the background of this. This tool wasn't originally designed for the scenario you describe (triggered by e.g. a git tag).

So yeah, let's close this for now. But I'm definitely interested in supporting this feature request.

**Comment by rohit-gohri** [comment]
I was trying to do the same for gitlab, this is what I came up with:

```json
    "git": {
      "commit": false,
      "tag": false,
      "push": false
    },
    "gitlab": {
      "release": true
    },
    "npm": false,
    "plugins": {
      "@release-it/keep-a-changelog": {
        "filename": "CHANGELOG.md",
        "keepUnreleased": true,
        "strictLatest": false
      }
    }
```

And I run it with:

```sh
npx release-it --ci --no-increment
```

on tags in Gitlab CI. The same can be done for Github Actions I think.

**Comment by amir20** [comment]
For anybody who is trying to do this, I ended doing something like `yarn release --github.release --no-increment --no-git --ci` which seems to work.

**Comment by webpro** [comment]
Just added this to the GitLab docs as well, so both platforms should be covered:

- https://github.com/release-it/release-it/blob/master/docs/github-releases.md#update-the-latest-release
- https://github.com/release-it/release-it/blob/master/docs/gitlab-releases.md#update-the-latest-release
