### ISSUE TITLE
Pre-Release version for next version release not incrementing

### ISSUE THREAD

**Issue by loganbfisher** [release-it/release-it#626]
Ok so I have successfully automated my versioning to go as follows.

**feature merged into qa -> creates tag 0.0.1-qa.0**
**feature merged into staging -> creates tag 0.0.1-staging.0**
**staging merged into master -> creates tag 0.0.1 and github release 0.0.1**

Then I start merging items in for the next release into qa.  Instead of creating a new pre-release tagged 0.0.2-qa.0 it creates another versioned pre-release of the last release version (example: 0.0.1-qa.1).  Am I missing something?  I have attached my scripts for each env below for your reference.

This is the last hurdle I need to get past and I am at a loss.  Any help would be greatly appreciated. 

### Production
**.release-it.json**
```
{
  "git": {
    "changelog": "git log --pretty=format:\"* %s (%h)\" ${latestTag}...HEAD",
    "requireCleanWorkingDir": false,
    "requireBranch": false,
    "requireUpstream": false,
    "requireCommits": false,
    "addUntrackedFiles": false,
    "commit": true,
    "commitMessage": "Official Release ${version}",
    "commitArgs": [],
    "tag": true,
    "tagName": null,
    "tagAnnotation": "Official Release ${version}",
    "tagArgs": [],
    "push": true,
    "pushArgs": ["--follow-tags"],
    "pushRepo": ""
  },
  "github": {
    "release": true,
    "releaseName": "Official Release ${version}",
    "releaseNotes": null,
    "preRelease": false,
    "draft": false,
    "assets": null,
    "host": null,
    "timeout": 0,
    "proxy": null,
    "skipChecks": false
  }
}
```

**Release-it command**
`DEBUG=release-it:* release-it --ci --no-npm`

### Staging
**.release-it.json**
```
{
  "git": {
    "changelog": "git log --pretty=format:\"* %s (%h)\" ${latestTag}...HEAD",
    "requireCleanWorkingDir": false,
    "requireBranch": false,
    "requireUpstream": false,
    "requireCommits": false,
    "addUntrackedFiles": false,
    "commit": true,
    "commitMessage": "Release Candidate ${version}",
    "commitArgs": [],
    "tag": true,
    "tagName": null,
    "tagAnnotation": "Release Candidate ${version}",
    "tagArgs": [],
    "push": true,
    "pushArgs": ["--follow-tags"],
    "pushRepo": ""
  },
  "github": {
    "release": false
  }
}
```

**Release-it command**
`DEBUG=release-it:* release-it patch --preRelease=staging --ci --no-npm`

### QA
**.release-it.json**
```
{
  "git": {
    "changelog": "git log --pretty=format:\"* %s (%h)\" ${latestTag}...HEAD",
    "requireCleanWorkingDir": false,
    "requireBranch": false,
    "requireUpstream": false,
    "requireCommits": false,
    "addUntrackedFiles": false,
    "commit": true,
    "commitMessage": "Pre-Release ${version}",
    "commitArgs": [],
    "tag": true,
    "tagName": null,
    "tagAnnotation": "Pre-Release ${version}",
    "tagArgs": [],
    "push": true,
    "pushArgs": ["--follow-tags"],
    "pushRepo": ""
  },
  "github": {
    "release": false
  }
}
```

**Release-it command**
`DEBUG=release-it:*  release-it patch--preRelease=qa --ci --no-npm`

**Comment by webpro** [comment]
That workflow should be fine indeed. I simulated your situation a bit, and I'm going from `0.0.1` to `0.0.2-qa.0` (with the other tags also in history). Even if all tags are pointing to the same commit, I go to `0.0.2-qa.0`. So I can't reproduce your issue.

If you have a reproducible case I could look into it.

**Comment by loganbfisher** [comment]
Ok I will do some more digging.  For what it’s worth the same problems happen if I run the steps locally.  I thought at first it was some weird caching mechanism in my ci/cd pipeline but if it happens locally too then that isn’t the problem.  Could it be likely that my commit history is in a bad state?  I may try on a new repo and see if I get the same results.

**Comment by webpro** [comment]
Yeah, check which tags exist after `git fetch` and see the commands are being executed in debug mode.

**Comment by loganbfisher** [comment]
It keeps saying no tags exist...

**Comment by webpro** [comment]
Maybe you can share a rep(r)o? Or the commands to reproduce this scenario?

**Comment by loganbfisher** [comment]
Ok I created a test repo and added the same exact scripts I am using currently and it works as expected.  So I understand correctly this is probably caused by commits getting out order?  Would force pushing cause this problem?

**Comment by webpro** [comment]
Maybe the tags are in different branches on the origin, and they're not coming down with `git fetch` to the clone being released from. You could do a manual `git pull` beforehand (e.g. in a `before:init` hook).

**Comment by loganbfisher** [comment]
I just published an article on how I used release-it to automate my releases.  I really appreciate the work you have put into this project! https://medium.com/@loganfisher_40888/building-an-automated-release-management-pipeline-with-release-it-codefresh-io-and-github-f97c9ac1ac57?sk=5e4e286b1db21a504c1d1eb66f6ecd89

**Comment by webpro** [comment]
Thanks, and nice article! 👏
