### ISSUE TITLE
[question] Environment variable "GITLAB_TOKEN" is required for GitLab releases

### ISSUE THREAD

**Issue by nighttimedev** [release-it/release-it#636]
As the title already says, I'm always getting 

> Environment variable "GITLAB_TOKEN" is required for GitLab releases

when executing `npm run release`
My package.json looks like this (reduced verison):
```json
{
  "name": "...",
  "version": "...",
  "description": "...",
  "main": "app.js",
  "scripts": {
    "release": "release-it"
  },
  "repository": {
    "type": "git",
    "url": "git+https://gitlab.com/.../... .git"
  },
  "author": "...",
  "license": "...",
  "bugs": {
    "url": "https://gitlab.com/.../.../issues"
  },
  "homepage": "https://gitlab.com/.../...#readme",
  "devDependencies": {
    "release-it": "^13.5.1"
  },
  "release-it": {
    "git": {
      "tagName": "v${version}",
      "requireCleanWorkingDir": false,
      "requireUpstream": false,
      "commitMessage": "Release v%s"
    },
    "gitlab": {
      "release": true
    },
    "npm": {
      "publish": false
    }
  },
  "dependencies": {
    "chart.js": "^2.9.3",
    "electron": "^8.2.0",
    "lowdb": "^1.0.0"
  }
}
```

I'm running on Win 10 Pro, and I tried to set `GITLAB_TOKEN` by entering `get GITLAB_TOKEN = tokenHere`

Edit:

`get | findstr "GITLAB_TOKEN"` also returns my token which confuses me even more because it's definetly set.

**Comment by adrienjoly** [comment]
I had the same issue with `GITHUB_TOKEN`.

My setup (using `zsh` on macOS):
- I had a `.env` file that contained `GITHUB_TOKEN="<my token>"`
- my npm script: `"release": "source .env && echo $GITHUB_TOKEN && node_modules/.bin/release-it --no-npm.publish --dry-run"`

When running `$ npm run release`, the github token was printed in my terminal (by the `echo` command), but not visible by `release-it`.

After I typed `$ export GITHUB_TOKEN="<my token>"` in my terminal (note the `export`), it worked.

**Comment by webpro** [comment]
> I'm running on Win 10 Pro, and I tried to set `GITLAB_TOKEN` by entering `get GITLAB_TOKEN = tokenHere`

I guess you mean `set` (not `get`) here.

I'm not on Windows, so I'm not sure how to do this. Perhaps e.g. https://superuser.com/questions/1334129/setting-an-environment-variable-in-windows-10-gpodder has the answer.

> After I typed `$ export GITHUB_TOKEN="<my token>"` in my terminal (note the `export`), it worked.

Yes, you really need to `export` the variable ([docs](https://github.com/release-it/release-it/blob/master/docs/gitlab-releases.md#gitlab-releases)).

**Comment by rchl** [comment]
> > After I typed `$ export GITHUB_TOKEN="<my token>"` in my terminal (note the `export`), it worked.
> 
> Yes, you really need to `export` the variable ([docs](https://github.com/release-it/release-it/blob/master/docs/gitlab-releases.md#gitlab-releases)).

Or just prefix your npm command with a token like:
```
GITLAB_TOKEN=asdf npm run release
```
That way it will only be set for the duration of the command which should be better from security standpoint.

**Comment by nighttimedev** [comment]
It would be so great if stuff just worked... Release-it is so great, and it improves my workflow a lot... But like...
Is there a way to put the token into some kind of config file? I know that's not the most secure thing to do, but once someone gets access to my local file system I'm screwed anyways.

**Comment by webpro** [comment]
Added a section about environment variables, including a good cross-os solution: https://github.com/release-it/release-it/blob/master/docs/environment-variables.md
