### ISSUE TITLE
Command seems to be timing out

### ISSUE THREAD

**Issue by mkay581** [release-it/release-it#637]
Hello, we're running into an issue where running release-it to create a new minor version in our private artifactory repository. Here's the npm command that just runs `release-it` under the hood.

```bash
DEBUG=release-it:* npm run release -- minor --ci --verbose --disable-metrics
```

The only error I can find is that it seems to be timing out. But we never had this issue before. And the npm `*-debug.log` file doesn't give any information other than the command failing. Can anyone help? Thanks!

Error:

```bash
npm notice PING https://artifacts.werally.in/artifactory/api/npm/npm
****
2020-04-03T17:23:03.365Z release-it:shell { command:
   'npm whoami --registry https://artifacts.werally.in/artifactory/api/npm/npm',
  options: {},
  code: 0,
  stdout: ****,
  stderr: '' }
0.3.1
2020-04-03T17:23:03.784Z release-it:shell { command:
   'npm show @rally/chatterbox-ui@latest version --registry https://artifacts.werally.in/artifactory/api/npm/npm',
  options: { write: false },
  code: 0,
  stdout: '0.3.1',
  stderr: '' }
ERROR Timed out after 10000ms.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @rally/chatterbox-ui@0.3.1 release: `release-it "minor" "--ci" "--verbose" "--disable-metrics"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @rally/chatterbox-ui@0.3.1 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/.npm/_logs/2020-04-03T17_23_13_004Z-debug.log
```

**Comment by mkay581** [comment]
Oh, looks like there's a metric call that returns a payload that says its timed out (see `payload` key below). But it's odd that the response seems to still return a result.

```bash
2020-04-03T17:08:14.756Z release-it:shell { command:
   'npm show @rally/chatterbox-ui@latest version --registry https://artifacts.werally.in/artifactory/api/npm/npm',
  options: { write: false },
  code: 0,
  stdout: '0.3.1',
  stderr: '' }
2020-04-03T17:08:23.970Z release-it:metrics { url: 'http://www.google-analytics.com/collect',
  statusCode: 200,
  statusMessage: 'OK',
  payload: 't=exception&exd=Error%3A+Timed+out+after+10000ms.' }
```

**Comment by webpro** [comment]
Yes, something times out. There is another request to verify the npm user is a project collaborator. You could try with '--npm.skipChecks' to verify one of the npm requests is timing out. And maybe there's more information/configuration I'm missing.

**Comment by mkay581** [comment]
Yeah, skipping checks seems to have worked. But is that recommended?

**Comment by webpro** [comment]
No it's not recommended. But now I have a clue. I will investigate when I have some time. Although I can't see why just that command is timing out. Is it consistent?

**Comment by mkay581** [comment]
Haha, yeah it surprised me too! Yeah its been consistent all day. We've even tried downgrading the library but of course that didn't work because this is a request which is external to the library.

**Comment by webpro** [comment]
You saw this:

```
npm notice PING https://artifacts.werally.in/artifactory/api/npm/npm
```

But did you also get the PONG response?

```
npm notice PONG 0.38ms
```

If not, then I suppose that's the one timing out. If it's unsupported, it would return an error such as `400` or `404` and release-it would warn about this, but continue the process.

**Comment by mkay581** [comment]
No `PONG`. It works when I do it locally and if I were to just publish a release using `npm publish` which is what's making me think its this package. I also don't see any `400` or `404` just errors with `ERROR Timed out after 10000ms.`

**Comment by webpro** [comment]
So when you do this locally, it's not timing out?

```
npm ping --registry https://artifacts.werally.in/artifactory/api/npm/npm
```

Seeing that the `npm whoami` request works just fine, this is pretty strange. Also, this `npm ping` check has been there for over a year (since v9.7.0). In any case, the `--npm.skipChecks` is there for situations like this, so feel free to use it.

**Comment by mkay581** [comment]
Nah its not timing out locally, just when release-it is ran in CI (we use Jenkins) in attempt to publish to our artifactory URL. FWIW, this worked before without `--npm.skipChecks` and verified with our Ops team that nothing changed with permissions in CI. 

We've started using `--npm.skipChecks` in our CI builds. What are the downsides of skipping checks?

**Comment by webpro** [comment]
Didn't receive any other complaints about this and there have been no changes regarding this command, so I'm going to close this issue.

Skipping the checks means:

- No `npm ping` to see if the registry is up
- No `npm whoami` to see if the current user is authenticated
- No `npm show version` to check the latest version in the registry (or if it's a new package).

Additionally, I want to add a check whether the user is a package collaborator.

**Comment by mkay581** [comment]
No problem! I don't think we need any of those checks since we've adopted a pretty strict process for publishing to our private registry. Thanks for that information and for your time.

**Comment by jonkwheeler** [comment]
@webpro It's hitting me now and become a blocker. Right now I'm staying in the middle of nowhere and the internet is quite slow. Any work arounds? How about an option command line option to change the time out in seconds?

**Comment by webpro** [comment]
@jonkwheeler Now it's an option in [v13.7.0](https://github.com/release-it/release-it/releases/tag/13.7.0)

Use it like `--npm.timeout=100` (in seconds)

**Comment by jonkwheeler** [comment]
Looking like while updated to 13.7.0 I now get this error - https://github.com/release-it/release-it/issues/674

I'm going to have to revert for now and revisit this.

```
Error: No valid exports main found for '/Users/jonwheeler/folder_name/package-name/node_modules/yargs-parser'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/jonwheeler/folder_name/package-name/release-it/bin/release-it.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1128:30) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by webpro** [comment]
Removing node_modules and re-install doesn't help?

**Comment by jonkwheeler** [comment]
> Removing node_modules and re-install doesn't help?

It did not 👎
