### ISSUE TITLE
--no-increment option not respected

### ISSUE THREAD

**Issue by tvvignesh** [release-it/release-it#644]
Hi. I have been trying to use `release-it`. While it works great, I was wondering why the `--no-increment` flag does not work. I tried setting my current version to `0.0.0` both in `package.json` as well as through Git tagging and I want to start off releases from the same version but it doesn't let me do that. 

NOTE: If I remove the `@release-it/conventional-changelog` plugin, it works. The --no-increment option is not respected when the plugin is added.

Screenshot below:

![Screenshot from 2020-04-18 01-01-07](https://user-images.githubusercontent.com/1165845/79607091-4a0c4780-8110-11ea-958f-dab565e551c9.png)

This is what I have in my config:

```
"release-it": {
        "git": {
            "commitMessage": "chore: release v${version}",
            "requireBranch": [
                "master",
                "production"
            ],
            "tag": true,
            "tagName": null,
            "push": true,
            "pushArgs": [
                "--follow-tags"
            ],
            "commitArgs": [],
            "tagAnnotation": "Release ${version}",
            "addUntrackedFiles": false,
            "requireCommits": false
        },
        "plugins": {
            "@release-it/conventional-changelog": {
                "preset": "angular",
                "infile": "CHANGELOG.md",
                "outfile": "CHANGELOG.md"
            }
        }
    },
```

Thanks in advance.

**Comment by webpro** [comment]
The `@release-it/conventional-changelog` plugin uses `conventional-recommended-bump` to determine the next version. The plugin indeed doesn't respect `--no-increment`, because what would be the point of the plugin?

So what is the issue then? You get e.g. v0.0.1 and that would be a proper version for a first release, no?

**Comment by tvvignesh** [comment]
@webpro Got it. So, it is by design then. Was wondering if I could start releasing from `0.0.0` but maybe it does not make sense. Will close this issue. Thanks.
