### ISSUE TITLE
isCollaborator check fails when access token is different from ssh credentials

### ISSUE THREAD

**Issue by manuFL** [release-it/release-it#653]
Hi,
I'm using your GitLab plugin for releasing my projects on a GitLab private server.

If I try to publish a new release via a GITLAB_TOKEN associated to my ssh credentials, everything goes well. If I try instead to publish a new release via a different access token, from another account (we created one just for this purpose), `isCollaborator` check in `lib/plugin/gitlab/GitLab.js` fails due to 404 error on the testing endpoint.

The problem seems to be related to the fact that the call this endpoint: `projects/${this.id}/members/${id}` (I'm using a version of Gitlab < 12.4, but it should be the same also for the new one) fails for all the users except the one whose credential are associated to my GitLab ssh account.

The good news is that the call to `projects/${this.id}/members/all/` (without id) returns the complete list of the users associated to my project, without any error.

In order to overcome this issue, could you kindly check for collaborators permissions using the array returned from `projects/${this.id}/members/all/`, instead of relying on the single-user endpoint, which breaks in mixed scenarios like mine?

Meanwhile, I'm leaving the `"skipChecks": true` option to be able to post releases, as temporary workaround.

Thank you very much in advance,
Emanuele

**Comment by webpro** [comment]
What release-it does, is a call to `/user` to get the user `id` associated with the token. Then the next call to verify project membership is based on this `id`.

> The problem seems to be related to the fact that the call fails for all the users except the one whose credential are associated to my GitLab ssh account.

Sounds like this is actually an issue with the GitLab API, right? I'll dig into it soon.

**Comment by manuFL** [comment]
Yes exactly! Let me know if you need further information.

Thank you.

**Comment by manuFL** [comment]
This is still relevant, yes!

**Comment by manuFL** [comment]
Yes this is still relevant
