### ISSUE TITLE
How I would use this with GitHub Actions

### ISSUE THREAD

**Issue by chriscn** [release-it/release-it#657]
I would like to use this incombination of CI / CD of GitHub actions. Is this possible?

**Comment by webpro** [comment]
Yes. There is no documentation about Actions yet, but still this might be interesting examples: https://github.com/release-it/release-it/blob/master/docs/ci.md

And release-it itself also uses Actions: https://github.com/release-it/release-it/blob/master/.github/workflows/test.yml

**Comment by ahmadnassri** [comment]
while the actions config linked shows a test workflow, it doesn't actually use `release-it` in actions ... i'm currently seeing issues with running in github actions as the default `actions/checkout` seems to check out the head in a detached state (I think) which results in `release-it` not finding the "current" tag ....

**Comment by ahmadnassri** [comment]
it seems we need to ensure that github actions checkout step is pulling a depth more than 1

```yml
- uses: actions/checkout@v2
  with:
    fetch-depth: 0
```

see [`actions/checkout`](https://github.com/actions/checkout#Fetch-all-history-for-all-tags-and-branches) for more details
