### ISSUE TITLE
A bit of duplication in github release notes

### ISSUE THREAD

**Issue by rchl** [release-it/release-it#658]
I'm using your amazing package for releasing `nuxt-i18n`.

I've been bothered a bit for a while now with some duplicate information in release notes. Namely the version and date that is sort of repeated twice.

You can see yourself here: https://github.com/nuxt-community/nuxt-i18n/releases

Talking about the top of the release:
![Screenshot 2020-04-30 at 09 02 12](https://user-images.githubusercontent.com/153197/80681613-535ac400-8ac1-11ea-9431-43947303c544.png)

The version is duplicated and date is sort of unnecessary also as github shows when release was done.

Since I'm also adding release information to CHANGELOG.md, the date there makes sense: https://github.com/nuxt-community/nuxt-i18n/blob/master/CHANGELOG.md

I'm using `@release-it/conventional-changelog` plugin and this configuration: https://github.com/nuxt-community/nuxt-i18n/blob/3b77fda74e2ec8ec44578c32f6eb436c229aebc4/package.json#L47-L65

**Comment by rchl** [comment]
It's more like an open question than a bug report.
I must admit I haven't looked thoroughly enough at configuration options.
I can see now that I can set `github.releaseNotes` to override default notes. I guess that's the way to go here right? I just have to figure out how to do it a clenest way, without too much duplication.

**Comment by webpro** [comment]
Yes, I understand. This was the simplest solution to re-use the changelog output exactly as-is. You could indeed override using `github.releaseNotes`, perhaps you could try something like this:

```
"github": {
  "releaseNotes": "echo \"${changelog}\" | sed 1,5d"
}
```

Not actually tried this, but you get the idea: print the existing changelog and modify it.

**Comment by rchl** [comment]
Thank you. I will try it when I get a chance to release something. Don't have any unreleased commits right now.

**Comment by rchl** [comment]
Thank you again. That solution works great.
