### ISSUE TITLE
[Feature Request] add granular `increment` control @ config

### ISSUE THREAD

**Issue by Enteleform** [release-it/release-it#661]
This will allow projects to enforce specific conventions.  

&nbsp;  
For example, a config with

```javascript
increment: {
  patch:    true,
  minor:    true,
  major:    true,
  prepatch: false,
  preminor: false,
  premajor: false,
  other:    false,
},
```

would show as follows in interactive mode
```c#
? Select increment (next version): (Use arrow keys)
> patch (0.0.1) 
  minor (0.1.0) 
  major (1.0.0) 
```

**Comment by webpro** [comment]
Hi, @Enteleform!

Interesting idea, but at first thought I don't really like this extra complexity in the core of release-it. I'll keep this issue open so others can show their interest.

If it is important for you, you could create a plugin based on the current version plugin. Some example code (pseudo/untested):

```js
const Version = require('release-it/lib/plugin/version/Version')

class CustomVersion extends Version {
  disablePlugin() {
    return 'version'
  }

  constructor(...args) {
    super(...args);

    const prompts = {
      incrementList: {
        type: 'list',
        message: 'Select increment:',
        choices: this.options.increments || ['patch', 'minor', 'major']
      }
   };
    this.registerPrompts(prompts);
  }
}
```

Usage:

```json
{
  "plugins": {
    "./custom-version.js": {
      "increments":  ["patch", "minor", "major"]
    }
  }
}
```

**Comment by eMarek** [comment]
I would also like to have an option to pick increments. I am currently not interested into "prereleased" types.

I tried to write a plugin, but I now I get that previous version is always `0.0.0`.

**Comment by webpro** [comment]
Implement a `getLatestVersion` method in your plugin class and have it return `null` or `undefined`.

**Comment by brandondurham** [comment]
@webpro Can I just say how much I appreciate your response being basically “not sure I think that’s a good idea for the project, BUT HERE IS HOW YOU CAN DO IT IN _YOUR_ PROJECT.” So gracious and thoughtful.
