### ISSUE TITLE
Feature: Allow release-it to create major "v1" tag for "v1.0.1" version

### ISSUE THREAD

**Issue by ruzickap** [release-it/release-it#663]
Hello.

Would it be possible to add some parameter which allows `release-it` to create also the major tags like:

`v1.0.1` -> `v1` 
`v2.1.0` -> `v2`

This is especially handy when developing + creating GitHub Actions (for example: https://github.com/ruzickap/action-my-broken-link-checker/releases).

GH Actions needs to call 

```yaml
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v1.0.1
```

or

```yaml
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v1
```

The `@v1` tag is handy when you do not want to change the patch/minor versions all the time.

**Comment by webpro** [comment]
Based on some shell scripting:

```
❯ echo v1.0.0 | cut -d. -f1
v1
```

You could for example (untested):


```json
{
  "hooks": {
    "after:bump": "git tag --force $(echo ${tagName} | cut -d. -f1)"
  }
}
```

**Comment by ruzickap** [comment]
Yes, that is possible - no question about it. You can use git to tag `v1` yourself.

But when you run the `release-it` again, then you got into problems, because last tag is not `v1.0.0`, but `v1`:

```bash
# release-it -VV
$ git rev-parse --abbrev-ref HEAD
master
$ git config --get branch.master.remote
origin
$ git remote get-url origin
git@github.com:ruzickap/action-my-broken-link-checker.git
$ git fetch

$ git describe --tags --abbrev=0
v1
...
...
? Select increment (next version): (Use arrow keys)
❯ patch (null)
  minor (null)
  major (null)
  prepatch (null)
  preminor (null)
  premajor (null)
  Other, please specify...
```

Looks like `release-it` can not parse `v1` properly and it offers only the `null` "version":

```bash
$ git tag --list
v1
v1.0.0
```

Thank you

**Comment by webpro** [comment]
> Yes, that is possible - no question about it. You can use git to tag `v1` yourself.

Hey, I'm just trying to help here.

> Looks like release-it can not parse `v1` properly

With such a "dual-tag" system, release-it would also need to parse such tags and determine the "highest" (according to semver) one. Not sure I want to get into this.

Feel free to extend the existing Git plugin, though, and use this as a plugin. This would allow you to adjust both the tag reading and writing. Perhaps based on some parameter as you suggested. Let me know if you need any help!

**Comment by ruzickap** [comment]
Hello.

I'm sorry I didn't want to be offensive. 
You are doing great work on a great tool - thank you for that.

Parsing multiple tags is too complex and it may be hard to implement.

Thank you for your help.

Keep up the good work :-)
