### ISSUE TITLE
Ability to rename a draft release

### ISSUE THREAD

**Issue by Page-** [release-it/release-it#668]
I have a use case where we have a draft release per PR so that the release artifacts of a PR can be generated/tested and then reused on a merge, this means that when merging I need to be able to rename the release's tag/name from the PR naming schema to the versioned v1.2.3 naming scheme once the PR is merged - I'm happy to work on implementing and PR that but I'd like to get an idea of how you'd want to approach adding it before I start

**Comment by webpro** [comment]
I would think that when you use `--github.draft` for the first round, and then `--no-increment` for the second round with a "hard-coded" `--github.tagName=v1.2.3`, it should do what you're after.

Would be a non-documented feature. Internally, the GitHub plugin defaults to the `git.tagName` setting from the Git plugin, but not if its own option is set already.
