### ISSUE TITLE
configure verbosity in config file

### ISSUE THREAD

**Issue by crimson-med** [release-it/release-it#670]
I noticed we can run `release-it --verbose` and this will display the output of all hooks. 
This is very practical as in my hooks I have some ssh commands that launch a script and thus I can see the output of scripts:

```
{
    "hooks": {
        "before:init": "echo 'Deploying XXX'",
        "after:bump": "git push origin master --follow-tags",
        "after:release": [
            "ssh -t -t user@dev 'sudo ./pack.sh v${version}'",
            "ssh -t -t user@prod 'sudo ./unpack.sh v${version} && . post-deploy.sh ${version}'",
            "echo Successfully released ${name} v${version} to ${repo.repository}.\n"
        ]
    }
  }
```

Is there any way to add --verbose to my: `release-it.json` so by default when I simply do the command `release-it` it will be with the verbose info

**Comment by webpro** [comment]
Did you try to add `"verbose": true`? Otherwise it's a bug :)

**Comment by crimson-med** [comment]
Yes I also tried:
{
    "verbose": true,
    "hooks": {
        "before:init": "echo 'Deploying XXX'",
        "after:bump": "git push origin master --follow-tags",
        "after:release": [
            "ssh -t -t user@dev 'sudo ./pack.sh v${version}'",
            "ssh -t -t user@prod 'sudo ./unpack.sh v${version} && . post-deploy.sh ${version}'",
            "echo Successfully released ${name} v${version} to ${repo.repository}.\n"
        ]
    }

**Comment by webpro** [comment]
OK, clear. On *nix you could add a function or alias for this, though, for example:

```
alias release="release-it --verbose"
```

**Comment by crimson-med** [comment]
Seeing as we use release-it to make the deployment easier for multiple contributors of the project I wouldn't want to ask everyone to add an alias. Is this a confirmed bug that `"verbose": true` does not change anything or is it a pending feature?

**Comment by webpro** [comment]
I think everything is working fine actually. Which version of release-it are you using?

- `"verbose": true` - log hooks commands and their output
- `"verbose": 2` - log all (hooks + internal) commands and their output

Verified that this also works from a local `.release-it.json` config file.

I will updated the docs for raising the verbosity level from a config file.

**Comment by crimson-med** [comment]
my current version is `13.6.2` and during post creation was `13.6.1`

As of `13.6.2` this is now working

**Comment by webpro** [comment]
The 13.6.x releases contain no related changes, but I'm happy it's working for you now.
