### ISSUE TITLE
unable to publish package

### ISSUE THREAD

**Issue by varora1406** [release-it/release-it#671]
command ran - `yarn release-it`

Selected development release, with commit, tag, push.
Then selected to publish package (new package for npm), and error pops up:

> npm ERR! 401 Unauthorized - PUT https://registry.yarnpkg.com/_package-name_ - You must be logged in to publish packages.

**Comment by varora1406** [comment]
Apologies, it was mistake of wrong Github URL in package file.
Point still to be noted - Error message was not clear of reason

**Comment by troZee** [comment]
In my case, I needed to add below code to `package.json`

```
  "publishConfig": {
    "registry": "https://registry.npmjs.org/"
  },
```
