### ISSUE TITLE
Clean version of prereleases

### ISSUE THREAD

**Issue by eMarek** [release-it/release-it#673]
Let's imagine that I am releasing prereleases in some period of time `v1.4.0-rc.0`, `v1.4.0-rc.1`, `v1.4.0-rc.2`, etc...

Is it possible to have clean version in `package.json` after each prerelease has been done? By that I mean that `package.json` version would be always the same `1.4.0` no matter which release candidate I am making.

My use case is that I have a pipeline workflow rule which runs the pipeline if tag is in format `v.[X].[X].[X]` or `v.[X].[X].[X]-rc.[X]`. I also create the build name based on the tags. However I would like to have clean `package.json` version in order to have less merge conflicts and that I can reuse the number else where.

Subquestion, is it possible to replace dot for dash. I would prefer `v1.4.0-rc-2` over `v1.4.0-rc.2`?

**Comment by webpro** [comment]
> Is it possible to have clean version in `package.json` after each prerelease has been done?

You could use a hook for this (see #663 for a somewhat similar situation).

> Subquestion, is it possible to replace dot for dash. I would prefer `v1.4.0-rc-2` over `v1.4.0-rc.2`?

release-it follows the [semver specs](https://semver.org/) by using [semver](https://www.npmjs.com/package/semver). I think both the specs and the lib don't support this (not 100% sure, though).

**Comment by eMarek** [comment]
I was not aware that `v1.4.0-rc.2` is by semver specs. I will stick with this format then. Thanks for letting me know.

Regarding that first question, I think that #663 does not address my problem. I will try to paraphrase my situation. I am on version `1.3.0` at the moment. My latest tag is `v1.3.0`. Now I would like to create minor prerelase where new GIT tag `v1.4.0-rc.0` is created and my `package.json` version to become `1.4.0`. Is this possible to achieve?

**Comment by webpro** [comment]
What I meant to indicate with a reference to the other issue is that you can use a hook to update the version number. You would basically re-set the `version` in `package.json`, e.g. in the `after:bump` hook you could use `npm version 1.4.0` - and like in the other ticket you might need some shell scripting or similar to get the desired version (without the pre-id).

Thinking of it, maybe release-it could easily add `major`, `minor`, `patch` variables in these template hooks.

**Comment by eMarek** [comment]
Understood. Actually I've figured it out that I will rather use full version of prerelease (e.g. `v1.4.0-rc.0`) in package.json file. Entire delivery workflow is better. Thank for the help anyway.
