### ISSUE TITLE
Error: No valid exports main found for '/release-it/node_modules/uuid'

### ISSUE THREAD

**Issue by antoniandre** [release-it/release-it#674]
Hi, thanks for this package, it looks great and I'd like to use it.
I tried to install it following the instructions: `npm init release-it`

Then run it with `npm run release`.

When I run it this error is returned: `Error: No valid exports main found for '/release-it/node_modules/uuid'`

I found this related issue https://github.com/uuidjs/uuid/issues/428 but everybody says upgrading node solves the issue and the issue is closed.

I upgraded to the latest node (14.4.0) and npm (6.14.5), also tried the node version 14.2.0 that people so it worked with, but the error is still there.

I tried release-it@13.6.2 and release-it@13.5.8.

Thanks for help!

**Comment by ctavan** [comment]
I fear that this is specific to your local setup. Are you installing release-it as a local devDependency or globally? Have you tried removing the `node_modules` directory and installing again?

I've quickly installed it locally and it works without problems on Node.js 14.4.0

**Comment by webpro** [comment]
While at Node v14.4.0, I just added release-it v13.6.2 to some project and `npm run release` runs without errors. So I also think it's not an issue in the release-it package, that's why I'm going to close this issue.
