### ISSUE TITLE
release-it ignores NPM_REGISTRY and NPM_TOKEN

### ISSUE THREAD

**Issue by ebekebe** [release-it/release-it#675]
I noticed that release-it v13.6.2 doesn't seem to honor the environment variables `NPM_REGISTRY` and `NPM_TOKEN`. We use it to publish to the github registry without the need to touch config files like `.npmrc`.

The following works:
```sh
$ release-it --no-npm.publish && npm publish
```

The following doesn't work:
```
$ release-it
ERROR Not authenticated with npm. Please `npm login` and try again.
```

The env vars seems to be available to release-it:
```
$ node_modules/release-it/bin/release-it.js "--verbose" "--hooks.before:init=echo \$NPM_REGISTRY"
$ echo $NPM_REGISTRY
npm.pkg.github.com
ERROR Not authenticated with npm. Please `npm login` and try again.
```

Originally posted [here](https://github.com/release-it/release-it/issues/592#issuecomment-642688106).

**Comment by webpro** [comment]
This means the `npm whoami` command fails for you.

You could use `--npm.skipChecks` so it skips `npm ping` and `npm whoami`.

Now I'm curious whether `npm publish` from release-it works for you :)

**Comment by ebekebe** [comment]
@webpro Indeed, `npm whoami` fails.

With `--npm.skipChecks` it works now. Thank you.

I would love to see this documented somewhere. At least I couldn't find it in the documentation. I looked into [readme](https://github.com/release-it/release-it/blob/master/README.md), [npm](https://github.com/release-it/release-it/blob/master/docs/npm.md) and [ci](https://github.com/release-it/release-it/blob/master/docs/ci.md#npm).

**Comment by webpro** [comment]
Good to hear. I agree it's not clear in the docs. There is https://github.com/release-it/release-it/blob/master/README.md#prerequisite-checks and then https://github.com/release-it/release-it/blob/master/docs/prerequisites.md

But this should obviously be linked to from the npm page itself. Will do! Thanks for pointing this out.
