### ISSUE TITLE
Version plugin not enabled when defining another plugin in config

### ISSUE THREAD

**Issue by nightvisi0n** [release-it/release-it#676]
Hey, at first thanks for this cool project.  

Unfortunately I stumbled upon a bug with the plugin system.  
With the following config:  
```json
{
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": "angular",
      "infile": "CHANGELOG.md"
    }
  }
}
```
release-it don't asks which release type it should generate (and generally it's unable to generate a version:  
```shell
❯ npm run release

[..]

🚀 Let's release [..] (currently at null)


Changelog:
[..]

Changeset:
[..]
AM CHANGELOG.md

? Commit (Release )? (Y/n) 
```

If I enforce the loading of the `version` plugin everything is normal again:  

```json
{
  "plugins": {
    "./node_modules/release-it/lib/plugin/version/Version.js": {},
    "@release-it/conventional-changelog": {
      "preset": "angular",
      "infile": "CHANGELOG.md"
    }
  }
}
```

```shell
❯ npm run release

[..]

🚀 Let's release [..] (currently at 0.0.0)


Changelog:
[..]

? Select increment (next version): (Use arrow keys)
❯ patch (0.0.1) 
  minor (0.1.0) 
  major (1.0.0) 
  prepatch (0.0.1-0) 
  preminor (0.1.0-0) 
  premajor (1.0.0-0) 
  Other, please specify... 
```

**Comment by webpro** [comment]
The idea of this plugin is to provide the recommended bump for you, based on the commits. so it should not ask you for the next version. It comes with this version before the Version plugin does, so it has precedence.

Perhaps this doesn't work when there are no tags and/or no commits yet.
