### ISSUE TITLE
Make release-it create a PR rather than pushing the changes to master

### ISSUE THREAD

**Issue by pedroapfilho** [release-it/release-it#678]
On the current workflow that we use, we have to "release" master in order to push the changes on our package.json. What would be nice to have, would be to create a PR with the changes to master, and not pushing it directly.

**Comment by webpro** [comment]
But that's not what _release-it_ was made for :)

Besides opening a PR, what would release-it still do in your workflow?

**Comment by pedroapfilho** [comment]
Well, our workflow is basically:

1- Bump the version on the `package.json`, so we know the version that we have in `dev`, `staging` and `live`

2- Create the tag

3- Release that tag on Github with all the changes

So at the end, we have the release made with all the changes, the tag of the release, the `package.json` updated and `travis` ready to deploy that release

**Comment by webpro** [comment]
On mobile currently. But you could at least generate a url to start creating a PR for this. You can log this to the console and then open (e.g. cmd-click) in the browser. Use the after:release hook and available variables to echo this url (not sure how this url looks like, but you basically compare branches from it).

**Comment by pedroapfilho** [comment]
Well, thinking about it, I could use the CLI to:

1- Create a new branch with the name as that tag (not sure how to get the tag here)
2- Use the `gh pr create --fill` to create the PR.

Nice catch. Then I would need only to remove the `push` of the `release-it` and add these parts to the `after:hook`.

BTW, do you know how can I get the release tag on the `after:hook`?

**Comment by webpro** [comment]
Sounds good! This idea we can add to the docs.

You can use all variables mentioned in the hooks section of the docs and config options like ${git.latestTag}
