### ISSUE TITLE
Mode to keep 'Select increment' prompt and skip the rest

### ISSUE THREAD

**Issue by Cmacu** [release-it/release-it#681]
A mode where `Select increment (next version):` is enabled, and the rest of the prompts (commit, tag, push, release) are skipped based on the defined settings would be nice.

**Comment by webpro** [comment]
I'm working on this feature, expect it soon in v14

**Comment by webpro** [comment]
You can try this with `--only-version` in [v14.0.0-alpha.0](https://github.com/release-it/release-it/releases/tag/14.0.0-alpha.0)

Please give it a try with `npm install release-it@alpha`
