### ISSUE TITLE
Empty release published when using git.changelog

### ISSUE THREAD

**Issue by rohitchawla22** [release-it/release-it#683]
for release-it in package.json, when adding changelog as a property under git eg:

```
"git": {
      "requireCleanWorkingDir": false,
      "requireUpstream": false,
      "requireCommits": false,
      "addUntrackedFiles": false,
      "pushArgs": ["--force", "--no-verify"],
      "changelog": "git log --pretty=format:'* %s (%h)' [REV_RANGE]"
    },
```

By following the documentation, I tried using 
```
"changelog": "git log --pretty=format:\"* %s (%h)\" ${from}...${to}",
```

and the result remains the same.
Publishes a release on github with no data, resulting in an empty entry in CHANGELOG.md.

**Comment by webpro** [comment]
So the default is this:

```json
"git": {
  "changelog": "git log --pretty=format:\"* %s (%h)\" ${from}...${to}",
}
```

Then it still depends on the commits between the latest tag and the `HEAD`.

With `"requireCommits": false`, you may have no commits, it's probably a good idea to use the default setting here (`true`).
