### ISSUE TITLE
Plugin to comment/label linked GitHub issues

### ISSUE THREAD

**Issue by maniax89** [release-it/release-it#685]
I was wondering if there is a list of community plugins or potentially a plug-in that matches the functionality of  https://github.com/semantic-release/github (which comments on related GitHub issues that are found in the changelog). I wanted to use `release-it` because it offers more flexibility around prereleases than semantic-release.

If not, I'm not sure if there are any desires to include the functionality in the already embedded github plugin  https://github.com/release-it/release-it/blob/master/lib/plugin/github/GitHub.js or it's better to make a completely separate plugin.

**Comment by webpro** [comment]
Afaic, the list is https://www.npmjs.com/search?q=keywords:release-it-plugin (and https://github.com/release-it/release-it#plugins)

Sounds like the feature you mention is not available yet, and would work best in a separate plugin. This could potentially inherit from the internal GitHub plugin, but I'm not sure if this has added value.

**Comment by maniax89** [comment]
One benefit I see is to maintain common configuration variables like GitHub personal access token and host so that users wouldn't have to define common github-related configuration multiple times

**Comment by webpro** [comment]
That would definitely be inconvenient. Sharing configuration (or other data) would not be an issue with a separate plugin (there's eg the [getInitialOptions](https://github.com/release-it/release-it/blob/master/docs/plugins.md#getinitialoptionsoptions-pluginname--object) with access to all config).
