### ISSUE TITLE
release-it plus git-flow commands

### ISSUE THREAD

**Issue by jason-henriksen** [release-it/release-it#691]
I love the look of release-it, especially the interactive nature of the system.
But my company needs a tool that offers both version management and branch management that follows the full git-flow process.

I'm considering making a fork of release-it that would support:

```
feature start <featureName>          // create a feature branch from develop and enforce a naming convention
feature finish <featureName>  // merge the branch into develop

release start <featureName>         // create a release branch from develop, bump ver and add -RC automatically. QA tests here.
release finish <featureName> // merge the release branch to master and remove -RC automatically
release now <featureName>         // merge develop to master with a bumped version number (skip the release branch)

fix start <featureName>                 // create a fix branch from a release branch and add -fix automatically
fix complete <featureName> // merge the fix branch to a release branch and bump version plus add -RC automatically

````
(Basically, mimicking git-flow cli, but keeping it all in one tool.)
If I wrote this, would your team have any interest in it?   
Or is there some other tool you use to manage the branches that you would suggest instead?

**Comment by webpro** [comment]
I think version/release management and a specific branching model don't go very well into a single tool. As you wrote out, the branch management consist of multiple commands at different moments in the process. On the other hand, the actual release is usually (ideally?) only a single invocation (release-it). However, we can still look into how release-it could assist better in any release flow.

Also, I think it will help to write out the actual shell (mostly git) commands for this flow for each moment/step in the process.

Maybe interesting: there's `npm version 1.2.3` that can bump and commit in a single commit.

Obviously you are free to fork this repo and modify as you see fit.

Personally I'm usually not using any other tools than plain Git. The "team" is just me, by the way :)

**Comment by jason-henriksen** [comment]
Generally, I agree with you and prefer to use git directly.  But I'm working for a medium sized corp and they do not want the developers making inconsistent branch names and doing things that could mess up the release process.  So this is mostly a sort of "guard rails" effort around the branch management that will use the release-it for the version management, tagging and change logging.

I've made a clone of the repo and I've started adding what I need.   I'll send you an animated gif when it's done so you can see if you have any interest in it.

BTW, the plugin architecture you put together is the main reason I decided to re-use your code.  It's really really nice to be able hook into your setup.   Even if you don't end up needing the parts I add, I really appreciate that you put together such a clean system for this.  Thank You!

**Comment by webpro** [comment]
That's great @jason-henriksen, if you could implement this as a plugin, it might be useful to more people/teams using git-flow! Happy to look into it when you have something. Any questions/feedback on the plugin system is also welcome of course.

**Comment by jason-henriksen** [comment]
Here's a recording of the user interface for what I did.  If you click the image it zooms in and it's a lot easier to read.  Also, my git access was slow in this recording.  Give it a minute and the recording will continue
https://imgur.com/a/xXraSDl

It is 90% done in a plugin, but there were a few things that I altered the tasks.js and versions.js to do.   I think with a little more effort I could minimize those 'outside-the-plugin' changes and give you a pretty clean "just the plugin" build.

Take a look at that image, and if you like the direction I'll keep cleaning it up, finish the unit tests and send the code your way.

**Comment by webpro** [comment]
Nice work Jason! Looks good. Looking forward to see what changes this requires in the release-it core. Note that, at least initially, I'd rather see this as an external plugin, maintained by you and your team (as key users).

**Comment by jason-henriksen** [comment]
Sure, sounds good.  I'll try to package it that way, and give a separate PR for the "core" changes that are needed.
It may be a  week or so, but I'll get back to you when it's ready.

**Comment by softmantk** [comment]
@jason-henriksen  any updates ?
