### ISSUE TITLE
Allow variables to be used in cmd line arguments

### ISSUE THREAD

**Issue by mmckeon16** [release-it/release-it#693]
I am trying to use ${version} in this cmd arguments in package.json for releasing a release candidate like the following:
`npx release-it --git.commitMessage \"chore(Release): v${version} [skip-ci-rc]\""`

Which overrides the git commit message hook for an actual release (since my rc release and actual release commit messages are different), but the ${version} is empty so the actual release message that is committed is "chore(Release): v [skip-ci-rc]"

I am using release-it@13.6.7

**Comment by webpro** [comment]
Please use single quotes on the command line, I think the shell is already trying to replace variables before it enters release-it.

**Comment by mmckeon16** [comment]
yup, that was it. Thank you!!
