### ISSUE TITLE
Only-version flag doesn't work

### ISSUE THREAD

**Issue by michaelcavallaro03** [release-it/release-it#694]
Hi 👋 

Looking at the documentation, it appears that the flag `--only-version` is supposed to disable all prompts with the exception of the version specification ie. `minor`, `major`, etc. However I have not been able to get this feature to work.

Very briefly looking at the code for `release-it` it doesn't appear that this flag has been implemented. (very well could be missing something).

Running: `release-it --only-version` I would expect to only be prompted for version however I am getting all prompts.

Am I understanding it's implementation correctly? Or is this feature not yet implemented?

I'm happy to open up a PR to add this! Thanks!

**Comment by michaelcavallaro03** [comment]
Realizing now that this might be a duplicate of #681

**Comment by webpro** [comment]
Sorry @michaelcavallaro03, I updated the docs and already included this bit about an upcoming feature.

However, you can try this now with `--only-version` in [v14.0.0-alpha.0](https://github.com/release-it/release-it/releases/tag/14.0.0-alpha.0)

Please give it a try with `npm install release-it@alpha`

**Comment by michaelcavallaro03** [comment]
@webpro  No worries at all! That sounds awesome! Thanks for letting me know! Also, great work on this library was very easy to setup 🚀
