### ISSUE TITLE
No effect on git commit message option 

### ISSUE THREAD

**Issue by lGSMl** [release-it/release-it#695]
I was trying to edit git commit message to include '[skip ci]' key phrase for gitlab.

I have tried both - add it to .release-it.json in project root like

```
cat .\.release-it.json
{
  "git": {
    "requireCleanWorkingDir": true,
    "requireUpstream": true,
    "commitMessage": "Release ${version} [skip ci]"
  }
}
```

and supply argument directly in cli like
`npx release-it prepatch --preRelease=alpha --npm.ignoreVersion --git.commitMessage='Release ${version} [skip ci]'`

but in both cases commit message was default, e.g. `Release 2.1.4-alpha.32`

version used `"release-it": "13.6.6",` (latest one conflicts with @types/yargs-parse)

**Comment by webpro** [comment]
That's odd. Just verified and seems to work fine here, and I know many users do this.

Are you sure in the git log you don't see `[skip ci`? Maybe you refer to the `gitlab.releaseName` option?

**Comment by lGSMl** [comment]
I am sorry, was bad on my side. Our in-house npm registry messed up versioning and I was trying to use this option on the version it was not there yet.
