### ISSUE TITLE
Change Order (GitHub after npm) / Fail-safe Rollback & Publishing

### ISSUE THREAD

**Issue by buschtoens** [release-it/release-it#701]
Sorry, if this has been asked before, but a quick skim through the issue tracker didn't show anything.

Would it be possible to change the execution order, so that the commit is pushed to and the release is created on GitHub _after_ the package was successfully published on npm?

The reasoning is that the npm publish step IMO is the most fragile one and may break, e.g. because of lacking permissions or errors in the `prepublishOnly` script. If it fails, the version bump commit has already been pushed and the GitHub release has already been created.

This means that in case of a failed npm publish, I need to remove the commit, force push the main branch and also delete the tag.

**Comment by webpro** [comment]
Currently this is not a feature, but I understand it makes sense. I'll look into it soon.

Personally I'd just re-run `npm publish` again in case of a hiccup (provided it's just an access/network issue).

And just saying, there are some checks in place (for npm: `npm ping`, `npm whoami` and `npm access ls-collaborators`), but yeah, anything could fail in the whole process for sure :)

**Comment by buschtoens** [comment]
Yeah, `npm publish` seems to be an acceptable solution as well. I just need to consciously remember using the right `--tag`, if necessary. 😄 

Thanks for considering!

**Comment by rwjblue** [comment]
> Personally I'd just re-run npm publish again in case of a hiccup (provided it's just an access/network issue).

I don't think this actually works properly. Specifically the following rollback behavior leaves the local repository in a different state than the remote:

https://github.com/release-it/release-it/blob/229ed755e23c19706c5fd77cbdc547901ca84aba/lib/plugin/git/Git.js#L48-L50

Which is only removed in `afterRelease`:

https://github.com/release-it/release-it/blob/229ed755e23c19706c5fd77cbdc547901ca84aba/lib/plugin/git/Git.js#L179-L183

But (assuming an error occurs during a `prepare` script or something) the remote has already received the new commit and tag:

https://github.com/release-it/release-it/blob/229ed755e23c19706c5fd77cbdc547901ca84aba/lib/plugin/git/Git.js#L62

---

Maybe we should ensure that `rollback` cannot be called after `.push()` has completed?

**Comment by webpro** [comment]
Thanks guys, very useful input. I'm going to give this a good thought this weekend, and see whether/how the order of things should change (there might be use cases that would be negatively impacted). My first idea right now is that this order makes sense:

1. npm version (bump)
2. npm publish
3. git commit + push
4. github (or gitlab) release

I think the npm publish step is the most error-prone step, making roll-backs less of a necessity (but for sure this can be improved as well).

**Comment by webpro** [comment]
@buschtoens @rwjblue Just released [v14.1.0-next.0](https://github.com/release-it/release-it/releases/tag/14.1.0-next.0) with the order as mentioned before. Also the rollback is disabled after a successful push.

Any chance you guys could give `release-it@next` a go? :)

**Comment by rwjblue** [comment]
Tested locally, and seems to be much better. Thank you for working on it!

**Comment by webpro** [comment]
Thanks guys, it's in [14.1.0](https://github.com/release-it/release-it/releases/tag/14.1.0)
