### ISSUE TITLE
CI Detection broken on github?

### ISSUE THREAD

**Issue by TheRealWaldo** [release-it/release-it#702]
Hey @webpro , 

  Looks like another spot may be impacted:

```
 🚀 Let's release gh-action-release-it (currently at 0.1.1)
  
  
  Changelog:
  ## [0.2.0](https://github.com/TheRealWaldo/release-it/compare/v0.1.1...v0.2.0) (2020-09-15)
  
  ### Features
  * return version and latestVersion outputs #90 ([2035af0](https://github.com/TheRealWaldo/release-it/commit/2035af0692bfa6e0d9dd7a531a4570f199de65df))
  
  - npm run lint-fix && npm run build
  ✔ npm run lint-fix && npm run build
  
  Changeset:
  M README.md
   M dist/index.js
   M package-lock.json
   M package.json
  
  ? Commit (chore(release): v0.2.0)? (Y/n) Rolling back changes...
```

Doesn't indicate failure, and this is without dry-run.  With dry-run it seems to still work.

**Comment by webpro** [comment]
That looks odd. Did you have a chance to confirm and commit here, or not?

What happens with a `DEBUG=release-it:* release-it [...]`?

(By the way, you can use arrays in hooks, e.g. `["npm run lint-fix", "npm run build"]`)

**Comment by TheRealWaldo** [comment]
@webpro this is a CI run; it shouldn't be prompting at all (and was working prior to the 14 release)

**Comment by webpro** [comment]
Right, didn't realize it's running in a GitHub Action. Should have been fixed in v14.0.2 (#699), in which I've also added a test for this which passes in a GitHub Action, and restores the original logic (as in v13).

Do you have something to reproduce this?

**Comment by TheRealWaldo** [comment]
Hi @webpro , Yes when we do actual releases; it seems to work fine when we use the --dry-run flag for our testing pre-release.  But the moment you remove the --dry-run flag it starts prompting again.

This shows a failing run (on the release-it step):
https://github.com/TheRealWaldo/release-it/runs/1119435406?check_suite_focus=true

It's further made more complicated by the fact that when it aborts, it still returns success, so unless one is paying attention you would never know it didn't work.

So perhaps also a feature request, that on abort, release-it returns an exit code other than 0?

**Comment by webpro** [comment]
* Perhaps from the GitHub Action, it's running in a different (Alpine) container, where `is-ci` won't find some environment variable (i.e. `CI`)? You can use `--ci` or `ci: true` in the release-it config to enforce this.
* When release-it runs from CLI it exits code with `1` on errors, and it throws when used programmatically. But the error is catched/handled here?

https://github.com/TheRealWaldo/release-it/blob/master/src/index.js#L97-L108

**Comment by TheRealWaldo** [comment]
@webpro release-it doesn't actually throw an exception here apparently, so not getting to the catch. Because it's being called programatically it's not leveraging the CLI wrapper; is there another result that it returns besides throwing an exception in this condition?

Looking through the release-it code I do not see an abort or timeout triggering a fail of any kind....  Also trying on the CLI, it returns 0 post abort.

Other errors are certainly being caught and failing the build appropriately from past experience, but the abort doesn't seem to.

This is also running in a standard ubuntu container (same as the with the --dry-run, which is working as expected without prompting) and was fully functional prior to v14.

**Comment by TheRealWaldo** [comment]
Just a note @webpro , I haven't found the exact location, but this feels like a scoping issue.  The value from is-ci doesn't seem to be propagating everywhere it's needed.

**Comment by webpro** [comment]
I don't have time to dig into this now, but you can use `--ci` (or `ci: true`) to force this setting.

**Comment by webpro** [comment]
I'm going to close this issue. CI detection is apparently failing in specific cases, but can be forced with `--ci`. Feel free to re-open and discuss further.
