### ISSUE TITLE
after:git:release hook not executed

### ISSUE THREAD

**Issue by j-ulrich** [release-it/release-it#705]
I try to use the `after:git:release` hook but it is not executed. It isn't logged in a `--dry-run` either.

If I use `after:git:afterRelease` instead, the hook is executed and also logged in `--dry-run`.

In case it matters, my config also has these settings:
```json
	"git": {
		"tag": false,
		"push": false
	},
	"npm": {
		"publish": false
	},
```
I also tried it when setting the git settings to true but it's the same: `after:git:release` is not executed but `after:git:afterRelease` is executed.

This is how the end of the output from a dry run looks like with `after:git:release` hook:
```
? Commit (Release 0.5.1)? Yes
! git commit --message Release 0.5.1
🏁 Done (in 3s.)
```

In contrast, the same config but just replacing `after:git:release` with `after:git:afterRelease`:
```
? Commit (Release 0.5.1)? Yes
! git commit --message Release 0.5.1
! echo "hello from the after:git:afterRelease hook!"
🏁 Done (in 2s.)
```

I'm using version 14.0.3.

**Comment by webpro** [comment]
Only when the `git push` was successful, it will execute the `after:git:release` hook. Same goes for e.g. the `npm publish` (`after:npm:release` hook). I just added a line in the docs about this, thanks :)
