### ISSUE TITLE
Add option github.releasePublishMarketplace for Github Actions

### ISSUE THREAD

**Issue by imsamdez** [release-it/release-it#706]
Hey,

When it comes to create a new release for a Github Action, there is an option to publish it to Github Marketplace (see screen bellow, sorry for dark theme btw!)

<img width="1046" alt="9bf5404de95abfbf20848194aeeb7f5f" src="https://user-images.githubusercontent.com/22425976/94370187-b8592b00-00ee-11eb-8faa-5c0bd930a384.png">

I checked current release-it options for `github` and could not find something related to this.

Is it implemented yet ? If not, would it be relevant in an upcoming version ? 

Thanks for your answer!

**Comment by rwjblue** [comment]
I looked for this also!! When I looked a few months ago, I couldn't find anything in the GH API request that we could use that emulates what they have in the GH GUI.

Here is what we are doing right now:

https://github.com/release-it/release-it/blob/229ed755e23c19706c5fd77cbdc547901ca84aba/lib/plugin/github/GitHub.js#L205

This is ultimately calling through to this GH API: 

https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-release

But I don't see any parameters that can be used to emulate that "publish to the marketplace" checkbox...

**Comment by imsamdez** [comment]
Well, the process of publishing requires a lot of prerequisites (unique name, description, two-factor enabled, accept terms...). That can explain why its not yet implemented!

I found [this topic](https://github.community/t/how-to-publish-an-action-to-the-marketplace-programmatically/16452/5) on GH Community where it says that it should come but we don't have a timeline yet.

So i guess we can close this issue!

**Comment by webpro** [comment]
For what it's worth, we could already add the configuration option and remind/warn the user to follow the link to the GH release (it's printed at the end of the release-it process), and manually publish the action to the marketplace.

**Comment by webpro** [comment]
Closing this issue for now.
