### ISSUE TITLE
Increase existing prerelease version by patch, minor, major

### ISSUE THREAD

**Issue by pstrh** [release-it/release-it#707]
It would be nice if release-it would behave like semver if the current version is a prerelease version and the version should now be incremented by patch, minor, major.

Semver allows to increment the version from 1.2.3-next.0 to 1.3.0-next.0 directly by calling:

    semver --increment preminor --preid next 1.2.3-next.0
    // result: 1.3.0-next.0

Instead release-it will increment from 1.2.3-next.0 to 1.2.3-next.1.

    release-it preminor --preReleaseId=next
    // result: 1.2.3-next.1

    release-it minor --preRelease=next
    // result: 1.2.3-next.1

The change would be helpful if you already released a prerelease version, but then later decide to increase the version (e.g. from minor to major).

Thank you for this great project 😃👍

**Comment by webpro** [comment]
Yes I agree @pstrh, never needed this myself, but can look into this soon. Or feel free to take a stab at it and open a PR :)

**Comment by pstrh** [comment]
@webpro Great! I would try to help with the issue and will create a PR within the next days.

**Comment by webpro** [comment]
Nice! Let me know if/when you need any help, happy to assist.

**Comment by pstrh** [comment]
Released with v14.2.0
