### ISSUE TITLE
yarn build not working

### ISSUE THREAD

**Issue by Manjiri1101** [release-it/release-it#712]
Hello,
I am executing yarn build command from vscode, it is throwing the following errors:

`warning package.json: No license field
$ yarn clean:code
warning package.json: No license field
$ rm -rf dist
'rm' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1`

I am afraid to remove "dist" folder. Can anyone help me out?
Thanks.

**Comment by webpro** [comment]
Hello @Manjiri1101, I don't think this issue is related to release-it. So I'm closing this ticket.
