### ISSUE TITLE
Prerelease continuation increases patch version in CI mode

### ISSUE THREAD

**Issue by pstrh** [release-it/release-it#714]
#707 introduced an inconsistent behaviour of interactive and CI mode in regards to prerelease continuation.

**Steps and result:**
Current version is 2.0.0-beta.1

    release-it --preRelease=rc 

results in 2.0.0-rc.0

While

    release-it --preRelease=rc --ci

results in 2.0.1-rc.0

**Expected:**
Both commands should result in 2.0.0-rc.0. With the ```--ci``` flag the patch version should not be increased.

**Cause:**
Reason for this issue is that "patch" is the default version increment in CI mode and since #707 patch/minor/major are process in conjunction with the preRelease flag.

**Comment by webpro** [comment]
Closing this as the fix has been released.
