### ISSUE TITLE
@release-it/conventional-changelog: version not printed in custom message

### ISSUE THREAD

**Issue by Morriz** [release-it/release-it#717]
Hoi Lars and co, when using a custom message icw the `@release-it/conventional-changelog` plugin `%s` is not replaced in the `"commitMessage": "chore(release): v%s"` when running npm release with scripts `"release": "release-it"`. This results in the message `chore(release): v`.

**Comment by webpro** [comment]
Hi Maurice! Please use the `${version}` syntax instead (indeed, it was `%s` before).
