### ISSUE TITLE
git http support

### ISSUE THREAD

**Issue by jbadeau** [release-it/release-it#718]
Hello,

I am using CodeFresh to build and it uses http to clone repos.

Do u support or plan to support Git http connections?

**Comment by webpro** [comment]
I'm not aware of issues here. I don't know CodeFresh. Git protocol `https` works fine, not sure about `http`. Did you try, and if so, what errors do you encounter? In general, release-it defers this work to Git itself (e.g. when you can do `git push` manually, then release-it does the same and should work as well).

**Comment by jbadeau** [comment]
I checkout using https with codefrech
when I try to run release-it, i get the expected message that the username and email is not set

1. add support to provide the git username and email and password via env args in the 

```json
git": {
    "userName": "${gitUserName}"
    "pushRepo": "${gitUserEmail}"
    "pushRepo": "https://${gitUserName}:${gitUserPassword}@stash.example.org/project/repo.git master"
  },
```
then when release-it sets the user name and password then pushes.

**Comment by webpro** [comment]
You can set options like `git.pushRepo` and `git.pushArgs` from the command line, so I think something like this should work (inject the environment variables directly from the command line):

```
release-it --git.pushRepo="https://${USERNAME}:${PASSWORD}@stash.example.org/project/repo.git"
```

Also see https://github.com/release-it/release-it/blob/master/docs/git.md#extra-arguments

Let me know if/what works for you, I could obviously add some documentation for this.

**Comment by jbadeau** [comment]
Sorry, i figured out another way
