### ISSUE TITLE
gitlab empty changelog description

### ISSUE THREAD

**Issue by iambumblehead** [release-it/release-it#719]
Hello and regards for this great package I am using with the following command
```bash
release-it minor --git.requireBranch=master --no-npm.publish --ci
```

and the package.json definition,
```json
{
  "release-it": {
    "gitlab": {
      "release": true
    }
  }
}
```

This is mostly working for me -- a release is generated and the package.json version is incremented, **however the changelog at the gitlab release page is always empty.** The release page hyperlinks to an "Evidences" json file and when that json file is downloaded and opened, the description definition is almost empty --this appears to be the property where the changelog would be found `"description":"-"`

There is not an existing changelog found in the project sources.

Would you tell me what I'm doing wrong? How should I change things so that a changelog is generated?

**Comment by webpro** [comment]
Let's see what's happening with:

```
DEBUG=release-it:* release-it [...]
```

Haven't kept up with the GitLab API lately. What version of GitLab are you using, or is it the public gitlab.com?

**Comment by iambumblehead** [comment]
thanks for coming here to assist me so quickly @webpro --everything looks great now! there was another, older part of the pipeline generating tags just before the release-it part.

I removed the older part and there is a changelog and everything looks terrific now.

Thank you and i will close this ticket.
