### ISSUE TITLE
Getting Error fatal: tag '2.0.2' already exists with ignoreVersion set to true

### ISSUE THREAD

**Issue by georgipandurov** [release-it/release-it#720]
I continue getting this annoying error saying that tag already exists even when I have set:
```
npm: {
    publish: false,
    ignoreVersion: true
  }
```
I have checked all of the flags that exist in your documentation and I can't see anything else that can help me stop seeing this error. I just want release-it to bump to the next version if that tag already exists.

I few more lines, I making sure we have the latest changes by calling this before executing release-it:
```
git pull
git fetch --prune --prune-tags origin
```

Also, just so you can get a better idea of what is my scenario, I am using release-it in CircleCI job to publish the new version after my build is successful. So that makes it even harder to fix when it fails because we have to fix it manually by removing the wrong tags or adding new commits just to update the version properly so we really consider switching to different library.

**Comment by webpro** [comment]
Apparently in your scenario the tag already exists when release-it pushes it, so release-it probably does not correctly determine the latest tag, or this tag is not available yet. Are you sure the `git pull` and `git fetch` commands take the latest tag?

You can this to see more about what's happening and which commands are being used:

```
DEBUG=release-it:* release-it [...]
```

By the way, release-it does a `git fetch` (but without any arguments).
