### ISSUE TITLE
Verify as collaborator not working 

### ISSUE THREAD

**Issue by Lueton** [release-it/release-it#724]
Hi there! I'm using version `v13.7.1` of gitlab (self-hosted community edition). My `.release-it.json` looks like this:  
```
...
"gitlab": {
        "release": true,
        "releaseName": "Release v${version}",
        "tokenRef": "GITLAB_TOKEN",
        "origin": "https://git.example.com"
    }
...
```
For my repo the init method in the GitLab.js file assigns the this.id variable (which will later be used to create the collaborator request) with `username/reponame`. In the isCollaborator method the two requests created look like this:
```
https://git.example.com/api/v4/projects/username/reponame/members/all/4
and
https://git.example.com/api/v4/projects/username/reponame/members/4
```
This doesn't work for me, both of them return just 404. A working request for my repository would be:
```
https://git.example.com/api/v4/projects/projectId/members/userid
```
Did i miss something? Is something wrongly configured?

**Comment by webpro** [comment]
Hi @Lueton. To me it seems that in your example `projectId` is "username/reponame" and `userid` is "4", so the working request looks the same as the one returning the 404s, right? Did you try a real request (e.g. using curl) with the working url?

Note that `projectId` actually looks like `username%2Freponame` in the url.
