### ISSUE TITLE
Wrong commit URL when using a custom origin with GitLab

### ISSUE THREAD

**Issue by xens** [release-it/release-it#725]
I have a self-hosted Gitlab instance with two different endpoints for GIT and HTTPS:

* Git -> git.mysite.com (direct SSH access for GIT over SSH)
* HTTPS -> gitlab.mysite.com (reverse-proxified Gitlab instance)

To be able to properly use `release-it` I had to set the following option in my config file:

```
    "gitlab": {
      "release": true,
      "origin": "https://gitlab.mysite.com"
    }
```

otherwise `release-it` would always tries to deduce the GitLab URL based on the `git remote`.

So far so good.

Problem arises during Releases where `release-it` will not honor the `origin` value to reference commits, so the GitLab HTTPS URLs are pointing to the Git/SSH URLs instead.

**Comment by xens** [comment]
Issue seems to be present only when using the [convention-changelog plugin](https://github.com/release-it/conventional-changelog), it works as expected without it.

**Comment by xens** [comment]
Issue seems to be present only when using the convention-changelog plugin, it works as expected without it.

**Comment by webpro** [comment]
Are you sure about the plugin? This one only reads the local git logs to determine the recommended bump and the changelog. Could you please do a debug run to see what's going wrong?

```
DEBUG=release-it:* release-it [...]`
```
