### ISSUE TITLE
after:publish hook

### ISSUE THREAD

**Issue by niekvandael** [release-it/release-it#731]
Hi, 

The documentation states that there is no after:publish-hook.
Is there any (undocumented) way of implementing that hook?

https://www.npmjs.com/package/release-it#hooks

Thanks.

**Comment by webpro** [comment]
The "release" hook is the generic name for things like "git push", "github release" and "npm publish", so I think the `after:release` hook is what you're after. In case you need to be very specific you could use `after:npm:release`.

**Comment by niekvandael** [comment]
@webpro That indeed did the trick, thanks !!!
