### ISSUE TITLE
How to add all commits from GH prerelease into upcoming stable release?

### ISSUE THREAD

**Issue by markcellus** [release-it/release-it#733]
This isn't any fault of the release-it maintainers. But I've always found it a little odd that when a stable Github release is created off of a prerelease, the diff commits on the stable release never lists all of the diff commits made in the prerelease. Here's an example:

Let's assume our `foo` package is currently on stable version `1.4.3`.

1. I make commit A to master branch
1. I cut a preminor Github release from master of `1.5.0-alpha`
2. I make commit B to master
3. I cut a new minor Github release from master of `1.5.0`
4. The commit diff in the Github releases page for `1.5.0` include commit B but does not include commit A

I realize that this is intended behavior because commit A is shown in the `1.5.0-alpha` Github release but consumers wouldn't really be concerned with `1.5.0-alpha`-- only the stable version-- so they'll miss the commits that actually went into the `1.5.0` stable release notes.

Is there a way that we can have both commit A and commit B in the stable `1.5.0` release in my example above?

**Comment by webpro** [comment]
Yes, I totally understand, had this annoyance myself as well.

In theory you could modify the default `git.changelog` command when doing the stable release and make sure you basically replace `${from}` with e.g. `1.4.3` in your example:

```
{
  "git": {
    "changelog": "git log --pretty=format:\"* %s (%h)\" 1.4.3...${to}"
  }
}
```

Since you're doing everything from the same master branch this should work. With some scripting you could also automate determining the latest stable version. Let me know if this could be a viable approach and/or you need more help.

**Comment by markcellus** [comment]
That is a great suggestion. Let me try that and I'll report back. 👍

**Comment by laurenz-glueck** [comment]
@markcellus Have you already found an easy way to automatically get the latest stable version? 😇

**Comment by markcellus** [comment]
Hey @laurenz-glueck. Yes, I was able to get all tags, sort them by numerical order, filter out prereleases (ie. tags that end with `-beta` or `-alpha`), and use that to compare against the new version using the `changelog` field @webpro mentioned [above](https://github.com/release-it/release-it/issues/733#issuecomment-770195473).

**Comment by markcellus** [comment]
No longer and issue closing.

**Comment by webpro** [comment]
I realized the introduced `git.tagMatch` feature might be a nice approach for what we discussed in this topic: https://github.com/release-it/release-it/blob/master/docs/git.md#tag-match

Maybe a new flag could make this feature more obvious/friendly, but it's a start.
