### ISSUE TITLE
Unable to implement custom version format.

### ISSUE THREAD

**Issue by niecore** [release-it/release-it#735]
I am trying to implement a custom version format but the call of "parseVersion" in tasks.js is trying to do a semvar parsing which fails in my case.

**Comment by niecore** [comment]
My implementation is also based on a plugin. I think `release-it-calver-plugin` works because the resulting version string can be parsed to a semver via the call to `semver.coerce`.

I would suggest that the plugin is extended by an interface that returns `{version, isPreRelease, preReleaseId}`. parseVersion can then go to Version.js as default.

Then plugins which want to implement a complete cusom versioning scheme can be fully functional.

**Comment by webpro** [comment]
> I think `release-it-calver-plugin` works because the resulting version string can be parsed to a semver via the call to `semver.coerce`.

Now I look at the implementation of the calver plugin I'm surprised it works. E.g.:

```
❯ semver -c 21.1.0.0-dev.0
21.1.0
```

Which "works", but not as intended. Now `npm publish` or `git tag` will use `21.1.0` as (sem) version.

In any case, feel free to open a PR with your ideas for release-it and I'm happy to look into it.
