### ISSUE TITLE
Support yarn berry

### ISSUE THREAD

**Issue by jsamr** [release-it/release-it#737]
This is a feature request.

Yarn berry (v2) requires to run `yarn npm publish` instead of `npm publish` because it will resolve some dependencies schemes very specifically (such as the [workspace protocol](https://yarnpkg.com/features/workspaces)). Currently, `release-it` has hard-coded references to `npm publish` in the npm plugin.

**Comment by webpro** [comment]
I don't use Yarn v2 myself currently, but I'm happy to add it (to the npm plugin) if it's feasible. I have a few things to work out (any help appreciated):

- [ ] `npm version ${version} --no-git-tag-version` looks identical to [yarn version](https://classic.yarnpkg.com/en/docs/cli/version/)
- [ ] Is registry up (`npm ping`)
- [ ] Is user authenticated (`npm whoami`)
- [ ] Is user a collaborator (`npm access ls-collaborators ${name}`)
- [ ] Check latest package version in registry (`npm show ${name}@${tag} version`)
- [ ] Check pre-release tags (`npm view ${name} dist-tags --json`)
- [ ] Publish including `--otp` and `--dry-run` etc.
- [ ] The `--registry` argument in all commands

Let's figure out if we can simply replace `npm` with `yarn` where necessary, extend the plugin class and override a method or two, or should it be completely new plugin.

**Comment by jsamr** [comment]
It is still relevant bot!

**Comment by webpro** [comment]
I have released [14.11.0-next.0](https://github.com/release-it/release-it/releases/tag/14.11.0-next.0) that adds experimental support for Yarn v2 and pnpm.

You can install this version using `npm install release-it@yarn`

**Comment by webpro** [comment]
Also see https://github.com/release-it/release-it/blob/feature%2Fyarn-pnpm/docs/npm.md#yarn

**Comment by jsamr** [comment]
@webpro That's very exciting! I'll try it out

**Comment by webpro** [comment]
I changed to API (in [14.11.0-next.1](https://github.com/release-it/release-it/releases/tag/14.11.0-next.1)), to support Yarn v1 and v2. For now I decided to drop the automatic detection of what it should use to version/publish.

```
release-it --npm.yarn     # Yarn v2
release-it --npm.yarn1    # Yarn v1
release-it --npm.pnpm     # pnpm
```

**Comment by OliverDudgeon** [comment]
Looks like `next.1` gets stuck on OTP for me, is this going to get merged in to latest eventually?

**Comment by Farenheith** [comment]
For those facing this issue, I found a really good solution that is configuring .release-it.js like that
```js
  ...
  npm: {
    ...
    versionArgs: '--workspaces=false'
  },
  ...
```

This parameter will be passed directly to npm version call and somehow will make it ignore workspace protocol in the dependencies. If you just want to bump version in an api, for example, this is enough
