### ISSUE TITLE
Only last commit made has effect on verison bump and written to changelog

### ISSUE THREAD

**Issue by b12k** [release-it/release-it#738]
Hello,
Issue was initially created in https://github.com/release-it/conventional-changelog/issues/16
But it may be related to release-it itself.

TLDR;
In my `release-it` + `@release-it/conventional-changelog` setup only last commit made is affecting version bump and written to the changelog.

Details in original issue.

Thanx in advance.

**Comment by matteodisabatino** [comment]
Noticed too.

**Comment by b12k** [comment]
UP.
Are there any thoughts why this may happen?
Any one? ;)

**Comment by webpro** [comment]
Let's discuss in one location (https://github.com/release-it/conventional-changelog/issues/16)
