### ISSUE TITLE
uploads assets with CI_JOB_TOKEN

### ISSUE THREAD

**Issue by niekvandael** [release-it/release-it#740]
Hi @webpro ,

Gitlab v 13.5 introduced uploads of binary files.
This way, we can keep working with CI_JOB_TOKEN and there is no need to generate personal access tokens.

I was just wondering if this is ever gonna integrate into release-it?

Thank you.

Doc's:
https://about.gitlab.com/releases/2020/10/22/gitlab-13-5-released/#generic-package-registry
https://docs.gitlab.com/ee/ci/yaml/#release-assets-as-generic-packages​
https://gitlab.com/gitlab-org/release-cli/-/tree/master/docs/examples/release-assets-as-generic-package/

**Comment by webpro** [comment]
You can already upload `gitlab.assets` (attach binaries to releases). Or is this not what you mean?
