### ISSUE TITLE
No matter what I do I get the “Please `npm login` and try again.” message when trying to cut a release

### ISSUE THREAD

**Issue by brandondurham** [release-it/release-it#744]
#### My related packages:

- release-it@14.4.0
- @release-it/conventional-changelog@2.0.0
- dotenv-cli@4.0.0

#### My config

```json
{
  "hooks": {
    "before:init": ["yarn lint", "yarn test"],
    "after:bump": "yarn build"
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "infile": "CHANGELOG.md",
      "preset": "angular"
    }
  },
  "git": {
    "changelog": "git log --pretty=format:\"* %s (%h)\" ${from}...${to}",
    "requireCleanWorkingDir": true,
    "requireBranch": "main",
    "requireUpstream": true,
    "requireCommits": true,
    "addUntrackedFiles": false,
    "commit": true,
    "commitMessage": "chore: release v${version}",
    "commitArgs": [],
    "tag": true,
    "tagName": null,
    "tagAnnotation": "Release v${version}",
    "tagArgs": [],
    "push": true,
    "pushArgs": ["--follow-tags"],
    "pushRepo": ""
  },
  "npm": {
    "publish": true,
    "skipChecks": false
  },
  "github": {
    "release": true,
    "releaseName": "Release v${version}",
    "tokenRef": "GITHUB_TOKEN"
  }
}
```

#### My .npmrc

```
//registry.npmjs.org/:_authToken=$NPM_TOKEN
always-auth=true
```

#### My .yarnrc

```
registry "https://registry.npmjs.org/"
```

#### My .env

```
GITHUB_TOKEN="#########################################"
NPM_TOKEN="#########-####-####-####-#############"
```

#### My package.json contains

```json
"publishConfig": {
  "registry": "https://registry.npmjs.org/"
},
```

#### My release script

```json
"release": "HUSKY_SKIP_HOOKS=1 dotenv release-it",
```

## The problem

When I run `yarn release` I always get this message:

> ERROR Not authenticated with npm. Please `npm login` and try again.

If I hardcode the `NPM_TOKEN` from `.env` in the `.npmrc` file everything works. You’ll see I’m running `dotenv` in the release command above, so I’m not sure why it isn’t picking it up.

If I run `npm publish` directly, oddly enough I get this error:

>  Not Found - PUT https://registry.npmjs.org/@scope%2fpackage-name - Not found

It’s a private package, so I’m not sure if that’s part of the issue.

What am I missing?

**Comment by brandondurham** [comment]
I’ve removed the local `.npmrc` and `.yarnrc` files altogether, removed my `~/.npmrc` file, re-logged in via `npm login`, checked `npm whoami` which returned the proper username, added `"skipChecks": true` to `.release-it.json`, and still receive this error when running `yarn release`:

```bash
? Publish @scope/package-name to npm? Yes
ERROR npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in.
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2021-02-19T18_07_18_480Z-debug.log

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by webpro** [comment]
In the situation you describe in the last comment, do you still get this `ENEEDAUTH` when using `npm run release`?

Not using Yarn myself. Maybe it's an issue with Yarn v2?

**Comment by driiftkiing** [comment]
I'm not sure if this is the right place, but I have struggled now to get this published with by using `yarn release --npm.skipChecks`.

First of all I had an `automation` access token from npm, but this was not working because of the collaborator check `npm access ls-collaborators`.
So therefore I have changed it to a `publish` access token, but then i was getting `ERROR Not authenticated with npm. Please `npm login` and try again.`.
Then i have used the command  `yarn release --npm.skipChecks` (see [docs](https://github.com/release-it/release-it/blob/master/docs/npm.md#prerequisite-checks) then I was getting `npm ERR! 404 Not Found - PUT https://registry.yarnpkg.com/@scoped%2fpackage - Not found`.
To solve that problem, i have changed the registry in `package.json` to `https://registry.npmjs.org`:
```json
  "publishConfig": {
    "access": "public",
    "registry": "https://registry.npmjs.org"
  }
```

**Comment by webpro** [comment]
@driiftkiing Thanks for your feedback. Are you saying that you got it working eventually for your situation? Albeit with `--npm.skipChecks`?

**Comment by driiftkiing** [comment]
Yes, but also setting the registry to npm, otherwise it would not have been working with yarn.

**Comment by thelinuxlich** [comment]
I can't run a release too with Yarn v1, same problem.

**Comment by webpro** [comment]
Does anybody know if this is related (or even the same issue): https://github.com/release-it/release-it/issues/697#issuecomment-800082329

**Comment by webpro** [comment]
I added the `npm.publishArgs` option in [v14.5.0](https://github.com/release-it/release-it/releases/tag/14.5.0) so you can do something like this which might help to work around the issue:

```
release-it --npm.publishArgs="--registry=https://registry.npmjs.org"
```

**Comment by klarkc** [comment]
Same happens with [pnpm](https://pnpm.io/)

**Comment by lolmaus** [comment]
> Is this still relevant?

This issue is still relevant. It would fail with Yarn with an unhelpful error message.

**Comment by webpro** [comment]
No idea whether it's a solution for this issue, but perhaps it makes sense to use `yarn publish` (v1) or `yarn npm publish` (v2) when starting the process with e.g. `yarn release`. Or `pnpm publish`.

I released [14.11.0-next.1](https://github.com/release-it/release-it/releases/tag/14.11.0-next.1) which does this (see #737). You can use `npm install release-it@yarn` (or the yarn equivalent ;-) to install it.

Also see:

- https://github.com/release-it/release-it/blob/feature%2Fyarn-pnpm/docs/npm.md#yarn-v1
- https://github.com/release-it/release-it/blob/feature%2Fyarn-pnpm/docs/npm.md#yarn-v2
- https://github.com/release-it/release-it/blob/feature%2Fyarn-pnpm/docs/npm.md#pnpm

Please give it a shot, happy to hear any feedback.

**Comment by Minozzzi** [comment]
I had this problem running yarn release. So I logged in with npm login, ran npm adduser with the same credentials as npm login and then ran npm run release. Maybe it works for you too

**Comment by dunklesToast** [comment]
Had the same error message but turned out that the problem was the `release-it-yarn-workspaces` plugin. It requires it's own configuration where you need to disabled `skipChecks` as well:

```json
"plugins": {
  "release-it-yarn-workspaces": {
    "skipChecks": true,
  }
},
```
Probably won't help you guys that do not use this plugin :/
