### ISSUE TITLE
Command substitution not working anymore

### ISSUE THREAD

**Issue by driiftkiing** [release-it/release-it#745]
I have a command substitution inside `tagAnnotation`. But since you are using `execa` to execute commands, this is not working anymore.
Do you have an idea, how I can bring this to work again?

```json
{
  "git": {
    "commitMessage": "Version bump (v${latestVersion} => v${version})",
    "tagAnnotation": "Version v${version} - $(date +\"%Y-%m-%d\")"
  }
}
```

**Comment by webpro** [comment]
Since command line options are used as configuration, and used as the context to replace `${placeholders}` in commands, this works:

```json
{
  "git": {
    "commitMessage": "Version bump (v${latestVersion} => v${version})",
    "tagAnnotation": "Version v${version} - ${TODAY}"
  }
}
```

```
release-it --TODAY=$(date +"%Y-%m-%d")
```

Just make sure not to overwrite existing configuration options.

**Comment by driiftkiing** [comment]
Oh great, thanks - it works like a charm
