### ISSUE TITLE
release-it not change package.json file

### ISSUE THREAD

**Issue by YevheniiHorokhov** [release-it/release-it#748]
Helllo! 
I try change version via release-it  and it work fine for several time but today not work changing package.json version.
i run command "release-it" and it not change package.json version, only tag previous commit and push, but must change package.json, create new commit, tag it and push.

**my config file** 
git:
  commitMessage: 'chore: release v${version}'
  tagName: 'v${version}'
npm:
  publish: false

**log history**

🚀 Let's release folfok.api (currently at 0.17.9)

Empty changelog

? Select increment (next version): patch (0.17.10)

Empty changeset

? Commit (chore: release v0.17.10)? Yes

On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
WARNING No changes to commit. The latest commit will be tagged.

**Comment by webpro** [comment]
How does your config file look like **exactly**?

Also see https://github.com/release-it/release-it/blob/master/docs/npm.md#skip-publish

**Comment by YevheniiHorokhov** [comment]
> How does your config file look like **exactly**?
> 
> Also see https://github.com/release-it/release-it/blob/master/docs/npm.md#skip-publish

**my config file**
git:
commitMessage: 'chore: release v${version}'
tagName: 'v${version}'
npm:
publish: false

**Comment by webpro** [comment]
That's not exactly the file, right? Can you create a code block and insert the JSON (or whatever).

Anyway, if it works for "several times", then I would think that somehow something has changed on your end. Are you running release-it from the project root directory, that has the `package.json` (which is not modified somehow by something else)?

You should also try a debug run, to see exactly what's going on:

```
DEBUG=release-it:* release-it [...]
```

**Comment by YevheniiHorokhov** [comment]
@webpro thanks a lot, it worked now, need run from root directory as you say. Webstorm by default open last directory ('src') and i miss it. Really thanks.

**Comment by webpro** [comment]
Alright, great. I added a comment to the docs!
