### ISSUE TITLE
Be able to have a github release without needing a GITHUB_TOKEN

### ISSUE THREAD

**Issue by mansona** [release-it/release-it#749]
Hey folks 👋 I'm in the process of "porting" my release process from using `np` and doing a bunch of things manually to using `release-it` and everything being fully automated. I'm particularly interested in this because it would allow other collaborators on my open source projects to be able to release things way more easily 🎉 

One thing that I think might be a stickler for people is the need to create a GITHUB_TOKEN to be able to create github releases. It seems like `np` uses https://github.com/sindresorhus/new-github-release-url  and https://www.npmjs.com/package/open under the hood and it generates a url and opens it in your browser. All you would then need to do would be to hit save and that side-steps the need for a GITHUB_TOKEN for every contributor because they would be able to use their browser session. 

Is this something that you would like to see in release-it? if so then I might (eventually) find the time to contribute a PR with a configurable process that uses the `new-github-release-url` or maybe even default to that if no GITHUB_TOKEN is detected. 

I thought I should ask before landing a PR for a potentially unwanted feature 😄

**Comment by webpro** [comment]
Excellent, that's a very good idea. Also defaulting to this option is something I like (after setting `github.release` to `true`). Looking forward to your PR!

**Comment by mansona** [comment]
I plan to still work on this, I just haven't had the time recently 👍

**Comment by webpro** [comment]
I just took a stab at at, it's in [v14.11.0-github.0](https://github.com/release-it/release-it/releases/tag/14.11.0-github.0)

You can install using `npm install release-it@github`

What do you think?

**Comment by nordurljosahvida** [comment]
Tried:

```
npm install release-it@github
npm install git+https://git@github.com/release-it/release-it#14.11.0-github.0
npm install github:release-it/release-it#14.11.0-github.0
```

all three still release 14.0 with `release-it -v`, and token is still required when releasing with `releases: true`

**Comment by webpro** [comment]
Thanks for trying, @nordurljosahvida. How did you run release-it after installing it?

- When using release-it globally, you can use `npm install release-it@github -g`
- When using it in a project, after installing, you can use `npx release-it` to use the local version of release-it.

**Comment by nordurljosahvida** [comment]
@webpro ha, of course, super new to npm sorry, got it. so it opens a page on github to publish the release, there's no way of doing this without, right?

**Comment by webpro** [comment]
> @webpro ha, of course, super new to npm sorry, got it. so it opens a page on github to publish the release

Yes.

> there's no way of doing this without, right?

Without? Not sure I understand. You would not set `github.release: true` to skip this.

**Comment by nordurljosahvida** [comment]
sorry, I meant to do a release without github token and without opening a page

**Comment by webpro** [comment]
When doing a git commit, tag, push, then this tag shows up as a tag in GutHub, and not a release. This works without doing a GitHub Release (GitHub just happens to be the origin of your Git repo). What you describe is simply not doing a GitHub release at all. This would require either a GitHub token or the web-based manual input.

**Comment by nordurljosahvida** [comment]
ok, thanks

**Comment by nordurljosahvida** [comment]
One last question ;]

Although web-based is good to have to avoid the need of a token, I've ended up generating one and adding it to config. However now the development version of release-it I installed is still opening up the webpage instead of doing it through the token. How do I configure it to use the token and publish the release directly without web-based input?

Thanks!

**Comment by nordurljosahvida** [comment]
Update: solved, read through the instructions better, figured out the env var thing. Thanks! ;]

**Comment by webpro** [comment]
This has been added in [v14.11.0](https://github.com/release-it/release-it/releases/tag/14.11.0)
