### ISSUE TITLE
Option to set target branch to create release from

### ISSUE THREAD

**Issue by nickatnight** [release-it/release-it#752]
Hi, I'm not sure if I'm missing something, but it doesn't seem there is an option to select a target branch to create release from? In the current implementation, it looks like the release is created from whatever the default branch of the repo is? I think this is related to #340 , but that ticket is closed. Here is what my .yml file looks like

![Screen Shot 2021-04-06 at 4 05 56 PM](https://user-images.githubusercontent.com/8783431/113788566-172cdc00-96f2-11eb-9dba-33336bceb7c0.png)

This is for GitHub with a non-npm project. Please advise

**Comment by webpro** [comment]
This is not supported, indeed. I'm happy to look into a PR for this.
