### ISSUE TITLE
Using wrong version when publish beta on github

### ISSUE THREAD

**Issue by zhangciwu** [release-it/release-it#755]
Command: `"release-it --no-git --no-npm --preRelease=beta"`
```
$ release-it --no-git --no-npm --preRelease=beta

🚀 Let's release marksy-lite (8.1.0-beta.0...8.1.0-beta.1)


Changelog:
...

? Create a pre-release on GitHub (Release 8.1.0-beta.1)? Yes
ERROR 422 (Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"})
error Command failed with exit code 1.
```

Cause `8.1.0-beta.1` already exists

I checked and found it's using this command to get latest tag: `command: 'git describe --tags --match=* --abbrev=0',`
But actually it's not getting the latest tag.

```
bash-3.2$ git describe --tags --match=* --abbrev=0
v8.1.0-beta.0
bash-3.2$ git tag | sort -V | tail -1
v8.1.0-beta.1
```
So to use `git tag | sort -V | tail -1` to get the latest tag? Or some other better command

**Comment by webpro** [comment]
It *is* getting the latest (in time). What you want is the "highest" or "greatest" version in the semver-based versioning.

But isn't it weird that a higher tag was set *earlier* than a lower tag? That should not happen?

By the way, the `sort` command does not support this kind of sorting, but [node-semver](https://github.com/npm/node-semver) provides a solution.

**Comment by zhangciwu** [comment]
```
git log --tags --simplify-by-decoration --pretty="format:%ai %d"

2021-04-12 14:59:20 +0800  (tag: v8.1.0-beta.2)
2020-08-31 20:16:05 +0300  (tag: v8.1.0-beta.1, tag: v8.1.0-beta.0, tag: v8.1.0-alpha.0, origin/master, origin/HEAD, master)
2019-05-24 13:00:43 +0200  (tag: v8.0.0)
```

I use release-it today(beta.0 and beta.1 created by release-it), pretty weird these two tags are marked last year

**Comment by webpro** [comment]
That's weird indeed. In the end release-it is deferring tagging to `git tag` - no magic included.

**Comment by zhangciwu** [comment]
Checked and found that it's because beta.0 and beta.1 are all on master git node, which has the date of last year. But I was working in my new branch, should be tagging on this branch than master

**Comment by webpro** [comment]
Glad you figured it out! Guess we can close issue now.
