### ISSUE TITLE
Question: how to handle hybrid release flow (locally + CI)?

### ISSUE THREAD

**Issue by dlecan** [release-it/release-it#757]
Hello,

Here is the release workflow I would like to set up:

1. On the developer machine
  - launch manually the release process
  - run tests, linting ...
  - choose the version
  - update the package.json
  - commit and push code and tag
2. On CI, triggered by the tag
  - checkout the tag
  - run tests linting
  - build
  - package
  - publish/deploy artifacts: npm, gh release, docker ...

Do you know if release-it would be able to handle it?

Thank you

**Comment by webpro** [comment]
The short answer: yes.

The slightly longer answer:

1. This is basically what it does by default, plus:
  - Add hooks to run tests etc. (e.g. `"hooks": { "before:init": ["npm test", "npm run lint"] }`)
  - Disable npm publish (`--no-npm.publish` or `"npm": { "publish": false }`)
2. Prepare keys or tokens on the CI environment, and:
  - Point to another config file than locally
  - Set `--github.release` or `"github": { "release": true }`
  - Disable git commands (`--no.git` or `"git": false`)
  - Add hooks to test, build, package
  - Add hooks to do the docker things (e.g. `"after:release"`)

Let me know if you have any questions or the docs fall short!

**Comment by dlecan** [comment]
Thank you, let's deploy release-it :)
