### ISSUE TITLE
Use current version

### ISSUE THREAD

**Issue by JakubMrowca** [release-it/release-it#758]
Hi I have a question. Can I create a tag and release for the current version from package.json?  
Something like this:
` "release-pr": "dotenv release-it -- ci --git.tagName='pr-v${version}' --gitlab.releaseName='${version}-PR'`
Where $version is current version.

**Comment by JakubMrowca** [comment]
no problem... i can use  %npm_package_version%

**Comment by webpro** [comment]
If you want to use the current version (from `package.json`) you can use the `--no-increment` flag. And then use the `${version}` placeholder.
