### ISSUE TITLE
Question: how to handle development "release", such as these based on timestamp?

### ISSUE THREAD

**Issue by dlecan** [release-it/release-it#760]
Hello,

We are trying to migrate our release process based on shell scripts to release-it.
No problem with classical releases.

We have also the concept of "nightly" builds, published by our CI tool.
The actual process:
1. increment the minor part of the version
1. add the modifier `dev` + a timestamp (or anything else built incrementally): `3.0.1-dev.202104271135`
1. publish the version on npm

=> no tag in git

We have seen the concept of pre-release of release-it, but we don't understand how to use it to achieve our needs.

Thank you

**Comment by webpro** [comment]
When you say "or anything else built incrementally", this is what release-it does for you: add `.0` to the modifier (`dev`) and keep incrementing this until the modifier changes or is removed. Then start at `0` again for the next modifier or pre-release.

```
release-it minor --preRelease=dev
```


If this number must be a timestamp you'll need to provide it on the command line directly:

```
release-it 3.0.1-dev.202104271135
```

> => no tag in git

Please see [skip Git steps](https://github.com/release-it/release-it/blob/master/docs/git.md#skip-git-steps).

**Comment by dlecan** [comment]
Thank you
