### ISSUE TITLE
Fatal ERROR when using "tagName"

### ISSUE THREAD

**Issue by SimoneCusimano** [release-it/release-it#761]
Hi,
I am using the _tagName_ attribute to filter the latest tag that the tool retrieves to generate the new version.

I am getting the following error:
```
$ git tag --annotate --message Release 21.04.3 [0-9][0-9].[0-1][0-9].[0-9]*
ERROR fatal: '[0-9][0-9].[0-1][0-9].[0-9]*' is not a valid tag name.
```

It seems that the tool uses it as a version value causing the error.

I assume the error is in the _tag_ function of the _lib/plugin/git/Git.js_ file. In particular, in [these lines](https://github.com/release-it/release-it/blob/b21476a58ee0cab619847be9f9e11a8f85dc7167/lib/plugin/git/Git.js#L176-L177), the attribute that is passed to the _git tag_ command should probably be _version_ instead of _tagName_.

I am using release-it with the following configuration:
```
{
  "hooks": {
    "after:release": "echo ${version} > VERSION && echo ${latestVersion} > LATEST_VERSION"
  },
  "git": {
    "commit": false,
    "requireUpstream": false,
    "requireCleanWorkingDir": false,
    "tagName" : "[0-9][0-9].[0-1][0-9].[0-9]*"
  },
  "npm": {
    "publish": false,
    "ignoreVersion": true,
    "skipChecks": true
  },
  "plugins": {
    "@csmith/release-it-calver-plugin": {
      "format": "YY.0M.MICRO"
    }
  },
  "verbose": 2
}
```

Complete logs follow here:
```
+ npx release-it --ci --disable-metrics

$ git rev-parse --abbrev-ref HEAD

develop

$ git config --get branch.develop.remote

$ git remote get-url origin

http://REPO_URL.git

$ git fetch

From http://REPO_URL

 * [new tag]         21.04.1    -> 21.04.1

* [new tag]         21.04.2    -> 21.04.2

 * [new tag]         R21-sp04   -> R21-sp04

$ git describe --tags --match=[0-9][0-9].[0-1][0-9].[0-9]* --abbrev=0

21.04.2

$ git log --pretty=format:"* %s (%h)" 21.04.2...HEAD

* Fix name (98607b7)

* Restore Integration branch (8753f73)

🚀 Let's release COMPONENT_NAME (21.04.2...21.04.3)

Changelog:

* Fix name (98607b7)

* Restore Integration branch (8753f73)

$ git tag --annotate --message Release 21.04.3 [0-9][0-9].[0-1][0-9].[0-9]*

ERROR fatal: '[0-9][0-9].[0-1][0-9].[0-9]*' is not a valid tag name.
```

**Comment by webpro** [comment]
> I am using the tagName attribute to filter the latest tag that the tool retrieves to generate the new version.

The `tagName` is the template for the next tag to be released. This template is _also_ used for the `--match` argument to find the latest tag. See #722 for more context (which is the PR introducing this).

The implementation you refer to uses the `tagName` from its `context` (the `version` is used by the `git.tagName` template option and the result is stored as `tagName` in the `context`).

**Comment by TheRealWaldo** [comment]
@webpro I noticed this happens if there are not yet any tags in the repository (i.e. a fresh repo).  I have worked around it by manually adding a tag, but it's a bit annoying when creating many new projects.

**Comment by SimoneCusimano** [comment]
Same here

**Comment by webpro** [comment]
I added `git.tagMatch` in [v14.11.0](https://github.com/release-it/release-it/releases/tag/14.11.0)

Could you please open a new issue for problematic cases without any tags yet in the repo? I can't reproduce here.
