### ISSUE TITLE
Provide a command to only print the next version

### ISSUE THREAD

**Issue by StarpTech** [release-it/release-it#766]
Hi, currently we solve it with

```
npx release-it@14.6.1 --ci --no-git.tag --no-git.push --no-git.commit --no-npm --no-gitlab --hooks.after:release \"echo -n \"\\${version}\" > .VERSION\"
```
which is pretty verbose.

**Comment by webpro** [comment]
Creative :-) Not much better, but wanted to share anyway:

```
npx release-it@14.6.1 --ci --no-git --no-npm --no-gitlab --hooks.after:release \"echo -n \"\\${version}\" > .VERSION\"
```

What do you think would be a good API (CLI argument) for this? All the `v` and `V` options are basically taken.

**Comment by StarpTech** [comment]
Hi, good to see that somebody else is doing the same 😄 

```
npx release-it@14.6.1 release-version
```

**Comment by webpro** [comment]
Oh, I just wanted to indicate you can use `--no-git` instead of of all `--no-git.*` flags separately :)

Adding a `--release-version` flag sounds good indeed. Feel free to open a PR, otherwise I'll probably get to it in the next week.

**Comment by StarpTech** [comment]
I tried it several times with '-no-*' but run into some issues with the dry run. I'll retry.

**Comment by webpro** [comment]
The `--release-version` flag was added in [v14.7.0](https://github.com/release-it/release-it/releases/tag/14.7.0)

**Comment by StarpTech** [comment]
Awesome! @webpro thank you.

**Comment by StarpTech** [comment]
Do I understand correctly, that I only need to run `npx release-it@14.6.1 --release-version` to get the version?

**Comment by webpro** [comment]
An example usage:

```
❯ npx release-it major --release-version
15.0.0
```

If you want to specify the version of release-it itself, you should use at least `release-it@14.7.0`.

**Comment by StarpTech** [comment]
Thanks.

**Comment by StarpTech** [comment]
There is an issue: `npx release-it major --release-version` doesn't produce the same version as `npx release-it major`. The first command only respect the version of the package.json. The second one the git tags.

**Comment by StarpTech** [comment]
--no-npm --gitlab.release --disable-metrics --git.requireBranch=master
```
$ git rev-parse --abbrev-ref HEAD
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git config --get branch.master.remote
$ git remote get-url origin
! git fetch
$ git describe --tags --match=* --abbrev=0
$ git symbolic-ref HEAD
$ git for-each-ref --format="%(upstream:short)" refs/heads/master
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git config --get branch.master.remote  [cached]
$ git remote get-url origin  [cached]
! git fetch
$ git describe --tags --match=* --abbrev=0  [cached]
$ git log --pretty=format:"* %s (%h)" 0.0.4...HEAD
$ git log --pretty=format:"* %s (%h)" 0.0.4...HEAD  [cached]
🚀 Let's release gol (0.0.4...0.0.5)
```


--ci --dry-run --release-version
```
npx: installed 296 in 10.612s
$ git rev-parse --abbrev-ref HEAD
$ git config --get branch.master.remote
$ git remote get-url origin
! git fetch
$ git describe --tags --match=* --abbrev=0
$ git symbolic-ref HEAD
$ git for-each-ref --format="%(upstream:short)" refs/heads/master
$ git log --pretty=format:"* %s (%h)" 0.0.4...HEAD
0.1.3
```

**Comment by webpro** [comment]
Not sure exactly which commands you are comparing? I see a `--no-npm` - this results in `package.json` being ignored.

**Comment by StarpTech** [comment]
I see. It's very confusing that a specific arg combination results in a different release version. I assumed that we always rely on tags. Would you mind to support the flag `npx release-it --release-version` with git?

**Comment by webpro** [comment]
I understand it's confusing if you had that assumption. However, disabling the npm plugin disables reading from and writing to `package.json` (and `npm publish`). You can use `--npm.ignoreVersion` to not read this `version` (but rely on Git tags instead):

```
npx release-it --npm.ignoreVersion --release-version
```

**Comment by StarpTech** [comment]
Thanks! We should really maintain a cheatsheet 😄
