### ISSUE TITLE
Possibility to use "own" gitlab-server?

### ISSUE THREAD

**Issue by pfeucht84** [release-it/release-it#768]
Hi there,
first thanks for your outstanding work!
I would like to use release-it but with a custom gitlab-server with different URL.
Is it possible to do so?
Thanks in advance
Philipp

**Comment by webpro** [comment]
Yes, you can use the `gitlab.origin` configuration option for this.

Also see https://github.com/release-it/release-it/blob/master/docs/gitlab-releases.md#origin
