### ISSUE TITLE
Changelog generation

### ISSUE THREAD

**Issue by DomiR** [release-it/release-it#770]
Thank you for your work!

I'd like to use the conventional-changelog plugin, but would still like to select the next version manually.

The problem is, that the changelog is generated before the version bump. So a plugin that only wants to provide the changelog generation does not have access to the incremented version.

I'm proposing to move the changelog generation down the pipeline (from https://github.com/release-it/release-it/blob/e1d2c4ab58fd762c98de27f213d6bd27bb5e0b98/lib/tasks.js#L68 to https://github.com/release-it/release-it/blob/e1d2c4ab58fd762c98de27f213d6bd27bb5e0b98/lib/tasks.js#L85).

Would you be open to a PR for that?

**Comment by webpro** [comment]
Please see https://github.com/release-it/conventional-changelog/issues/17

Please comment there if you have any feedback or questions.
