### ISSUE TITLE
Generate release notes from gitlab issues closed since latest release

### ISSUE THREAD

**Issue by arthurlogilab** [release-it/release-it#776]
On some projects it would be nice to be able to use the closed tickets as changelog / release notes for a release. Since release-it already has access to the API to create a new Release content, maybe this content can be obtained with the same token and tool. 

Looking into the templates https://github.com/release-it/release-it/tree/master/templates to see how this could be done. 

Thanks for your advice, if this is out of the scope for release-it, that's understandable too.

**Comment by webpro** [comment]
My first impression is that this would be a good fit for a plugin. Not sure whether this plugin should be an extension of the GitLab plugin (by class inheritance), or a new plugin. Plugins have access to all configuration.

See for example https://github.com/release-it/conventional-changelog/blob/master/index.js

And plugin docs at https://github.com/release-it/release-it/blob/master/docs/plugins.md

Let me know whether you're interested in implementing this, I'm happy to assist.

**Comment by arthurlogilab** [comment]
Got a first release note by using the python binding to gitlab's API :  

```
import gitlab
gl = gitlab.Gitlab('https://gitlab.example.org', private_token='xx')
print('\n* '.join(['{} #{}'.format(x.title, x.iid) for x in p.issues.list(state='closed', order_by='updated_at', sort='desc', updated_after='2021-06-01T00:00:00Z', all=True)]))
```

Manually edited it, but that's a start. 

I guess to do something similar as a plugin, we would need to do the equivalent with javascript. Maybe https://github.com/jdalrymple/gitbeaker is a good library to do this.

**Comment by arthurlogilab** [comment]
I think this request is still relevant, but I'm happy for the project to close it as "implement it as a plugin" suggestion.

**Comment by webpro** [comment]
That's my point of view indeed, feel free to open a new ticket to discuss when you're working on it!
