### ISSUE TITLE
JavaScript API

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [release-it/release-it#777]
Is there a way to run release-it with javascript? like 
```
const release = require('release-it')

release({
  // Options
}).then(() => {
  console.log('done')
})
```
I didn't see anything in the docs, but the [`lib/index.js`](https://github.com/release-it/release-it/blob/54df17ee15c68990f3ce104f067613e951bbe651/lib/index.js#L11) file looks like it runs release-it.

If this is currently works, can it be added to the docs?

**Comment by webpro** [comment]
I agree it isn't very clear, but it's down here: https://github.com/release-it/release-it#use-release-it-programmatically

**Comment by ChocolateLoverRaj** [comment]
Oh, sorry, I missed that section when looking through the readme. Since the readme has the section this issue doesn't make sense.
