### ISSUE TITLE
adding '-y' option to args

### ISSUE THREAD

**Issue by roseline124** [release-it/release-it#780]
I always do yes these four questions.
It takes few minutes(not so long. maybe 1~2minutes.) to see Last question(`Create a pre-release`).
So It'll be comfortable to use 'y' option that answers all the questions as 'Yes', I think.
How about that?

```shell
? Commit (Release 0.2.15-alpha.2)? Yes
? Tag (v0.2.15-alpha.2)? Yes
? Push? Yes
? Create a pre-release on GitHub (Release 0.2.15-alpha.2)? Yes
```

**Comment by webpro** [comment]
That's basically what the `--ci` option is for ("non-interactive").

**Comment by roseline124** [comment]
I see! Thank you so much :)

**Comment by webpro** [comment]
https://github.com/release-it/release-it#interactive-vs-ci-mode
