### ISSUE TITLE
npx release-it doesn't bump package-lock.json

### ISSUE THREAD

**Issue by abeforgit** [release-it/release-it#782]
When using release-it as a global install, both the `package.json` and the `package-lock.json` are bumped as expected. However, when using  `npx release-it`, only the `package.json` is bumped.

We observe this behavior with a completely default (aka nonexistant) config, using the following commands:

`npx release-it --no-git`

and then selecting "no" to the question whether to release on npm or not. (Selecting "yes" has the same effect, since it's a private package).

### versions

node: v12.18.3
npm: 6.10.3

**Comment by webpro** [comment]
The following sequence works properly:

```
npm init -f
npm install
npx release-it --no-git
```

Both `package-lock.json` and `package.json` have their `version` bumped.

Tried this with Node.js v12/npm v6 and Node.js v16/npm v7.

Do you have more details or, better, a reproducible repo/testcase?

**Comment by abeforgit** [comment]
Im unable to reproduce it in a clean repo, very strange. Especially because the `npm version minor` command does work as expected, and as I understand it `release-it` delegates to it, so I'm very confused. 

Some details about the affected repo:
- we only recently re-enabled the lockfile generation, as we were having trouble with it way back when the project was started
- Even when removing and re-generating the lockfile, then commiting, and then running `release-it`, the issue persists
- the issue appears consistently, no matter which type of version bump we do

the repo  can be seen here:
https://github.com/lblod/frontend-gelinkt-notuleren-publicatie/blob/master/package.json

It is an [emberJS](https://emberjs.com/) project, but I wasn't able to reproduce this even in a clean ember project, so I doubt this is relevant.

**Comment by webpro** [comment]
Yeah, release-it delegates to `npm version`.

It's a far stretch, but maybe there is a mismatch with npm and lockfile versions in the CI environment, or when spawning this process? As npm v7 uses lockfile v2.

By the way, a dry run should not actually modify files.
