### ISSUE TITLE
[question] How to avoid release creation based on conventional changelog

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [release-it/release-it#783]
### The question

I'm using `release-it` for managing releases for non NodeJS project.
I'm using `conventionalcommits` preset to create release notes / changelog.

I want a new release to be created only if changes contains fixes and features (`fix: ...`, `feat: ...`).
Currently, even if changes contains `'chore: ` - the release is created.

How to avoid this ?

### Possible workaround

I suppose my goal can be achieved by adding some hook that analyzes content of ${changelog} and breaks the release.
But, I'd like to not fail the run of `release-it` but make it successfully exit without producing the release.
For better consistency of CI environements.

### Version information

```
$ npm --version
6.14.13

$ node --version
v14.17.1

$ cat package.json
{
  "devDependencies": {
    "@release-it/conventional-changelog": "^3.0.1",
    "release-it": "^14.10.0"
  }
}
```

**Comment by webpro** [comment]
Looks like none of release-it, the @release-it/conventional-changelog plugin, or [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) itself has a feature like this. Let me know if the latter has this feature, then maybe we can use it.

**Comment by webpro** [comment]
Maybe you can append something like ` || true` to the hook after stopping the release-it process to have a `0` exit code.

**Comment by ievgenii-shepeliuk** [comment]
Hello @webpro 

I know that [semantic-release](https://github.com/semantic-release/semantic-release) works like this. 
You could take a look at their code, I'm not JS expert to be able find it myself :(

**Comment by webpro** [comment]
Sorry, I'm not very interested in this feature myself. Happy to look into a PR, though.

**Comment by ievgenii-shepeliuk** [comment]
> Sorry, I'm not very interested in this feature myself. Happy to look into a PR, though.

not from my side, obviously.
