### ISSUE TITLE
Read the next version from a file without incrementing it

### ISSUE THREAD

**Issue by qisylvia** [release-it/release-it#784]
I have a template-config.json file which I manually edit the version number I want to release. I am using the release-it/bumper plugin to read the version property from this file. My .release-it.json looks like this:
{
  "plugins": {
    "@release-it/bumper": {
      "in": {
        "file": "template-config.json",
        "path": "ProductVersionName"
      }
    }
  },
  "git": {
    "commitMessage": "chore: release v${version}"
  },
  "github": {
    "release": true
  }
}

I want release-it to use the version from the template-config.json file as the next release version, and NOT increment it. Therefore, I used "release-it --ci --no-increment". 

The first time I ran it, it worked just fine. The version, say 1.0, was not incremented, Release 1.0 was created as expected. 

I then made more commits, and incremented the version in the template-config.json to 2.0. Ran "release-it --ci --no-increment" again. This time, Release 2.0 is created, but it replaced Release 1.0. This is not expected. I would not want Release 2.0 to replace Release 1.0 by using the --no-increment option. I want to keep Release 1.0. 

Is there a way to achieve what I am trying to do? 

Or, if we could provide an option to specify the version in the non-interactive mode, this option currently exists in the interactive mode already, that could solve my problem too.

**Comment by webpro** [comment]
The `--no-increment` is meant to update an existing release (without incrementing the version). I understand for your use case it's confusing. You can provide the increment or version as the first argument, e.g.:

```
release-it 2.0.0 --ci
```

**Comment by qisylvia** [comment]
@webpro Thank you, this works for me.
