### ISSUE TITLE
Suggestion for Dependabot security alert (lodash)

### ISSUE THREAD

**Issue by webketje** [release-it/release-it#786]
> Dependabot cannot update lodash to a non-vulnerable version
>
> The latest possible version that can be installed is 4.17.15 because of the following conflicting dependencies:
> release-it@13.6.2 requires lodash@4.17.15
> 
> The earliest fixed version is 4.17.21.

Maybe to have some leeway specify `"lodash": 4.x.x`?

**Comment by webpro** [comment]
Please upgrade to the latest release-it version of either v13 or v14
