### ISSUE TITLE
[question] CI: All project files as new after create symbolic-ref

### ISSUE THREAD

**Issue by mjunior** [release-it/release-it#787]
I'm working on branch gt/feat/release-it. 

I Trying to configure the release-it in my CI. Here we are using Azure Devops Pipeline.

Azure makes git checkout automaticaly, so my pipeline start with this log.

   HEAD is now at 696968a..
   
After that I remove and add a origin with my azure git token

`git remote add origin https://<GIT_TOKEN>@dev.azure.com/<comp-any_name>/<project_name>/_git/<repository_name>`

When I create a symbolic-ref all files of my project are moving to git stagged as a NEW FILE.

```
* (HEAD detached at 2ad3738) --> git status
fatal: your current branch 'gt/feat/release-it' does not have any commits yet
On branch gt/feat/release-it

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

	new file:   .azuredevops/pull_request_template.md
	new file:   .dockerignore
	new file:   .editorconfig
	new file:   .gitignore
	new file:   .husky/.gitignore
	new file:   .husky/commit-msg
	new file:   .npmrc
	new file:   .release-it.json
	new file:   .vscode/settings.json
	new file:   CHANGELOG.md
	new file:   Dockerfile
	new file:   README.md
	new file:   angular.json
```

git symbolic-ref HEAD refs/heads/gt/feat/release-it

There are something wrong ? I known that problem is not related with release-it, but I dont find anything on google about it :(

When I repeated this steps in my computer that did not happen.

**Comment by webpro** [comment]
This is kind of a known issue on CI environments in general: only the HEAD is fetched, not any history/previous commits.

That's why release-it doesn't see any commits (and can't generate a changelog).

So you would need to make sure at least the commits up to and including the latest tag are available.
