### ISSUE TITLE
Changelog version and links are incremented when told not to increment (but version is fine)

### ISSUE THREAD

**Issue by TheRealWaldo** [release-it/release-it#790]
```
release-it
  🚀 Let's update release-it (currently at 0.5.0)
  Changelog:
  ## [0.6.0](https://github.com/TheRealWaldo/release-it/compare/v0.4.0...v0.6.0) (2021-07-07)
  
  ### Features
  * add info to output when no-increment is set ([451029d](https://github.com/TheRealWaldo/release-it/commit/451029db291207a669a8f529e964724a2e2f76cd))
  
  ### Bug Fixes
  * rebuild was not done ([986813d](https://github.com/TheRealWaldo/release-it/commit/986813de99ba20708aef6a0ac9a6f0dd4f121833))
  - Git tag
  ✔ Git tag
  - Git push
  ✔ Git push
  - GitHub update release
  ✔ GitHub update release
  - echo Successfully bumped release to v0.5.0 for TheRealWaldo/release-it.
  ✔ echo Successfully bumped release to v0.5.0 for TheRealWaldo/release-it.
  🔗 https://github.com/TheRealWaldo/release-it/releases/tag/v0.5.0
  🏁 Done (in 3s.)
```
Expected that the changelog was to be the same as the release version.

A note; this is done in CI mode.

**Comment by webpro** [comment]
Assuming you are using the conventional-changelog plugin, you can use its [`ignoreRecommendedBump` ](https://github.com/release-it/conventional-changelog/blob/ad74134b8746397bbd4e66aa6729047d3940d374/README.md#ignorerecommendedbump) option.

**Comment by TheRealWaldo** [comment]
@webpro is there a way to tell everything to not increment without having to identify each and every different mechanism for each plugin that may or may not be in use?

**Comment by webpro** [comment]
Well, that's kind of a rhetorical question, isn't it. The issue you are facing here, mostly originates from a "decentralized" plugin system and a growing user base, each coming with their own challenges and edge cases. The last 2.5 years (since release-it v9) have been quite steady and stable from an API perspective, most folks had little to zero breaking changes. Having some specifically recurring and/or open issues, maybe it's a good moment to think a few things over and prepare for another major update.

For now, I hope you are using release-it to your satisfaction, or not at all.

**Comment by TheRealWaldo** [comment]
@webpro apologies; I did not intend the question to be rhetorical or offensive.   It has been challenging with documentation and walking through the source code to figure out what was happening in many cases and how everything is supposed to be configured.  I figured it more appropriate to ask than to assume there wasn't a standard way to tell all plugins not to bump based on what little research I had done.

I guess perhaps that this would be a feature request?

**Comment by jimwong666** [comment]
> 假设您使用的是 conventional-changelog 插件，您可以使用它的[`ignoreRecommendedBump` ](https://github.com/release-it/conventional-changelog/blob/ad74134b8746397bbd4e66aa6729047d3940d374/README.md#ignorerecommendedbump)选项。

thanks 😘

**Comment by jimwong666** [comment]
> Assuming you are using the conventional-changelog plugin, you can use its [`ignoreRecommendedBump` ](https://github.com/release-it/conventional-changelog/blob/ad74134b8746397bbd4e66aa6729047d3940d374/README.md#ignorerecommendedbump) option.

thanks 😘
