### ISSUE TITLE
Support ESModule Plugins

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [release-it/release-it#791]
I tried using a `module` plugin and got the error: `ERROR Must use import to load ES Module`.

This is asking for a big change, but it would be better if release-it was written with `type=module`, so that both CommonJS and ESModule plugins can be used.

**Comment by webpro** [comment]
Yes, I totally agree and plan to do this. Will be a breaking change however, as release-it currently supports Node.js v10.

**Comment by ChocolateLoverRaj** [comment]
When are you planning on discontinuing node 10 support? Also node 10 itself is not even in maintenance anymore: https://nodejs.org/en/about/releases/.

**Comment by webpro** [comment]
It was more work than expected, but here we go. Feel free to try [v15.0.0-esm.0](https://github.com/release-it/release-it/releases/tag/15.0.0-esm.0):

```
npm install release-it@esm
```

**Comment by ChocolateLoverRaj** [comment]
@webpro sorry but I already switched to compiling the TypeScript to CommonJS. I was using https://www.npmjs.com/package/trim-newlines, which had as esmodule only export, which forced me to compile to esmodule, but then I switched to using https://www.npmjs.com/package/trim-off-newlines, which has CommonJS exports. If I ever need to make a esmodule plugin, I will use the ESM prerelease.

**Comment by webpro** [comment]
No problem! Switching to ES Modules is a good move anyway, and forced me, amongst other things, to finally get rid of proxyquire. Around 6% of releases is still done using release-it v14 with Node.js <12 so I'm not in a hurry anyway.

**Comment by jimmywarting** [comment]
When can we expect to see v15 as stable?

**Comment by ChocolateLoverRaj** [comment]
> When can we expect to see v15 as stable?

Node 15 will never be LTS, but Node 16 will in October 26 - https://nodejs.org/en/about/releases/.

**Comment by jimmywarting** [comment]
Sry, if i was a bit unclear, but i wasn't talking about NodeJS versions
i where asking about when `release-it@15.0.0-esm.2` would become stable and released as `release-it@15.0.0` (stable)

**Comment by janbiasi** [comment]
I'm also wondering when the final stable-release of v15 will be available 😄 any news?

**Comment by webpro** [comment]
I have merged all the changes from master into the `feature/es-modules` branch and released [15.0.0-esm.3](https://github.com/release-it/release-it/releases/tag/15.0.0-esm.3). [Tests are passing](https://github.com/release-it/release-it/actions/runs/1526876782), so it's getting more stable now.

Please help moving this forward by using it in your project (e.g. `npm install -D release-it@esm`) and report your findings here (or by opening new tickets).

**Comment by jairhenrique** [comment]
Move bumper to esm! https://github.com/release-it/bumper/pull/19

**Comment by webpro** [comment]
Moving to a new pinned issue: https://github.com/release-it/release-it/issues/859
