### ISSUE TITLE
Allow pre-release versions from any branch

### ISSUE THREAD

**Issue by drewcorlin1** [release-it/release-it#793]
It is a common use case for my team to want to publish pre-release versions from working branches. Would it be possible to support this in some way, while still allowing us to specify a `requireBranch`?

Perhaps this could be supported with another config property `git.allowPreRelease` (definitely open to better names)?

That field could then either be set to a boolean, string or regex (similar to how `requireBranch` works now)

Apologies if this is currently possible and I'm just missing it.

**Comment by webpro** [comment]
What you can do already is specifying the `git.requireBranch` in the configuration, and override this using `--no-git.requireBranch` from the command-line as needed.

**Comment by drewcorlin1** [comment]
Ah that's great - thanks so much!
