### ISSUE TITLE
Help with skipping a new release tag

### ISSUE THREAD

**Issue by csantanapr** [release-it/release-it#795]
Use case:

I’m aware of the flag git.requiredCommits=true

this will skip the release process if the commit I checkout is the one with the latest release tag

what I want to do in my CI script is to grab the string for the latest release so I can use it as a unique identifier to rerun some testing against the latest release tag software

whts the easiest way to get the tag? Some git command with same logic that release-it uses or release-it has a dry-run that prints the latest tag?

**Comment by webpro** [comment]
> whts the easiest way to get the tag?

```
git describe --tags --abbrev=0
```
