### ISSUE TITLE
1.0.0 -> 1.0.1 should contain all changes from any 1.0.1 pre-releases (beta, alpha)

### ISSUE THREAD

**Issue by mrousavy** [release-it/release-it#796]
My stable version is 1.0.0, and I've been working on a lot of features in a pre-release (so 1.0.1-beta.1, 1.0.1-beta.2, 1.0.1-beta.3, 1.0.1-beta.4, and so on), and now I want to publish a new stable release - so 1.0.1. However, this release only contains the differences since the latest pre-release, and not since the latest stable release.

Is there a way to make release-it generate a changelog since the last stable release?

**Comment by webpro** [comment]
Please see #733

**Comment by mrousavy** [comment]
I see, that's a nice workaround thanks @webpro.

**Comment by webpro** [comment]
I realized the introduced `git.tagMatch` feature might be a nice approach for what we discussed in this topic: https://github.com/release-it/release-it/blob/master/docs/git.md#tag-match

Maybe a new flag could make this feature more obvious/friendly, but it's a start.
