### ISSUE TITLE
release-it@14.11.0 breaks Node 10 compatibility (under yarn)

### ISSUE THREAD

**Issue by rwjblue** [release-it/release-it#797]
At the moment, we still explicitly declare support for Node 10:

https://github.com/release-it/release-it/blob/d702675ecdb328eb987df6d6f0c2247be6d2fb5b/package.json#L110-L112

Unfortunately, introducing the [open](https://github.com/sindresorhus/open) package in https://github.com/release-it/release-it/commit/675f82338c35b733a619a73b4a4874d2dc1c7f1c breaks Node 10 compatibility (when using `yarn`, due to it's strict enforcement of engines).

**Comment by webpro** [comment]
Thanks @rwjblue, release-it itself also should work in Node v10
