### ISSUE TITLE
EDITOR support

### ISSUE THREAD

**Issue by LastDragon-ru** [release-it/release-it#799]
Sometimes I want to edit changelog before commit/push to fix/edit some messages, eg:

![image](https://user-images.githubusercontent.com/1329824/129469925-305718fd-31d6-4e42-b07e-3e4093b851ea.png)

But seems there is no way to do it? (editing in  text editor before commit is not an option, because changes will not be committed)

**Comment by webpro** [comment]
I remember this release-it plugin actually has this: https://github.com/rwjblue/release-it-lerna-changelog

Feel free to add this to release-it, I'm happy to merge this feature. Or maybe look into it myself when I have the time.

**Comment by LastDragon-ru** [comment]
still actual
