### ISSUE TITLE
Is it possible to upload a file and attach it with the release? 

### ISSUE THREAD

**Issue by arpwal** [release-it/release-it#800]
Hey there,

We wanted to upload a release binary (.dmg/.exe) on GitHub, using release-it. 
I searched the docs but didn't find the config for that. 

If not available yet, would it be possible to add that feature? 

Thank you, for this amazing project! :) 
Saves me countless hours monthly.

**Comment by webpro** [comment]
Please see https://github.com/release-it/release-it/blob/master/docs/github-releases.md#attach-binary-assets
