### ISSUE TITLE
How to update GitHub release?

### ISSUE THREAD

**Issue by brandonaut** [release-it/release-it#801]
I'm having trouble figuring out how to upload assets to an existing GitHub Enterprise release. The docs seem to conflict with the warnings in release-it.

I have an existing release (6.97.0) on GitHub Enterprise. When I try to add assets to the release according to the [docs](https://github.com/release-it/release-it/blob/master/docs/github-releases.md#update-the-latest-release), I get a deprecation warning:

```
❯ npx release-it --no-increment --no-git --github.release --github.update --github.assets=*.md -VV
Using --no-increment with --github.release is deprecated. Add --github.update in release-it v15.
```

And the update fails:

```
$ git log --pretty=format:"* %s (%h)" v6.97.0...v6.97.0^1
fatal: ambiguous argument 'v6.97.0...v6.97.01': unknown revision or path not in the working tree.Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
ERROR fatal: ambiguous argument 'v6.97.0...v6.97.01': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

I guess this is because it's still trying to increment the version?

If I remove the `--github.release` flag, the command succeeds but the release is not updated:

```
❯ npx release-it --no-increment --no-git --github.update --github.assets=*.md                    
 
🚀 Let's update xxxxxxxx (currently at 6.97.0)


Empty changelog

✔ npx auto-changelog
🏁 Done (in 9s.)
```

Is `--github.release` supposed to be used with `--github.update`, or not?

release-it version:
```
❯ npx release-it --version                                                              
v14.11.5
```

**Comment by brandonaut** [comment]
My current workaround is to take out `--no-git` and just skip all the git steps interactively. If I do that, then I can use `--no-increment` with `--github.release` and `--github.update`. For example:

```
❯ npx release-it --no-increment --github.update --github.release  --github.assets=*.md
Using --no-increment with --github.release is deprecated. Add --github.update in release-it v15.
```

I still get the deprecation warning, but at least it tries to update the release.

**Comment by brandonaut** [comment]
I think the `v6.97.01` and `v6.97.0^1` are being supplied by `release-it`, even when `--no-increment` is provided. I don't have those versions in my repo. It really looks to me like passing `--no-git` makes it ignore `--no-increment` as a parameter.

Here's the (obfuscated) output from a dry run:
```
❯ npx release-it --no-git --github.update --github.release --no-increment --dry-run
Using --no-increment with --github.release is deprecated. Add --github.update in release-it v15.
$ git rev-parse --abbrev-ref HEAD
$ git config --get branch.xxxxxxxx.remote
$ git remote get-url xxxxxxxxx
! git fetch
$ git describe --tags --match=* --abbrev=0
$ git rev-list v6.97.0 --tags --max-count=1
$ git describe --tags --abbrev=0 86df6aafd0a446cd4c9837f92c770e13f6473111^
$ git log --pretty=format:"* %s (%h)" v6.99.0...v6.97.0^1
ERROR fatal: ambiguous argument 'v6.99.0...v6.97.01': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by webpro** [comment]
The `--no-increment` flag first finds the latest tag:

```
git describe --tags --match=* --abbrev=0
```

This returns `v6.97.0`, and the second latest tag `v6.99.0` is resolved by:

```
git rev-list v6.97.0 --tags --max-count=1
git describe --tags --abbrev=0 86df6aafd0a446cd4c9837f92c770e13f6473111^
```

That's odd, because the highest semver tags is not the latest. But that should still return one or more commits:

```
git log --pretty=format:"* %s (%h)" v6.99.0...v6.97.0^1
```

However, somehow this seems to become `v6.97.01` (without the `^`). Could you please try to debug this command? Perhaps quoting helps:

```
git log --pretty=format:"* %s (%h)" v6.99.0..."v6.97.0^1"
```

Are you by any chance running this on Windows? I found [a note about Escaping the caret on Windows](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection):

>On Windows in cmd.exe, ^ is a special character and needs to be treated differently. You can either double it or put the commit reference in quotes:

```
$ git show HEAD^     # will NOT work on Windows
$ git show HEAD^^    # OK
$ git show "HEAD^"   # OK
```

**Comment by brandonaut** [comment]
Ah, I was overlooking the caret as part of the Git command. Yes, I'm on Windows and if I run the git log command from Cmd prompt, then I can repro the error. 

I guess then release-it should wrap that arg in quotes? Or maybe avoid using a shell for the call?

**Comment by BastianKamp** [comment]
Is there a workaround or a fix for this bug?

**Comment by webpro** [comment]
Thanks for reminding me, @BastianKamp.

There is a fix using quotes in the `caret` pre-release (`14.11.7-caret.0`), which can be installed like this:

```
npm install -D release-it@caret
```

Would be great to have confirmation this is actually a proper fix on Windows.

**Comment by BastianKamp** [comment]
@webpro 
i see no difference.
![image](https://user-images.githubusercontent.com/40761884/134911065-0996cb52-1a0e-4dbd-a2e7-e60ef7790adf.png)

**Comment by webpro** [comment]
OK, there are two steps. One I think I fixed. As for the other one: could you please try this config setting as well, so that the `${to}` gets quoted:

```
"git": {
  "changelog": "git log --pretty=format:\"* %s (%h)\" ${from}...\"${to}\""
}
```

This is something that I can then add to the default config.

**Comment by baparham** [comment]
@webpro the workaround you suggested to modify the changelog doesn't seem to be merged into the main branch. It fixes the same problem for me, but is there a particular reason this isn't the default changelog command now?

**Comment by baparham** [comment]
eh, kind of, when `--no-git` is specified, as in the example to update assets, it still executes the built in changelog command, not the one I have overridden in my config file.
