### ISSUE TITLE
--preRelease ignores conventional-changelog

### ISSUE THREAD

**Issue by zolex** [release-it/release-it#807]
The pre-release option together with conventional-changelog does not behave as expected:

when I call `release-it --release-version -d` it shows the next version according to commits (e.g. latest is 0.1.2 and there are commits with new features so it outputs 0.2.0)

when I call `release-it --release-version -d --preRelease=alpha` it ignores the commits and outputs 0.1.2-alpha.0

I know you can pass it the "minor" argument so it will output 0.2.0-alpha.0 but this is useless because if I wanted to bump manually I wouldn't use release-it...

It should respect the commit messages using conventional-changelog also for pre-releases (as it does without the --preRelease option), at least it should have an additional option to enable this behavior.

**Comment by webpro** [comment]
> It should respect the commit messages

Well, release-it itself doesn't know how to do this, so it asks (in interactive mode) or defaults to "patch". There are many conventions here, so that's why release-it has plugins like https://github.com/release-it/conventional-changelog

**Comment by zolex** [comment]
well I forgot to mention that I am using conventional-changelog and it does it right for normal releases but it ignores it with the --preRelease option

**Comment by zolex** [comment]
![image](https://user-images.githubusercontent.com/398739/132474569-0f61d4c9-7057-449c-be9f-6a27fccd87d6.png)

**Comment by zolex** [comment]
@webpro can you confirm this?

**Comment by JMMarchant** [comment]
Also ran into this issue; had a pre-major breaking change on pre-release version `0.5.3-beta.X`. Would expect it to go to `0.6.0-beta.0` but instead just bumped to `0.5.3-beta.X+1`.

Looking at the debug I can see that `conventional-changelog` correctly identified that the bump should be minor but this then seems to get ignored because `--preRelease=beta` was being used.

**Comment by webpro** [comment]
The issues should be fixed in [release-it v14.12.1](https://github.com/release-it/release-it/releases/tag/14.12.1) + [@release-it/conventional-changelog v4.0.0](https://github.com/release-it/conventional-changelog/releases/tag/4.0.0)

Note that previously conventional-changelog did indeed not support pre-releases. Reason being that the behavior of subsequent pre-releases is not always expected or obvious for everyone. Now the plugin follows the behavior of release-it: in subsequent pre-releases, the increment is `prerelease`.

**Comment by zolex** [comment]
> The issues should be fixed in [release-it v14.12.1](https://github.com/release-it/release-it/releases/tag/14.12.1) + [@release-it/conventional-changelog v4.0.0](https://github.com/release-it/conventional-changelog/releases/tag/4.0.0)

awesome! Thank you very much

**Comment by zolex** [comment]
just tested it and now it works as expected. well done. thank you :)

**Comment by zolex** [comment]
maybe I was too quick... it seems that there are still issues. now using release-it 4.12.1 and release-it/conventional-changelog 4.0.0 but look at this behavior:

refering to the following example screenshot: shouldn't the 0.3.13-alpha.1 be 0.4.0-alpha.0 because it found the "New:" keyword? and the 0.3.13-alpha.2 should then be 0.4.0-alpha.1 !?

![image](https://user-images.githubusercontent.com/398739/148741739-50b8c07b-420b-46f6-b3c4-51d898c7e124.png)

**Comment by webpro** [comment]
> Note that previously conventional-changelog did indeed not support pre-releases. Reason being that the behavior of subsequent pre-releases is not always expected or obvious for everyone. Now the plugin follows the behavior of release-it: in subsequent pre-releases, the increment is `prerelease`.

That's what I tried to explain here. Many workflows don't want e.g. "new features" to bump the minor version number while in a pre-release tag/pre-id. While in the "alpha" or "next" tag/pre-id (consecutive pre-releases), changes should not result in version bumps (just `prerelease` bumps). This is the behavior of release-it. However, when combining this with "recommended bump", this bump would unexpectedly happen. That's what I've fixed/changed in the latest releases.

I also understand release-it is not following semver here. I think it would be fairly easy to support both workflows, by making one default and have a flag for the other. So either we can think about either adding the flag now, or make semver the default + add a flag for the current behavior in a new major release for release-it (v15).

**Comment by zolex** [comment]
it would be really helpful to add this new behavior, because as you can see in the screenshot now, it completely ignores in the versioning that there are new features, even when you finally do a production release:

I mean it is a very common scenario, that you add new features+bugfixes for the next minor release but first release a beta or rc before you do the production release...


![image](https://user-images.githubusercontent.com/398739/148746211-2aa1949d-b988-4e19-9015-eb84234371ca.png)

**Comment by zolex** [comment]
@webpro so adding the flag now would be really really helpful :-* (and also not require a bc release)

**Comment by webpro** [comment]
Yes, I think it would be best to add the (experimental) flag soon, use it. And if all is well we can still swap the default behavior in an upcoming release.

**Comment by zolex** [comment]
@webpro and maybe another thing: it would be great if you make a prod release, that it collects all the commits again sinec the last prod release, like combining everything from the prereleases for this version!

**Comment by webpro** [comment]
I have released [v4.1.0](https://github.com/release-it/conventional-changelog/releases/tag/4.1.0) with a new `strictSemVer` for this. Also added a line to the docs here (https://github.com/release-it/release-it/blob/master/docs/pre-releases.md).

**Comment by zolex** [comment]
@webpro thanks for your effort. that is a step into the right direction for us and I guess I should leave you alone now, but I still got issues. imagine the following workflow:


current version is 0.3.5

now lets say the team is working on 3 new features and 5 bugfixes that should result in version 0.4.0

in the meantime the team wants to make pre-releases to be deployed on QA stage so that the QA team can test the fixes and new features.

in the fist step 1 feature and 2 bugfixes are implemented so the release should be 0.4.0-alpha.0 (this works fine right now)

in the second step 2 features and 3 bugfixes are implemented so the release should be 0.4.0-alpha.1 (currently release-it bumps it to 0.5.0-alpha.0)

in the third step all features and all bugfixes are implemented so the release should be 0.4.0-beta.0 (currently release-it bumps it to 0.6.0-beta.0)

in the fourth step a bug from a previously implemented feature is fixed so the release should be 0.4.0-beta.1 (currently release-it bumps it to 0.6.1-beta.0)

in the sixth step maybe some final texts are added so the team wants an 0.4.0-rc.0 (currently release-it would create 0.6.1-rc.0)

in the sevenths step they found a last minute fix and want to release it as 0.4.0-rc.1 (currently release it makes a 0.6.2-rc.0)

finally the team wants to do the production release as 0.4.0 (but according to the described workflow above, release-it makes a 0.6.2)

**Comment by zolex** [comment]
@webpro the logic might be as simple as:
* if previous release is a prod release, then the next pre-release WILL bump the version number
* if previous release is a pre-release, then the next pre-release WILL NOT bump the version number, with two exceptions:
  * if previous pre-release was patch and the next pre-release contains a new feature, then bump minor
  * if previous pre-release was patch or minor and the next pre-release contains a BC, then bump major

**Comment by webpro** [comment]
> in the second step 2 features and 3 bugfixes are implemented so the release should be 0.4.0-alpha.1 (currently release-it bumps it to 0.5.0-alpha.0)

This is how it works, and I'm making assumptions about the situation and configuration:

- Current version is `0.4.0-alpha.0`
- Assuming recommended bump is `minor` from `@conventional-changelog` (since there's 2 new features)
- Assuming `strictSemVer: true` in plugin option is enabled
- Assuming a pre-release is desired, the bump will be `preminor`
- Assuming the pre-id should still be `alpha`
- New version is `0.5.0-alpha.0`, see e.g. [node-semver](https://github.com/npm/node-semver) output:

```
$ semver -i preminor --preid alpha 0.4.0-alpha.0
0.5.0-alpha.0
```

So, WDYT?

**Comment by zolex** [comment]
@webpro I think the key to do it right is to always use the last prod release version as a base for all pre-release bumps. so multiple new features in multiple pre-releases should only once bump the minor and not individually. same for patch and major.

**Comment by zolex** [comment]
in the end, pre-releases are not real releases and if each pre-release individually bumps the version numbers, then there is a break between previous and next production release, which is not valid semantic versioning

**Comment by webpro** [comment]
> @webpro I think the key to do it right is to always use the last prod release version as a base for all pre-release bumps. so multiple new features in multiple pre-releases should only once bump the minor and not individually. same for patch and major.

Now I understand your reasoning/workflow, interesting. Do you have any resources or articles using this strategy? The semver specs don't seem to mention anything about bumping at all, so I'm simply not sure if this is default behavior, or whether there is some kind of "default" strategy or anything?

> in the end, pre-releases are not real releases and if each pre-release individually bumps the version numbers, then there is a break between previous and next production release, which is not valid semantic versioning

I think I agree, and that's also why release-it has the behavior it has: when the previous release was a pre-release, and we want another pre-release, bump using `prelease` (and not one of `premajor`, `preminor` or `prepatch`).

On the other hand, what says it's (not) valid? The workflow could potentially involve working on two releases in parallel (which is what I thought you were describing initially), eventually resulting in "proper" semver.

**Comment by zolex** [comment]
> Now I understand your reasoning/workflow, interesting. Do you have any resources or articles using this strategy? The semver specs don't seem to mention anything about bumping at all, so I'm simply not sure if this is default behavior, or whether there is some kind of "default" strategy or anything?

sadly I do not have a resource that I can share. I am new to the concept of letting the commit messages increment the version numbers. I am used to work towards specific versions containing a predefined set of features and fixes according to a roadmap. I am now trying to utilize release-it and conventional-changelog to achieve the same results as with a roadmap.

> On the other hand, what says it's (not) valid? The workflow could potentially involve working on two releases in parallel (which is what I thought you were describing initially), eventually resulting in "proper" semver.

for some reason I just believe that skipping versions in production releases is not semantic. I'll let you know if I find a resource that supports my thinking.

> I think I agree, and that's also why release-it has the behavior it has: when the previous release was a pre-release, and we want another pre-release, bump using `prelease` (and not one of `premajor`, `preminor` or `prepatch`).

we want to use release-it in a CI pipeline and the goal is that devs do not have to worry about anything. we only want them to merge things into "master" to create a production release and whenever they merge something into a "pre-release/xxx" branch it should create a pre-release with the suffix "-xxx".

maybe you can explain a strategy using release-it and conventional-changelog to achieve the behavior I am describing? important requirement is that you should not have to care about anything but merging into the respective branches.

**Comment by zolex** [comment]
@webpro now this would be my approach for a workaround

```
LATEST=$(git-semver-tags | head -n1)
LATEST_PROD=$(git-semver-tags | grep -v - | head -n1)
LATEST_DIFF=$(semver-diff $LATEST_PROD $LATEST)

sed -i '' 's/"strictSemVer": false/"strictSemVer": true/' .release-it.json

STRICT_BUMP=$(release-it --ci -VV -d --release-version --preRelease=alpha | tail -n1)
STRICT_DIFF=$(semver-diff $LATEST_PROD $STRICT_BUMP)

echo Latest: $LATEST
echo Latest Prod: $LATEST_PROD
echo Latest Diff: $LATEST_DIFF
echo Strict Bump: $STRICT_BUMP
echo Strict Diff: $STRICT_DIFF

if [ "$LATEST_DIFF" = "$STRICT_DIFF" ]; then
	sed -i '' 's/"strictSemVer": true/"strictSemVer": false/' .release-it.json
fi


FINAL_BUMP=$(release-it --ci -VV -d --release-version --preRelease=alpha | tail -n1)

echo Final Bump: $FINAL_BUMP
```

output:

```
Latest: 0.5.0-alpha.0
Latest Prod: 0.4.0
Latest Diff: minor
Strict Bump: 0.6.0-alpha.0
Strict Diff: minor
Final Bump: 0.5.0-alpha.1
```


now it would be helpful if we can pass strictSemVer as a commandline argument or/an even better if release-it could optionally behave like this workaround ^^

**Comment by zolex** [comment]
if anyone cares, here is my working solution for github actions

```
  release:
    name: Create Release
    runs-on: [ self-hosted, CAI-Enterprise ]
    #needs: [ build, test, security ]
    outputs:
      version: ${{ steps.release_it.outputs.version }}
    steps:
      - name: Checekout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup release-it
        run: |
          npm i -g release-it@~14.12.1 @release-it/conventional-changelog@~4.1.0 git-semver-tags semver-diff-cli conventional-changelog-cli conventional-changelog-eslint

      - id: pre_release
        name: Is pre-release?
        run: |
          if [[ $GITHUB_REF =~ pre-release/[^/]+$ ]]; then
            echo "::set-output name=argument::--preRelease=$(echo ${GITHUB_REF#refs/heads/pre-release/})"
          fi

      - name: Set strict pre-release mode
        if: |
          always() &&
          steps.pre_release.outputs.argument
        env:
          PRE_RELEASE: ${{ steps.pre_release.outputs.argument }}
        run: |
          LATEST=$(git-semver-tags | head -n1)
          LATEST_PROD=$(git-semver-tags | grep -v - | head -n1)
          LATEST_DIFF=$(semver-diff $LATEST_PROD $LATEST)
          sed -i 's/"strictSemVer": false/"strictSemVer": true/' .release-it.json
          STRICT_BUMP=$(release-it --ci -d --release-version $PRE_RELEASE | tail -n1)
          STRICT_DIFF=$(semver-diff $LATEST_PROD $STRICT_BUMP)
          echo Latest: $LATEST
          echo Latest Prod: $LATEST_PROD
          echo Latest Diff: $LATEST_DIFF
          conventional-changelog
          echo Strict Bump: $STRICT_BUMP
          echo Strict Diff: $STRICT_DIFF
          if [ "$LATEST_DIFF" = "$STRICT_DIFF" ]; then
            echo "Don't bump $LATEST_DIFF again during pre-release" 
            sed -i 's/"strictSemVer": true/"strictSemVer": false/' .release-it.json
          fi

      - id: release_it
        name: Create Release
        env:
          PRE_RELEASE: ${{ steps.pre_release.outputs.argument }}
        run: |
          git config --global user.name "release-it"
          git config --global user.email "release-it@noreply.coxautoinc.com"
          export GITHUB_TOKEN=${{ github.token }}
          echo "::set-output name=version::$(release-it -d --ci --release-version $PRE_RELEASE | tail -n1)"
          release-it -VV --ci $PRE_RELEASE
```

**Comment by plasticrake** [comment]
I agree with what @zolex is describing - base prereleases version off the the last production release.

I also would like the changelog of a production release to aggregate all the changes from any prereleases since the last production release as @zolex mentioned above. I know it has been raised before (#733, #796) but it's not clear to me exactly what the workaround is for this. A working example would be great.

**Comment by webpro** [comment]
I realized the introduced `git.tagMatch` feature might be helpful for certain workflows: https://github.com/release-it/release-it/blob/master/docs/git.md#tag-match

Maybe a new flag could make this feature more obvious/friendly, but it's a start.
