### ISSUE TITLE
Cannot create a manual release for a private repo which I am a collaborator for

### ISSUE THREAD

**Issue by NS-BOBBY-C** [release-it/release-it#809]
# UPDATE

I'm OK with closing this issue, but I completed a workaround rather than fixed my existing configuration. Feel free to close this issue! I ended up removing the GITHUB_TOKEN definition from my .zshrc, and then restarting my computer. After that, I followed the directions for the GitHub CLI found [here](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git) which then allowed me to successfully release. Not sure what I had configured wrong where (I also cleared a VSCode credential for git in Mac KeyChain and regenerated personal access tokens in GitHub).

# Original Issue

I'm getting the following error:

```bash
ERROR User NS-BOBBY-C is not a collaborator for REPO/HERE
```

However, I am a collaborator to the repo in question and have been for over two years.

![image](https://user-images.githubusercontent.com/29097404/133441109-dbd034fb-f59e-4336-a520-ed4546c17111.png)

Note -  this is a private repo and I won't be able to share any URLs or details of it. I am willing to work with someone to create a private repo, add me as a collaborator, and debug if necessary.

Release-It Configuration (from package.json):
```JSON
{
  ...
  "devDependencies": {
    "release-it": "^14.11.5",
  },
  ...
  "release-it": {
    "git": {
      "commitMessage": "chore: release v${version}"
    },
    "github": {
      "release": true
    },
    "npm": {
      "publish": false
    }
}
```

### Logging with "release": "DEBUG=release-it:* release-it -VV",

```bash
GET /user - 200 in 259ms
octokit repos#checkCollaborator (NS-BOBBY-C)
request {
  method: 'GET',
  baseUrl: 'https://api.github.com',
  headers: {
    accept: 'application/vnd.github.v3+json',
    'user-agent': 'release-it/14.11.5 octokit-rest.js/18.9.0 octokit-core.js/3.5.1 Node.js/14.17.1 (darwin; x64)'
  },
  mediaType: { format: '', previews: [] },
  request: { timeout: 0, hook: [Function: bound bound register] },
  url: '/repos/{owner}/{repo}/collaborators/{username}',
  owner: '[REDACTED OWNER]',
  repo: '[REDACTED REPO]',
  username: 'NS-BOBBY-C'
}
GET /repos/[REDACTED OWNER]/[REDACTED REPO]/collaborators/NS-BOBBY-C - 404 in 371ms
  release-it:github HttpError: Not Found
  release-it:github     at [PROJECT PATH]/node_modules/@octokit/request/dist-node/index.js:86:21
  release-it:github     at processTicksAndRejections (internal/process/task_queues.js:95:5)
  release-it:github     at async GitHub.isCollaborator ([PROJECT PATH]/node_modules/release-it/lib/plugin/github/GitHub.js:107:7)
  release-it:github     at async GitHub.init ([PROJECT PATH]/node_modules/release-it/lib/plugin/github/GitHub.js:61:15)
  release-it:github     at async runLifeCycleHook ([PROJECT PATH]/node_modules/release-it/lib/tasks.js:50:28)
  release-it:github     at async runTasks ([PROJECT PATH]/node_modules/release-it/lib/tasks.js:61:7) +0ms
  release-it:metrics {
  release-it:metrics   url: 'http://www.google-analytics.com/collect',
  release-it:metrics   statusCode: 200,
  release-it:metrics   statusMessage: 'OK',
  release-it:metrics   payload: 't=exception&exd=Error%3A+User+NS-BOBBY-C+is+not+a+collaborator+for+[REDACTED OWNER]%2F[REDACTED REPO].'
  release-it:metrics } +2s
ERROR User NS-BOBBY-C is not a collaborator for [REDACTED OWNER]/[REDACTED REPO].
Documentation: https://git.io/release-it-github
```

**Comment by NS-BOBBY-C** [comment]
I initially thought it was an API status issue ([GitHub Status](https://www.githubstatus.com/)) after seeing the "HttpError: Not Found" in the debug log. I also looked into Octokit a little following code from lib/plugin/github/GitHub.js to try and understand what is going on a bit more.

My wild guess is that Octokit isn't authenticated as me correctly and then the request for a private repo isn't working. However, that's unfounded based on my limited knowledge of the moving parts and could be wildly off.

**Comment by NS-BOBBY-C** [comment]
I'm OK with closing this issue, but I completed a workaround rather than fixed my existing configuration. Feel free to close this issue! I ended up removing the GITHUB_TOKEN definition from my .zshrc, and then restarting my computer. After that, I followed the directions for the GitHub CLI found [here](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git) which then allowed me to successfully release. Not sure what I had configured wrong where (I also cleared a VSCode credential for git in Mac KeyChain and regenerated personal access tokens in GitHub).

**Comment by LichKing-2234** [comment]
> I'm OK with closing this issue, but I completed a workaround rather than fixed my existing configuration. Feel free to close this issue! I ended up removing the GITHUB_TOKEN definition from my .zshrc, and then restarting my computer. After that, I followed the directions for the GitHub CLI found [here](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git) which then allowed me to successfully release. Not sure what I had configured wrong where (I also cleared a VSCode credential for git in Mac KeyChain and regenerated personal access tokens in GitHub).

The same issue, but not work for me.

**Comment by webpro** [comment]
These issues don't sound like release-it bugs, but rather configuration issues on your end.

You can use `--github.skipChecks` to skip the check. Feel free to open an issue if you feel it's worth a bug report or discussion.

**Comment by NS-BOBBY-C** [comment]
@webpro likely an obsoletion of the GitHub password based authentication. If there is an issue, I would recommend that its not worth the time since a more secure means of authentication exists and is recommended! :)
