### ISSUE TITLE
Pre-release versioning not incrementing correctly when prerelease has multiple alphabetic and numeric sections

### ISSUE THREAD

**Issue by ivandov** [release-it/release-it#812]
I was attempting to create a pre-release format that allows me to limit the increments of our `beta` pre-release to only be bumped for when we're releasing drops to our external (outside of our team) stakeholders.

I was following the [pre-release semver spec](https://semver.org/#spec-item-9) and attempting to use a pattern similar to the format they reference `1.0.0-x.7.z.92`. In my case, I was hoping to use something like `v2.1.0-beta.0.rc.0` and have our team follow the process that every sprint, we'd release for our testers an incremented final digit `beta.0.rc.1` -> `beta.0.rc.2` and then when we're ready for external release, we'd drop `beta.0`.

This process would be followed for future `beta.X` releases. 

However, when using this format and attempting to use:
```
release-it --preRelease=beta.0.rc
```

It will properly create a `v2.1.0-beta.0.rc.0` release as expected. Then when the same command is run again, it will NOT increment as expected to `v2.1.0-beta.0.rc.1`. 

Instead, if I use the following command:
```
release-it --preRelease=beta
```

That WILL increment the version to `v2.1.0-beta.0.rc.1`. The matching around the string that is passed to the `preRelease` flag does not seem to parse correctly if the pre-release version has segments that are number based!

**Comment by mikhail-vazhenin** [comment]
I have the same problem.
The first time I run command with parameters:
```
release-it --preRelease=beta
```
As result I have `1.0.1-beta.0`.
If I need increment beta again and create version `1.0.1-beta.1` , I try to run command again, but version is not incremented. I have `1.0.1-beta.0` again.

Also I found that version will be incremented correctly if I will run after previous command this one:
```
release-it --preRelease
```
Result of this command will be `1.0.1-beta.1`.

In this case I need check every time I have or not already added prerelease tag and use different arguments in every case.
This is very inconvenient.

Could you add ability to increment beta by single argument list, for example use `release-it --preRelease=beta` for the first and subsequent steps?

**Comment by mikhail-vazhenin** [comment]
Ok. I got how it must work.
it's not so convenient, but I figured out how it should work.

The previous comment is no longer relevant.

**Comment by webpro** [comment]
Is it working properly @mikhail-vazhenin? It's documented at https://github.com/release-it/release-it/blob/master/docs/pre-releases.md, please let me know if you did encounter any bugs?
