### ISSUE TITLE
How to make publish execute after push

### ISSUE THREAD

**Issue by 2018mjy** [release-it/release-it#814]
![image](https://user-images.githubusercontent.com/39129537/134800599-c458adc5-3744-4a28-a279-2f33788acaf9.png)
![image](https://user-images.githubusercontent.com/39129537/134801093-4929d94d-e683-4aa5-9c8e-2a7bcaecb1bb.png)

I see on the document that publish can be executed after push.  Is there any configuration item to adjust their order?

**Comment by webpro** [comment]
The `npm publish` happens before the Git push/GitHub release, as the former potentially gives the most issues (network, authentication, collaborator, etc), so there's less to clean up in case of issues.

They are separate, internal plugins, and there's currently no way to change their order.

Out of curiosity, for what use case/reason would it be preferable to run the Git push before the npm publish?

**Comment by 2018mjy** [comment]
Before, I used to execute publish at the end, it's just a matter of habit. But I thought about what you said, I feel very reasonable, publish is indeed better in front. thank you for your reply
