### ISSUE TITLE
Disable version update to package.json

### ISSUE THREAD

**Issue by khoinguyen** [release-it/release-it#815]
The package.json are required to build Docker, and I want to Docker build able to cache the dependencies, so the package.json should not change between release except when new dependencies changes.

Release it by default always change the package.json. I've used `@release-it/bumper` to bump the version to VERSION file and I don't want the package.json to change just because the version bump.

I dig thru the document but looks like there are no way to disable this behavior.

**Comment by webpro** [comment]
Sounds like maybe you also don't want to `npm publish` the project? Then you can use `npm: false` to disable the plugin altogether.

**Comment by khoinguyen** [comment]
thank you!
