### ISSUE TITLE
nodejs in hooks is stuck

### ISSUE THREAD

**Issue by 2018mjy** [release-it/release-it#821]
When I run this command alone, it is normal, 
![image](https://user-images.githubusercontent.com/39129537/136933076-1566b40f-33c3-4d64-837b-a1be7b1966eb.png)
but when I run it in hooks, it will get stuck.
![image](https://user-images.githubusercontent.com/39129537/136933175-df0aaaa7-814e-43d1-9923-cb55223fabca.png)
![image](https://user-images.githubusercontent.com/39129537/136931480-cd9f1dcd-1855-43a8-be3e-136d033f0291.png)
The node file is as follows👇：
![image](https://user-images.githubusercontent.com/39129537/136933721-9243aee6-177e-482c-b482-75f07f7f3477.png)

**Comment by webpro** [comment]
Yes, another instance of inquirer is known to be problematic. Not sure exactly why, but I'll add it to the docs.
