### ISSUE TITLE
GH006: Protected branch update failed for refs/heads/master

### ISSUE THREAD

**Issue by newfunda** [release-it/release-it#822]
Changeset:
M CHANGELOG.md
 M package.json
- Git commit
✔ Git commit
- Git tag
✔ Git tag
- Git push
✖ Git push
ERROR remote: error: GH006: Protected branch update failed for refs/heads/master.

**Comment by newfunda** [comment]
I tried searching on internet but could not get any standard way, so, till the issues is fixed, I am publishing npm package with release and CHANGELOG.md with package.json version update in new branch, named as 'release', so till someone merge manually release to master as and when we release, there will be difference between master and release branch until it's merged.

**Comment by newfunda** [comment]
Once master branch is protected by PR, I feel there is no way to publish package in GitHub release.

**Comment by AliAzhdari** [comment]
why this issue is closed! there is no way in GitHub to handle this scenario! it is a common scenario.

**Comment by alvarogabrielgomez** [comment]
Yeah right, but would be very helpful if someone says a way to do that. A flow that recommends, something that helps.... Because only say "That is intended" and move on does not help to anybody. I have the same issue right now

**Comment by webpro** [comment]
I'm sorry to hear this is a frustrating issue to some.

Protected branches are a GitHub/GitLab feature.

What could be of help to the next developer facing this? I think the solution is to either remove the protection, or use another branch. Happy to add this to the docs, though.

What issues did you face? Anything else I could do?

**Comment by multivoltage** [comment]
Any idea?

**Comment by gethari** [comment]
is there a recommendation for this ? Most organizations & repositories use a `push` protected `master`/`main` branches, if the CI runs after the PR, obviously it cannot push code into it again, if we do run it on a say `release` branch, who will bring the changes back to `-> master` ? like the changelog files that gets generated ?
