### ISSUE TITLE
configuring release-it to bump version before generating changelog

### ISSUE THREAD

**Issue by rlsf** [release-it/release-it#830]
hello,
it's not exactly an issue, but i'm trying to utilize release-it for a project i'm working on, which already has a standard release procedure i cannot modify.
the release process is:
1. bump version file (package.json)
2. create changelog using https://github.com/github-changelog-generator/github-changelog-generator
3. create a release tag, push to github
4. create a github release with tag from step 3.

my problem is that release-it generates the changelog before bumping the version, so github-changelog-generator doesn't work correctly. is there any workaround to make it work this way?

**Comment by webpro** [comment]
Sounds like you can use a [hook](https://github.com/release-it/release-it#hooks) such as `before:bump` or `after:bump` to achieve what you want?

**Comment by rlsf** [comment]
> Sounds like you can use a [hook](https://github.com/release-it/release-it#hooks) such as `before:bump` or `after:bump` to achieve what you want?

i want the changelog generated by github changelog generator to be used as the changelog of the release.
however, the changelog of the release is being executed prior to the bump.
running the changelog generator at this point generates an empty changelog, since the version hasn't been advanced yet.

**Comment by webpro** [comment]
Not sure how to use that changelog generator, but I'm seeing [options](https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples) to provide values for "since-tag", "due-tag", "future-release". Which could be set in the command using `${from}` and `{to}` (just like `git.changelog`)

**Comment by rlsf** [comment]
let's say i have a repo with branch `1.0.0` already released, and i want to release a patch version (`1.0.1`).
running the changelog generator before bumping the version will yield an empty changelog, since `to` tag is still `1.0.0`
i need to bump `package.json` to `1.0.1`, and then run the generator, which will now be able to generate a proper changelog, for the changes that took place between `1.0.0` and `1.0.1`.

**Comment by webpro** [comment]
Sorry, totally forgot about the fact that this exact use case was the reason to have the `github.releaseNotes` option.

The initial changelog generator command can't have the target tag, as it needs to be printed before the next version is determined (as it helps with that in interactive mode).

Please refer to https://github.com/release-it/release-it/blob/master/docs/github-releases.md#release-notes

(I also just added a test to prevent regressions in https://github.com/release-it/release-it/commit/cd77539d9316dc96ad40c62c036594dd57447834)
