### ISSUE TITLE
question: how to use release-it in monorepo?

### ISSUE THREAD

**Issue by aladdin-add** [release-it/release-it#831]

**Comment by webpro** [comment]
There is no built-in support for monorepos in release-it. However, there are some other packages based on release-it that may be interesting:

- https://github.com/rwjblue/release-it-yarn-workspaces
- https://github.com/danderson00/release-em

**Comment by aladdin-add** [comment]
will give a try. thanks!

**Comment by paulrberg** [comment]
If you arrived here from Google (as I did), I recommend you check out [changesets](https://github.com/changesets/changesets).

It's like "release-it" but tailored to monorepos.
