### ISSUE TITLE
release-it ignoring bump argument

### ISSUE THREAD

**Issue by thet** [release-it/release-it#833]
When I do a ``npx release-it major --release-version --dry-run`` it totally ignores the ``major`` bump.

The following bumps the version to ``5.5.2`` instead ``6.0.0``:
```
npx release-it major --release-version --dry-run
$ npm ping
$ npm whoami
$ npm show @patternslib/patternslib@latest version
$ npm access ls-collaborators @patternslib/patternslib
$ git rev-parse --abbrev-ref HEAD
$ git diff --quiet HEAD
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git config --get branch.master.remote
$ git remote get-url origin
! git fetch
$ git describe --tags --match=* --abbrev=0
$ git symbolic-ref HEAD
$ git for-each-ref --format="%(upstream:short)" refs/heads/master
WARNING The recommended bump is "patch", but is overridden with "major".
$ git log --pretty=format:"* %s (%h)" 5.5.1...HEAD
5.5.2
```

```
npx release-it --version
v14.11.7
```

**Comment by thet** [comment]
Not sure, if that is actually an issue. I found the config option ``ignoreRecommendedBump`` in https://github.com/release-it/conventional-changelog#ignorerecommendedbump which fixes the problem for me.

However, I have the impression that the docs could be more clear on that. 

I thought until now that I was able to cut patch/minor/breaking releases by just passing the release type option to release-it and actually I cannot explain how I could have done the last major release without that option being respected despite the missing ``ignoreRecommendedBump``. Even more so, that my ``breaking`` type wasn't detected as a breaking change which should have result in a major release recommendation.

Ref: https://github.com/release-it/conventional-changelog/issues/37#issuecomment-971025108

**Comment by webpro** [comment]
Perhaps the main thing here is to see that `--dry-run` is not writing anything (e.g. no `git tag`, won't modify `package.json`). This is sometimes confusing and gives different output that an actual release.

Without digging into this yet, I think the last major release you did worked as expected without using `ignoreRecommendedBump`.
