### ISSUE TITLE
BuildCommand not working

### ISSUE THREAD

**Issue by danielAlgo** [release-it/release-it#835]
Hi all,

When I create a new release I also upload two files to the github releases.
Those files are created from the 'yarn build' command (script in package.json that runs 'yarn cross-env NODE_ENV=debug node ./scripts/build' ) and they have the name of the version in them i.e. "Setup 2.0.0".
I bump the version of the package json after I use release-it using "@release-it/bumper" and it happens after I build the file which takes the version no. from the package.json.

However, I want to bump the version number in the package and use the 'yarn build' command and only afterwards release-it.

Can you help me solve it please?
Thanks in advance

**Comment by danielAlgo** [comment]
Fixed it using
  "hooks": {
    "after:bump": "yarn build"
  },
  
  instead of BuildCommand

**Comment by webpro** [comment]
Glad you figured it out :)
