### ISSUE TITLE
Github assets

### ISSUE THREAD

**Issue by sbreiler-work** [release-it/release-it#836]
Hi,

it seems the assets config is ignored if the create release method decides to use the web interface, right? Is this intended behavior?

Could we introduce a warning or error message if the web interface is used and assets config is set? I could propose a PR, if interested.

On that note: are deploy keys supported?

**Thanks!**

**Comment by webpro** [comment]
> it seems the assets config is ignored if the create release method decides to use the web interface, right? Is this intended behavior?

Yes, the web interface is prepared by a link containing only text. It's impossible to include binary assets this way.
 
> Could we introduce a warning or error message if the web interface is used and assets config is set? I could propose a PR, if interested.

Yes, good idea! PR is very welcome. Thank you in advance.

> On that note: are deploy keys supported?

Yes, they should work. Do you encounter any issues?

**Comment by webpro** [comment]
Added a warning.
