### ISSUE TITLE
Run release-it in another folder

### ISSUE THREAD

**Issue by rondymesquita** [release-it/release-it#838]
Hi,

Is there any way to run release-it and run the tasks in another folder?
My plan is to have a single repository that releases in multiple folders using same configuration.
With that, I avoid to install release-it in each repository and use a single `.release-it.json` file.
Something like we have with npm `npm --prefix=./my-folder install`.

`release-it --directory=./sub-folder --config .release.it.json`
`release-it --directory=../folder-on-parent --config .release.it.json`

So, with a single config file, I can release two repositories using same configuration, with separated changelogs (since are different folders) and so on.

Thanks in advance.

**Comment by webpro** [comment]
This is not a feature in release-it, but probably some (shell) script around could work.
