### ISSUE TITLE
hotfix branch fails

### ISSUE THREAD

**Issue by lelandcope** [release-it/release-it#840]
I get the following error when trying to release a hotfix branch

`git flow release finish -m 'Released_version_21.12.6' 21.12.6 && git checkout master && git push origin master && git push --tags && git checkout develop && git push origin develop
ERROR Fatal: Branch 'release/21.12.6' does not exist and is required.`

Its basically telling me a release branch does not exist but as far as i know releasing from a hotfix branch is part of git flow. Any help would be great because it adds more work when we need to release a hotfix.

**Comment by lelandcope** [comment]
im using release-it and thats the error i received. I was hoping someone else came across this issue trying to release a hotfix branch and if they also ran into this issue.

**Comment by webpro** [comment]
You can release from any branch, but the error seems to be unrelated to release-it, but to something else (git or git flow itself):

> ERROR Fatal: Branch 'release/21.12.6' does not exist and is required.

Therefore I'm going to close this issue. Feel free to re-open or open another ticket if you think release-it has a bug.
