### ISSUE TITLE
support github's auto generated release notes

### ISSUE THREAD

**Issue by rlsf** [release-it/release-it#842]
github releases support generating release notes using a parameter sent on release creation, see here:
https://docs.github.com/en/rest/reference/repos#create-a-release--parameters (parameter name is `generate_release_notes`).

supporting this feature will simplify release notes generation for github based repos.

**Comment by rlsf** [comment]
@webpro any chance of releasing the updated version soon?

**Comment by webpro** [comment]
Apologies for the delay @rlsf, but it was just finally released in [v14.12.0](https://github.com/release-it/release-it/releases/tag/14.12.0). Thanks again!
