### ISSUE TITLE
Is it possible to merge semver and calver to achieve version format like YY.MM.MINOR.PATCH?

### ISSUE THREAD

**Issue by EugeneBran** [release-it/release-it#847]
Hello? is it possible to merge semver and calver to achieve version format like YY.MM.MINOR.PATCH?
I'am trying to do this with release-it-calver-plugin but i get errors like 
`ERROR Version and format lengths mismatch.`

**Comment by webpro** [comment]
Just to be sure, there is https://github.com/casmith/release-it-calver-plugin - maybe it's possible to configure this `format`?

Otherwise, you could create a [release-it plugin](https://github.com/release-it/release-it/blob/master/docs/plugins.md).

**Comment by EugeneBran** [comment]
I've tried, but i've an error: `ERROR Version and format lengths mismatch.` Is there some limitations on version format in release-it?

**Comment by webpro** [comment]
I don't recognize this error message, it's not coming from release-it itself (or a plugin), so I'd say it's from some dependency (such as calver).

**Comment by EugeneBran** [comment]
Thank you
