### ISSUE TITLE
npm skip publish not working through CI

### ISSUE THREAD

**Issue by dooleyb1** [release-it/release-it#849]
I'm trying to use `release-it` within CircleCI to perform GitHub releases for a private repository. I want the version in `package.json` to be incremented to reflect the release however I don't want to publish to any NPM repository. I'm using the following command and it seems to be attempting to run `npm publish` regardless of me passing the `--npm.publish=false` flag.

```bash
npx release-it minor \
          --ci \
          --npm.publish=false \
          --npm.skipChecks \
          --github.release \
          --github.releaseName=${version} \
          --git.commitMessage="[ci skip] - Automated release changes" \
          --github.autoGenerate
```

The error I'm seeing within CircleCI is as follows:

```bash
✔ npm version
Changeset:
 M package-lock.json
 M package.json
- npm publish
✖ npm publish
ERROR npm notice 
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/<repo> - Not found
npm ERR! 404 
npm ERR! 404  '<repo>@1.13.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

The docs say we can [skip publish](https://github.com/release-it/release-it/blob/master/docs/npm.md#skip-publish) by setting the `npm.publish` option however we are not using the `.release-it.json` file and only using CLI arguments / flags. 

Judging by [this line](https://github.com/release-it/release-it/blob/master/lib/plugin/npm/npm.js#L37) within the source code I'd expect it to exit here and not attempt to publish to npm?

Is there something I am missing?

**Comment by webpro** [comment]
Boolean flags can be negated with `--no-`, so in this case `--no-npm.publish`

**Comment by dooleyb1** [comment]
> ```shell
> --npm.skipChecks \
> ```

This worked perfectly, thank you @webpro 😄
