### ISSUE TITLE
`github.autoGenerate` fails release

### ISSUE THREAD

**Issue by poeck** [release-it/release-it#855]
When I use `github.autoGenerate` it fails the build with this error:

```bash
? Create a release on GitHub (v0.0.37)? Yes
ERROR 422 (Invalid request.

For 'properties/body', nil is not a string.)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm not sure If I configured something wrong, but it seems to work fine without the option!

**Comment by webpro** [comment]
Should be fixed in [v14.12.2](https://github.com/release-it/release-it/releases/tag/14.12.2)

**Comment by wottpal** [comment]
@webpro Have the exact same error with `15.11.0` :/

```
 ERROR 422 (Invalid request.

For 'properties/body', nil is not a string.)
```

**Comment by wottpal** [comment]
Figured it out, probably was due to this change of the github token name: https://github.com/release-it/release-it/commit/d13edef958f59dffecac6fa7ee0a1d7886852667. Please be aware that most of your docs/resources still quote `GITHUB_TOKEN`, which might lead to further issues down the road for you!

**Comment by webpro** [comment]
That updated GitHub token name is used only by me to release release-it itself. I've changed it since GitHub's new fine-grained PATs do not seem to work across organizations. Agree it's confusing, but everywhere else release-it uses and documents `GITHUB_TOKEN` by default.
