### ISSUE TITLE
Improper Privilege Management in shelljs

### ISSUE THREAD

**Issue by nbouvrette** [release-it/release-it#857]
Since I updated to `14.12.2`, I am getting the following [security warning](https://github.com/advisories/GHSA-64g7-mvw6-v9qj):

```sh
shelljs  <0.8.5
Severity: moderate
Improper Privilege Management in shelljs - https://github.com/advisories/GHSA-64g7-mvw6-v9qj
No fix available
```

**Comment by webpro** [comment]
Thanks @nbouvrette, did patch release for this ([v14.12.3](https://github.com/release-it/release-it/releases/tag/14.12.3))
