### ISSUE TITLE
ES Modules (release-it + plugins)

### ISSUE THREAD

**Issue by webpro** [release-it/release-it#859]
The release-it organization (OK lol, that's just me) wants to start using ES Modules exclusively from the upcoming major release of release-it and its plugins. When used from the CLI, which I expect is by far the majority, should have no breaking changes. Only when used programmatically, there 

Supporting some kind of hybrid of both CommonJS and ESM in a single distribution is not something I prefer, but I'm happy to backport fixes in the previous major for users sticking to CommonJS for the foreseeable future (depending on usage and severity of issues).

## Installable `esm` packages

The `esm` dist tags of the following packages are available, feel free to use them in your project. Please file bugs and feature requests in new, separate issues.

```
npm install -D release-it@esm
npm install -D @release-it/conventional-changelog@esm
npm install -D @release-it/bumper@esm
npm install -D @release-it/keep-a-changelog@esm
```

Note that release-it v15 is not compatible with plugins published in CommonJS. The advice is to stay on release-it v14 when using plugins that are not available in ESM yet. As mentioned, release-it v14 will be maintained for the foreseeable feature. Feel free to add your plugin in the comments and I'll add it to the status list.

## Status

Package (npm) | CommonJS (`latest`) | ESM (`esm`) | Status
---|---|---|---
release-it |  v14 | v15 | ✅ ~(1)~
@release-it/conventional-changelog | v4 | v5 | ✅ ~(2)~
@release-it/bumper | v3 | v4 | ✅ ~(2)~
@release-it/keep-a-changelog | v2 | v3 | ✅ ~(3)~

1. ~Major updates for ava, chalk and parse-json are (indeed) breaking, needs work. Not blocking, though.~
2. ~Some tests fail in Windows. Probably nothing blocking, though.~
3. ~Work for ESM has not started yet.~

**Comment by webpro** [comment]
Tagging some plugin maintainers: @rwjblue, @casmith, @jairhenrique, @j-ulrich, @ath0mas. Let me know if you have any questions, issues or concerns. In case you're not willing or able to migrate to ES Modules, it's probably best to indicate this in the `peerDependencies` of your `package.json` (and stick to release-it v14).

**Comment by casmith** [comment]
@webpro I just took a [first pass at converting](https://github.com/casmith/release-it-calver-plugin/pull/12) release-it-calver-plugin to ES modules and it seems relatively straightforward.

**Comment by rwjblue** [comment]
@webpro some of my plugins have already converted to ESM (while using release-it@14), and I'm loving it 😄 

---

In case folks are curious how to do this, you can look here:

* https://github.com/rwjblue/release-it-lerna-changelog/blob/a550ef00994b4df0b0f6ed72f46bb48098e4dd01/package.json#L47-L52
* https://github.com/rwjblue/release-it-lerna-changelog/blob/a550ef00994b4df0b0f6ed72f46bb48098e4dd01/cjs-wrapper.cjs#L5-L19

**Comment by rwjblue** [comment]
> Note that release-it v15 is not compatible with plugins published in CommonJS.

Why is this? It isn't obvious why we can't just `import()` the CJS versions as needed? Are the specific APIs for the plugin different in any way?

**Comment by rwjblue** [comment]
I absolutely might be missing something, but from a quick review of the loading code changes here:

https://github.com/release-it/release-it/blob/fe1c8cd2843f7d54a1c5b960876df7de70cddf8b/lib/plugin/factory.js#L24-L41

A CJS only plugin could support both v14 and v15 via something:

```js
module.exports = class MyPlugin extends Plugin {
  // supports unwrapping of `.default` that is done in release-it@15+
  static get default() {
    return this;
  }
  
  // other plugin code here
};
```

Alternatively, the loading code could do something like `plugin = 'default' in module ? module.default : module`.

🤔

**Comment by webpro** [comment]
Thanks for chiming in, @rwjblue. Great question too, I forgot to mention **why** indeed. Importing a CJS plugin from release-it (ESM) as you mention is indeed not an issue (it already works). However, the CJS plugin also needs to import "back" from release-it (ESM), to extend the `Plugin` class:

```
const { Plugin } = require('release-it');
class ConventionalChangelog extends Plugin {}
```

Example/shortened error message:

> ERROR require() of ES Module [...]/release-it/lib/index.js from [...]/node_modules/@release-it/conventional-changelog/index.js not supported.
Instead change the require of [...]/release-it/lib/index.js in [...]/node_modules/@release-it/conventional-changelog/index.js to a dynamic import() which is available in all CommonJS modules.


Not sure how to circumvent this 🤔 Any ideas welcome, obviously 😅

**Comment by jairhenrique** [comment]
I got an error when try to get config.

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/config' is not defined by "exports" in /Users/jairs/dev/boti/news-fragments/node_modules/release-it/package.json imported from /Users/jairs/dev/boti/news-fragments/src/config.js
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
    at packageResolve (node:internal/modules/esm/resolve:853:14)
    at moduleResolve (node:internal/modules/esm/resolve:910:18)
    at defaultResolve (node:internal/modules/esm/resolve:1005:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:475:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:245:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```


https://github.com/grupoboticario/news-fragments/blob/main/src/config.js#L1

**Comment by j-ulrich** [comment]
> Let me know if you have any questions, issues or concerns.

I'm already trying to migrate to ESM but I am having trouble with dependency mocking for the tests. It seems that at the moment the only library that supports mocking native ESMs is [testdouble](https://github.com/testdouble/testdouble.js). I will give it a try...

**Comment by webpro** [comment]
> > Let me know if you have any questions, issues or concerns.
> 
> I'm already trying to migrate to ESM but I am having trouble with dependency mocking for the tests. It seems that at the moment the only library that supports mocking native ESMs is [testdouble](https://github.com/testdouble/testdouble.js). I will give it a try...

Yes, in general ESM and mocking dependencies are not a great deal. However, actually using un-mocked dependencies for me works even better in many cases (YMMV, of course). For instance, the conventional-changelog plugin made this move.

**Comment by j-ulrich** [comment]
I managed to migrate [release-it-regex-bumper](https://github.com/j-ulrich/release-it-regex-bumper) to ESM. I had to replace my mocking libraries (rewiremock and mock-fs) with testdouble.js for the tests but then it worked.
So the plugin is ready and I will release a new major version supporting release-it 15.x when the final 15.0.0 version is released.

**Comment by webpro** [comment]
Heads up: issues have been solved and plugins have been prepared for ESM (and ESM only). The plan is to skip support for Node.js v12 as it's EOL, so release-it v15 will only support ESM and Node.js v14+, scheduled to be released around the Node.js v12 EOL date: 2022-04-30.

**Comment by webpro** [comment]
All plugins and release-it itself have been updated with a major bump and ES Modules only.

Any plugin that's not ready/compatible yet should mark release-it v14 as a `peerDependency`.

I'm going to close this one, but feel free to open new issues or PRs if you encounter any issues. Thanks!

**Comment by ath0mas** [comment]
Great job!
Could you please update [release-it/plugin-starterkit](https://github.com/release-it/plugin-starterkit) too?

**Comment by webpro** [comment]
Thanks @ath0mas. The behavior you describe is in my opinion a problem with Node.js' `require()`. Everyone can import anything they want, including internal/private modules that were not part of the public API. So, imho this internal code should not have been imported in the first place.

However, if you feel there is code that should be made public, feel free to open a PR, happy to review/discuss.
