### ISSUE TITLE
GitHub release body text is overwritten

### ISSUE THREAD

**Issue by klauss42** [release-it/release-it#860]
Hi
I use release-it to create a Github pre-release including changelog. This works fine, the Github Release has nice changelog content .
Later I promote the release to a final release using --github.update, but then the changelog in the body text of the Github release gets overwritten by empty string.

I think this is a bug introduced by commit bdbc2ca8369dd112427697af2371f7abfa062c68

Thanks 
Klaus

**Comment by webpro** [comment]
Thanks for the report, that should not happen indeed. Two questions here:

- I assume you did see this work properly before?
- I also assume you used the `--github.autoGenerate` flag with the `--github.update`?

**Comment by klauss42** [comment]
Hi, 
yes, it worked properly before. Currently I use an older version v14.12.1 to workaround the issue. 

I use --github.update but not --github.autogenerate. I use release-it for a 2-step release process with Github releases:

pre-release: release-it --ci --github.preRelease --git.requireCommits
final release: release-it --ci --no-increment --no-git --github.release --github.update

**Comment by webpro** [comment]
Thanks. I was asking, since #855 complicates matters :)

**Comment by webpro** [comment]
Should be fixed in [v14.12.5](https://github.com/release-it/release-it/releases/tag/14.12.5)
