### ISSUE TITLE
Exposure of Sensitive Information to an Unauthorized Actor

### ISSUE THREAD

**Issue by nbouvrette** [release-it/release-it#862]
It looks like the dependency `"@octokit/rest": "18.12.0"` uses `"node-fetch": "^2.6.1"` which has a high risk vulnerability.

That package has not been updated since October last year and I am not sure that updating to `node-fetch` > 3.1.1 will not cause breaking changes. I open an issue in their repo if this helps: https://github.com/octokit/request.js/issues/448

```sh
node-fetch  <3.1.1
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
```

I tried to fix it with an `npm audit fix --force` but it doesn't seem to work.

**Comment by nbouvrette** [comment]
Maybe it would be worth considering replacing Octokit? This is the second week in a row I am getting flagged because I am using `release-it` :( 

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/6453322/150650478-f0f58337-b020-4fbb-aa77-988d75e7e80d.png">

https://github.com/octokit/request.js/issues/448#issuecomment-1019324612

> But, the octokit modules are unmaintained.

**Comment by webpro** [comment]
Thanks for raising this, @nbouvrette. Let's see how the situation with Octokit will develop (it's not trivial to replace).
