### ISSUE TITLE
How to get variables escaped when using a cli to pass hook options

### ISSUE THREAD

**Issue by simple-beck** [release-it/release-it#865]
`npx release-it --hooks.after:release="echo Successfully released ${name} v${version} to ${repo.repository}."`

This would just strip off the variables part as arguments get passed to the module. I tried escaping using single quotes -> nothing helps. I would appreciate if someone has a working solution

**Comment by webpro** [comment]
This seems to work:

```
npx release-it --'hooks.after:release="echo Successfully released ${name} v${version} to ${repo.repository}."'
```

So single-quote the argument as a whole. It isn't pretty indeed! Better suggestions are welcome of course. By the way, release-it uses [yargs-parser](https://www.npmjs.com/package/yargs-parser) for this, but it doesn't mention colons.
