### ISSUE TITLE
Github Serverless Function Failing

### ISSUE THREAD

**Issue by dbibbens** [release-it/release-it#874]
I authorized Github to allow release-it plugin. and tried to re-run getting the following.

![Screen Shot 2022-03-06 at 12 17 40 PM](https://user-images.githubusercontent.com/1612247/156934369-e850c68b-bddd-4f13-b378-b0f426496d11.png)
e

**Comment by webpro** [comment]
I have absolutely no idea what I could say or do with this information. Please open an issue with debug logs or something (see e.g. https://github.com/release-it/release-it/blob/master/README.md#troubleshooting--debugging)
