### ISSUE TITLE
Clearer documentation for GitHub Enterprise

### ISSUE THREAD

**Issue by geotrev** [release-it/release-it#875]
Hello there,

I'm using `release-it` on GH Enterprise and noticed there [isn't very clear documentation](https://github.com/release-it/release-it/blob/master/docs/github-releases.md#host) on how to set a configuration for it.

My GHE instance uses a non-github URL, so based on the [sourcecode](https://github.com/release-it/release-it/blob/master/lib/plugin/github/GitHub.js#L158), would this be correct?

```json
{
  "release-it": {
    "github": {
      "host": "private.source.com"
    }
  }
}
```

Which results in `https://private.source.com/api/v3`.

If this looks right, I'm happy to make a PR that specifies the right keys in the README or github release doc. Right now there's no mention of them as far as I can tell, except by source code and looking at the base config schema in `config/.release-it.json`.

Thanks!

**Comment by webpro** [comment]
Just add 6d7c3f2c143185a77e3f46d885bf4e489571da97

Does this help? Happy to receive a PR for anything else that's not clear :)

**Comment by geotrev** [comment]
That's great, thank you!
