### ISSUE TITLE
Github action release to npm not working

### ISSUE THREAD

**Issue by The-Code-Monkey** [release-it/release-it#876]
I'm having issues with using release it from the github action, ive followed the docs but can't seem to get it to work keep getting errors such as this doesnt exist in the registry when it already does.

https://github.com/The-Code-Monkey/tcm-cli/runs/5497045006?check_suite_focus=true

**Comment by The-Code-Monkey** [comment]
@webpro I have tried by adding it to my publishConfig and that doesnt help i got this.

https://github.com/The-Code-Monkey/Components/runs/5692556767?check_suite_focus=true 

Should i try to do npm access instead inline.

**Comment by webpro** [comment]
Does a manual `npm publish` from your own machine work properly?

**Comment by The-Code-Monkey** [comment]
yeah manual works from my machine, i did one this morning. the only difference is that its on the github ci

**Comment by The-Code-Monkey** [comment]
the strange this is that it says not found yet when you click the link it is there with version 0.2.32

**Comment by webpro** [comment]
The `publishConfig` should be in `package.json`.

Seeing a 404 to https://registry.yarnpkg.com/@aw-web-design%2fcomponents is it even the correct registry? Should the `/` be encoded?

**Comment by The-Code-Monkey** [comment]
oh it is on npm how come it trying to release to yarn, how do i change that?

**Comment by The-Code-Monkey** [comment]
the publish config is in my package json file though

**Comment by The-Code-Monkey** [comment]
https://github.com/The-Code-Monkey/Components/runs/5693224809?check_suite_focus=true

ok so i have got it pointing at npm instead but im still getting the error of not in the registry.

**Comment by The-Code-Monkey** [comment]
Is there a working example of deploying a package to npm via github actions anywhere? All the examples listed on the docs are for local command line use

**Comment by webpro** [comment]
Yes, it's in the CI section: https://github.com/release-it/release-it/blob/master/docs/ci.md#github-actions

Seeing plenty of folks using release-it from GitHub Actions (you can search here in issues).

Going to close this issue, as I'm not sure what I could add here.
