### ISSUE TITLE
Enhance requireBranch to support wildcards

### ISSUE THREAD

**Issue by jasongerbes** [release-it/release-it#877]
The `requireBranch` config option currently supports a string (e.g. `'main'`), or an array of strings (e.g. `['main', 'develop']`).

It would be great if this could be enhanced to support wildcards, for example: `['main', 'support/*']`.

**Comment by webpro** [comment]
Good idea! Nice & easy to implement, it's in [v14.13.0](https://github.com/release-it/release-it/releases/tag/14.13.0)

**Comment by jasongerbes** [comment]
Thanks @webpro!
