### ISSUE TITLE
Issues authenticating with Yarn

### ISSUE THREAD

**Issue by ctjlewis** [release-it/release-it#880]
Trying to run `yarn release` does not work, and the program says I'm not authenticated despite being logged into Yarn and NPM.

`npm run release` works, but `yarn release` throws. Any ideas as to how to resolve this?

**Comment by ctjlewis** [comment]
Closed by same fix in https://github.com/release-it/release-it/issues/879.

**Comment by ctjlewis** [comment]
```json
"scripts": {
    "release": "release-it"
}
```

```shell
$ yarn release-it minor --release-version

ERROR Not authenticated with npm. Please `npm login` and try again.
Documentation: https://git.io/release-it-npm
```

```shell
npm run release -- minor --release-version

> @tsmodule/tsmodule@30.0.6 release
> release-it "minor" "--release-version"
30.1.0
```

**Comment by webpro** [comment]
Yeah, release-it uses `npm` under the hood exclusively (also to `npm publish`). You could try `--npm.skipChecks`, though. Also make sure to set the correct `publishConfig.registry`?
