### ISSUE TITLE
Not being prompted for 2FA

### ISSUE THREAD

**Issue by Saeris** [release-it/release-it#881]
When running `release-it`, everything appears to work fine until trying to publish to NPM, at which point I'm not prompted to enter an OTP, resulting in the publish failing. Tried using the `--npm.otp` flag, but this didn't work either. Here's a sample from my terminal:

```bash
PS C:\Users\drake\GitHub\@saeris\eslint-config> yarn release

🚀 Let's release @saeris/eslint-config (2.0.2...2.1.0)


Changelog:
## [2.1.0](https://github.com/saeris/eslint-config/compare/v2.0.2...v2.1.0) (2022-03-20)


### Features

* Add Next config, Upgrade to Yarn 3, Upgrade Dependencies ([8769866](https://github.com/saeris/eslint-config/commit/8769866543c935748be198a027c68394a3b19169))
* Remove Yarn PNP, upgrade dependencies ([c3d1a19](https://github.com/saeris/eslint-config/commit/c3d1a19353d5776847701abff32d4a9bdcbd165e))      


Changeset:
A  CHANGELOG.md
 M package.json

? Publish @saeris/eslint-config to npm? Yes
ERROR npm notice
npm notice 📦  @saeris/eslint-config@2.1.0
npm notice === Tarball Contents ===
npm notice 1.1kB  LICENSE
npm notice 2.5kB  README.md
npm notice 3.0kB  package.json
npm notice 791B   src/__tests__/eslint-config.spec.ts
npm notice 37.1kB src/base.js
npm notice 301B   src/index.js
npm notice 5.6kB  src/jest.js
npm notice 2.5kB  src/next.js
npm notice 20.2kB src/react.js
npm notice 8.2kB  src/type-aware.js
npm notice 17.7kB src/typescript.js
npm notice name:          @saeris/eslint-config
npm notice version:       2.1.0
npm notice filename:      @saeris/eslint-config-2.1.0.tgz
npm notice package size:  14.7 kB
npm notice unpacked size: 99.0 kB
npm notice shasum:        863fba4dd805233fbbaf1d6dc8c2193841b5a9e3
npm notice integrity:     sha512-Dn4zSOiTW2QAO[...]sB+9/Kj9Tmrwg==
npm notice total files:   11
npm notice
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/@saeris%2feslint-config - This package requires that publishers enable TFA and provide an OTP to publish. For more info, visit: https://go.npm.me/2fa-guide
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\drake\AppData\Local\npm-cache\_logs\2022-03-20T18_31_35_336Z-debug.log

Rolling back changes...
PS C:\Users\drake\GitHub\@saeris\eslint-config> npm whoami
saeris
```

I verified that I was logged into npm with `npm whoami` as you can see in the log. Made sure to login with both `npm` and `yarn` just in case that would have been an issue. Ran the command from PowerShell inside of VSCode running on Windows 10. I'm using yarn v3.2 for my package manager without pnp (so same module resolution as yarn 1/npm).

Was hoping to migrate to `release-it` from `np`, since `np` won't add yarn 2/3 support.

And minor gripe, it would be great if `release-it` would roll-back all changes on failure (undo version bump, changelog creation, etc). In trying to get this set up I have to manually reset my working directory each time.

I think until a fix can be found, I can skip npm publishing and do that manually. I'm not ready to set up automated releases via ci until I can verify that everything behaves the way I'd like it to first.

**Comment by Saeris** [comment]
I'm not sure if npm/cli#4519 is related, but I can't seem to manually publish either, as it won't prompt me for 2FA there either.

Why does package publishing have to be so hard all the time? 😭

**Comment by webpro** [comment]
Bug regarding 2FA noted.

> `Rolling back changes...`

This actually works pretty well for me, sorry to hear it does not for you. It only reverts on a Git level.

By the way, release-it doesn't officially support yarn, it uses npm under the hood exclusively. I did explore this territory before (#737 and #744), but as I'm not a yarn/pnpm user myself I don't actually feel very comfortable to start supporting this.
