### ISSUE TITLE
Add dotenv prefix publishing --preRelease command does not take effect

### ISSUE THREAD

**Issue by jhw621** [release-it/release-it#884]
Package. json is configured as follows:
"scripts": {
    "release:beta": "dotenv release-it major --preRelease=beta",
  },

If dotenv is added to the prefix, the release does not preRelease=beta. Instead, patch is added to the prefix to get the desired beta. Why?

**Comment by webpro** [comment]
Because you're missing two dashes (`--`), please see here: https://github.com/release-it/release-it/blob/6164e54a06006769ff7f5082b8fb90e3a6e1e315/docs/environment-variables.md#dotenv
