### ISSUE TITLE
Corrupted release-it.svg animation on Firefox

### ISSUE THREAD

**Issue by cas--** [release-it/release-it#894]
I just found that when viewing the Readme on Firefox the release-it.svg animation is corrupted. I have not looked into any solution for it and likely needs reporting upstream to Firefox but thought you might be able to fix it so that the Readme looks good again for Firefox visitors :smile: 

<img width="276" alt="image" src="https://user-images.githubusercontent.com/606038/163796861-67c1ee6f-aa7a-4367-ae7c-da6d82657749.png">

**Comment by webpro** [comment]
Are you looking at this from the github.com website? Looks fine for me:

<img width="1143" alt="Screen Shot 2022-04-18 at 8 06 34 AM" src="https://user-images.githubusercontent.com/456426/163799892-81ae2bf5-f32c-45d8-bde6-cd0a98273631.png">

**Comment by cas--** [comment]
Hmm how interesting, perhaps a Firefox for Linux issue? I have tested on both my laptops that run Ubuntu 20.04.

<img width="169" alt="image" src="https://user-images.githubusercontent.com/606038/163801144-76f171b0-55b8-4eec-b959-f848e2b9d13d.png">

**Comment by webpro** [comment]
Maybe it's caused by the deprecated `xlink:href` attribute, which I should get rid of anyway. Will do shortly!

**Comment by cas--** [comment]
Checked in Windows 10 VM and animation looks okay so Linux only issue :roll_eyes: 

Thanks for looking into it

**Comment by webpro** [comment]
I've removed the `xlink` namespace from the image, could you please verify on Linux if the issue is no longer visible?

**Comment by cas--** [comment]
So after further investigation it is a Firefox profile minimum font size issue which I set it to fix Linux hidpi font scaling issues on both laptops. Here is the upstream issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1677988

This is rather obscure so you might want to close this issue but for reference adding `font-size` attribute to every `text` element is one workaround that works: 

```diff
-<text y="1.67" class="e">⠋</text>
+<text font-size="1.67" y="1.67" class="e">⠋</text>
```

**Comment by webpro** [comment]
Yeah feels like quite an edge case, thanks for reporting though! Feel free to submit a fix.
