### ISSUE TITLE
globs in asset names not expanding during dry-run

### ISSUE THREAD

**Issue by guillaumeboehm** [release-it/release-it#898]
A minor issue, the glob expansion works fine in normal run but not in dry run, it still shows 'whatevername${version}' which is a little bit confusing,

**Comment by webpro** [comment]
Thanks @guillaumeboehm! The placeholders (such as `${version}` were never replaced in this message, also not in an actual run. Should be fixed in [v15.1.2](https://github.com/release-it/release-it/releases/tag/15.1.2).
