### ISSUE TITLE
GitLab release support for special assets `Links`

### ISSUE THREAD

**Issue by anb0s** [release-it/release-it#900]
Is it possible to add Link(s) as asset via release-it?

![image](https://user-images.githubusercontent.com/95811/168863659-a9b92790-0e64-414a-8fbe-ae3c9d88eb0f.png)

**Comment by webpro** [comment]
Yes: https://github.com/release-it/release-it/blob/master/docs/gitlab-releases.md#attach-binary-assets

**Comment by anb0s** [comment]
thanks, i know about "normal" assets, i'm asking about special assets called `Links` here:
![image](https://user-images.githubusercontent.com/95811/168901837-2cd24f40-5e34-4f55-9798-d31c2321c9c9.png)

they are shown then as `Other` etc.
![image](https://user-images.githubusercontent.com/95811/168901870-3b27a0dc-8fb7-4776-a3ba-6cba0ddeca58.png)

**Comment by webpro** [comment]
Right, well, no then. Feel free to open a PR for this, let me know if you need any help.

**Comment by webpro** [comment]
Seems to be about using the proper `link_type`:

- https://docs.gitlab.com/ee/user/project/releases/index.html#link-types
- https://docs.gitlab.com/ee/api/releases/links.html

Going to close this ticket now due to inactivity, but I would be happy to review a PR for this.
