### ISSUE TITLE
GirLab add assets after release shows `409 (Conflict)`

### ISSUE THREAD

**Issue by anb0s** [release-it/release-it#903]
I'm trying to update an already published GitLab release with assets and found in the docs that it should work with:
```
release-it --no-increment --no-git --gitlab.release --gitlab.assets=*.html
```

I'm facing this error:
```
- GitLab upload assets
✔ GitLab upload assets
- GitLab release
✖ GitLab release
ERROR Response code 409 (Conflict)
```

There are not such assets (`*.html`) files in the release, just the automatic ones:
![image](https://user-images.githubusercontent.com/95811/169363445-87a00320-d78c-4323-a436-b6b9dd3bdd51.png)

Any idea how to debug this?

**Comment by webpro** [comment]
I'm missing the `--github.update` flag, did you try that?

To debug:

```
NODE_DEBUG=release-it:* release-it [...]
```

**Comment by webpro** [comment]
Ah that was the confusion, the docs of GitLab and GitHub are different.

But, even more confusingly, the GitLab plugin does not have this update feature in its implementation and there are also no tests for this. Probably best to assume this isn't going to work in the GitLab plugin. Sorry! Let's keep this ticket open, I'll either fix up the docs or the implementation soon.
