### ISSUE TITLE
Versions 15 and higher break non-esm projects 

### ISSUE THREAD

**Issue by markcellus** [release-it/release-it#909]
I've noticed versions 15+ of the package are enforcing ESM usage. But it breaks projects that are using [release-it programmatically](https://github.com/release-it/release-it/blob/14.14.3/docs/recipes/programmatic.md) and have not/can not yet upgrade their projects to ESM.

I realize ES modules are the future, but many projects still need time to upgrade to them.

Is the idea for this package to no longer support non-esm usage? Thanks for any information.

**Comment by webpro** [comment]
Yes, this was the breaking change of v15: https://github.com/release-it/release-it/blob/master/CHANGELOG.md

However, v14 still has the same features, and I'm happy to accept bug fixes in that range too.

**Comment by markcellus** [comment]
Sure, but our org now has over 50 projects that are not yet esm that are depending on this package. These projects also have auto-upgrade mechanisms like Dependabot that upgrades the deps automatically.

To get around this, we'd have to somehow force projects not to use any version 15 or higher which unfortunately isn't so easy to do. Especially since we also have a custom library that also depends on release-it.

We'll probably have to just move off of release-it entirely and move forward with a fully custom solution if we can't rely on future versions of release-it.

Is there no way you can provide a CJS version of the project alongside an ESM version? I've done this on my open source packages.

**Comment by webpro** [comment]
Sorry, but I'm not very interested in maintaining a [dual package hazard](https://nodejs.org/api/packages.html#packages_dual_package_hazard). This is also [problematic in (release-it) plugins](https://github.com/release-it/release-it/issues/859#issuecomment-1015899664). Better to be upfront and strict about the module system.

Major bumps allow for breaking changes, this is pretty common. In this very project, I had to defer upgrades of [many ESM-only packages](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) that did the same in the last year or so, until release-it itself was ESM-only as well. And now that Node.js v12 is EOL, and TypeScript started supporting ESM, release-it isn't the first project to make this move.

**Comment by markcellus** [comment]
Supporting both esm and cjs isnt uncommon and the packages I've built and used have never led to any of the hazards you link to. However, I do see how they can happen, depending on how consumers use them. 

Node versions have little to do with package implementations. Just because Node 12 is at EOL doesnt mean that CJS isnt still used.  

It doesnt seem like there's any regard here for projects that havent transitioned to ESM yet. So we'll just fork it and start building a custom solution from there or start moving off of the package. Thanks for the information.

**Comment by markcellus** [comment]
Just spoke with a colleague and it probably makes more sense to fork this package solely for CJS support, until dependents can move over to ESM. So I've created and published [`release-it-cjs`](https://www.npmjs.com/package/release-it-cjs). I'll happily pull in any bug fixes you make to 14.x. In the meantime, I'll just have our org move over to using it.

**Comment by webpro** [comment]
Thanks @markcellus!
