### ISSUE TITLE
got vulnerability, through update-notifier

### ISSUE THREAD

**Issue by rlsf** [release-it/release-it#915]
update-notifier v5.1.0 depends indirectly on got v9.6.0, which had an identified vulnerability, as described here:
https://security.snyk.io/vuln/SNYK-JS-GOT-2932019

please update release-it dependency of update-notifier to v6.0.0, which depends on a non-vulnerable version of got.
i've opened a PR with this fix: #914 

on a side note, it looks like tests rely on @webpro  running them.

**Comment by webpro** [comment]
Closed by #914
