### ISSUE TITLE
Usage with Yarn

### ISSUE THREAD

**Issue by cravend** [release-it/release-it#919]
Hi! I've been using release-it for a couple weeks now, so far I've really enjoyed it. However, I recently realized that the flags described in issue #737 _weren't_ actually implemented into master — the branch: https://github.com/release-it/release-it/compare/feature/yarn-pnpm was never merged in.

Is there any reason that this can't be merged? Right now, I don't see a way to use `yarn npm publish` at all (I'm on yarn berry but I don't even see documentation for Yarn v1).

P.S: I would be willing to clean up this branch/fix merge conflicts/etc if you're still willing to support this feature :)

**Comment by cravend** [comment]
I've been playing around with the previous feature branch trying to resolve merge conflicts. The biggest issue so far is updating the tests to be ESM-compliant. 

What exactly would maintaining the Yarn feature entail?

**Comment by webpro** [comment]
> I've been playing around with the previous feature branch trying to resolve merge conflicts. The biggest issue so far is updating the tests to be ESM-compliant.

Maybe it would take less efforts to re-implement (copy-paste) features in the current v15 master branch.

> What exactly would maintaining the Yarn feature entail?

Help out with at least issues concerning Yarn and/or fixing bugs and consider feature requests for the Yarn part(s). You could become a maintainer of this repository (or whatever role is necessary).
