### ISSUE TITLE
Package.json exports field defines extensionless export that errors in pure ESM environments

### ISSUE THREAD

**Issue by scalvert** [release-it/release-it#920]
The fixed export of `release/test/util` in #539 helped consumers access the test utils again (thank you!). Using an extensionless export, however, has complicated compatibility across multiple `release-it` versions. Pure ESM `release-it` plugins, when testing using `ava`, will error with extensionless sub-paths. 

https://github.com/rwjblue/release-it-lerna-changelog/runs/7347409577?check_suite_focus=true

```shell
> release-it-lerna-changelog@4.0.1 test /home/runner/work/release-it-lerna-changelog/release-it-lerna-changelog
> ava
  Uncaught exception in test.js
  Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/home/runner/work/release-it-lerna-changelog/release-it-lerna-changelog/node_modules/release-it/test/util' is not supported resolving ES modules imported from /home/runner/work/release-it-lerna-changelog/release-it-lerna-changelog/test.js
  Did you mean to import release-it-lerna-changelog/release-it-lerna-changelog/node_modules/release-it/test/util/index.js?
  ✖ test.js exited with a non-zero exit code: 1
```

The Node documentation [encourages the use of extension-based exports when those exports point to a single file](https://nodejs.org/api/packages.html#subpath-exports), as is the case here. I've tested converting the package's exports to use an extension instead of a sub-path, and it ensures correct compatibility across `release-it` versions 14-latest (15.1.1). 

Change:

```json
  "exports": {
    ".": "./lib/index.js",
    "./test/util/index.js": "./test/util/index.js"
  },
```

If you'd be open to it, I'll open a PR making that change in the latest version.

**Comment by webpro** [comment]
Thanks @scalvert. Agreed, just patched it in [v15.1.2](https://github.com/release-it/release-it/releases/tag/15.1.2). Since it's a test util I consider this not a breaking change.
