### ISSUE TITLE
Build error in react-native projects

### ISSUE THREAD

**Issue by mlecoq** [release-it/release-it#923]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `release-it@15.1.3` for the project I'm working on.

I have the following error while building a `react-native` project 

Invalid `Podfile`  unexpected token at 'Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/expo/workingdir/build/node_modules/release-it/package.json

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/release-it/package.json b/node_modules/release-it/package.json
index 0c43af1..f40c285 100644
--- a/node_modules/release-it/package.json
+++ b/node_modules/release-it/package.json
@@ -38,6 +38,7 @@
   "type": "module",
   "exports": {
     ".": "./lib/index.js",
+    "./package.json": "./package.json",
     "./test/util/index.js": "./test/util/index.js"
   },
   "files": [
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

If you agree with this change I will make a PR

**Comment by webpro** [comment]
Alright, it's in [v15.2.0](https://github.com/release-it/release-it/releases/tag/15.2.0)
