### ISSUE TITLE
Scoped plugin names break context lookup

### ISSUE THREAD

**Issue by scalvert** [release-it/release-it#925]
When updating/renaming our plugins, `release-it-yarn-workspaces` and `release-it-lerna-changelog`, to their new scoped variants, `@release-it-plugins/workspaces` and `@release-it-plugins/lerna-changelog`, our [context lookups are broken](https://github.com/release-it-plugins/workspaces/issues/80). It appears that `release-it` seemingly intentionally (but maybe inadvertently) [strips the scope off the plugin's name](https://github.com/release-it/release-it/blob/ce3a7266b9fe5c6560f31fbf9e3c867de992c652/lib/plugin/factory.js#L40).

It's unclear why it does this. @webpro - is there a reason why plugin names are mutated like this when loading?

**Comment by webpro** [comment]
Not sure, to be honest, other than that it's over 2 years ago and maybe I didn't like `@` and `/` in object keys or something.

Thanks for the fix!
