### ISSUE TITLE
Config to not bump version but do publish and tagging

### ISSUE THREAD

**Issue by k2snowman69** [release-it/release-it#927]
I've got a ton of custom code on my side that I'd love to see if I can replace with `release-it`. Our projects aren't using semantic commit which means we need to manually bump the version, however the rest is automated since we're using semver. For example

1. On your local machine, create a new branch `release-new-beta`
1. Locally run `npm version 1.0.2-beta.1`
   - This updates the changelog, package.json and package-lock.json
1. Push this branch to origin, create a PR, get sign off
1. Merge the PR into main
   - This starts the CI pipeline. The rest of the steps are in context of the CI pipeline
1. The CI pipeline "detects" the version in the package.json hasn't been published
   - Currently does this by comparing the version in package.json against npm registry. Open to changing this to be git tags instead or something else
1. Calculates the "dist-tag" by parsing the version in the package.json and returning either prerelease which in this example would be `beta` or `latest` if no prerelease tag is found
1. Runs npm publish --tag {prerelease}
1. Creates and pushes a new git tag to main

So taking the items out of your readme I've crossed out the items I think I want to turn off:

- ~~Bump version (in e.g. `package.json`)~~
- [~~Git commit~~, tag, push](#git)
- ~~Execute any (test or build) commands using [hooks](#hooks)~~
- [Create release at GitHub](#github-releases) or [GitLab](#gitlab-releases)
- ~~[Generate changelog](#changelog)~~
- [Publish to npm](#publish-to-npm)
- [Manage pre-releases](#manage-pre-releases)

Hopefully that made sense and hopefully you can help reduce my custom code!

**Comment by webpro** [comment]
Not sure what you're asking for. You're free to use any part of release-it that fits in your workflow. You could do everything you mention from a single configuration, or just a small part of it. Got a config you're trying out or something?

**Comment by k2snowman69** [comment]
Let me try to explain it a different way:
 - I want to manually perform the git commit for the version and change-log updates
 - Have release-it perform a npm publish (no version bump required), git tags, etc

Here's the config I got to:

```
module.exports = {
  increment: false,
  git: {
    commit: false,
    changelog: false,
  },
};

```

And the command I've been testing with:

```
npx release-it --ci --dry-run
```

This actually worked other than the git tag:
 - Not marking beta versions as pre-release
 - Not containing the changelog contents for that version

So getting closer...

**Comment by k2snowman69** [comment]
Awesome, the last bit of work for me is to find a tool that I can override `git.changelog` to read from the existing changelog instead of generating it from the git log. You've documented how to do that, I just have to search, closing this out as I eventually got there! It did take me a long time to be honest.

If I can come up with some suggestions to organize the docs that would have helped, I'll let you know!
