### ISSUE TITLE
No push tag and no push to remote repository.Please help me how to solve it

### ISSUE THREAD

**Issue by xsj114** [release-it/release-it#929]
![image](https://user-images.githubusercontent.com/33807441/183630871-910ca9d2-301d-45b7-8d50-f9fb9537fc78.png)

**Comment by webpro** [comment]
Looks like a dry run? That doesn't write or push anything.

**Comment by xsj114** [comment]
> Looks like a dry run? That doesn't write or push anything.

Thanks, I removed dry run and he can publish normally.

**Comment by webpro** [comment]
Alright
