### ISSUE TITLE
Security issue: GHSA-vp56-6g26-6827

### ISSUE THREAD

**Issue by nbouvrette** [release-it/release-it#930]
I previously opened a PR to update `node-fetch` which you already did in https://github.com/release-it/release-it/commit/ae9ccb9d28d48f88681d455a44a66a794c066f3f. 

But in order to fix this issue, we need a new `release-it` version!

**Comment by webpro** [comment]
Yes! It's in [v15.3.0](https://github.com/release-it/release-it/releases/tag/15.3.0). Thanks for the report :)
