### ISSUE TITLE
[github] repo names with periods are not respected

### ISSUE THREAD

**Issue by timmywil** [release-it/release-it#931]
At first, I thought my issue was the same as https://github.com/release-it/release-it/issues/908, but I think I know what's going on.

My repo has a name with a period, named after the domain, like "example.com". The GitHub plugin doesn't seem to like this and strips the period and everything after it when constructing the repo name. So, not only does the initial collaborator check fail (which logs "org/example" instead of "org/example.com" btw), it passes every step except the github release step to post release notes, which just errors with 

![image](https://user-images.githubusercontent.com/192451/183975160-e8459f75-3c6b-4829-a5fb-e9f901b6dbed.png)

Edit: after further research, I see you're using `git-url-parse`. I passed my git url through that and that does seem to be the source of the problem. I've also opened [an issue there](https://github.com/IonicaBizau/git-url-parse/issues/143). It's not just the period. It's the combination of the period in the name *and* the URL format (`git@github.com:org/example.com.git`), which is the default recommendation on GitHub for remote URLs.

**Comment by timmywil** [comment]
The associated issue in git-url-parse has been fixed. All that's left is to update to version 13 in release-it.

**Comment by webpro** [comment]
Thanks @timmywil, the updates (and unfortunately some fixes) are in [v15.4.1](https://github.com/release-it/release-it/releases/tag/15.4.1)
