### ISSUE TITLE
Access dry run config inside hook

### ISSUE THREAD

**Issue by JVarghese99** [release-it/release-it#935]
Hello,
Sorry, this is not an issue but more of a question.
Is there a way to access the dry-run flag in the hooks?
I want to do something similar to
`'after:bump': 'if [ "$DRY_RUN" != "true" ]; then git push; fi',`

Btw, thanks for the great docs

regards,
John

**Comment by webpro** [comment]
Well, the irony here is that commands are not even executed in a dry run, so it would not matter.

For completeness sake, the configuration is available in hooks. E.g.:

```json
{
  "hooks": {
    "before:init": "if [ ${verbose} ]; then echo \"CI: ${ci}\"; else echo \"Prerelease: ${version.isPreRelease}\"; fi;"
  }
}
```
