### ISSUE TITLE
assets could not being find

### ISSUE THREAD

**Issue by tiagoporto** [release-it/release-it#937]
Hello, first of all, nice library, thanks.

I'm trying to publish some assets with new releases using github actions,  but it's not working.

```
WARNING octokit repos.uploadReleaseAssets: did not find "./builds/*.dmg" relative to /runner/_work/desktop-app/desktop-app
```

As we can see in the print the folder builds exist.

![image](https://user-images.githubusercontent.com/3688905/189972968-9c503f6b-9de6-4b45-a634-05ee5d400e13.png)

```json
// .release-it.json

{
  "hooks": {
    "before:init": " if [ -d 'builds' ]; then ls builds/; else ls; fi",
    "after:release": "ls ./builds/"
  },
  "git": {
    "commitMessage": "chore(release): ${version}",
    "tagName": "v${version}",
    "tag": false,
    "push": false
  },
  "github": {
    "releaseName": "v${version}",
    "release": true,
    "draft": false,
    "assets": ["builds/*.dmg"]
  },
  "npm": {
    "publish": false
  },
  "gitlab": {
    "release": false
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": "conventionalcommits",
      "context": {
        "linkCompare": true
      }
    }
  }
}

```

```json
// package.json
  "scripts": {
    "release": "release-it --ci",
},
```

I've tried downgrade release-it lib, without success.

Anything else that I could try?

**Comment by tiagoporto** [comment]
Hi @webpro, this is the output.

```
Run NODE_DEBUG=release-it:* yarn release -VV--preRelease=beta --no-git --verbose
RELEASE-IT:CONFIG 669: {
  cosmiconfig: {
    config: {
      hooks: [Object],
      git: [Object],
      github: [Object],
      npm: [Object],
      gitlab: [Object],
      plugins: [Object]
    },
    filepath: '/runner/_work/desktop-app/desktop-app/.release-it.json'
  }
}
RELEASE-IT:CONFIG 669: {
  system: { 'release-it': '15.3.0', node: 'v16.17.0', os: 'Linux 5.4' }
}
RELEASE-IT:CONFIG 669: {
  _: [],
  verbose: 3,
  git: false,
  increment: undefined,
  ci: true,
  hooks: {
    'before:init': " if [ -d 'builds' ]; then ls builds/; else ls; fi",
    'after:release': 'ls ./builds/'
  },
  github: {
    releaseName: 'v${version}',
    release: true,
    draft: false,
    assets: [ './builds/*.dmg' ],
    releaseNotes: null,
    autoGenerate: false,
    preRelease: false,
    tokenRef: 'GITHUB_TOKEN',
    host: null,
    timeout: 0,
    proxy: null,
    skipChecks: false,
    web: false
  },
  npm: {
    publish: false,
    publishPath: '.',
    publishArgs: [],
    tag: null,
    otp: null,
    ignoreVersion: false,
    allowSameVersion: false,
    skipChecks: false,
    timeout: 10
  },
  gitlab: {
    release: false,
    releaseName: 'Release ${version}',
    releaseNotes: null,
    milestones: [],
    tokenRef: 'GITLAB_TOKEN',
    tokenHeader: 'Private-Token',
    certificateAuthorityFile: null,
    assets: null,
    origin: null,
    skipChecks: false
  },
  plugins: {
    '@release-it/conventional-changelog': { preset: 'conventionalcommits', context: [Object] }
  },
  version: {
    increment: undefined,
    isPreRelease: false,
    preReleaseId: undefined
  }
}
RELEASE-IT:CONFIG 669: {
  '@release-it/conventional-changelog': { preset: 'conventionalcommits', context: { linkCompare: true } }
}
RELEASE-IT:PLUGINS 669: {
  namespace: '@release-it/conventional-changelog',
  options: {
    preset: 'conventionalcommits',
    context: { linkCompare: true },
    tagPrefix: ''
  }
}
RELEASE-IT:PLUGINS 669: {
  namespace: 'npm',
  options: {
    publish: false,
    publishPath: '.',
    publishArgs: [],
    tag: null,
    otp: null,
    ignoreVersion: false,
    allowSameVersion: false,
    skipChecks: false,
    timeout: 10
  }
}
RELEASE-IT:PLUGINS 669: {
  namespace: 'github',
  options: {
    releaseName: 'v${version}',
    release: true,
    draft: false,
    assets: [ './builds/*.dmg' ],
    releaseNotes: null,
    autoGenerate: false,
    preRelease: false,
    tokenRef: 'GITHUB_TOKEN',
    host: null,
    timeout: 0,
    proxy: null,
    skipChecks: false,
    web: false,
    tagName: null,
    tagMatch: null,
    pushRepo: '',
    changelog: 'git log --pretty=format:"* %s (%h)" ${from}...${to}'
  }
}
$  if [ -d 'builds' ]; then ls builds/; else ls; fi
tiago-1.0.0-beta.18-intel64.dmg
tiago-1.0.0-beta.18-intel64.dmg
RELEASE-IT:SHELL 669: {
  command: " if [ -d 'builds' ]; then ls builds/; else ls; fi",
  options: { external: true },
  code: 0,
  stdout: 'tiago-1.0.0-beta.18-intel64.dmg',
  stderr: ''
}
DESKAPP
RELEASE-IT:SHELL 669: {
  command: 'git rev-parse --abbrev-ref HEAD',
  options: { write: false },
  code: 0,
  stdout: 'DESKAPP',
  stderr: ''
}
origin
RELEASE-IT:SHELL 669: {
  command: 'git config --get branch.DESKAPP.remote',
  options: { write: false },
  code: 0,
  stdout: 'origin',
  stderr: ''
}
https://github.com/tiago/desktop-app
RELEASE-IT:SHELL 669: {
  command: 'git remote get-url origin',
  options: { write: false },
  code: 0,
  stdout: 'https://github.com/tiago/desktop-app',
  stderr: ''
}
RELEASE-IT:SHELL 669: { command: 'git fetch', options: {}, code: 0, stdout: '', stderr: '' }
v1.0.0-beta.17
RELEASE-IT:SHELL 669: {
  command: 'git describe --tags --match=* --abbrev=0',
  options: { write: false },
  code: 0,
  stdout: 'v1.0.0-beta.17',
  stderr: ''
}
RELEASE-IT:CONFIG 669: {
  tagTemplate: 'v${version}',
  latestTag: 'v1.0.0-beta.17',
  secondLatestTag: null,
  branchName: 'DESKAPP'
}
RELEASE-IT:@RELEASE-IT/CONVENTIONAL-CHANGELOG 669: {
  increment: undefined,
  latestVersion: '1.0.0-beta.17',
  isPreRelease: false,
  preReleaseId: undefined
}
RELEASE-IT:@RELEASE-IT/CONVENTIONAL-CHANGELOG 669: conventionalRecommendedBump {
  options: {
    preset: 'conventionalcommits',
    context: { linkCompare: true },
    tagPrefix: ''
  }
}
RELEASE-IT:@RELEASE-IT/CONVENTIONAL-CHANGELOG 669: {
  err: null,
  result: {
    level: 2,
    reason: 'There are 0 BREAKING CHANGES and 0 features',
    releaseType: 'patch'
  }
}
RELEASE-IT:@RELEASE-IT/CONVENTIONAL-CHANGELOG 669: conventionalChangelog {
  options: { releaseCount: 1, preset: 'conventionalcommits', tagPrefix: '' },
  context: {
    version: '1.0.0',
    previousTag: 'v1.0.0-beta.17',
    currentTag: 'v1.0.0',
    linkCompare: true
  },
  gitRawCommitsOpts: {
    debug: [Function: logger] { enabled: [Getter] },
    from: 'v1.0.0-beta.17'
  },
  parserOpts: undefined,
  writerOpts: undefined
}
RELEASE-IT:@RELEASE-IT/CONVENTIONAL-CHANGELOG 669: Your git-log command is:
git log --format=%B%n-hash-%n%H%n-gitTags-%n%d%n-committerDate-%n%ci%n------------------------ >8 ------------------------ v1.0.0-beta.17 --no-merges
RELEASE-IT:@RELEASE-IT/CONVENTIONAL-CHANGELOG 669: Your git-log command is:
git log --format=%B%n-hash-%n%H%n-gitTags-%n%d%n-committerDate-%n%ci%n------------------------ >8 ------------------------ v1.0.0-beta.17..HEAD --no-merges
RELEASE-IT:CONFIG 669: {
  name: 'desktop-app',
🚀 Let's release desktop-app (1.0.0-beta.17...1.0.0)
  latestVersion: '1.0.0-beta.17',
  version: '1.0.0',
  changelog: '## [1.0.0](https://github.com/tiago/desktop-app/compare/v1.0.0-beta.17...v1.0.0) (2022-09-13)'
}
RELEASE-IT:CONFIG 669: { version: '1.0.0', isPreRelease: false, preReleaseId: null }
Changelog:
## [1.0.0](https://github.com/tiago/desktop-app/compare/v1.0.0-beta.17...v1.0.0) (2022-09-13)
v1.0.0
RELEASE-IT:SHELL 669: {
  command: 'npm version 1.0.0 --no-git-tag-version',
  options: {},
  code: 0,
  stdout: 'v1.0.0',
  stderr: ''
}
RELEASE-IT:CONFIG 669: { tagName: 'v1.0.0' }
RELEASE-IT:GITHUB 669: {
  owner: 'tiago',
  repo: 'desktop-app',
  tag_name: 'v1.0.0',
  name: 'v1.0.0',
  body: '## [1.0.0](https://github.com/tiago/desktop-app/compare/v1.0.0-beta.17...v1.0.0) (2022-09-13)',
  draft: false,
  prerelease: false,
  generate_release_notes: false
}
request {
  method: 'POST',
  baseUrl: 'https://api.github.com',
  headers: {
    accept: 'application/vnd.github.v3+json',
    'user-agent': 'release-it/15.3.0 octokit-rest.js/19.0.3 octokit-core.js/4.0.4 Node.js/16.17.0 (linux; x64)'
  },
  mediaType: { format: '', previews: [] },
  request: {
    timeout: 0,
    fetch: [AsyncFunction: fetch],
    hook: [Function: bound bound register]
  },
  url: '/repos/{owner}/{repo}/releases',
  owner: 'tiago',
  repo: 'desktop-app',
  tag_name: 'v1.0.0',
  name: 'v1.0.0',
  body: '## [1.0.0](https://github.com/tiago/desktop-app/compare/v1.0.0-beta.17...v1.0.0) (2022-09-13)',
  draft: false,
  prerelease: false,
  generate_release_notes: false
}
POST /repos/tiago/desktop-app/releases - 201 in 533ms
RELEASE-IT:GITHUB 669: {
  url: 'https://api.github.com/repos/tiago/desktop-app/releases/77037359',
  assets_url: 'https://api.github.com/repos/tiago/desktop-app/releases/77037359/assets',
  upload_url: 'https://uploads.github.com/repos/tiago/desktop-app/releases/77037359/assets{?name,label}',
  html_url: 'https://github.com/tiago/desktop-app/releases/tag/v1.0.0',
  id: 77037359,
  author: {
    login: 'tiago-devbot',
    id: 22910544,
    node_id: 'MDQ6VXNlcjIyOTEwNTQ0',
    avatar_url: 'https://avatars.githubusercontent.com/u/22910544?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/tiago-devbot',
    html_url: 'https://github.com/tiago-devbot',
    followers_url: 'https://api.github.com/users/tiago-devbot/followers',
    following_url: 'https://api.github.com/users/tiago-devbot/following{/other_user}',
    gists_url: 'https://api.github.com/users/tiago-devbot/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/tiago-devbot/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/tiago-devbot/subscriptions',
    organizations_url: 'https://api.github.com/users/tiago-devbot/orgs',
    repos_url: 'https://api.github.com/users/tiago-devbot/repos',
    events_url: 'https://api.github.com/users/tiago-devbot/events{/privacy}',
    received_events_url: 'https://api.github.com/users/tiago-devbot/received_events',
    type: 'User',
    site_admin: false
  },
  node_id: 'RE_kwDOGR2clc4El38v',
  tag_name: 'v1.0.0',
  target_commitish: 'master',
  name: 'v1.0.0',
  draft: false,
  prerelease: false,
  created_at: '2022-09-12T21:47:03Z',
  published_at: '2022-09-13T18:31:29Z',
  assets: [],
  tarball_url: 'https://api.github.com/repos/tiago/desktop-app/tarball/v1.0.0',
  zipball_url: 'https://api.github.com/repos/tiago/desktop-app/zipball/v1.0.0',
  body: '## [1.0.0](https://github.com/tiago/desktop-app/compare/v1.0.0-beta.17...v1.0.0) (2022-09-13)'
}
WARNING octokit repos.uploadReleaseAssets: did not find "./builds/*.dmg" relative to /runner/_work/desktop-app/desktop-app
$ ls ./builds/
tiago-1.0.0-beta.18-intel64.dmg
tiago-1.0.0-beta.18-intel64.dmg
RELEASE-IT:SHELL 669: {
  command: 'ls ./builds/',
  options: { external: true },
  code: 0,
  stdout: 'tiago-1.0.0-beta.18-intel64.dmg',
  stderr: ''
}
🔗 https://github.com/tiago/desktop-app/releases/tag/v1.0.0
🏁 Done (in 2s.)
```

**Comment by tiagoporto** [comment]
This is the release 
![image](https://user-images.githubusercontent.com/3688905/189985350-902a882b-1ca3-4ba2-9ed2-b33da4e0a3cd.png)

**Comment by webpro** [comment]
Sorry, but combining `-VV` and `--verbose` resulted in a verbosity level of `3`. Please use only `-VV` as I was looking for the output of this line: https://github.com/release-it/release-it/blob/master/lib/plugin/github/GitHub.js#L287

**Comment by tiagoporto** [comment]
Ops, Sorry, check if there is what you need now

<details>
<summary>debug</summary>

<pre>
Run NODE_DEBUG=release-it:* yarn release -VV --preRelease=beta --no-git
  
RELEASE-IT:CONFIG 642: {
  cosmiconfig: {
    config: {
      hooks: [Object],
      git: [Object],
      github: [Object],
      npm: [Object],
      gitlab: [Object],
      plugins: [Object]
    },
    filepath: '/runner/_work/desktop-app/desktop-app/.release-it.json'
  }
}
RELEASE-IT:CONFIG 642: {
  system: { 'release-it': '15.3.0', node: 'v16.17.0', os: 'Linux 5.4' }
}
RELEASE-IT:CONFIG 642: {
  _: [],
  verbose: 2,
  preRelease: 'beta',
  git: false,
  increment: undefined,
  ci: true,
  hooks: {
    'before:init': " if [ -d 'builds' ]; then ls builds/; else ls; fi",
    'after:release': 'ls ./builds/'
  },
  github: {
    releaseName: 'v${version}',
    release: true,
    draft: false,
    assets: [ './builds/*.dmg' ],
    releaseNotes: null,
    autoGenerate: false,
    preRelease: false,
    tokenRef: 'GITHUB_TOKEN',
    host: null,
    timeout: 0,
    proxy: null,
    skipChecks: false,
    web: false
  },
  npm: {
    publish: false,
    publishPath: '.',
    publishArgs: [],
    tag: null,
    otp: null,
    ignoreVersion: false,
    allowSameVersion: false,
    skipChecks: false,
    timeout: 10
  },
  gitlab: {
    release: false,
    releaseName: 'Release ${version}',
    releaseNotes: null,
    milestones: [],
    tokenRef: 'GITLAB_TOKEN',
    tokenHeader: 'Private-Token',
    certificateAuthorityFile: null,
    assets: null,
    origin: null,
    skipChecks: false
  },
  plugins: {
    '@release-it/conventional-changelog': { preset: 'conventionalcommits', context: [Object] }
  },
  version: { increment: undefined, isPreRelease: true, preReleaseId: 'beta' }
}
RELEASE-IT:CONFIG 642: {
  '@release-it/conventional-changelog': { preset: 'conventionalcommits', context: { linkCompare: true } }
}
RELEASE-IT:PLUGINS 642: {
  namespace: '@release-it/conventional-changelog',
  options: {
    preset: 'conventionalcommits',
    context: { linkCompare: true },
    tagPrefix: ''
  }
}
RELEASE-IT:PLUGINS 642: {
  namespace: 'npm',
  options: {
    publish: false,
    publishPath: '.',
    publishArgs: [],
    tag: null,
    otp: null,
    ignoreVersion: false,
    allowSameVersion: false,
    skipChecks: false,
    timeout: 10
  }
}
RELEASE-IT:PLUGINS 642: {
  namespace: 'github',
  options: {
    releaseName: 'v${version}',
    release: true,
    draft: false,
    assets: [ './builds/*.dmg' ],
    releaseNotes: null,
    autoGenerate: false,
    preRelease: false,
    tokenRef: 'GITHUB_TOKEN',
    host: null,
    timeout: 0,
    proxy: null,
    skipChecks: false,
    web: false,
    tagName: null,
    tagMatch: null,
    pushRepo: '',
    changelog: 'git log --pretty=format:"* %s (%h)" ${from}...${to}'
  }
}
$  if [ -d 'builds' ]; then ls builds/; else ls; fi
tiago-1.0.0-beta.18-intel64.dmg
tiago-1.0.0-beta.18-intel64.dmg
RELEASE-IT:SHELL 642: {
  command: " if [ -d 'builds' ]; then ls builds/; else ls; fi",
  options: { external: true },
  code: 0,
  stdout: 'tiago-1.0.0-beta.18-intel64.dmg',
  stderr: ''
}
$ git rev-parse --abbrev-ref HEAD
DESKAPP
DESKAPP
RELEASE-IT:SHELL 642: {
  command: 'git rev-parse --abbrev-ref HEAD',
  options: { write: false },
  code: 0,
  stdout: 'DESKAPP',
  stderr: ''
}
$ git config --get branch.DESKAPP.remote
origin
origin
RELEASE-IT:SHELL 642: {
  command: 'git config --get branch.DESKAPP.remote',
  options: { write: false },
  code: 0,
  stdout: 'origin',
  stderr: ''
}
$ git remote get-url origin
https://github.com/tiago/desktop-app
https://github.com/tiago/desktop-app
RELEASE-IT:SHELL 642: {
  command: 'git remote get-url origin',
  options: { write: false },
  code: 0,
  stdout: 'https://github.com/tiago/desktop-app',
  stderr: ''
}
$ git fetch
RELEASE-IT:SHELL 642: { command: 'git fetch', options: {}, code: 0, stdout: '', stderr: '' }
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git describe --tags --match=* --abbrev=0
v1.0.0-beta.17
v1.0.0-beta.17
RELEASE-IT:SHELL 642: {
  command: 'git describe --tags --match=* --abbrev=0',
  options: { write: false },
  code: 0,
  stdout: 'v1.0.0-beta.17',
  stderr: ''
}
RELEASE-IT:CONFIG 642: {
  tagTemplate: 'v${version}',
  latestTag: 'v1.0.0-beta.17',
  secondLatestTag: null,
  branchName: 'DESKAPP'
}
RELEASE-IT:@RELEASE-IT/CONVENTIONAL-CHANGELOG 642: {
  increment: undefined,
  latestVersion: '1.0.0-beta.17',
  isPreRelease: true,
  preReleaseId: 'beta'
}
RELEASE-IT:@RELEASE-IT/CONVENTIONAL-CHANGELOG 642: conventionalRecommendedBump {
  options: {
    preset: 'conventionalcommits',
    context: { linkCompare: true },
    tagPrefix: ''
  }
}
RELEASE-IT:@RELEASE-IT/CONVENTIONAL-CHANGELOG 642: {
  err: null,
  result: {
    level: 2,
    reason: 'There are 0 BREAKING CHANGES and 0 features',
    releaseType: 'patch'
  }
}
RELEASE-IT:@RELEASE-IT/CONVENTIONAL-CHANGELOG 642: conventionalChangelog {
  options: { releaseCount: 1, preset: 'conventionalcommits', tagPrefix: '' },
  context: {
    version: '1.0.0-beta.18',
    previousTag: 'v1.0.0-beta.17',
    currentTag: 'v1.0.0-beta.18',
    linkCompare: true
  },
  gitRawCommitsOpts: {
    debug: [Function: logger] { enabled: [Getter] },
    from: 'v1.0.0-beta.17'
  },
  parserOpts: undefined,
  writerOpts: undefined
}
RELEASE-IT:@RELEASE-IT/CONVENTIONAL-CHANGELOG 642: Your git-log command is:
git log --format=%B%n-hash-%n%H%n-gitTags-%n%d%n-committerDate-%n%ci%n------------------------ >8 ------------------------ v1.0.0-beta.17 --no-merges
RELEASE-IT:@RELEASE-IT/CONVENTIONAL-CHANGELOG 642: Your git-log command is:
git log --format=%B%n-hash-%n%H%n-gitTags-%n%d%n-committerDate-%n%ci%n------------------------ >8 ------------------------ v1.0.0-beta.17..HEAD --no-merges
RELEASE-IT:CONFIG 642: {
  name: 'desktop-app',
  latestVersion: '1.0.0-beta.17',
  version: '1.0.0-beta.18',
  changelog: '## [1.0.0-beta.18](https://github.com/tiago/desktop-app/compare/v1.0.0-beta.17...v1.0.0-beta.18) (2022-09-13)'
}
🚀 Let's release desktop-app (1.0.0-beta.17...1.0.0-beta.18)
Changelog:
## [1.0.0-beta.18](https://github.com/tiago/desktop-app/compare/v1.0.0-beta.17...v1.0.0-beta.18) (2022-09-13)
RELEASE-IT:CONFIG 642: { version: '1.0.0-beta.18', isPreRelease: true, preReleaseId: 'beta' }
$ npm version 1.0.0-beta.18 --no-git-tag-version
v1.0.0-beta.18
v1.0.0-beta.18
RELEASE-IT:SHELL 642: {
  command: 'npm version 1.0.0-beta.18 --no-git-tag-version',
  options: {},
  code: 0,
  stdout: 'v1.0.0-beta.18',
  stderr: ''
}
RELEASE-IT:CONFIG 642: { tagName: 'v1.0.0-beta.18' }
$ Writing changelog to undefined
! octokit repos.createRelease "v1.0.0-beta.18" (v1.0.0-beta.18)
RELEASE-IT:GITHUB 642: {
  owner: 'tiago',
  repo: 'desktop-app',
  tag_name: 'v1.0.0-beta.18',
  name: 'v1.0.0-beta.18',
  body: '## [1.0.0-beta.18](https://github.com/tiago/desktop-app/compare/v1.0.0-beta.17...v1.0.0-beta.18) (2022-09-13)',
  draft: false,
  prerelease: true,
  generate_release_notes: false
}
request {
  method: 'POST',
  baseUrl: 'https://api.github.com',
  headers: {
    accept: 'application/vnd.github.v3+json',
    'user-agent': 'release-it/15.3.0 octokit-rest.js/19.0.3 octokit-core.js/4.0.4 Node.js/16.17.0 (linux; x64)'
  },
  mediaType: { format: '', previews: [] },
  request: {
    timeout: 0,
    fetch: [AsyncFunction: fetch],
    hook: [Function: bound bound register]
  },
  url: '/repos/{owner}/{repo}/releases',
  owner: 'tiago',
  repo: 'desktop-app',
  tag_name: 'v1.0.0-beta.18',
  name: 'v1.0.0-beta.18',
  body: '## [1.0.0-beta.18](https://github.com/tiago/desktop-app/compare/v1.0.0-beta.17...v1.0.0-beta.18) (2022-09-13)',
  draft: false,
  prerelease: true,
  generate_release_notes: false
}
POST /repos/tiago/desktop-app/releases - 201 in 523ms
RELEASE-IT:GITHUB 642: {
  url: 'https://api.github.com/repos/tiago/desktop-app/releases/77046940',
  assets_url: 'https://api.github.com/repos/tiago/desktop-app/releases/77046940/assets',
  upload_url: 'https://uploads.github.com/repos/tiago/desktop-app/releases/77046940/assets{?name,label}',
  html_url: 'https://github.com/tiago/desktop-app/releases/tag/v1.0.0-beta.18',
  id: 77046940,
  author: {
    login: 'tiago-devbot',
    id: 22910544,
    node_id: 'MDQ6VXNlcjIyOTEwNTQ0',
    avatar_url: 'https://avatars.githubusercontent.com/u/22910544?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/tiago-devbot',
    html_url: 'https://github.com/tiago-devbot',
    followers_url: 'https://api.github.com/users/tiago-devbot/followers',
    following_url: 'https://api.github.com/users/tiago-devbot/following{/other_user}',
    gists_url: 'https://api.github.com/users/tiago-devbot/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/tiago-devbot/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/tiago-devbot/subscriptions',
    organizations_url: 'https://api.github.com/users/tiago-devbot/orgs',
    repos_url: 'https://api.github.com/users/tiago-devbot/repos',
    events_url: 'https://api.github.com/users/tiago-devbot/events{/privacy}',
    received_events_url: 'https://api.github.com/users/tiago-devbot/received_events',
    type: 'User',
    site_admin: false
  },
  node_id: 'RE_kwDOGR2clc4El6Sc',
  tag_name: 'v1.0.0-beta.18',
  target_commitish: 'master',
  name: 'v1.0.0-beta.18',
  draft: false,
  prerelease: true,
  created_at: '2022-09-12T21:47:03Z',
  published_at: '2022-09-13T20:31:24Z',
  assets: [],
  tarball_url: 'https://api.github.com/repos/tiago/desktop-app/tarball/v1.0.0-beta.18',
  zipball_url: 'https://api.github.com/repos/tiago/desktop-app/zipball/v1.0.0-beta.18',
  body: '## [1.0.0-beta.18](https://github.com/tiago/desktop-app/compare/v1.0.0-beta.17...v1.0.0-beta.18) (2022-09-13)'
}
octokit repos.createRelease: done (https://api.github.com/repos/tiago/desktop-app/releases/77046940)
! octokit repos.uploadReleaseAssets ./builds/*.dmg
WARNING octokit repos.uploadReleaseAssets: did not find "./builds/*.dmg" relative to /runner/_work/desktop-app/desktop-app
$ ls ./builds/
tiago-1.0.0-beta.18-intel64.dmg
tiago-1.0.0-beta.18-intel64.dmg
RELEASE-IT:SHELL 642: {
  command: 'ls ./builds/',
  options: { external: true },
  code: 0,
  stdout: 'tiago-1.0.0-beta.18-intel64.dmg',
  stderr: ''
}
🔗 https://github.com/tiago/desktop-app/releases/tag/v1.0.0-beta.18
🏁 Done (in 2s.)
</pre>
</details>

**Comment by tiagoporto** [comment]
Hi @webpro, is this info you were looking?

**Comment by webpro** [comment]
Yes, I wanted to see whether somehow the asset glob pattern was modified by the template interpolation (as things like `${version}` will be replaced). But this is not the case.

I've just tried a few things myself, but `assets` always "just work" here. From a subdir, fancy file names, wildcards, binaries, etc. The only difference is that I'm on macOS and not using `yarn` myself, but I would be surprised this would be the culprit. I know this feature is used a lot in the wild, so I feel a bit out of options at this point.

Only thing I can recommend is to try on another machine such as your own.

**Comment by webpro** [comment]
From [v15.4.2](https://github.com/release-it/release-it/releases/tag/15.4.2) you can use `--dry-run` to test without actual releases :)

**Comment by tiagoporto** [comment]
> I've just tried a few things myself, but assets always "just work" here. From a subdir, fancy file names, wildcards, binaries, etc. The only difference is that I'm on macOS and not using yarn myself, but I would be surprised this would be the culprit. I know this feature is used a lot in the wild, so I feel a bit out of options at this point.

I've tested without yarn, the same result.

> Only thing I can recommend is to try on another machine such as your own.

Same result with other 2 different machines too (linux, mac).

Debug do not provide more details, I will try to recreate the same scenario in another repo.

😢

**Comment by tiagoporto** [comment]
Hi @webpro,  definitely there is something wrong with the lib.
I've tried to do the same with this [repo](https://github.com/tiagoporto/gerador-validador-cpf), the same result no assets is being published.

Release test
https://github.com/tiagoporto/gerador-validador-cpf/releases/tag/v5.0.3

[Workflow](https://github.com/tiagoporto/gerador-validador-cpf/blob/v5.0.3/.github/workflows/release.yml)

[.release-it.json](https://github.com/tiagoporto/gerador-validador-cpf/blob/v5.0.3/.release-it.json)

**Comment by tiagoporto** [comment]
I found the issue, is something related to a previous step in the workflow. I was trying to push a file, but it was a folder.

Thank you for the help.
