### ISSUE TITLE
GitHub Release URL assumes the npm packge name, not the git repo name

### ISSUE THREAD

**Issue by mceachen** [release-it/release-it#938]
First of all: **thank you for building and maintaining `release-it`**. :+1: :100: :1st_place_medal: :cook: 

I just did a release for [exiftool-vendored.js](https://github.com/photostructure/exiftool-vendored.js/), and when prompted to create a GitHub release, crafted the URL `https://github.com/photostructure/exiftool-vendored/releases/new?tag=v17.1.0&title=...`

This URL 404s because the git repository is at `exiftool-vendored.js`. The NPM package name doesn't include the ".js" suffix in the git repository.

**Comment by webpro** [comment]
That's odd, dots in the project name should not be an issue.

```
git remote -v
```

The dot is not missing here?

If not, can you do a run (no need to finish) like this:

```
NODE_DEBUG=release-it:* release-it [...]
```

There should appear some `repo` details before any prompt.

**Comment by mceachen** [comment]
```
$ git remote -v
origin	git@github.com:photostructure/exiftool-vendored.js.git (fetch)
origin	git@github.com:photostructure/exiftool-vendored.js.git (push)
```

```
$ NODE_DEBUG=release-it:* release-it

...

RELEASE-IT:CONFIG 1670947: {
  repo: {
    host: 'github.com',
    owner: 'photostructure',
    project: 'exiftool-vendored',
    protocol: 'ssh',
    remote: 'git@github.com:photostructure/exiftool-vendored.js.git',
    repository: 'photostructure/exiftool-vendored'
  }
}
```

So that looks correct!

**Comment by mceachen** [comment]
FWIW, git-url-parse is doing the right thing:

```
> require("git-url-parse")("git@github.com:photostructure/exiftool-vendored.js.git")
{
  protocols: [ 'ssh' ],
  protocol: 'ssh',
  port: '',
  resource: 'github.com',
  host: 'github.com',
  user: 'git',
  password: '',
  pathname: '/photostructure/exiftool-vendored.js.git',
  hash: '',
  search: '',
  href: 'git@github.com:photostructure/exiftool-vendored.js.git',
  query: {},
  parse_failed: false,
  token: '',
  toString: [Function (anonymous)],
  source: 'github.com',
  git_suffix: true,
  name: 'exiftool-vendored.js',
  owner: 'photostructure',
  commit: undefined,
  ref: '',
  filepathtype: '',
  filepath: '',
  organization: 'photostructure',
  full_name: 'photostructure/exiftool-vendored.js'
}
```

**Comment by webpro** [comment]
Can't reproduce it, here I've set my remote to your git url and all seems fine:

```
RELEASE-IT:CONFIG 55424: {
  remoteUrl: 'git@github.com:photostructure/exiftool-vendored.js.git',
  branchName: 'master',
  repo: {
    host: 'github.com',
    owner: 'photostructure',
    project: 'exiftool-vendored.js',
    protocol: 'ssh',
    remote: 'git@github.com:photostructure/exiftool-vendored.js.git',
    repository: 'photostructure/exiftool-vendored.js'
  }
}
```

On which version of release-it are you?

**Comment by mceachen** [comment]
OMG. I'd been testing with an older version of node (via nvm) that had old versions of stuff... and forgot to switch it back.

Turns out that this is a bug in v15.2.0, and **is not an issue in v15.4.2**.

Apologies for the bother. Thanks again for `release-it` and the assist!
