### ISSUE TITLE
TypeScript errors starting with 15.4.2

### ISSUE THREAD

**Issue by planttheidea** [release-it/release-it#941]
I use `release-it` for a number of packages (love it, btw, great work!), and have noticed that if I blindly update to the latest version (`15.4.2`) I start getting TS errors:

```
node_modules/@types/cacheable-request/index.d.ts:108:70 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

108         off(event: 'response', listener: (response: ServerResponse | ResponseLike) => void): this;
```

I also get this if I wipe out my `yarn.lock` file. meaning it is a nested dependency. Traversing through `yarn.lock`, I see that `@types/cacheable-request` seem to be related to `got` and `update-notifier`, and since [`got` was updated in the most recent patch](https://github.com/release-it/release-it/commit/97095d53325c904eec18678a6e7f786a47b4544f), I'm guessing that is the culprit.

Naturally this is an upstream issue, but it is causing pain for consumers of your package. Is it possible that you can pin the version of `got` until the upstream issue is resolved? I do not get this error on `15.4.1`, so my packages are pinned to this version for now.

**Comment by johanhammar** [comment]
I'm seeing this as well. Seems related to https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62099 & https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62102

**Comment by andreafspeziale** [comment]
Same problem here while TS building. It should be just a matter of `got` [bumping](https://github.com/sindresorhus/got/releases/tag/v12.5.1)
```
release-it@15.4.2
  └─┬ got@12.4.1
    └── cacheable-request@7.0.2
```

Thanks for your hard work!

**Comment by Codex-** [comment]
Also requesting that this be bumped as the inclusion of this without allowing minor bumping in the lock causes depending on `release-it` to pull `got`@`12.4.1` which has this conflict with later typings. 

The upstream issue was fixed in `got` [here](https://github.com/sindresorhus/got/pull/2146/files) and has been released already.

**Comment by webpro** [comment]
Thanks, everyone. It's in [v15.4.3](https://github.com/release-it/release-it/releases/tag/15.4.3).
