### ISSUE TITLE
add --workspaces-update=false to 'npm version'

### ISSUE THREAD

**Issue by basz** [release-it/release-it#942]
I believe 'npm version ...' should be run with this flag. `--workspaces-update=false`

while using workspaces `npm version` will do an update on the node_modules, which interferes with yarn/pnpm package installers. In my case it also does not complete for a very long time, and I need to remove it's generated lock file.

https://docs.npmjs.com/cli/v8/commands/npm-version#workspaces-update

**Comment by webpro** [comment]
Regardless from what release-it should do, I've added the `versionArgs` option so you can add any argument: https://github.com/release-it/release-it/blob/master/docs/npm.md#extra-arguments

It's in [v15.5.0](https://github.com/release-it/release-it/releases/tag/15.5.0)

**Comment by basz** [comment]
thanks!

**Comment by machty** [comment]
For Google posterity, this issue fixed the errors I was getting using release-it in my pnpm workspace:

```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

By adding `--workspaces-update` to npm.versionArgs, I was able to fix the issue.
