### ISSUE TITLE
Support for multiple config files like .releaseitrc and more

### ISSUE THREAD

**Issue by dodanex** [release-it/release-it#953]
Please add, if possible, support for multiple configuration files like in this example: 
- `.releaseitrc`
- `.release-it`
- `.releaseit.yml`
- `.releaseitrc.yaml`

**Comment by webpro** [comment]
This is the list that release-it looks for by default:

```
package.json
.release-it.json
.release-it.js
.release-it.cjs
.release-it.yaml
.release-it.yml
.release-it.toml
```

Anything else you can point to using `release-it --config my-config.yml`

**Comment by webpro** [comment]
Happy to re-consider when more people show interest. For now I'm going to close this.
