### ISSUE TITLE
npm 9.0.0: auth-type defaults to "web"

### ISSUE THREAD

**Issue by aladdin-add** [release-it/release-it#954]
![image](https://user-images.githubusercontent.com/13050025/200764057-e51d0996-a56b-4334-86e6-92b376d0976b.png)

I was using:
* node.js: v19.0.0
* npm: v9.0.1
* release-it: v15.5.0

Pressing enter, I want release-it to publish to npm like it always does, but it didn't. It could be related to npm v9.0 changes:
![image](https://user-images.githubusercontent.com/13050025/200765049-356c9286-2f43-4dc7-8bd6-a16cf67e00f9.png)

https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/

**Comment by webpro** [comment]
You are showing a screenshot with "No". But what did you see when you actually tried to publish to npm? Do you have debug output?

**Comment by aladdin-add** [comment]
that's the problem: i pressed enter, it should use the default(Y), but it was just showing a web auth page. 

I had retried it - seems working fine tho.
