### ISSUE TITLE
Support Pnpm workspace

### ISSUE THREAD

**Issue by McDaddy** [release-it/release-it#956]
currently if publish package with pnpm workspace package, it will not overwrite `workspace` like

```
  "dependencies": {
    "react": "18.0.0",
    "xxxx": "workspace:*"
  },
```

but it should be like
```
  "dependencies": {
    "react": "18.0.0",
    "xxxx": "^1.0.0"
  },
```

when I publish with cli `pnpm publish` it works fine

**Comment by webpro** [comment]
release-it uses `npm` (and thus `npm publish`) under the hood. Also see for instance #919.

**Comment by wottpal** [comment]
Does "closed this as completed" mean pnpm publish / workspaces are supported now? Or are there no plans for `release-it` to support this? Would be a bummer, know more and more devs that are switching.

**Comment by antitoxic** [comment]
@webpro `pnpm publish` is different from `npm publish` because `pnpm` will replace all references to monorepo packages in `package.json`.

Quote from the docs:

> So for example, if we have `foo`, `bar`, `qar`, `zoo` in the workspace and they all are at version `1.5.0`, the following:
> 
> ```json
> {
>   "dependencies": {
>     "foo": "workspace:*",
>     "bar": "workspace:~",
>     "qar": "workspace:^",	
>     "zoo": "workspace:^1.5.0"
>   }
> }
> ```
> 
> Will be transformed into:
> 
> ```json
> {
>   "dependencies": {
>     "foo": "1.5.0",
>     "bar": "~1.5.0",
>     "qar": "^1.5.0",
>     "zoo": "^1.5.0"
>   }
> }
> ```

**Comment by antitoxic** [comment]
Anyways I thought of a workaround (not tested yet) which will hopefully make this work:

- run `pnpm pack` as a command to a `before:npm:release` hook in the `release-it` config
- add the name of the `.tar.gz` file created by `pnpm` pack to `npm.publishPath` in the `release-it` config where hopefully we can use the `${version}` variable

**Comment by webpro** [comment]
Another approach could be to use some combo of `npm.publish: false` and release-it hooks to `pnpm publish` (you might need the same idea for `pnpm version`).

**Comment by webpro** [comment]
This might help: https://github.com/hyoban/release-it-pnpm

**Comment by FRSgit** [comment]
This configuration works quite well:
```ts
{
    npm: {
      publish: true,
      publishPath: "package-pack.tgz",
    },
    hooks: {
      "before:npm:release": "mv $(pnpm pack) package-pack.tgz",
      "after:npm:release": "rm package-pack.tgz",
    },
}
```

Working repository for reference: https://github.com/FRSOURCE/toolkit/

**Comment by antitoxic** [comment]
Awesome @FRSgit ! Glad it worked for you. In the meantime i did something very similar:

```js
{
  /**
  * Account for pnpm workspace dependencies (e.g. "^workspace" versions):
  * https://github.com/release-it/release-it/issues/956
  */
  npm: {
    publish: true,
    publishPath: '*.tgz'
  },
  hooks: {
    'before:npm:release': 'pnpm pack'
  }
}
```

I am not removing the `tgz` since we only do this during CI/CD
