### ISSUE TITLE
is there a recommended 'hello world' example for customizing the changelog?

### ISSUE THREAD

**Issue by iambumblehead** [release-it/release-it#957]
Hello,

Is there a small 'hello world' style example one might use to try customizing the changelog, so that the duplicates are removed?

This is one of my favorite packages and I use it in tens of projects.

A nit is the changelog nearly repeats each item in the gitlab list. Here is an example from part of a release-it changelog generated for gitlab, where the flow is: create an issue, create an MR from the issue, complete the MR and merge into the default/main branch,
```markdown
* Merge branch '338-update-coverage-badge-with-new-location-remove-sinon-more-tests' into 'main' (a086eda)
* Resolve "update coverage badge with new location, remove sinon more tests" (a1b7bf7)
* Merge branch '337-remove-a-few-more-unused-dependencies-remove-sinon-from-env-tests' into 'main' (33c1e25)
* Resolve "remove a few more unused dependencies, remove sinon from env tests" (71bb12a)
* Merge branch '334-investigate-resolve-un-comment-two-tests-that-caused-test-runner-to-hang' into 'main' (54175c7)
* Resolve "investigate, resolve, un-comment two tests that caused test runner to hang" (21e4db7)
```

I see [from the documentation](https://github.com/release-it/release-it/blob/master/docs/gitlab-releases.md#release-notes) that it is possible to customize the output this way,
```json
{
  "gitlab": {
    "release": true,
    "releaseNotes": "generate-release-notes.sh ${latestVersion} ${version}"
  }
}
```

Any example or recommendations you might give are appreciated, thank you :)

**Comment by webpro** [comment]
This is the default command:

```
git log --pretty=format:"* %s (%h)" ${from}...${to}"
```

So what you could do either directly in the `gitlab.releaseNotes` value, or deferred to in some shell script, is run something that gets you the results you need. For instance, if you want to skip the merge commits:

```json
{
  "gitlab": {
    "release": true,
    "releaseNotes": "git log --no-merges --pretty=format:\"* %s (%h)\" ${from}...${to}",
  }
}
```

Does that help?

**Comment by webpro** [comment]
> This is one of my favorite packages and I use it in tens of projects.

Thank you so much, I really appreciate this!

**Comment by iambumblehead** [comment]
I tried simply pasting the suggested line into the package.json and the release pipeline failed with this error
```bash
"isPreRelease":false,"preReleaseId":null,"tagName":"0.17.0"}
ERROR ReferenceError: from is not defined
```

**Comment by webpro** [comment]
Sorry about that. What you see below that error message is the data available in the command. Here's a better example:

```json
{
  "gitlab": {
    "release": true,
    "releaseNotes": "git log --no-merges --pretty=format:\"* %s (%h)\" ${latestTag}...${tagName}",
  }
}
```

**Comment by iambumblehead** [comment]
```bash
ERROR fatal: ambiguous argument '7.37.0...7.38.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
```

**Comment by iambumblehead** [comment]
I believe this is what is needed,
```console
git log --no-merges --pretty=format:"* %s (%h)" 7.37.0...main
```

**Comment by iambumblehead** [comment]
@webpro this is working :)
```json
{
  "release-it": {
    "gitlab": {
      "release": true,
      "releaseNotes": "git log --no-merges --pretty=format:\"* %s %h\" ${latestTag}...main"
    }
  }
}
```

**Comment by webpro** [comment]
Thank you, much appreciated! All the trial & error at least just made it to the docs for others to enjoy :)
