### ISSUE TITLE
NPM Collaborator Warning

### ISSUE THREAD

**Issue by karmaniverous** [release-it/release-it#960]
I am running:

```bash
dotenv -c -- release-it
```

I have my GitHib token in `.env.local` and I have verified it is getting passed properly.

When I run this command, I get this warning at the top of the interactive process:

```text
WARNING Unable to verify if user karmaniverous is a collaborator for @karmaniverous/npm-package-template.
```

This warning is apparently coming from NPM. When I set `release-it.npm.publish: false` in `package.json`, the warning goes away.

I am in fact the repo owner. My NPM account is in fact linked to my GitHub account. The warning doesn't seem to prevent the package from publishing, but it's annoying.

Any ideas?

**Comment by webpro** [comment]
Probably fixed by #966
