### ISSUE TITLE
Package version does not change

### ISSUE THREAD

**Issue by pkolt** [release-it/release-it#961]
Hi!

I noticed that if you specify `--no-npm` flag, then the version in the **package.json** file will not be changed.

My flow is in two parts, so I don't need to publish the package to NPM in the first part. Do you have any thoughts on this?

```json
{
  "scripts": {
    "release:prepare": "dotenv release-it -- --no-npm --no-github",
    "release:publish": "dotenv release-it -- --no-increment --no-git"
  }
}
```

Thanks!

**Comment by webpro** [comment]
I guess what you want is `--no-npm.publish` (not `--no-npm`)

**Comment by pkolt** [comment]
Hi @webpro !

It works! Thanks 👍
