### ISSUE TITLE
Release failed due to "Body is too long" error.

### ISSUE THREAD

**Issue by aacevski** [release-it/release-it#965]
Hey y'all,

I have a project which I'm trying to add the `release-it` package and I'm generating a custom changelog. The issue is that there have been a big number of PR's and this initial changelog is too big and the request fails with the following error:  
![image](https://user-images.githubusercontent.com/44305048/209476075-0c64e60f-59d5-488b-accd-871331023aed.png)

Is there a solution to this issue? To me it would work fine if there is a way for the changelog to be generated after a certain date for example.

Thank you in advance!

**Comment by V0lantis** [comment]
Same here :wave:

**Comment by webpro** [comment]
I think an easy/generic/no-config solution would be to just truncate the text and then add a line "[this changelog is truncated to 124k characaters]" or something. Would that work?

**Comment by anselmbradford** [comment]
@webpro I'm experiencing this too, but with a much lower character count. I put a `console.log(body.length)` in [truncateBody](https://github.com/release-it/release-it/blob/eeda65b820c2c1c8b77d21280b717098db1e336c/lib/plugin/github/GitHub.js#L38), and my body length is 6297. I adjusted the truncation amount and couldn't get the GH page to load till I brought it down to 6106 characters. Any idea why this is so much lower?
