### ISSUE TITLE
how to skip prompting Tag, Push?

### ISSUE THREAD

**Issue by thilllon** [release-it/release-it#967]
Hi,
Is there any way to skip prompting Tag, Push? Because we always chose them true.
Thanks.

![image](https://user-images.githubusercontent.com/44559468/210273679-cfae55a3-214e-4dbd-afd6-9dd219b0662d.png)

**Comment by aacevski** [comment]
If you add the --ci flag, it should skip all these prompts.

**Comment by webpro** [comment]
Or use `--only-version`

https://github.com/release-it/release-it#interactive-vs-ci-mode

There is unfortunately no way to pre-answer only specific prompts.

**Comment by thilllon** [comment]
@aacevski @webpro It works. Thanks!

**Comment by satya164** [comment]
The problem with `--ci` flag is that it doesn't prompt for 2FA.
