### ISSUE TITLE
Publishing failed using release-it

### ISSUE THREAD

**Issue by txp1035** [release-it/release-it#968]
I'm having problems releasing the new version, which uses a custom template

Error message：
node:events:491
      throw er; // Unhandled 'error' event
      ^
Error: warning: refname '1.3.0' is ambiguous.
Node.js v18.12.1
![image](https://user-images.githubusercontent.com/9554297/210476343-9c234467-ff60-43cb-b2ee-f928a2c66bed.png)

commit message：
![image](https://user-images.githubusercontent.com/9554297/210476748-31cbfe07-91cd-4111-bacc-09af05f2a839.png)

**Comment by webpro** [comment]
> Error: warning: refname '1.3.0' is ambiguous.

This error comes from Git and it means that there are more refs with that name. By your commits it seems there's also a branch name ending with `1.3.0` (`txp1035/1.3.0`), maybe that's the issue.

This seems not an issue in release-it, so I'm going to close it.
