### ISSUE TITLE
Allow skipping releases that consist only of a set type of changes

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [release-it/release-it#969]
In repositories that use tools such as [Dependabot](https://github.com/dependabot) or [Renovate](https://github.com/apps/renovate), it's common for a majority of commits to be `chore: ...` / `chore(deps): ...` package bumps. It would be nice to have an option to skip releasing if commits only consist of a certain list of types. For example:

```json
{
  "git": {
    "skipIfOnly": ["chore", "docs"]
  }
}
```

The closest documentation/recipe I could find is https://github.com/release-it/release-it/blob/master/docs/recipes/require-commits.md.

This is only tangentially related to #964. I solved that one by fiddling with changelog settings - but the root cause of releases that only contain chores still exists.

**Comment by webpro** [comment]
The release-it plugin is only like a proxy to the underlying conventional-changelog package(s). Unfortunately it doesn't seem to have the option you want.

If you really want to, I can think of a few things to try (not interested in this personally). One potential direction I can think of right now is to cancel the release after the changelog generation, which could happen in the `before:bump` hook:

```json
{
  "hooks": {
    "before:bump": "if check-something then exit 1"
  }
}
```

There is also the `release-it --changelog` invocation which outputs only the changelog, which could be parsed and acted upon.

Another solution could be to extend the conventional-changelog plugin in a minimal way to just throw when the results of changelog generation matches your conditions.

**Comment by JoshuaKGoldberg** [comment]
Got it, thanks! I ended up writing a [`should-semantic-release`](https://github.com/JoshuaKGoldberg/should-semantic-release) helper to do just that:

```json
{
	"hooks": {
		"before:bump": "if ! npx should-semantic-release ; then exit 1 ; fi"
	}
}
```

Hope that helps if anybody needs. Cheers! ❤️

**Comment by skycaptain** [comment]
I encountered the same issue when we switched from semantic-release back to release-it for one project. `conventional-changelog-conventionalcommits` allows you to pass your own `whatBump` function with the options object. This function is used to determine the recommended bump. If it returns `undefined` no bump is done. Thus, I [copied the function](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-conventionalcommits/src/whatBump.js) from `conventional-changelog-conventionalcommits` and added a check to skip the hidden commit types.

So in my `.release-it.cjs`, I have:
```javascript
const { DEFAULT_COMMIT_TYPES } = require("conventional-changelog-conventionalcommits");
const { addBangNotes } = require("conventional-changelog-conventionalcommits/utils");

const config = { name: "conventionalcommits" };

module.exports = {
  plugins: {
    "@release-it/conventional-changelog": {
      preset: config,
      // FIXME: Because release-it only accepts CommonJS modules, we can not use loadPreset and
      // wrap the whatBump function from the original preset. Instead we have to reimplement the
      // whatBump function here. Fix as soon as release-it supports ESModules for config files
      whatBump: function (commits) {
        let level = undefined;
        let breakings = 0;
        let features = 0;

        commits.forEach((commit) => {
          var isHiddenType =
            DEFAULT_COMMIT_TYPES.find((type) => type.type === commit.type)?.hidden || false;

          // adds additional breaking change notes
          // for the special case, test(system)!: hello world, where there is
          // a '!' but no 'BREAKING CHANGE' in body:
          addBangNotes(commit);
          if (commit.notes.length > 0) {
            breakings += commit.notes.length;
            level = 0;
          } else if (commit.type === "feat" || commit.type === "feature") {
            features += 1;
            if (level === 2 || level === undefined) {
              level = 1;
            }
          } else if (!isHiddenType) {
            if (level === undefined) {
              level = 2;
            }
          }
        });

        if (config?.preMajor && level < 2) {
            level++;
        }

        return {
          level,
          reason:
            breakings === 1
              ? `There is ${breakings} BREAKING CHANGE and ${features} features`
              : `There are ${breakings} BREAKING CHANGES and ${features} features`,
        };
      },
    },
  },
};
```

It should be noted that `conventional-changelog-conventionalcommits` recently refacted their code (new `Bumper` class), so this code might need refactoring once https://github.com/release-it/conventional-changelog/issues/88 is done.

**Comment by Blackclaws** [comment]
Even with the custom whatBump function a prerelease will still count up the version for whatever reason

**Comment by ygrishajev** [comment]
Faced the same issue and fixed it this way in the fork https://github.com/ygrishajev/conventional-changelog/pull/1/files
It relies on my another PR to this repo so I'm not going with another one till I can get feedback from the owner.
