### ISSUE TITLE
Ignore/exclude folders from NPM deploy?

### ISSUE THREAD

**Issue by andyslack** [release-it/release-it#971]
Hi Guys,

Love your package, however is there a way to exclude folders?

I have packages which I publish to NPM and I would prefer not to publish the /src folder.

I of course want them to go into git.

Any guidance would be appricated.

**Comment by webpro** [comment]
Sounds like regular npm configuration to me: see e.g. https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files

**Comment by andyslack** [comment]
Spot on, thank you I had not come across the `.npmignore` file before.

```
// .npmignore
/src
```

Did the job perfectly. 

For completness, I had to remove from my `package.json` the `/src` folder from my `files` array.

Thanks for pointing me in the right direction @webpro
