### ISSUE TITLE
Pre-release is ignoring commits to bump version

### ISSUE THREAD

**Issue by tiagoporto** [release-it/release-it#972]
Thanks for the amazing lib.

I was doing a test mixing pre-release and release and I found a bug. `release-it` is ignoring commits after a pre-release and always bump the last value e.g.: 1.0.0-alpha.x. If there is a break change commit after version 1.0.0-alpha.0 `release-it` should bump to 2.0.0-alpha.0, instead bumps to 1.0.0-alpha.1.

Check this test:
![image](https://user-images.githubusercontent.com/3688905/211913058-f45e5bd5-0738-4f33-923a-e1ea7058116a.png)

I've tested with a different lib [standard-version](https://github.com/conventional-changelog/standard-version)

As you can see pre-release updates correctly based on the top commits.
![image](https://user-images.githubusercontent.com/3688905/211915269-3341c425-dfbd-4dc8-b48d-f2c983adbe3e.png)

I'm using the last version: 15.6.0

**Comment by tiagoporto** [comment]
Just found a way to fix that https://github.com/release-it/conventional-changelog#strictsemver

**Comment by webpro** [comment]
Without plugins, release-it itself does not have a notion of breaking changes, it just bumps the version based on the latest tag with the increment you provide.

The conventional-changelog plugin can provide the recommended bump based on a convention. E.g. with the `conventionalcommits` preset.

> From release 1.0.0 jumped to 1.0.3

From what I can see in the image, it goes (correctly) from v1.0.3-alpha.0 with a patch bump (based on "chore") to v1.0.3.

Perhaps https://github.com/release-it/release-it/blob/master/docs/git.md#tag-exclude is what you are after?

If you think there's an issue with the conventional-changelog plugin, please [open an issue there](https://github.com/release-it/conventional-changelog).

**Comment by tiagoporto** [comment]
I've created the bug, thanks https://github.com/release-it/conventional-changelog/issues/58.

Thank you for your answer.
