### ISSUE TITLE
Turborepo (monorepo) - how to filter commits that affect files in the folder with release-it.js (npm workspace item)?

### ISSUE THREAD

**Issue by b12k** [release-it/release-it#973]
Hello everyone!

    Disclaimer: I know there are issues (closed) related to monorepo integration. But unfortunately all the suggestions are not working for me.

I almost setup everything as I need for semantic releases in my monorepo. It is using `turborepo` as a manager.

### Repo structure:

```
package.json
turbo.json
.releases/
  app-a.CHANGELOG.md
  app-a.VERSION.json
  app-b.CHANGELOG.md
  app-b.VERSION.json
  lib-a.CHANGELOG.md
  lib-a.VERSION.json
  lib-b.CHANGELOG.md
  lib-b.VERSION.json
  lib-c.CHANGELOG.md
  lib-c.VERSION.json
apps/
  app-a/
    release-it.js
    package.json
  app-b/
    release-it.js
    package.json
libs/
  lib-a/
    release-it.js
    package.json
  lib-b/
    release-it.js
    package.json
  lib-c/
    release-it.js
    package.json
```

### Where:

- `app-a` explicitly depends on `lib-a`
- `app-b` explicitly depends on `lib-b`
- `lib-a` & `lib-b` explicitly depend on `lib-c`, making `lib-c` and implicit dependency on `app-a` & `app-b`
- releasing any of mentioned above should trigger `downstream` releases

### Release:

When `turborepo` executes scripts of a monorepo entity `process.cwd` is that entity folder (entity package.json location).

Every monorepo entity has `release-it` as a dependency, and other plugins as "bumper", "conventional changelog", etc. They are set to save changelog files and version files in the dedicated folder in the root not to invalidate turborepo cache of the respective monorepo element.

## Help needed:

- How to "filter" commits (that are used for calculating version bump and populate changelog) to include only those which touch files in the respective directory (process.cwd)?
- Is there a way to specify "default" bump? If no commits from above are found I want to bump "minor".

[Example repository](https://github.com/b12k/turborepo-release-it)

**Comment by b12k** [comment]
For `semantic-release` there is a plugin [semantic-release-monorepo](https://www.npmjs.com/package/semantic-release-monorepo) which filters commits based on files they touch relative to `process.cwd`.

**Comment by webpro** [comment]
- You could try the idea of `git log -- apps/app-a` etc. and override the `git.changelog` commands with it.
- Unfortunately release-it defaults to a `patch` release, and there's no option to override this. When using the conventional-changelog plugin, you could look into [whatBump](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-recommended-bump#whatbump), but that might be a bit tedious.
