### ISSUE TITLE
Question: Generate changelog with commits committed after the last release

### ISSUE THREAD

**Issue by dfilipeloja** [release-it/release-it#974]
Hello,

Is there any way to generate a changelog based on the latest commits committed after the latest release? I am using a feature branch and I am creating commits based on the conventional commits:

- fix: foo
- fix: bar
- fix: foo bar

But when I merge it into the main master it only appears the last commit committed (the foo commit). How to make the three commits appear in the bug section in the changelog instead of the commit that triggered the pipeline?

PS.: I am using Azure DevOps

**Comment by webpro** [comment]
The `git.changelog` option is available to override the default `git log` command: https://github.com/release-it/release-it/blob/2a8271ff9d92f92c2a9cae21946391a99dc9dae3/config/release-it.json#L4

**Comment by dfilipeloja** [comment]
I managed to solve it, thanks!

For people using Azure DevOps that are facing the same problem as mine the problem was [shallow fetch](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines#shallow-fetch).

```yml
steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0
```
With fetchDepth as 0 the agent can retrieve all the log history to create the CHANGELOG.md with all the changes.
