### ISSUE TITLE
Unable to bump version in package.json

### ISSUE THREAD

**Issue by paustint** [release-it/release-it#977]
I have an application that is not published to npm, I am using release-it just to manage creating a release and deploying a verison.

If `npm` is disabled, it appears that release-it still fails if some other plugin/process attempts to update the version in package.json. If npm publish is false, shouldn't any other logic related to npm be disabled?

Here is the problem I am facing:

**Having this configuration works for everything except package.json version is not updated**
```json
{
  "plugins": { },
  "npm": {
    "publish": false
  }
}
```

**Having this configuration fails with the error message `ERROR npm ERR! Version not changed`**
```json
{
  "plugins": {
    "@release-it/bumper": {
      "in": "package.json",
      "out": "package.json"
    }
  },
  "npm": {
    "publish": false
  }
}
```

**Comment by webpro** [comment]
There is a difference between `npm.publish: false` and `npm: false`: only the latter disables the npm plugin entirely.

The npm plugin also reads/write `package.json#version`, so when the `@release-it/bumper` is configured to do the same, the latter has precedence over the internal release-it plugin(s), but the former then fails (which is how `npm version` works). Two options:

- Let the npm plugin handle `package.json`
- Use `npm.allowSameVersion: true` (or `--npm.allowSameVersion` from cli)

I am surprised however that the `package.json` is not updated? Any more info or debug logs you can share?

**Comment by paustint** [comment]
>I am surprised however that the package.json is not updated in that first scenario? Any more info or debug logs you can share?

This is an extremely vanilla setup. I am pretty sure `publish: false` translates to a code path that does not modify package.json.

Here is a simple repro - install deps with yarn, then run `yarn release`
https://github.com/paustint/release-it-test
**I [added you as a collaborator](https://github.com/paustint/release-it-test/invitations) to the repo so feel free to do anything you want since it is just an example repo**

You can see that version `1.0.1` [was tagged](https://github.com/paustint/release-it-test/tags) in the repo - nothing to commit in the release since the package.json was ignored and untouched.

So it seems my best bet will be to set `npm=false` and then use the bumper plugin to manage package.json for me, at lease until this bug is fixed.

Here is the output from when I ran the command:
```
❯ yarn release
yarn run v1.22.19
$ release-it --verbose

🚀 Let's release release-it-test (currently at 1.0.0)


Changelog:
* remove TS (bc97897)
* update version (c781dec)
* initial (aa08edd)

? Select increment (next version): patch (1.0.1)
$ git checkout -- package.json

Empty changeset

? Commit (chore: release 1.0.1)? Yes

On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
WARNING No changes to commit. The latest commit will be tagged.
? Tag (v1.0.1)? Yes
? Push? Yes
🏁 Done (in 13s.)
✨  Done in 13.88s.
 ~/d/node/release-it-test  main  
```

**Comment by webpro** [comment]
There is literally `git checkout -- package.json` in the `after:bump` hook, causing the version bump in `package.json` to be reverted.

You can use `-VV` (double `--verbose`) to also see the "internal" commands aa they happen.

**Comment by paustint** [comment]
@webpro - I have never used `git checkout --` before so was not familiar with it.

This was added automatically by the libraries init command `yarn create release-it`, so I figured it was important for some reason and did not think to investigate the command.

Do you know why this command is added in the default init setup process? Maybe I am missing something, but I would think that reverting the package version would not be desired as the default behavior for a new project.

Thanks again for helping me through this!

**Comment by webpro** [comment]
Happy to help!

You might have used a modified version or something, because I'm sure that line is not in the release-it init script (there's nothing related to hooks at all): https://github.com/release-it/create-release-it/blob/master/index.js

So that's indeed not intentional nor desired indeed :)

**Comment by paustint** [comment]
ok - super bonehead move on my part.
I guess I had added release-it months ago when I was testing out an electron release process, but I totally forgot about that and so the file already had some stuff... 🤦🤦🤦🤦🤦

Sorry for wasting your time, but thank you so much for your help.
