### ISSUE TITLE
Question: Removing link from commits in CHANGELOG.md

### ISSUE THREAD

**Issue by dfilipeloja** [release-it/release-it#981]
Hello,

I have a question: How to remove the commits' link when generating the CHANGELOG.md?

Example:

### Features
* Added feature 1 ([74e2c9b](https://github.com/release-it/release-it))

**Comment by webpro** [comment]
The link as shown is generated automatically by GitHub, the default changelog generated by release-it contains no links.

Are you using a plugin? Depending on the plugin you are using, you might want to change template. See e.g. https://github.com/release-it/release-it/blob/main/docs/changelog.md or the repository of the plugin you're using.
