### ISSUE TITLE
some confusion about usage

### ISSUE THREAD

**Issue by bilibili-ayang** [release-it/release-it#985]
Hey, guys, there's a little bit of confusion

1. Figure 1 shows the problem I encountered, and I don't know how to fix it!
2. I created a new project, the error in the first step is gone, but the old project still exists.
3. Even though there are no more errors in the new project, the minor version was created for me directly after executing yarn release, and I was not allowed to choose my own version.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/75017711/222660529-21c1397d-1f85-4354-acd1-4665e0d248d6.png">

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/75017711/222663817-b6945748-6e74-4938-b8d1-5a7b99a1b953.png">

<img width="478" alt="image" src="https://user-images.githubusercontent.com/75017711/222661290-b2d3b5e5-769d-42ee-9cb8-4b19a318e0c8.png">

**Comment by webpro** [comment]
1. The error links to [Git: Upstream branch](https://github.com/release-it/release-it/blob/main/docs/git.md#upstream-branch). Git doesn't know which upstream branch to push to.
2. I don't understand the issue here?
3. Please see the [conventional-changelog plugin](https://github.com/release-it/conventional-changelog) to see what it does and how you can change its behavior.

**Comment by bilibili-ayang** [comment]
> 1. The error links to [Git: Upstream branch](https://github.com/release-it/release-it/blob/main/docs/git.md#upstream-branch). Git doesn't know which upstream branch to push to.
> 2. I don't understand the issue here?
> 3. Please see the [conventional-changelog plugin](https://github.com/release-it/conventional-changelog) to see what it does and how you can change its behavior.

The third problem is actually about release-it, I didn't select the version option, it just created the minor version automatically

**Comment by webpro** [comment]
From the screenshots I can see you configured this plugin, so please read those docs :)

**Comment by bilibili-ayang** [comment]
> From the screenshots I can see you configured this plugin, so please read those docs :)

ok, I see that everyone is able to choose their own version, but my side can not, solve the first problem, I go to the reference documentation!

**Comment by webpro** [comment]
> everyone is able to choose their own version

The idea of this plugin is that it does that for you based on the selected conventions.

**Comment by bilibili-ayang** [comment]
> 

Okay, thanks for the answer, I'll read the documentation again
