### ISSUE TITLE
Github Release notes empty

### ISSUE THREAD

**Issue by alexboulay** [release-it/release-it#991]
Hi!
I am trying out `release-it` and I think i'm doing something wrong or i am misunderstanding something because when i try to release a version, i can see the changelog output when running `npx release-it minor`.

However, when the tag is pushed, the Github release notes do not include the changelog that was outputted by the command.

Any help is appreciated :)

**Comment by webpro** [comment]
There's nothing I can see...?

But it sounds like maybe you misunderstood that the Git (commit/tag/push) part is not the same thing as the GitHub Release part, they are separate things/plugins. Still, by default the changelog should be sent along as release notes when doing `github.release: true` - maybe you forgot to set that flag?

**Comment by alexboulay** [comment]
Oh right! I did not even have `.release-it.json` in my project.

Also thanks for pointing out the difference between tags and releases! I also read `docs/github-releases.md` which helped me shed some light!

It's working great now! 

Thanks :).
