### ISSUE TITLE
"Not authenticated with npm" error but "npm publish" works

### ISSUE THREAD

**Issue by rchl** [release-it/release-it#992]
I have been running with publishing to npm disabled in [my project](https://github.com/nuxt-community/sentry-module/blob/8a365027b83708124aeb7f33f9d4038b8845a102/.release-it.cjs#L7-L9). Recently I've tried to re-enable publishing but I'm still getting:

```
ERROR Not authenticated with npm. Please `npm login` and try again.
Documentation: https://git.io/release-it-npm
```

I'm not sure why because `npm publish` works just fine.
`npm whoami` returns `rchl` when running manually.
I've tried running `DEBUG=release-it:* yarn release-it` but that doesn't produce any extra logs.

What's the reason for this package to think that I'm not logged in when I in fact am?

**Comment by rchl** [comment]
When I run with `--npm.skipChecks` then on publishing I get an error that includes:

```
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://registry.yarnpkg.com/
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

So it looks like it's actually trying to use `yarn` for publishing? The project is using `yarn` but I'm not using it when publishing manually.` And I'm also likely not logged in to npm using `yarn`.

**Comment by webpro** [comment]
I guess yarn overrides that registry. Maybe this would fix it in your `package.json` (or `.npmrc`):

```json
{
  "publishConfig": {
    "registry": "https://registry.npmjs.org"
  }
}
```

Please note that release-it is not using yarn in any way (https://github.com/search?q=repo%3Arelease-it%2Frelease-it%20yarn&type=code).

Thanks for raising this, I guess I need to put a big banner in the readme to warn folks.

**Comment by rchl** [comment]
I've tested by adding a
```
{
    "scripts": {
      "who": "npm whoami"
    }
}
```

and running it with yarn and it does indeed show the same error:


```
❯ yarn who
yarn run v1.22.19                                                                                                                                                                                                                         
$ npm whoami                                                                                                                                                                                                                              
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in.
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

But it also still fails after adding `publishConfig.registry`.

**Comment by webpro** [comment]
As a last resort you can also add `npm.publishArgs` (https://github.com/release-it/release-it/blob/main/docs/npm.md#extra-arguments). The initial checks are actually reading from `publishConfig.registry` so that should be covered.

I should just add `--registry` explicitly to the `npm publish` step as well (and document properly so yarn folks are not surprised).

**Comment by rchl** [comment]
But I guess another issue is that yarn doesn't consider the current user logged in which is a separate issues from the registry URL itself.

I will investigate this more when I have more time and post my findings here.

**Comment by webpro** [comment]
With release-it + `publishArgs.registry` you're basically deferring everything to npm and the npm registry. Yarn would be no longer involved.

**Comment by rchl** [comment]
But I have a feeling that running package.json with `yarn` sets various env variables that might be overriding what releast-it is doing.

**Comment by rchl** [comment]
I just found that this was reported before and the documentation links to the https://github.com/release-it/release-it/issues/95#issuecomment-344919384 issue at the bottom of https://github.com/release-it/release-it/blob/main/docs/npm.md

I've added `publishArgs.registry` to `package.json` and will test in the future whether that makes publishing actually work.

In the meantime maybe the documentation could have a tiny updated to also mention yarn in relation to that issue since this is probably the most common reason for this issue because yarn overrides `npm_config_registry` env variable.

**Comment by webpro** [comment]
I've updated the docs. Apologies for the hassle. Not a Yarn user myself, so didn't feel the pain.
