### ISSUE TITLE
Release-it in ReleaseFlow

### ISSUE THREAD

**Issue by rexkenley** [release-it/release-it#994]
Not an issue but asking for guidance

We are using [ReleaseFlow](https://learn.microsoft.com/en-us/devops/develop/how-microsoft-develops-devops) to manage our repo. How do I properly setup Release-it with [ReleaseFlow](https://learn.microsoft.com/en-us/devops/develop/how-microsoft-develops-devops)?

Thanks!

**Comment by rexkenley** [comment]
@webpro , I think I can make it work as is.

Is there more documentation on the config? Or can you please point me in the right direction on what the config properties mean?

Thanks!

**Comment by webpro** [comment]
Default values are noisy, I would not add them to the local config, and you can skip values you're unsure of.

Other than that, I guess you should just try and see what works for you. Especially with `npm.publish: false` not much harm can be done I guess.

**Comment by rexkenley** [comment]
Better? Did I set the requireBranch correctly? I want to  limit the releases to the main branch and releases/* branches.

```json
{
  "git": {
    "commitMessage": "v${version}",
    "push": false,
    "requireBranch": ["main", "releases/*"],
    "requireCommits": true,
    "tagAnnotation": "v${version}"
  },
  "npm": {
    "ignoreVersion": true,
    "publish": false
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": {
        "name": "conventionalcommits",
        "types": [
          {
            "type": "feat",
            "section": "Features"
          },
          {
            "type": "fix",
            "section": "Bug Fixes"
          }
        ]
      },
      "infile": "CHANGELOG.md"
    }
  }
}

```

**Comment by webpro** [comment]
Yeah that looks fine to me. The thing is, everyone has a different process, so I can't tell what works best for you specifically.

That's also why I don't have guidance on PR merge strategies, if that's what you mean by "squash commits". I have worked in many projects and each of them has different processes and people, etc. If you have questions from a release-it perspective, feel free to ask and I'll do my best to answer them.
