### ISSUE TITLE
Custom SSH port on Gitlab (Self Hosted) - URL Generation

### ISSUE THREAD

**Issue by mtompkins** [release-it/release-it#998]
Thanks for this utility!

I've searched issues and doc's, and can't find an approach to mitigate the following:

I use a custom SSH port of `2222`
```
git remote -v
origin  ssh://git@gitlab.xxxx:2222/yyyy/network-ansible.git (fetch)
origin  ssh://git@gitlab.xxxx:2222/yyyy/network-ansible.git (push)
```

I'm using `@release-it/conventional-changelog`

All `CHANGELOG.md` and some Release links are being generated that include the custom SSH port, however I need  to use the generic 443 type URL for embedded links:

Example of currently generated Release link:     
- `https://gitlab.xxxx:2222/yyyy/network-ansible/compare/0.4.4...0.5.0`      

Desired:     
- `https://gitlab.xxxx/yyyy/network-ansible/compare/0.4.4...0.5.0`    

Similar issue with links in `CHANGELOG.md`.

Apologies if I've missed the config setting.

----- Add'l Info
I did try the config option in gitlab as:
```
  "gitlab": {
    "origin": "https://gitlab.xxxx",
    "release": true,
    "releaseName": "Release v${version}"
  },
```

- In the CHANGELOG.md, all links have the port.
- In Gitlab's UI → Releases: the *compare* links have the port.
  - ex: `https://gitlab.xxxx:2222/yyyy/network-ansible/compare/0.4.3...0.4.4`

**Comment by mtompkins** [comment]
Update: It looks to be that the variables passed to the `Angular` preset I was using is the culprit.
I'll have to run to ground which variables and how to do this.

In the meantime I tried switching to `conventionalcommits` and created the needed entries of `commitUrlFormat`, `issueUrlFormat`, `compareUrlFormat`

**Comment by mtompkins** [comment]
For future folks looking to solve this problem, here is how I am handling it (with `conventionalcommits`)

I moved from `.json` to `.js`
`.release-it.js`
```
const {execSync} = require("child_process");
let gitBaseUrl = "https://gitlab.xxxx/";

try {
  gitBaseUrl = execSync("git config --get remote.origin.url")
    .toString()
    .replace("\n", "")
    .replace("ssh://git@", "https://")
    .replace(":2222", "")
    .replace(".git", "");
} catch (error) {
  console.error("No git repo found, changelog URLs will be incorrect", error);
};

module.exports = {
  hooks: {
    "before:init": "git fetch --prune --prune-tags origin",
    "after:release": "echo Successfully released v${version} to ${repo.repository}.",
  },

  git: {
    pushArgs: "--follow-tags -o ci.skip",
    tagName: "${version}",
    commitMessage: "Automated release ${version}",
  },

  npm: {
    publish: false,
  },

  github: {
    release: false,
  },

  gitlab: {
    release: true,
    releaseName: "Release v${version}",
  },

  plugins: {
    "@release-it/conventional-changelog": {
      preset: {
        name: "conventionalcommits",
        types: [
          {type: "feat", section: "✨ Features "},
          {type: "fix", section: "🐛 Bug Fixes"},
          {type: "perf", section: "⚡ Performance Improvements"},
          {type: "revert", section: "⏪ Reverts"},
          {type: "chore", section: "📦 Chores"},
          {type: "docs", section: "📝 Documentation"},
          {type: "style", section: "💄 Styles", hidden: true},
          {type: "refactor", section: "♻ Code Refactoring"},
          {type: "test", section: "✅ Tests"},
          {type: "build", section: "👷‍ Build System"},
          {type: "ci", section: "🔧 Continuous Integration | CI"},
        ],
        commitUrlFormat: gitBaseUrl + "/-/commit/{{hash}}",
        issueUrlFormat: gitBaseUrl + "/-/issues/{{id}}",
        compareUrlFormat: gitBaseUrl + "/-/compare/{{previousTag}}...{{currentTag}}",
      },
      header: "# Changelog",
      infile: "CHANGELOG.md",
    },
  },
};

```

**Comment by webpro** [comment]
If I understand correctly; someone recently added this feature: https://github.com/release-it/release-it/blob/main/docs/gitlab-releases.md#release-notes. Did you see that? Maybe it can do what you need in a bit less hacky way :)

**Comment by ColinHuang** [comment]
@mtompkins 
Have you tried the method suggested by webpro? It still doesn’t seem to achieve the desired result. Or could you share a more new approach?
